### ISSUE TITLE
When angular component will be release ?

### ISSUE THREAD

**Issue by yotewach** [pqina/filepond#10]
Waiting for angular component

**Comment by rikschennink** [comment]
@yotewach I'm currently working on Vue.

I've got zero professional experience with Angular so it'll be a while before I start working on that. Maybe you can ask the op of issue https://github.com/pqina/filepond/issues/9?

**Comment by rikschennink** [comment]
@yotewach I could not let this go, you can find the adapter here.
https://github.com/pqina/angular-filepond
