### ISSUE TITLE
Integration with S3

### ISSUE THREAD

**Issue by akadop** [pqina/filepond#100]
Hello,

Thanks for all your work on this awesome library. It's really my favorite of all the available image uploaders here. 

I'm having trouble getting the image to correctly upload to S3, though. I've written a custom onProcess function (in react) -- and tried both the encoded and regular transfers. The node server has `multiparty` and is looking out for the multipart request, and I am actually uploading something to S3 every time this happens... but it's never the entire image / the data is corrupted. 

Is there a working example of an S3 integration somewhere?

**Comment by rikschennink** [comment]
Glad to hear that!

There are some S3 example implementations to be found in this thread:
https://github.com/pqina/filepond/issues/55
