### ISSUE TITLE
[Bug] Loaded inputs stay disabled after enabling

### ISSUE THREAD

**Issue by viyic** [pqina/filepond#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

When FilePond starts disabled, all of the hidden inputs from `load` are disabled, but enabling it doesn't remove the disabled attribute, resulting in the inputs not getting sent to the server.

### Reproduction

https://codesandbox.io/p/sandbox/hopeful-scooby-rwcd9q
- Create a FilePond instance with the disabled option and some initial files
- Enable it using `setOptions({ disabled: false })`

### Environment

```markdown
- Device: HP Laptop 14-em0xxx
- OS: Windows 11
- Browser: Zen Browser 1.0.0-a.34 (Firefox 130)
```

**Comment by rikschennink** [comment]
@viyic Thanks for reporting, fixed in v4.31.3
