### ISSUE TITLE
[Bug] Process indicator when clicked acts as remove

### ISSUE THREAD

**Issue by hn1** [pqina/filepond#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

When uploading a file, the process indicator starts spinning and if you click that before the remove button is shown, it also removes the file and the processfiles event never completes after that and no error is thrown.

### Reproduction

```
pond = FilePond.create(document.querySelector('#files'));

pond.on('processfiles', (error, file, status) => {
    console.log(error);
    
});
```

### Environment

```markdown
- Device:
- OS:
- Browser:
```

**Comment by rikschennink** [comment]
You cancelled the processing of the file, so I guess it's correct that in that situation the process files event shouldn't fire.

**Comment by hn1** [comment]
Hi
Thanks for responding.
Let's say you have a loader that starts when adding a file:

pond.on('addfilestart', (error, file, status) => {

//disable buttons

document.querySelectorAll('#controls button').forEach((el) => {

el.disabled = true;

});

 controls.querySelector("button[type='submit']").innerHTML = '<img
> src="/images/tail-spin.svg" width="32" height="32" />';

//ShowLoader - animated svg
>
});


We also have :

pond.on('processfiles', (error, file, status) => {
>     document.querySelectorAll('#controls button').forEach((el) => {
>         el.disabled = false;
>     });
>     controls.querySelector("button[type='submit']").innerHTML = 'Send';
>
> });


If the user clicks the process button:
1-It deletes the upload and
2- The loader can never be removed because we do not have a processfile
event.

If clicking the process button deletes the upload, is there any way we can
fire the process telling it that it has ended.

Thanks

**Comment by rikschennink** [comment]
@hn1 Please take the time to correctly format your code snippets.

**Comment by hn1** [comment]
Strange. It looks perfect on the email but its all mangled here!
Any way, I hope I have demonstrated the issue (in particular when there are several images being uploaded at the same time) should you wish to fix it.
Thanks
