### ISSUE TITLE
When I use FilePond five times on the page, Laravel Livewire with FilamentPHP slows down when navigating to the Edit page

### ISSUE THREAD

**Issue by Alinawaz-786** [pqina/filepond#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I clicked on Edit, and the Edit page takes 1.5 minutes to load completely. I debugged our code and found that the issue is with FilePond not uploading properly on the page. do you have any how i can fixed it.

- I have use two table samll size images.
- also test on different browser

### Reproduction

Same above

### Environment

```markdown
- Device:
- OS:
- Browser:
```

**Comment by rikschennink** [comment]
I've created an example page with 10 FilePond instances, and as far as I can tell there is zero slowdown.
https://stackblitz.com/edit/github-rqasn6?file=index.html

This is most likely related to Laravel Livewire or FilamentPHP, I'm not sure if one of these offers a FilePond component or if you're implementing it manually.
