### ISSUE TITLE
[Bug] Fix Filepond Taking Over Paste in COntentEditable Elements

### ISSUE THREAD

**Issue by Rounak-stha** [pqina/filepond#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

In case when there're `contenteditable` elements (when using editors like Tiptap) available in the app along side `Filepond`, when pasting on the element, the filepond handler takes over the event and the image doe snot get pasted on the target element.

### Reproduction

Create cotenteditable element and try pasting image in it.

### Environment

```markdown
- Device: Laptop
- OS:windows 10
- Browser: Browser
```

**Comment by rikschennink** [comment]
Will push a new release later today.
