### ISSUE TITLE
[Bug] Can't get FilePond window object from a custom livewire component

### ISSUE THREAD

**Issue by z4yed** [pqina/filepond#1008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Can we access FilePond window object from custom livewire component? Or do we need to manually install that package within filament? I think FilePond is already builtin with Filament! 
<img width="1439" alt="Screenshot 2024-09-20 at 11 15 28 PM" src="https://github.com/user-attachments/assets/303cda4f-b399-4784-8a13-5d746e262756">

### Reproduction

Create a custom livewire component and search the FilePond object in window. 

### Environment

```markdown
- Device: MacBook Pro M2 2022
- OS: MacOs sonoma
- Browser: Google Chrome
```

**Comment by rikschennink** [comment]
Please post this to filepond livewire
https://github.com/spatie/livewire-filepond
