### ISSUE TITLE
[Feature] Download files from remote server

### ISSUE THREAD

**Issue by jtatsis** [pqina/filepond#1009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hi,

When editing an already saved record with files, I use the files parameter to pass already uploaded files to filepond.
If files are other than images (e.g. pdf, word documents) the user cannot download or preview these files.

Is there any way to download these files? 

### Describe the solution you'd like

Is it possible for the title of the file to be a download link?

### Describe alternatives you've considered

Can I use an existing plugin as template to add the download link?

**Comment by rikschennink** [comment]
Perhaps this can be accomplished with: https://github.com/nielsboogaard/filepond-plugin-get-file

**Comment by jtatsis** [comment]
Thanks! That's exactly what I was looking for!
