### ISSUE TITLE
[Bug] Not displaying maxFiles error

### ISSUE THREAD

**Issue by leaked** [pqina/filepond#1011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Hi there,

First of all, I want to thank you for all the hard work you've put into building such a great library!
The issue I’m facing is that it’s not showing any maxFiles errors at all.
Could I have made a mistake somewhere?

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>filepond</title>
    <link href="https://unpkg.com/filepond@4.31.4/dist/filepond.css" rel="stylesheet" />
  </head>
  <body>
    <input type="file" class="filepond" name="filepond" multiple />
    <script src="https://unpkg.com/filepond@4.31.4/dist/filepond.js"></script>
    <script>
      const inputElement = document.querySelector(".filepond");
      const pond = FilePond.create(inputElement, {
        maxFiles: 2,
      });
      console.log(pond.name); // "filepond"
      console.log(pond.maxFiles); // 2
      console.log(pond.allowMultiple); // true
      console.log(pond.required); // false
    </script>
  </body>
</html>
```

### Reproduction

[Code](https://[codesandbox.io/p/sandbox/filepond-plain-javascript-fkkrvs](https://codesandbox.io/p/sandbox/filepond-plain-javascript-fkkrvs))

### Environment

```markdown
- Device: -
- OS: Windows 11
- Browser: Chrome 129
```

**Comment by rikschennink** [comment]
By default it doesn't show an error, but you can listen to the `onwarning` event and use that to show a message below or above the drop area.
