### ISSUE TITLE
[Bug] Can't detect the actual file type when the extension is changed by renaming the file.

### ISSUE THREAD

**Issue by z4yed** [pqina/filepond#1013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

FilePond is unable to detect the actual file type when the file extension is manually changed by renaming the file.

### Reproduction

Set the accepted file type rule to image/*. When renaming a PDF file to .jpg, FilePond incorrectly accepts it, posing a potential security risk.

Is there any way to detect the actual mime-type of that file from filepond?

### Environment

```markdown
- Device: MacBook Air
- OS: MacOs 15.0.1
- Browser: Chrome
```

**Comment by rikschennink** [comment]
As everything on the client can be manipulated you _always_ have to check files on the server.

**Comment by z4yed** [comment]
Thanks.
