### ISSUE TITLE
How to have links in filename?

### ISSUE THREAD

**Issue by lekoala** [pqina/filepond#102]
Hi!

I'd like to have a clickable link or icon on the file so that it's possible to view or download the uploaded file (mostly for already uploaded files).

It seems html is escaped (but I didn't investigate much). Some kind of clickable icon next to the name would be perfect (I know there is the poster/preview plugin, but that's not quite what I want to do).

Do you have any idea how I can achieve that given the current state of FilePond?

**Comment by ayophanz** [comment]
Hi could you post sample code how to add url to make it clickable?

**Comment by rikschennink** [comment]
@ayophanz 
https://github.com/nielsboogaard/filepond-plugin-get-file

**Comment by ayophanz** [comment]
Thanks
It would be nice if filepond does have like this see video(link to view uploaded file) https://screencast-o-matic.com/watch/cY6h2DK0OS
I achieved this by jquery (jquery is my last option)
