### ISSUE TITLE
[Bug] svg image load from server causes error while parsing the response

### ISSUE THREAD

**Issue by psycho3069** [pqina/filepond#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [x] I have updated FilePond and its plugins

### Describe the bug

I have implemented all the necessary methods i.e. preview and upload seamlessly along with loading the image from the server to show it on the edit page. But recently faced this issue while trying to load the SVG image from the server. Getting error while trying to parse the response (which is blob according to documentation) even though the response is a valid SVG.

Error: parsererror 
Error Body: 
Invalid XML: This page contains the following errors:
error on line 1 at column 1: Start tag expected, '<' not found
Below is a rendering of the page up to the first error

References: 
Error (console error in ajax):
![image](https://github.com/user-attachments/assets/5948358d-36c3-474a-b55d-780094b184e9)

Response (valid SVG from server):
![image](https://github.com/user-attachments/assets/48e28910-4848-4aa8-8a8c-10cdf789ff35)

### Reproduction

Step 1:
Implement filepond upload (server: process) with preview image+pdf

```js
            process: {
                url: "<?php echo url('/admin/expertises/image-upload'); ?>",
                headers: {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                },
                ondata: (formData) => {
                    formData.append('module', moduleName); 
                    return formData;
                },
                onload: (response) => {
                    return response;
                },
                onerror: (responseString) => {
                    console.error(responseString);

                    errorResponse = JSON.parse(responseString);
                    
                    if (errorResponse && errorResponse.error && errorResponse.messages) {
                        toastr.error(
                            errorResponse.error, 
                            errorResponse.messages.cover ? errorResponse.messages.cover[0] : 'File Upload Failed', 
                            {
                                closeButton: true,
                                progressBar: true,
                                preventDuplicates: true
                            }
                        );
                    } else {
                        toastr.error('Failed', 'File Upload Failed', {
                            closeButton: true,
                            progressBar: true,
                            preventDuplicates: true
                        });
                    }
                    
                },
            },
```

Step 2:
Implement load method to load already uploaded file from server (which I have done with ajax)

```js
                    load: (source, load) => {
                        
                        $.ajax({
                            url: '<?php echo url("/admin/expertises/get-file"); ?>',
                            headers: {
                                'X-CSRF-TOKEN': '{{ csrf_token() }}'
                            },
                            type: 'POST',
                            data: {
                                source: source,
                            },
                            xhrFields: {
                                responseType: 'blob'
                            },
                            success: function(data) {
                                load(data);
                            },
                            error: function(xhr, status, error) {
                                console.error('AJAX request failed:', error);
                            }
                        });
                    },
```
                    
Step 3: Implement server method which returns the SVG image file

```js
    public function getUploadedFile($file_source){

        $filename = basename($file_source);

        // get the mime type from file name extension
        $mime_type = mime_content_type($file_source);

        if (file_exists($file_source)) {
            $fileContent = file_get_contents($file_source);

            $response = new Response($fileContent, 200);
            $response->header('Access-Control-Expose-Headers', 'Content-Disposition, Content-Length, X-Content-Transfer-Id');
            $response->header('Content-Type', $mime_type);
            $response->header('Content-Disposition', 'inline; filename="' . $filename . '"');

            return $response;
        } else {
            return response()->json(['error' => 'File not found'], 404);
        }
    }
```
    
Step 4: 
Try to upload a SVG file and then try to load it from server with a refresh (for me it is on the edit page)
You should find that the response is a valid SVG file but gets error on ajax methods error callback which will log the error message shown in the above description.

### Environment

```markdown
- Device: HP EliteBook G6 : Core i7 7th Gen
- OS: Windows 10 Pro : 22H2
- Browser: Google Chrome Version 130.0.6723.92 (Official Build) (64-bit)
```

**Comment by rikschennink** [comment]
From the stack trace it seems the error is in jQuery?

**Comment by psycho3069** [comment]
I am not sure. I just did all necessary and all other formats work properly except the SVG @rikschennink

**Comment by psycho3069** [comment]
Yes, error still occurs if `load(data)` is removed.

According to the documentation, I must return the images as blob which I did.
According to the documentation, I must use load(data) in the success where I receive the blob image which I did.

Now, this code works properly for all the other types of images except the svg. Now, what must I do to set it right ? or is there anything l'm doing wrong? Please tell me what I must do. Otherwise I'm stuck with it for few days. TIA @rikschennink 

![image](https://github.com/user-attachments/assets/8859758a-fc21-464a-949c-5abf3b6270d4)

**Comment by psycho3069** [comment]
After trying a lot and a lot and failing, just took your hint that the issue could be with ajax. Then I tried axios and it worked instantly.

Thanks a lot for your support. @rikschennink

**Comment by rikschennink** [comment]
Glad to hear it's resolved 👍
