### ISSUE TITLE
[Bug] Grid Layout: Container Height Adapts to Last Uploaded Image, Causing Misalignment

### ISSUE THREAD

**Issue by matheusnmcv** [pqina/filepond#1025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

When using FilePond with custom CSS to control the grid layout of uploaded items, the container height dynamically adjusts to match the height of the last uploaded image. If the last image has a smaller height than the others, the container shrinks, causing inconsistent alignment and layout issues for previously uploaded images.

![image](https://github.com/user-attachments/assets/6b75495c-13db-46bd-ac72-d5085b4d09d8)

![image](https://github.com/user-attachments/assets/df74b9ca-5764-4ce8-b665-514a15d49024)

### Reproduction

Add the custom CSS above to project to create a grid layout for FilePond items.
Upload an image with a large height (e.g., a portrait-oriented image).
Upload a second image with a smaller height (e.g., a landscape-oriented image).
Observe how the container height adjusts to the smaller image, misaligning the overall grid.

### Environment

```markdown
- Device: Desktop
- OS: Windows 10
- Browser: Chrome
```

**Comment by rikschennink** [comment]
See footnote of this section:
https://pqina.nl/filepond/docs/api/style/#grid-layout

Kind regards,

Rik | PQINA

PQINA BV
Sint Willibrordusstraat 16
5502 BH Veldhoven
The Netherlands
