### ISSUE TITLE
[Bug] Argument of type '"processfiles"' is not assignable to parameter of type 'FilePondEvent'.

### ISSUE THREAD

**Issue by zeroamps** [pqina/filepond#1028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Hi, there is a bug:

```Argument of type '"processfiles"' is not assignable to parameter of type 'FilePondEvent'.```

It looks it's missing  a TypeScript Declarations for that.

![image](https://github.com/user-attachments/assets/53864e07-4480-4ea6-bc2d-a75728a924a3)

I have to workaround it which is not ideal like this

```
    filePond.on('processfiles' as FilePond.FilePondEvent & 'processfiles', () => {
      console.log('processfiles');
    });
```

### Reproduction

```
import { Directive, ElementRef, input, OnInit } from '@angular/core';
import * as FilePond from 'filepond';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';

@Directive({
  selector: '[appFilePond]',
  standalone: true
})
export class FilePondDirective implements OnInit {
  config = input.required<FilePond.FilePondOptions>();

  constructor(private el: ElementRef) {}

  ngOnInit() {
    FilePond.registerPlugin(FilePondPluginFileValidateType);
    const filePond = FilePond.create(this.el.nativeElement, this.config());

    filePond.on('processfiles', () => {
      console.log('processfiles');
    });
  }
}
```

### Environment

```markdown
- Device: Macbook Pro
- OS: Windows 10
- Browser: Chrome 131
```

**Comment by rikschennink** [comment]
Thanks for reporting, should be fixed in `4.32.6`

**Comment by zeroamps** [comment]
Great! It works!

**Comment by rikschennink** [comment]
Glad to hear that :)
