### ISSUE TITLE
Multiple Inputs on the Page

### ISSUE THREAD

**Issue by stack-its** [pqina/filepond#104]
Hi Rik,

Making good progress now - preview loads now.  I will have multiple fileponds on the page.
I have moved the registerPlugins outside of any main functions.

If I generated the Drop/Browse prompt on first input - the preview loads.  If I then generate the prompt on a second input, the first input shows this error:

<img width="510" alt="206" src="https://user-images.githubusercontent.com/1207542/44303659-288c0480-a30c-11e8-9584-8fa616dd6417.png">

If I generate both prompts before starting drop/browse, then both previews show.
So, would you suggest I move my filepond callout and custom process/upload function outside of my main function?

**Comment by rikschennink** [comment]
I’m not sure what you mean with 

> generated the Drop/Browse prompt

**Comment by stack-its** [comment]
When I click on an image, a script builds the inputs & then does the file cloud call which creates file pond's Drop/Browse prompt, i.e. 'Drag & Drop File or Browse'

**Comment by rikschennink** [comment]
I'm not sure why it's throwing an error or what's happening, I do know that there are multiple FilePond instances running on the FilePond product page. The issue might be related to shared variables between functions or other code problems, I doubt it's in FilePond itself.
