### ISSUE TITLE
iconProcess doesn't work

### ISSUE THREAD

**Issue by dima19972525** [pqina/filepond#105]
Hi, i want to change process icon, but when i try it remains the same, other icons change.
` render() {

        const { allowMultiply, maxFiles, server, t } = this.props;
        return (
            <Panel
                className="panel-default"
                title={ 'FILE' }
                >
                <div>
                    <FilePond allowMultiple={allowMultiply} maxFiles={maxFiles} server={server} iconProcess={''}
                    iconRemove={''} iconRetry={''} iconUndo={''}>
                        {this.state.files.map(file => (
                            <File key={file} src={file}/>
                        ))}
                    </FilePond>
                </div>
            </Panel>
        );
    }`

![1](https://user-images.githubusercontent.com/23092460/44309487-1f646b80-a3d0-11e8-803e-bac886934b16.PNG)
![2](https://user-images.githubusercontent.com/23092460/44309488-1f646b80-a3d0-11e8-813a-07e085ad2e51.PNG)

**Comment by rikschennink** [comment]
The processing progress indicator is a dynamically animated SVG and can't be replaced. The `iconProcess` refers to the up arrow used to manually start a file upload.
