### ISSUE TITLE
insertAfter how to?

### ISSUE THREAD

**Issue by yukyolol** [pqina/filepond#108]
Hello, I know this is not a bug or something it's just I don't know where to place the insertAfter and how to do it.

Actually, I have a problem that my uploader loads before an element that has some dynamic values, and my uploader is having empty values.

So I think inserAfter should solve this problem right?
Or there's any "action" to "refresh" the Ffilepond and re-read again the properties?

If insertAfter should solve this how I can use it?
I want to load it after a div that has id = monsid

Where should I create the insertAfter?
Can you bring me please an example using my following code:
My code looks like this:
```
FilePond.registerPlugin(
  		FilePondPluginFileEncode,
  		FilePondPluginFileValidateType,
  		FilePondPluginFileValidateSize,
  		FilePondPluginImageExifOrientation,
      	FilePondPluginImageCrop,
  		FilePondPluginImagePreview,
      	FilePondPluginImageResize,
  		FilePondPluginImageValidateSize,
      	FilePondPluginImageTransform
	);

	const inputElement = document.querySelector('input[type="file"]');
	const pond = FilePond.create( inputElement, {
      	allowFileSizeValidation: dynamic.allowfilesizevalidation,
      	maxFileSize: ''+dynamic.maxfilesize+'',
      	maxTotalFileSize: ''+dynamic.maxtotalfilesize+'',
      	labelMaxFileSizeExceeded: ''+dynamic.labelmaxfilesizeexceeded+'',
      	labelMaxFileSize: ''+dynamic.labelmaxfilesize+'',
      	labelTotalFileSizeExceeded: ''+dynamic.labeltotalfilesizeexceeded+'',
      	labelMaxTotalFileSize: ''+dynamic.labelmaxtotalfilesize+''
  });
FilePond.setOptions({
    server: {
        process: (fieldName, file, metadata, load, error, progress, abort) => {

            const upload = uploadcare.fileFrom('object', file);
            
            upload.progress((uploadInfo) => {
                // State of your upload gets updated.
                // The callback is invoked at least once with a current state,
                // right after assignment.
                // https://uploadcare.com/docs/api_reference/javascript/files_uploads/#upload-info
                progress(true, uploadInfo.uploadProgress, 1);

            });

            upload.done((fileInfo) => {
                // Upload has successfully completed and a file is ready.
                // https://uploadcare.com/docs/api_reference/javascript/files_uploads/#file-info
                load(fileInfo.uuid);

            })
            .fail((err, fileInfo) => {
                // Upload failed, or something else went wrong, a file is not ready.
                error(err);

            });
            
            return {
                abort: () => {

                    // https://uploadcare.com/docs/api_reference/javascript/files_uploads/#file-cancel-uploading
                    upload.cancel();

                    // Let FilePond know the request has been cancelled
                    abort();
                }
            };
        }
    }
});
```

**Comment by yukyolol** [comment]
Hello, I've noticed also when any dynamic value changes I.e: file size, it keeps stuck on the old value. How I can force a refresh?

Thanks.

**Comment by rikschennink** [comment]
I’m not sure what you mean with both comments can you try to provide a test case or improve the example code?

**Comment by yukyolol** [comment]
My question is quite simple, sorry if you didn't understand.

I have everything working pretty well, I'm using dynamic fields to maxsize. When the filepond uploader loads on the page gets the value of that input only when loading first time. When the value of the input changes it stills using the old value. 

So my question is, how I can force filepond to update after x input is modified?

Thanks.

**Comment by rikschennink** [comment]
I’d youre writing this in vanilla JavaScript without using any frameworks you’ll have to listen for changes on your dynamic fields and re-assign the value to filepond properties.

**Comment by yukyolol** [comment]
So filepond does not have a refresh action to be called to do that?

Something like Filepond.refresh

**Comment by rikschennink** [comment]
No, and to be honest I'm not sure what you're looking for, this is basically how JavaScript functions, parameters are [passed by value](https://stackoverflow.com/questions/373419/whats-the-difference-between-passing-by-reference-vs-passing-by-value), see below:

```js
var foo = 1;

// imagine bar is the FilePond options object
var bar = foo;

console.log(bar); // logs 1

// now you change your variable vlue
foo = 2;

console.log(bar); // still logs 1
```
