### ISSUE TITLE
Filepond + Slim?

### ISSUE THREAD

**Issue by yukyolol** [pqina/filepond#109]
Hello, It's possible to use Filepond + Slim?

I have Filepond with cropping plugin but I want to give to the user the ability to drag his own cropping selection.

I saw there pqina has created also an awesome cropping plugin: https://pqina.nl/slim/
https://puu.sh/Bjn63/bdea9900f3.gif
My question is: It's possible to show the button and show the pop-up when the button is pressed.
And replace my cropping plugin with the slim cropping function?

Thanks.

**Comment by rikschennink** [comment]
In theory that is possible. You'd have to manually add the edit button to FilePond by writing a custom plugin (the quickest way to do that would be to fork the [image preview plugin](https://github.com/pqina/filepond-plugin-image-preview)).

You can then link up the button click with the Slim cropper.

Please note that I'm currently working on a new image cropper that will integrate with FilePond. You can [follow me on Twitter](https://twitter.com/rikschennink) to receive regular updates.

**Comment by yukyolol** [comment]
Is there any time estimation for this?
So I can wait or try to search for another solution until then

Thank you so much

**Comment by rikschennink** [comment]
I'm hoping it's done in a couple of months.
