### ISSUE TITLE
Filepond inside accordion does not have the right height

### ISSUE THREAD

**Issue by apandichi** [pqina/filepond#11]
When placing the filepond enhanced file input inside an accordion, the height of the "drag and drop" zone is not calculated correctly.

![screenshot from 2018-03-21 18-57-36](https://user-images.githubusercontent.com/1415168/37724616-db85f7c4-2d39-11e8-94ec-5050d731305b.png)

See [fiddlejs](https://jsfiddle.net/7yx7w9o5/4/)

**Comment by rikschennink** [comment]
@apandichi, good catch. FilePond measures the available space and then scales the drop area accordingly if it's initialized in an invisible element the available space will be 0 (as the element does not have any layout). 

You could initialize FilePond when the section becomes visible (maybe the accordion throws an event?).

I'll look into the following solutions
- Keep (cheap) render loop going while invisible to determine if FilePond has become visible
- Detect visibility changes and trigger re-render once FilePond has become visible

**Comment by rikschennink** [comment]
I've just published versions `1.2.5` of FilePond. It fixed the issue in my test case. Will close for now.

**Comment by apandichi** [comment]
@rikschennink Thanks, it fixed my problem too!

**Comment by rikschennink** [comment]
Awesome, thanks for confirming! @apandichi
