### ISSUE TITLE
dropOnPage not implemented?

### ISSUE THREAD

**Issue by leoliu** [pqina/filepond#113]
🐜 If you've found a bug, please use the template below to report it.

I am initialising filepond with `dropOnPage: true` but it doesn't seem to do anything. Is this an oversight?

**Comment by rikschennink** [comment]
You need to set `dropOnElement` to `false` for it to work.

**Comment by rikschennink** [comment]
That's interesting, I'll add it to my use case.

`dropOnPage` is mostly there to catch everything dropped and prevent the browser from opening dropped images, which is almost always not what you want :-)
