### ISSUE TITLE
Just show default image

### ISSUE THREAD

**Issue by Konafets** [pqina/filepond#114]
The documentation describes the `files` property to show an initial image, which should be uploaded immediately. Is there a way to just show an image without uploading it?

My usecase is an avatar upload:

1. If the user has not uploaded anything yet, it shows the default empty template.
2. The user uploads an image.
3. Next time the user goes to his profile page, he sees the uploaded image

**Comment by rikschennink** [comment]
Two options I think:

1. Set the default empty template as a background image on the drop area.

2. Use the [file poster plugin](
https://pqina.nl/filepond/docs/patterns/plugins/file-poster/) and add a stub file.

**Comment by Konafets** [comment]
Thanks!

**Comment by avillarubia2** [comment]
Good day @Konafets and @rikschennink 

I have same concern but my usecase is similar to this,
1. There is a file already uploaded.
2. When the user wants to update a file, can see first the file as a preview before doing the upload.

I am using Filepond on react.

Below is are some plugins and the file poster
```js
import { FilePond, registerPlugin } from 'react-filepond'
import FilePondPluginImagePreview from 'filepond-plugin-image-preview'
import FilePondPluginFilePoster from 'filepond-plugin-file-poster'
...other plugins
import 'filepond/dist/filepond.min.css'
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css'
import 'filepond-plugin-file-poster/dist/filepond-plugin-file-poster.css'

registerPlugin(
    ...other plugins
    FilePondPluginImagePreview,
    FilePondPluginFilePoster
)

export default FilePond
```

And below is the component itself.
```js
    const [file, setFile] = useState({
        source: '12345', //don't know what should be the value
        options: {
            type: 'local',
            file: {
                name: 'hedgehog.jpg',
                size: 189397, //correct size of the file
                type: 'image/jpeg'
            },
            metadata: {
                poster: 'http://localhost:3000/uploads/5e5a7981e1ee0b2128aa9ea6_hedgehog.jpg'
            }
        }
    })

return (
        <Uploader
            ref={ref => pond = ref}
            file={file}
            allowFileSizeValidation={true}
            maxFileSize="50mb"
            instantUpload={false}
            name='items'
            allowMultiple={false}
            allowFilePoster={true}
            onupdatefiles={fileItems => setMetadata(fileItems)}
            onprocessfile={(error, file) => {
                if (file && file.serverId)
                    d(setFileProp({ filenameExt: file.serverId }))
            }}
            onprocessfileprogress={(file, progress) => {
                if (file && file.status) {
                    d(setFileProp({ isUploading: file.status === 3 }))
                    d(setFileProp({ hasFileAdded: false }))
                }
            }}
            labelIdle='Drag & Drop files or <span class="filepond--label-action">Browse</span>'
            server={`${apiBaseUrl}api/uploads/`}
        />
    )
```

But when the component is mounted, it won't display the image url.
I am hoping that you can help me. Thank you.

**Comment by Riaan-ZA** [comment]
The files property can actually take an array with options, setting type option to local, prevents it from uploading again

```
file: {
    source: response.data.data.image,
    options: {
       type: 'local'
    }
}
```

**Comment by avillarubia** [comment]
@Riaan-ZA thank I'll try that

**Comment by avillarubia** [comment]
@Riaan-ZA I have the example below

https://codesandbox.io/s/filepond-file-poster-or-default-file-6xdlz

but it can render a preview of a remote image.

Do you have any idea that can help? Thank you.

**Comment by VeRJiL** [comment]
I could finally figure a way which is not optimal to load the image. Check this answer on stackoverflow:

[](https://stackoverflow.com/a/66220498/7295420)

they have a great library and good documents but some little details are missing from the Docs, I hope they update the docs
