### ISSUE TITLE
How to prevent dropping files greater than maxFiles?

### ISSUE THREAD

**Issue by leoliu** [pqina/filepond#115]
I have a UX design issue that I don't know how best to solve. I want to reject dropping files more than `maxFiles` completely i.e. they either all succeed or none does. This is easier for my users to reason about. I have an upload form that has `maxFiles: 36`, so reject partially can be confusing to work with.

**Comment by rikschennink** [comment]
I think I'll replace the way it currently functions with this solution as it's a lot clearer to the user. 

I've added it to the roadmap.

**Comment by leoliu** [comment]
Excellent and thanks for taking this on.

**Comment by rikschennink** [comment]
Publishing `2.0.0` right now, fixes this issue. Turned out to be a bug. Let me know if it works :-)

**Comment by leoliu** [comment]
Already using `2.2.0` seems working as expected. Thanks.
