### ISSUE TITLE
Failed to construct 'Worker': Access to the script at 'blob:https...'

### ISSUE THREAD

**Issue by leoliu** [pqina/filepond#118]
I have `script-src 'self'` in the `content-security-policy` header and found this exception that seems to relate to the preview plugin:

```
Uncaught DOMException: Failed to construct 'Worker': Access to the script at 'blob:https://example.com/b6714c1d-702a-4041-b5f9-7b36dc3d1fa4' is denied by the document's Content Security Policy.
    at Fn (https://example.com/assets/js/main-718609cb98.js:18:84505)
    at https://example.com/assets/js/main-718609cb98.js:34:26960
    at Image.DID_IMAGE_PREVIEW_CONTAINER_CREATE.n.onload (https://example.com/assets/js/main-718609cb98.js:34:26784)
```

User agent:

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36

**Comment by rikschennink** [comment]
The workers are generated dynamically, can you test if this works:
https://github.com/mapbox/mapbox-gl-js/issues/4062#issuecomment-319702384

**Comment by leoliu** [comment]
I have to add `blob:` for img-src so yes it will silence the error.

But I am a bit hesitant to add blob: to script-like context since the main purpose of CSP is to prevent XSS. Do you see a way that can solve the issue without requiring a `blob:` in CSP? Thanks.

**Comment by rikschennink** [comment]
> I have to add `blob:` for img-src so yes it will silence the error.

Okay great.

> But I am a bit hesitant to add blob: to script-like context since the main purpose of CSP is to prevent XSS. Do you see a way that can solve the issue without requiring a blob: in CSP? Thanks.

I could only find the following resource on security risk. 
https://security.stackexchange.com/questions/190331/is-allowing-blob-in-content-security-policy-a-risk

I don't think it's possible to solve this without extracting worker code from the library, but that would make the library setup process a hassle as every worker would be in its own file. It seems a lot of other libraries also advice to add `:blob` to the CSP.

**Comment by leoliu** [comment]
Thanks a lot. I'll do that. Feel free to close this.

**Comment by djmason9** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src
worker-src 'self' 'unsafe-inline' * blob:;

this helped me

**Comment by martinschilliger** [comment]
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src
> worker-src 'self' 'unsafe-inline' * blob:;
> 
> this helped me

Ok, is it whise to add `*` with the other entries? `worker-src 'self' blob: ;` was enough for me.

**Comment by M0ns1gn0r** [comment]
It is not wise as it defeats the whole purpose of CSP.

**Comment by nxmndr** [comment]
Tried both versions of CSP without success. Same error messages about "about:blank" report URI and worker-src.
