### ISSUE TITLE
How to only compress image without resizing it?

### ISSUE THREAD

**Issue by yoldar** [pqina/filepond#121]
Hi! Thank you for that great upload plugin!

Is it possible to compress the image without resizing it? I mean only to compress? Because as I understood compression happens only when these attributes are set:
```
imageCropAspectRatio="1:1"
:imageResizeTargetWidth="300"
:imageResizeTargetHeight="300"
imageResizeMode="cover"
```

**Comment by rikschennink** [comment]
If you omit the resize or crop plugin and only have the quality parameter set it should compress as well.

```js
imageTransformOutputQuality: 60
```

See this related thread:
https://github.com/pqina/filepond-plugin-image-transform/issues/1

**Comment by qjnz** [comment]
setting `imageTransformOutputQuality` does not seem to work for me.  https://codesandbox.io/s/react-file-upload-0e0qj?file=/src/components/filepond.js
