### ISSUE TITLE
Ability to throw FilePond error?

### ISSUE THREAD

**Issue by dannycallaghan** [pqina/filepond#124]
Firstly, thank you for FilePond - it's awesome.

Is there a way I can throw a FilePond error?

In my app, after a successful file upload, I POST the details to an API endpoint. If, for some reason, that POST fails, I'd love to be able to show the fault within FilePond, so that everything is contained with the beautiful FilePond UI.

Something like:

```javascript
onprocessfile: (error, file) => {
    if (!error) {
        AttachmentsService
            .addFile()
            .then(() => {
                // Continue
            }, () => {
                FilePond.fire('error', 'Cannot add file');
                // Option to remove or retry?
        })
    }
}
```
Is anything like this possible?

Thanks in advance.

**Comment by rikschennink** [comment]
Hi @dannycallaghan!

That's currently not possible without writing a custom processing method. You could then do the two upload steps in a single go and handle the error states gracefully as well.

**Comment by dannycallaghan** [comment]
Thanks for the quick response @rikschennink 

Fair enough, thanks for the confirmation. I'll try and put something together.

**Comment by rikschennink** [comment]
I've written a quick outline of a custom processing method, haven't tested it thoroughly but this is basically it.

There's more info to be found here:
https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects

And some information on the server config in the FilePond docs:
https://pqina.nl/filepond/docs/patterns/api/server/#advanced

```js
const pond = create(document.querySelector('input[type=file]'), {
    server: {
        process: (fieldName, file, metadata, load, error, progress, abort) => {

            const formData = new FormData();
            formData.append(fieldName, file, file.name);

            const request = new XMLHttpRequest();
            request.open('POST', 'http://foo.com/submitform.php');

            request.upload.onprogress = (e) => {
                progress(e.lengthComputable, e.loaded, e.total);
            };

            request.onload = function() {
                if (request.status >= 200 && request.status < 300) {

                    // do your custom upload here and only call the load when that is done, if not call error

                    load(request.responseText);
                }
                else {
                    error('oh no');
                }
            };

            request.send(formData);

        }
    }
});
```

**Comment by dannycallaghan** [comment]
Wow, awesome stuff @rikschennink. Thanks for this, leaving the office now, but will give it a go as soon as.

Cheers.

**Comment by Michaelvons** [comment]
Using the custom method, when there is a 400 or 500 error, How do I reflect that on the UI i.e with a red background colour?

**Comment by rikschennink** [comment]
@Michaelvons  use `error` callback

**Comment by Michaelvons** [comment]
I guess you mean the `onerror`  callback in the `server` object
I see the error response but how do I toggle the UI from that callback.

Any sample code will be helpful. Thanks

**Comment by rikschennink** [comment]
@Michaelvons See the `error('oh no');` part of the code snippet a couple comments back.

**Comment by Michaelvons** [comment]
@rikschennink Gracias!!. Works perfectly!. Thanks
