### ISSUE TITLE
React: populating initial files issue // load via server

### ISSUE THREAD

**Issue by lukey78** [pqina/filepond#125]
### Summary

Setting initial files with the `files` property on `<FilePond>` instance seems to have no effect. Is this correct?

Setting initial files with `<File>` children works like this:
```jsx
{this.props.existingFileIds.map(fileId => (
    <File key={fileId} src={fileId} origin={'local'}/>
))}
```

But: 

If I remove the file (via GUI) and/or add new files, FilePond tries to load the newly uploaded files with the **load** method. But the newly uploaded files were only transferred temporarily, so the "load" fails of course.

Even if the `this.props.existingFileIds` is an empty array, this behaviour occurs.

Why is this happening?

### Expected behaviour

One can set initial files with `<File>` children, but removing a file and adding new files should result in the same behavior => transfer via the process route, but don't issue a "load" afterward.

**Comment by rikschennink** [comment]
The initial files list will be preloaded by FilePond as long as the file data is not stubbed. Using the `origin` property you can inform FilePond where the files are located on the server, `local` (for uploaded files) or `limbo` (for temp files).

I just tested to be sure, but if I drop new files they are added normally and not routed through the `server.load` endpoint.

Maybe I'm misunderstanding the issue, can you elaborate?

**Comment by lukey78** [comment]
I'm sorry, the problem was not in FilePond, but in my wrapping component using Formik. Formik tried to rerender the FilePond field several times upon image removal, and that caused the component to misbehave. I fixed that by implementing a shouldComponentUpdate => return false function.

**Comment by rikschennink** [comment]
@lukey78 Alright! Thanks for the updated :)
