### ISSUE TITLE
2.3.0 broken

### ISSUE THREAD

**Issue by leoliu** [pqina/filepond#126]
🐜 If you've found a bug, please use the template below to report it.

I upgraded to 2.3.0 today and broke my app due to:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval'
```

The script sample that causes this problem: `"(function anonymous(\n) {\ntry {return thi"`

**Comment by rikschennink** [comment]
Just published `2.3.1` should resolve the issue.
