### ISSUE TITLE
Vue and FilePond styling issue

### ISSUE THREAD

**Issue by fabianPas** [pqina/filepond#129]
### Summary

I've been using FilePond in my backend application since a few days. I first used FilePond without any adapter which worked perfectly including the FilePreviewPlugin. As I'm using Laravel I wanted to implement FilePond using Vue.js and after implementation the styling showed a few errors as can be seen [here](https://imgur.com/a/QCddVAZ).

The file preview is not centered and the button to remove the file is aligned to the left. When the plugin is removed, the remove button is still aligned to the left. No other plugins are installed.

### How to reproduce

Implement FilePond using Vue.js.

### Expected behaviour

A centered preview image and a removal button aligned to the right next to e.g. 'Upload Complete'.

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Device       | Desktop
| Browser      | Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by rikschennink** [comment]
Hi! 

Are you using the [vue-filepond](https://github.com/pqina/vue-filepond) adapter?

With version 3.0.0 of FilePond some styles have been updated, are you sure you have version 3.0.0 CSS files and have cleared the browser cache?

**Comment by fabianPas** [comment]
I am using the vue-filepond adapter with the following CSS files in my view:

```
<link rel="stylesheet" href="https://unpkg.com/filepond/dist/filepond.min.css">   
<link rel="stylesheet" href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css">
```

I've emptied the cache without results. I'm developing with caching disabled, so it shouldn't be a problem.

**Comment by rikschennink** [comment]
I think because the FilePond dependency within the adapter has not yet been updated but you're using the unpk url's you're mixing versions.

This should install the latest version of FilePond.
```
npm install filepond@latest
```

**Comment by fabianPas** [comment]
I've run the `npm install` command but nothing has changed. Am I supposed to use the CSS files from the `dist` directory instead of the `unpkg.com` urls?

**Comment by rikschennink** [comment]
Either that or lock the unpkg.com urls to an earlier major version.

```
https://unpkg.com/filepond@^2/dist/filepond.min.css
https://unpkg.com/filepond-plugin-image-preview@^2/dist/filepond-plugin-image-preview.min.css
```

**Comment by fabianPas** [comment]
Using the locks you provided the remove button is back at it's position, the preview image is still not centered. Also, using the CSS files from the `dist` directory does not seem to fix the issues described.

**Comment by rikschennink** [comment]
Are you using version 2.x of FilePond or 3.x?

**Comment by fabianPas** [comment]
You got me there. I forgot to revert the npm packages to 2.x. It works with 2.x now! But can we confirm there is something weird going on using Filepond 3.x?

**Comment by rikschennink** [comment]
Fantastic! 

I'll test the vue-filepond adapter with v3 in the coming days. Will update here.

**Comment by rikschennink** [comment]
Package has been updated to v3

**Comment by davoodmood** [comment]
I have a big issue with the Vue FilePond I cannot customize any css. Neither from the component template's scoped CSS, nor after accessing the FilePont Instance to alter styling with javascript. This is a big for using this library in vue.
