### ISSUE TITLE
the plugin is very good, the docs sucks

### ISSUE THREAD

**Issue by leandroruel** [pqina/filepond#130]
i'm trying to upload with filepond, but the docs are very bad on pointing me to a direction

**Comment by rikschennink** [comment]
Hi!

I'm very much open to constructive criticism on the product, I'm however not open to the generic bashing of said product.

You could've added something of value to this issue (like what specifically in the docs you didn't understand, where did you get stuck?), that would've allowed me to help you out. You choose to ignore the issue template and stopped adding value to the issue after generically bashing the docs, there's not really anything here for me to help you with. 

I welcome you to open a new issue and try again. Try to follow the issue template and also, try to be a nicer person.
