### ISSUE TITLE
How to upload file as octet stream instead of multipart form data ?

### ISSUE THREAD

**Issue by ravindra4me** [pqina/filepond#132]
My server doesn't support multipart form data processing, it accepts octetstreams only. How to configure filepond so that it uses binary octet stream upload only instead of multipart form data ?

**Comment by ravindra4me** [comment]
Nevermind, this can be closed now. i modified the filepond.js by change xhr upload script.

**Comment by rikschennink** [comment]
As far as I can tell by quickly searching online the only requirement is an additional request header.

You can add these in the server configuration object.

```js
pond.server = {
  url: 'url-to-api',
  process: {
    headers: {
      'Content-Type': 'application/octet-stream'
    }
  }
}
```
