### ISSUE TITLE
Display images previews in a grid

### ISSUE THREAD

**Issue by pryley** [pqina/filepond#134]
It would really be nice if Filepond allowed you out-of-the-box to display image previews in a grid (left-to-right, flex) instead of top to bottom.

**Comment by rikschennink** [comment]
@pryley fully agree! I have some ideas about this, but at the moment it's quite the undertaking, when I'm done with the [Image Editor plugin](https://pqina.nl/filepond/image-editor.html) I'm moving on to these kinds of improvements.

**Comment by mloukili** [comment]
Great work, unfortunately we couldn't use it due to the top-down layout.

**Comment by cheukman-octopus** [comment]
I could also be interested in using left to right layout if possible as well, kinda took a peek in the logic. Would love to have some guidance on how to start this if possible.

**Comment by rikschennink** [comment]
@cheukman-octopus Please make this request into a new issue.

**Comment by cheukman-octopus** [comment]
Apologize for the confusion, I meant I would be interested in the Grid layout too (top left being the first item, the new item will be on the right of that, new row when the current row is filled). Wouldn't mind contributing to this if I can have some pointers of where I can start calculating the position and container size etc

**Comment by osnielcainzos** [comment]
very nice work, any update on this feature ?

**Comment by rikschennink** [comment]
Thanks @osnielcainzos! I regularly tweet updates, latest update:
https://twitter.com/rikschennink/status/1088457575845191681

I hope to pick it up again later this week.

**Comment by rikschennink** [comment]
Just published version `4.0.0`, which includes [grid layout](https://pqina.nl/filepond/docs/patterns/api/style/#grid-layout)

![kapture 2019-02-04 at 12 13 33](https://user-images.githubusercontent.com/1132575/52216797-60c1d800-2897-11e9-951c-3e8a8f729f96.gif)

Please let me know if it works as intended.

**Comment by pryley** [comment]
Looks great so far. Thanks!

**Comment by ThamrinPH** [comment]
> Just published version `4.0.0`, which includes [grid layout](https://pqina.nl/filepond/docs/patterns/api/style/#grid-layout)

i already added this but 
`.filepond--item {
    width: calc(50% - .5em);
}`
this is the result, am i missing something?
![missed something](https://user-images.githubusercontent.com/24406362/53005766-7a057f80-3466-11e9-9d7f-e32fa52c9edf.gif)

**Comment by rikschennink** [comment]
I need more information. Please review issue template => https://github.com/pqina/filepond/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by aavram** [comment]
was the issue found to ThamrinPH's question? I have the same problem

**Comment by rikschennink** [comment]
@aavram please share a public demo, happy to take a look.

**Comment by aavram** [comment]
i actually figured it out; i just had to comment the previous css that was in the filepond.css file except for absolute positioning

**Comment by rikschennink** [comment]
@aavram fantastic! :-)

**Comment by Jesper54** [comment]
It works great, got it working in my laravel 8 project. Great work!

**Comment by QasimAsghar9** [comment]
Kindly someone tell me how to preview image in filepond

**Comment by rikschennink** [comment]
For clarity: https://pqina.nl/filepond/docs/patterns/api/style/#grid-layout

**Comment by QasimAsghar9** [comment]
Yes it is possible

**Comment by AMPZart** [comment]
Hi, 
How to remove the black frame around images?
The size of this frame remains unchanged regardless of the size of the image.
![Screenshot 2024-11-24 at 22-19-46 - TestVendeurId](https://github.com/user-attachments/assets/1dd1a734-ba18-4f96-b50f-8aaf418bb4cb)
Merci :)

**Comment by rikschennink** [comment]
@AMPZart I think setting `background:transparent` on the `.filepond--image-preview` element should work.

**Comment by AMPZart** [comment]
Thanks,
'transparent' doesn't solve the problem.
I often have very vertical or very horizontal images.
I guess a compromise of ratio must be found.
With some ratios the bands do not appear.
And if they appear I colored them in white.
```css
.filepond--root .filepond--image-preview{
background: #ffffff;
}

``` 

It is not possible to get each image in full?

(congratulations for this work. I tried Dropzone for a long time, but I had to abandon it because I could not transfer, at the same time, images and data to my controller. Filepond is great) 

![10_20_____Screenshot 2024-11-25 at 16-58-28 - TestVendeurId](https://github.com/user-attachments/assets/c55b8cd1-f8a9-4bcc-94fc-5832b921de7c)
![20_10____Screenshot 2024-11-25 at 16-59-51 - TestVendeurId](https://github.com/user-attachments/assets/a5fbdae2-b236-4174-b71c-e76df80aaed7)
![16_10_____Screenshot 2024-11-25 at 17-01-01 - TestVendeurId](https://github.com/user-attachments/assets/e048cf93-acfc-4e8d-a223-5fb5205fdad5)
![1_1_____Screenshot 2024-11-25 at 17-02-27 - TestVendeurId](https://github.com/user-attachments/assets/626e5897-e627-438a-823a-438d272ab429)
![1_1__blanc_Screenshot 2024-11-25 at 17-03-19 - TestVendeurId](https://github.com/user-attachments/assets/b9df0e0a-2182-4350-b7e3-8a268b453ad6)

**Comment by rikschennink** [comment]
All image tiles have to be the same size (in v4, this will no longer be the case in v5), so if you know the images are portrait, you can adjust the tile size to be portrait as well and that should improve things.

**Comment by programersi-lead** [comment]
Uploaded files container (previews) toggle to last grid element so.. effect:  if the smallest preview is a last one, other perviews get's out the container because contianer height is set by the last (smallest one).

Any advice?

**Comment by rikschennink** [comment]
@programersi-lead see https://pqina.nl/filepond/docs/api/style/#grid-layout

> Make sure that each item is the same height. FilePond currently calculates the height of the first item in the list and then uses that as the base height for each item. You can set the item height using styleItemPanelAspectRatio, imageCropAspectRatio, or by setting a fixed imagePreviewHeight.

**Comment by programersi-lead** [comment]
@rikschennink thanks for the quick reply and really great library!
