### ISSUE TITLE
IE11 - XMLHttpRequest hangs indefinitely

### ISSUE THREAD

**Issue by glennpenridge** [pqina/filepond#135]
Hi there, I'd like to submit a bug regarding IE11 XHR support for FilePond. I've included a fix for the bug as well. (At least, the bug that appears on my system.)

I am using FilePond 3.0.2.

### Summary

When FilePond prepares a POST request in IE11, the request hangs indefinitely.  It never fires a network request at all.

### How to Reproduce
**NB:** I know the steps for repro are for React, but the wrapper uses the core FilePond module to work so I figured it'd be more relevant here.

Fresh install of [create-react-app](https://github.com/facebook/create-react-app), `filepond-react`, `@babel/polyfill` and `filepond-polyfill`.

Tested with the following in `src/App.js` in the render method:
```js
<FilePond
  allowMultiple
  maxFiles={20}
  server={My Super Secret API URI}
/>
```

Attempting to make a network request to the server URI will never fire. (Drag and drop or browse actions.)

I've tested this in other browsers (Chrome, Firefox, Edge) and they don't have this issue.

### Expected Behaviour

Network requests should fire immediately and not hang indefinitely.

### Additional Information
This bug can be fixed by swapping some lines under `sendRequest` around so that it reads:
```js
    // add headers
    xhr.open(options.method, url, true);

    // set timeout if defined
    if (isInt(options.timeout)) {
      xhr.timeout = options.timeout;
    }
```

... instead of:
```js
    // set timeout if defined
    if (isInt(options.timeout)) {
      xhr.timeout = options.timeout;
    }

    // add headers
    xhr.open(options.method, url, true);
```

You can find a reference for this fix [here](https://github.com/stephanebachelier/superapi/issues/5).

No new bugs introduced from my tests in Chrome 69.0.3497.100, Firefox 62.0.3 or Edge 41.16299.611.0.

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Device       | Dell Optiplex 9020
| Browser      | IE 11 Version 11.611.16299.0

**Comment by rikschennink** [comment]
Thanks for the high-detail bug report @glennpenridge , super helpfull for fixing the issue.

**Comment by glennpenridge** [comment]
Thanks mate!
