### ISSUE TITLE
React wrapper - no onprocessfile event fired

### ISSUE THREAD

**Issue by lytvynenko** [pqina/filepond#14]
Hi! First of all, thank you very much for this library. Saved massive amount of time for us.

Here is an example https://codesandbox.io/s/x2zw6jzj24 (server code here: https://runkit.com/lytvynenko/5ab2b90f25eebc0012140268) , where "onprocessfile" event  isn't happening.

**Comment by rikschennink** [comment]
Thanks! Glad you like it!

Apparently, I somehow forgot to add the `onprocessfile` callback to the options object. Just did and published version `1.2.6`

**Comment by lytvynenko** [comment]
Woah! Blazing fast turnaround! You're absolute legend! Keep it up!
