### ISSUE TITLE
Validating Excel Files

### ISSUE THREAD

**Issue by jdriesen** [pqina/filepond#140]
### Summary
It seems that Filepond uses the file MIME types to check for valid filetypes.
Which I like a lot !

I'm using 
```javascript
acceptedFileTypes       = "application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, .xlsx"
```

This works PERFECTLY, as long as the MIME-type (content type) for the file is filled in...

Though, it seems, that certain versions of MSOffice (Excel) are NOT filling in the MIME-type of an Excel file. (*******)
See attachment.

(*******) It seems that in these particular situations, certain registry keys are not set...
More info can be found here: https://community.spiceworks.com/topic/128659-xlsx-file-will-not-associate-with-excel-2007-win7

This results is the fact that Filepond will NOT recognize this file as a valid file (although, it IS a valid file ...)
...

### How to reproduce
Well, that's rather difficult. (unless you already have the "Office version installed which causes the problem" ...

Unfortunately, I can NOT send you the EXCEL file, cause, as soon as you'll DETACH it on your computer, AND you've the regkeys set, it will automatically add the correct MIME-type to the file Properties (even without opening the file...)

I'm testing this locally by temporarily removing  the regkeys... (don't forget to take a backup of your registry !!)

### Expected behaviour
If would be great if Filepond accepts valid Excel files, even when the MIME-type is missing (i.e. 'empty string')
...

### Additional information
When I'm uploading my file (with the missing MIME-type) to https://sheet.zoho.com/sheet/excelviewer , everything works fine ...

So, in one way or another... it should be possible to upload ExcelFiles with a missing MIME-type
...

| Environment  | Version
|------------- | -----------
| OS           Windows 
| Device       Any Computer
| Browser      Chrome
![excel_properties](https://user-images.githubusercontent.com/1137648/46745529-8bb36b00-ccad-11e8-83be-0e6660490829.PNG)

**Comment by rikschennink** [comment]
You’re in luck!

I’ve published a new version of the file validation plugin this afternoon and it allows setting a custom file type detector function (see docs). 

You can use this method to test if the default analysis resulted in an empty string and if so you can then return a correct mime type. Either by basing it on the file extension or for instance actually reading the file data with FileReader.

**Comment by jdriesen** [comment]
PS... You're saying "see docs" ...
Are you talking about the online docs at https://pqina.nl/filepond/docs/patterns/plugins/file-validate-type/ ?
(don't see anything related with "custom filetype detector", that's why I'm asking)

Thanks in advance for your replu.

Grtz,
Johnny

**Comment by jdriesen** [comment]
Found the docu...
Thought not yet 100% clear to me how to use it... 
(sorry) ...

**Comment by rikschennink** [comment]
No worries! :-)

I’ve written an example function in this comment:
https://github.com/pqina/filepond-plugin-file-validate-type/issues/6#issuecomment-428554985

If needed I’m happy to help out tomorrow morning.

**Comment by jdriesen** [comment]
Clear docu. Thanks man. Great support.

I'm using Filepond with Vue...
Is this function also available in the Vue Instance ?

**Comment by rikschennink** [comment]
If you update the file validate type plugin to the latest version it should be available no matter the adapter used.

**Comment by rikschennink** [comment]
Hi @jdriesen, it seems like you need to set the `acceptedFileTypes` array, this method is only for detecting the type, the validator still needs to have a list of acceptable file types.

**Comment by jdriesen** [comment]
Thanks for your prompt reply ...

Even with the "acceptedFileTypes" array set, the function is not performed.

(Just as an info, and see also my post from yesterday ... the AcceptFileTypes will return a "not accepted" cause my MimeType is and empty string" ...)

**Comment by rikschennink** [comment]
Looking at the detector method again, it seems like it's not returning the Promise.

```js
methods: {

detector(source, type) {
  // This function is never executed...           
  console.log("In Detector")
  return new Promise((resolve, reject) => {
         console.log(source, type);
         // do custom type detection here and return with promise
         resolve(type);
      })  
  }
}
```

I'm not sure if the detector should be in the `methods` list. It's basically a function that stands on its own, it's an event or anything so the `@` doesn't work.

I haven't tested this code snippet but I think it should be configured something like this:

```vue
<template>
  <div id="app">
    <FilePond :fileValidateTypeDetectType="detectorFunction"></FilePond>
  </div>
</template>

<script>

export default {
  data() {
    return {
      detectorFunction:(source, type) => new Promise((resolve, reject) => {
        // ...
      })
    }
  },
```

**Comment by jdriesen** [comment]
Feedback at lightning speed.
Thanks @rikschennink 

Will test it ASAP and will provide Feedback

**Comment by jdriesen** [comment]
**This is working like a CHARM !!**

Really great piece of software, and wonderful support !

Thanks again @rikschennink

**Comment by rikschennink** [comment]
Fantastic! :-)

**Comment by jdriesen** [comment]
Extra small remark ...

When using the :fileValidateTypeDetectType = "detectorFunction", the 
acceptedFileTypes param becomes obsolete in the component definition

(cause all validation now has to be done in the "detectorFunction)


In case it might help somebody ...
This is my detectorFunction
```javascript
detectorFunction:(source, type) => {
        console.log("in detectorFunction")
        return new Promise((resolve, reject) => {
          // console.log(source, type);
          
            // do custom type detection here and return with promise
            let validTypes = [
              "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
              "application/vnd.ms-excel",
              "application/vnd.oasis.opendocument.spreadsheet"
            ]
            
        
            // Check of Valid MIME type
            let bCondition01 = (validTypes.indexOf(type) > -1)
            
            // In case MIME-Type is empty ... check for extention
            let ext = source.name.slice(-5).toLowerCase()
            let bCondition02 = (type == "") && (ext === ".xlsx")
            
            if (bCondition01 || bCondition02) {
              resolve(validTypes[0])
            } else {
              reject()
            }
            
            // resolve(type);
          })
      }, // End of detectorFunction
```

**Comment by rikschennink** [comment]
It depends on the implementation, FilePond will try to detect the type using browser methods and pass the type that it has detected to the `detectorFunction`.

You can rewrite the above method to only test if `type` is empty and then correct the mime type based on the extension.

**Comment by jdriesen** [comment]
Well, that's what I tried, and this was NOT working ... (sorry to say ...).
That's why I came up with this solution...

**Comment by rikschennink** [comment]
With or without `acceptedFileTypes` property?

**Comment by jdriesen** [comment]
With "acceptedFileTypes" ...

My idea was (at least, how I was thinking it would work out of the box...)

- If the MIME type matches one of the "acceptedFileTypes", it is an accepted file
- if the MIME type does NOT match one of the "acceptedFileTypes", the "detectFunction" is performed.

Though, this didn't seem to be the case...
That's why I REMOVED the "acceptedFileTypes", and moved all my "logic" to the function ...

Hope this clarifies my situation a bit ...
If not ... please let me know ...

**Comment by rikschennink** [comment]
It will always call the detect method, even if it detected a type, this is to allow correction of the mime type even if it seems correct.

**Comment by jdriesen** [comment]
Perfectly clear.
Thanks @rikschennink
