### ISSUE TITLE
Question: How to trigger revert

### ISSUE THREAD

**Issue by SephVelut** [pqina/filepond#143]
Thank you for this great plugin. I'm aware that by providing a `{server: { revert:(...) => {` object to `setOptions` will allow you to define custom operations processing uploaded files. But lets say I want to add some extra buttons to the uploader for several tasks, besides obviously creating my own onClick handlers, how can I, given a upload id already, inform filepond to revert an upload? 

I know there's a cancel button built in but my needs are more specific.

I'm using filepond with Vue as a single page component.

**Comment by rikschennink** [comment]
The `revert` handler is triggered by the `removeFile` call, so maybe you can use that?

**Comment by SephVelut** [comment]
Is there anyway to call `removeFile` from `vue-filepond`? I'm using filepond with vuejs

**Comment by zoicho** [comment]
> The `revert` handler is triggered by the `removeFile` call, so maybe you can use that?

i dont think this is true, did you try?

**Comment by rikschennink** [comment]
@sbusch You're right, it doesn't call the `revert`, see test case: https://codesandbox.io/s/vanilla-filepond-revert-remove-o2yqo?file=/src/index.js

Will see if I can pick this up later this week.

**Comment by rikschennink** [comment]
@sbusch should be fixed in 4.13.5, please confirm.
https://github.com/pqina/filepond/releases/tag/4.13.5

**Comment by sbusch** [comment]
@rikschennink first thank you for your effort! I now had the time to test it the new release. Unfortunatley it doesn't work for me.

When I call `filepond.removeFile()`, the first uploaded file is removed from view but no `DELETE` request (as defined by `server.revert`) is submitted.

The reason is - at least - that the file's `origin` is 1 (== `FileOrigin.INPUT`), so your change at https://github.com/pqina/filepond/blob/044a7ca00393b6f03cf732ae61a2ce6a876ad8a1/src/js/app/actions.js#L906 does not apply. I wrote "at least" because I'm not sure if `item.revert(createRevertFunction(...` would issue such a DELETE operation at all...

**Comment by rikschennink** [comment]
@sbusch just published 4.13.6 which should fix this issue

**Comment by sbusch** [comment]
Works for me, `removeFile()` and `removeFiles()` trigger the `DELETE` request :-)

Thank you very much!

**Comment by rikschennink** [comment]
@sbusch this functionality has been reset in `4.13.7` as it caused backwards incompatibility issues, you can still trigger revert by adding `{ revert: true }` as a parameter to `removeFile()` or `removeFiles()`

**Comment by sbusch** [comment]
@rikschennink Thanks for the heads-up, didn't expect that kind of service! I'll update & test it

**Comment by sbusch** [comment]
@rikschennink better late than never:

`removeFile()` works as expected:

- `removeFile({revert: false})` removes first element and doesn't revert (= no `DELETE` XHR)
- `removeFile({revert: true})`  removes first element **and reverts the upload** with a `DELETE` XHR

But I cannot get `removeFiles()` working.  Behavior is the same for `removeFiles({revert: false})` and `removeFiles({revert: true})`, always:

- all items are removed from list
- a revert with `DELETE` XHR is issued for the first file (independent of `revert` option)

Am I holding it wrong? ;-)

**Comment by rikschennink** [comment]
@sbusch should be fixed in release 4.19

**Comment by ryanzzeng** [comment]
Is it possible to remove specify file by passing the id, it always remove the first file? 

Can we do some thing like `this.$refs.filePond.removeFile({ revert: true, id: serverId });` ? (passing the actualid id in DB)
