### ISSUE TITLE
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by leoliu** [pqina/filepond#145]
A user of mine that is using a laptop with only 2G ram often gets the following crash on Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36:

```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
  at l(/assets/js/main-f3b1015f23.js:68:35814)
  at ? (/assets/js/main-f3b1015f23.js:68:40458)
```

Images are normally less than 25M in size so the OOM crash is a bit out of proportion.

**Comment by rikschennink** [comment]
Had some time to search around and found this related Chromium issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=242215

Which plugins are you using and can you post your settings?

**Comment by rikschennink** [comment]
The latest version of the image preview plugin features improved memory usage. Can you re-test and let me know if the problem still occurs. Will close in the mean time.

**Comment by leoliu** [comment]
Thanks. I have the latest version in production now and will post back if something happens.
