### ISSUE TITLE
Drag and re-order files before upload

### ISSUE THREAD

**Issue by leoliu** [pqina/filepond#146]
I have received a report from a user that a feature disappeared recently. Previously it was possible to drag and re-corder files before uploading them. Now it is not possible any more. Is this intentional?

I have checked the documentation and commit log but could not find anything related to this change.

**Comment by clementmas** [comment]
Well that'd be a great plugin to have :) Is this something you're considering on your roadmap?

Meanwhile, is there any way to reverse the default order (i.e. insert new files at the bottom of the list)?

**Comment by rikschennink** [comment]
An earlier version of FilePond had it but I removed it to get to 1.0 quicker, will probably add it in the future somewhere if demand grows.

**Comment by kelong** [comment]
I also need reverse sorting and it's critical for me. Trying to hack it somehow right now with no luck :(

**Comment by rikschennink** [comment]
@kelong I'm currently working on a grid view, which also required rewriting the way files are dropped, I might add sorting to the mix as well.

**Comment by kelong** [comment]
@rikschennink Great thanks. That would change a lot. How long do you think it would take to do that?

**Comment by rikschennink** [comment]
@kelong Can't give time estimate as this is work that is done in between other work

**Comment by rikschennink** [comment]
@kelong @clementmas No drag and drop yet but I've added [file sorting](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#sorting-files) in version `4.0.0`

**Comment by smickar** [comment]
Hi, when you finish drag and drop file sorting, could you also change hidden input field "filepond" with file ID to an array (<input type="hidden" name="filepond[]" value), or to filepond1 .... filepond100000 :). So it will be easy to write sorting to db on server (now I receive only one variable filepond) Thank you.

**Comment by rikschennink** [comment]
@smickar are the files not sorted correctly?

**Comment by smickar** [comment]
Hi, it is not about sorting, but about that every file hase same hidden input name "filepond". So when I submit form with Filepond I receive only one variable "filepond", even if I have xx files.

**Comment by rikschennink** [comment]
@smickar, that's basically how it works at the moment, this is how the PHP boilerplate functions: https://github.com/pqina/filepond-boilerplate-php

**Comment by violabg** [comment]
Hope ti see manuale sorting soon

**Comment by p-young** [comment]
Also hoping to see this feature implemented!

**Comment by alperbicer** [comment]
hi @rikschennink, is there any development about drag and drop sorting?

**Comment by rikschennink** [comment]
I've developed a tiny prototype but so far haven't had time to work on it further.

**Comment by KilledDebtor** [comment]
I did not find any uploader with manual sorting :(

**Comment by andonimihai** [comment]
@KilledDebtor I think this one is a good example: https://innostudio.de/fileuploader/

**Comment by yqlim** [comment]
I have written a simple plugin for this: https://github.com/yqlim/filepond-plugin-drag-reorder

It has been tested for ajax submission. It has not been tested with FilePond upload feature however.

**Comment by caroliina** [comment]
Is the prototype code available somewhere? I am also super interested in this feature. I agree with a previous comment that it should apply to existing files (I want to implement a way to manually sort existing + new images and save them with their sequence information). @yqlim solution might do the trick though, I need to test it out. Thank you!

**Comment by jwsinner** [comment]
There is a work around until the official solution gets pushed. It's rough, but it gets the job done.

1. In filepond.js create a global variable just after 'use strict' to store an index value.
`(this, function (exports) {
	'use strict';

	var idx;
	var isNode = function isNode(value) {
		return value instanceof HTMLElement;
	};`
2. In the write$5 (around line 8913) function, assign the value of dragIndex to your global index variable.
`// get index
		var dragIndex = dragCoordinates
			? getItemIndexByPosition(root, dragCoordinates)
			: null;
		idx = dragIndex;`
3. Declare a function variable in the public API section that returns your global index variable.
`//
		// PUBLIC API -------------------------------------------------------------------------------------
		//
		var setOptions = function setOptions(options) {
			return store.dispatch('SET_OPTIONS', { options: options });
		};

		var getFile = function getFile(query) {
			return store.query('GET_ACTIVE_ITEM', query);
		};

		var getDraggedIndex = function getDraggedIndex() {
			return idx;
		}`
4. In the createOptionAPI declaration around line 11496 create a reference to the function you created above.
`createOptionAPI(store, defaultOptions),
			{
				/**
				 * Override options defined in options object
				 * @param options
				 */
				setOptions: setOptions,

				getDraggedIndex: getDraggedIndex,`
5. Now that you have a reference to the index, you can use this with your FilePond instance. In the addfile event, make each file added draggable, then add dragstart and dragend event listeners.
`$('.filepond--list').children().attr("draggable", true);

				var imgs = document.querySelectorAll(".filepond--item");
				[].forEach.call(imgs, function(col) {
					col.addEventListener('dragstart', dragStart, false);
					col.addEventListener('dragend', dropped, false);
				});`
6. In dragstart, get the file id from the event target id, store the file in a new variable, then remove the file from the FilePond instance. Then in the dragend function get your index value and add the new file at that index.
`var newFile;

		function dragStart(event) {
			var itemId = event.target.id.substring('filepond--item-'.length);
			newFile = pond.getFile(itemId);
			pond.removeFile(itemId);
		}

		function dropped(event) {
			var index = pond.getDraggedIndex();
			pond.addFile(newFile.file, { index: index });
		}`

**Comment by rikschennink** [comment]
👉 https://twitter.com/rikschennink/status/1205139448360509442?s=20

**Comment by jwsinner** [comment]
Looking good. Can't wait for the update. I've hacked together a rough drag and drop reordering so it'll be nice to have something cleaner to work with.

**Comment by rikschennink** [comment]
First reorder by drag/drop has been added in `4.9.1`.

- Enable with `allowReorder`
- Only works in column mode (not yet in grid)
- Only works on browsers that support Pointer Events, that's most browsers nowadays.
- Works when files list shows scrollbar but still needs some tweaks.

**Comment by EmmanuelJego** [comment]
@rikschennink You made my day ! Really nice, thanks for your work !

**Comment by nusoft** [comment]
@rikschennink Thanks a lot for this update! Is there (or will there be) a Callback for listening to reordering events? Or is there another way to get the order of the files when it changes?

**Comment by rikschennink** [comment]
@nusoft That sounds like a good idea. It currently does not trigger any events.

**Comment by OneMajed** [comment]
@rikschennink I enabled `allowReorder` but it didn't work with me.. I just want to get the order of elements once I submit the form. How would I do that?

**Comment by rikschennink** [comment]
Hi @OneMajed I don't understand how this is related to re-order, can you elaborate

**Comment by OneMajed** [comment]
Currently, I am sending the images using ajax.
What I need to achieve is once I submit the form with the images, I need the images order to be sent to my backend with the same order displayed. How can I receive this list (for example as a json)

Thanks @rikschennink

**Comment by rikschennink** [comment]
@OneMajed `getFiles` should return the correct order.

**Comment by OneMajed** [comment]
Thanks @rikschennink it worked with me

**Comment by prince272** [comment]
Any plans to support grid reorder. Only works in column mode.

**Comment by rikschennink** [comment]
@prince272 https://github.com/pqina/filepond/pull/421

**Comment by rikschennink** [comment]
Now available in `4.15.0`
