### ISSUE TITLE
Event "FilePond:removefile" not working since v3.1.2

### ISSUE THREAD

**Issue by dreamon11** [pqina/filepond#149]
Since v3.1.2, the event "FilePond:removefile" is not working when click on Remove button.

Works in v3.1.1.

```
$('.my-pond').on('FilePond:removefile', function(e) {
  console.log('file removed event', e);
});
```

| Environment  | Version
|------------- | -----------
| OS           | Debian
| Device       | PC
| Browser      | Firefox

**Comment by rikschennink** [comment]
Thanks so much for reporting, I just published version `3.1.6` which resolves this problem.

**Comment by rikschennink** [comment]
Just published version `3.1.6` which fixes this issue.

**Comment by radicaljhonpaul** [comment]
jquery-filepond not working

        $('.my-pond').on('FilePond:removeFile', function(e) {
            console.log('file added event', e.detail.file.file);
        });

but it works on addFile

**Comment by rikschennink** [comment]
It should be `removefile` lowercase.

**Comment by radicaljhonpaul** [comment]
Oh, yeah I figured it out yesterday. Thanks by the way. hahhaa

**Comment by fidahasan** [comment]
> It should be `removefile` lowercase.

ohhhh man i was about to tear my last hair ... LOWERCASE ffffffffffffff NOT FFFFFF
