### ISSUE TITLE
Parameter available on event functions

### ISSUE THREAD

**Issue by pathvine** [pqina/filepond#15]
Hi @rikschennink,

For the `pond.on(event, function)`, the `addfile` event yields parameters of (error, file) for the callback function. Do you happen to have a list of what parameters are available for other events such as processfile and removefile, etc.?

**Comment by rikschennink** [comment]
Hi @pathvine, I'm updating the docs now. In the meantime, the handler parameters are the same as the [callback parameters](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#callbacks).
