### ISSUE TITLE
Reload and delete button rendering problem in Wordpress and iOS

### ISSUE THREAD

**Issue by mwenell** [pqina/filepond#152]
### Summary
I'm developing Wordpress plugin for filepond. After image upload, the x and reload buttons are not circle as they should be. Instead it is oval which begins form left side of image and ends at the right side of the image. This does not happen in desktop, only in iOS Safari.

This might be a css conflict in wordpress as well.
...

### How to reproduce
Go to following URL with iOS phone (iOS Safari) and take a photo to upload. Wait until the image is uploaded and x button (circle, green) will appear and it should be oval this time.

URL to test page:
https://demo.mydatabankapp.com/diary_demo/
...

### Expected behaviour
Expected the x button to be circle as it is in desktop.
...

### Additional information
I'm developing Wordpress plugin implementing filepond shortcode. It can be used e.g. together with Ninja forms and other form plugins. However, I did not find any reason or bug in my code. And it was difficult to find what CSS value does this.
...

| Environment  | Version
|------------- | -----------------
| iOS                | 12.0.1 (16A404)
| iPhone          | 6S
| Safari            |

**Comment by mwenell** [comment]
Thanks. It works fine.

**Comment by rikschennink** [comment]
Alright, great! I've updated the CSS of FilePond so a future release will bring more specificity to layout specific styles which should result in less collisions.
