### ISSUE TITLE
Infinite "Uploading" message when trying to LOAD a file from server

### ISSUE THREAD

**Issue by micrac** [pqina/filepond#153]
Hello,

### Summary
I am working with Angular + Node/Express project. I am using **filePond** to upload images to the server as a part of data form (e.g. registration form with photo). I also added plugin `filepond-plugin-image-preview`. Part of the task is to be able to edit previously uploaded image using code from Server section of filepond documentation. 

At the moment I can download the file from server (temporary solution is to get it from HD) which is displayed in filepond control on the page. I can see the picture but 100% sign does not appear. I see infinite "Uploading" message. I have no idea how to push things forward:
![obraz](https://user-images.githubusercontent.com/21370613/47710786-f106d600-dc33-11e8-914a-0b05141f33db.png)

I did a bit of debugging and found, that in the below case status is never set to `ItemStatus.PROCESSING_COMPLETE`. I found the section:

```javascript
// file received
          if (origin === FileOrigin$1.LIMBO && state.serverFileReference) {
            setStatus(ItemStatus.PROCESSING_COMPLETE);
          } else {
            setStatus(ItemStatus.IDLE);
          }
```
But my case is not LIMBO but LOCAL. 

The other one is:

```javascript
      processor.on('load-perceived', function(serverFileReference) {
        // no longer required
        state.activeProcessor = null;

        // need this id to be able to rever the upload
        state.serverFileReference = serverFileReference;

        setStatus(ItemStatus.PROCESSING_COMPLETE);
        fire('process-complete', serverFileReference);
      });

```
But this one is neither called.

I also saw that the code:

```
      var progressFn = function progressFn() {
        // we've not yet started the real download, stop here
        // the request might not go through, for instance, there might be some server trouble
        // if state.progress is null, the server does not allow computing progress and we show the spinner instead
        if (state.duration === 0 || state.progress === null) {
          return;
        }
        // as we're now processing, fire the progress event
        api.fire('progress', api.getProgress());
      };
```
never passes the first if condition, therefore `api.fire('progress', ...` is never called.
### How to reproduce
The code to reproduce:

**Client code:**

```javascript
pondFiles = [
    {
        source: 'file-name',
        options: {
            type: 'local'
        }
    }
]  

pondOptions = {
    class: 'my-filepond',
    multiple: true,
    labelIdle: 'Drop files here',
    acceptedFileTypes: 'image/jpeg, image/png',
    server: {
        url: "https://localhost:1444",
        process: "./upload",
        load: 
        (uniqueFileId, load, error, progress, abort, headers) => {
            // Should request a file object from the server here ...

            const req = new XMLHttpRequest();
            req.onprogress = (e) => {
                progress(true, e.loaded, e.total);
            }
            
            req.onload = function() {
                if (req.status >= 200 && req.status < 300) {
                    // the load method accepts either a string (id) or an object
                    progress(true, 1,1);
                    load(req.response);
                }
                else {
                    // Can call the error method if something is wrong, should exit after
                    error('oh no');
                }
            } 
            
            req.open("GET", "https://localhost:1444/load/tst.jpg", true);
            req.responseType = "blob";
            req.send();
            
            // Should expose an abort method so the request can be cancelled
            return {
                abort: () => {
                        // User tapped cancel, abort our ongoing actions here
                        // Let FilePond know the request has been cancelled
                        abort();
                   }
             };
        }
    },
    allowImagePreview:	true,
    imagePreviewMinHeight: 128,
    imagePreviewMaxHeight: 256
  }
```

and on template:

```html
<file-pond #myPond 
                [options]="pondOptions" 
                [files]="pondFiles"
                (oninit)="pondHandleInit()"
                (onaddfile)="pondHandleAddFile($event)"
                >
</file-pond>

```
**Server code (exposed at httsp://localhost:1444):**
```javascript
app.get('/load/:ff', function(req, res) {

    console.log("APP.LOAD");

    var __dirname = './upload';
    var options = {
        root: __dirname + '', //'/public/',
        dotfiles: 'deny',
        headers: {
            'x-timestamp': Date.now(),
            'x-sent': true,
            'Content-Disposition': 'inline',
            'filename': "my-file.jpg"
        }
      };
      var fileName = req.params.name;
      // the real file on HD (in relative path __dirname)
      fileName = 'filepond-1540716142035.jpeg';
      res.sendFile(fileName, options, function (err) {
        if (err) {
          next(err);
        } else {
          console.log('Sent:', fileName);
        }
      });
});
```

### Expected behaviour
I would like to see the picture with progress indicator set to 100%.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | Windows win32 x64
| Device       | PC.
| Browser      | Chrome 70.0.3538.77 (Official version) (64-bit) and Firefox 63.0 (64 bit)
|Angular CLI| 6.1.5
|Node| 8.11.3

**Comment by rikschennink** [comment]
Is the custom load method called?

**Comment by micrac** [comment]
I am not sure what you mean by 'custom'. The only `load `method I call is the one inside `onload` callback. I verified - it is called for sure - as the result I can see preview of the image.

**Comment by rikschennink** [comment]
@micrac I mean the `server.load` method, FilePond should call it to load the initial file, if I understand correctly the red car === `https://localhost:1444/load/tst.jpg`

**Comment by micrac** [comment]
Correct, the server send out red car. I see it in browser for test as well as in preview.

**Comment by rikschennink** [comment]
With these setting it should mark the file as already uploaded (green), it shouldn't start the upload process.

**Comment by micrac** [comment]
Yes, this is my problem. I know that the whole picture is dowloaded from the server (verified), I know the progress is set to 100%, I call load (as in example for filepond). I don't know what I am missing.

**Comment by micrac** [comment]
Forgot to add: filepond v 3.2.5

**Comment by rikschennink** [comment]
I've updated my comment, it shouldn't show the file in green (as that is for just uploaded files a.k.a. temp/limbo files). It should however not get stuck at 100%.

I've tested and this code snippet does set the file to the correct state, so I'm guessing something happens in your load method causing it to not run the `load` callback.

```js
export class AppComponent {

  pondOptions = {
    server: {
      load: (uniqueFileId, load, error, progress, abort, headers) => {
        fetch('./index.html').then(res => res.blob()).then(load)
      }
    }
  }

  pondFiles = [
    {
      source: '123456',
      options: {
        type: 'local'
      }
    }
  ]

}
```

**Comment by micrac** [comment]
I have tested your example - works correctly, ends as expected, shows grey background.
However if instead of HTML you would use a picture the problem remains although it is a bit different. Here is the code:

```javascript
pondOptions = {
    class: 'my-filepond',
    multiple: true,
    acceptedFileTypes: 'image/jpeg, image/png',
    server: {
        // ###### PROCESS SECTION ########
        //url: "https://localhost:1444",
        //process: "./upload",
        // ###### End of: PROCESS SECTION ########
        load: (uniqueFileId, load, error, progress, abort, headers) => {
            fetch('https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/New_Logo_Gmail.svg/185px-New_Logo_Gmail.svg.png').
                then(res => res.blob()).
                then(load);
        }
  }}
 
  pondFiles = [
    {
        source: '444',
        options: {
            type: 'local'
        }
    }
  ]
```
As a result I have:
![obraz](https://user-images.githubusercontent.com/21370613/47774123-6afa9600-dcec-11e8-88b8-12e644ec0a98.png)
with console message: `POST https://localhost:4200/ 404` (i.e. it tries to upload but `process` is not defined.
When I uncomment `##### PROCESS SECTION ######` the old problem reappears:
![obraz](https://user-images.githubusercontent.com/21370613/47774266-cdec2d00-dcec-11e8-9966-d53927a4e2eb.png)

It seems that when using preview-plugin and operating on images filepond gets the image from server and then automatically tries to upload it using `process`.

**Comment by rikschennink** [comment]
I've reproduced the issue, it seems that this did work in an older version of FilePond, will test some more and get back to you.

**Comment by micrac** [comment]
I have installed preview plugin v 3.0.0. Works ok, so the issue should be logged there

**Comment by rikschennink** [comment]
It's an internal FilePond issue, I'm now working on a fix.

**Comment by rikschennink** [comment]
I've just updated the `ngx-filepond` adapter to version `4.0.1`, it now has FilePond as a peerDependency. FilePond has been updated to version `3.3.0` and the image preview plugin has been updated to version `3.1.3`. Updating all modules should resolve the issue.

**Comment by micrac** [comment]
Hi, I have installed ngx-filepond (npm i ngx-filepond) but filepond did not get updated. I had to do it manually. But filepond works like a charm. Thanks a lot.

BTW - great tool, everything you need is there :-)

**Comment by techuila** [comment]
@rikschennink I'm having the same issue. it uploads automatically after loading files from the server.

**Comment by techuila** [comment]
In my case, calling a setMetadata onaddfile uploads the loaded file from the server
`onaddfile={(error, file) => {
      if (!error) {
        file.setMetadata('points', `point_${state.editedItem.point_nr || point_temp.point_nr }_${state.editedItem.id || point_temp.id }`)
         file.setMetadata('uniqueid', `_${new Date().getTime()}`)
        }
    }}`

**Comment by rikschennink** [comment]
You can do a silent update by passing `true` as the third parameter.
```js
onaddfile={(error, file) => {
  if (error) return;
  file.setMetadata('points', `point_${state.editedItem.point_nr || point_temp.point_nr }_${state.editedItem.id || point_temp.id }`, true)
  file.setMetadata('uniqueid', `_${new Date().getTime()}`, true)
}}
```
