### ISSUE TITLE
how to capture an event when the file limit has been exceeded?

### ISSUE THREAD

**Issue by alorenc** [pqina/filepond#156]
If I set maxFiles to 3 and want to send more files, it should return an error, can I somehow capture this event? To display the appropriate message to the user.

**Comment by alorenc** [comment]
It does not work for me. I'm using vue-filepond.

The onWarning event used in <filepond @warning ...> does not return a message.
I also tried: window.addEventListener ('FilePond: onwarning', ... but this also returns nothing.

Attempting to upload more files does not pass through any v-on events.

**Comment by rikschennink** [comment]
Confirmed, will be fixed in next update of filepond core.

**Comment by rikschennink** [comment]
Just published version `3.3.1` of FilePond core and version `4.0.1` of vue-filepond. FilePond has been moved to the peer dependencies list so you'll have to install it separately. Please confirm this fixes the issue, you might have to

**Comment by alorenc** [comment]
Thank you very much, it works.

**Comment by muhyilmaz** [comment]
This file count limiter not working properly. It must be updated. There is no exception or message for maxFile property when it passes the limit.

**Comment by kso9115** [comment]
warning event

It does not work for me.
I am using FilePond 4.32.7 version.
If you set the maxFiles attribute to 3, I want an alarm window to pop up when you attach four files
