### ISSUE TITLE
Not updating the progress to success

### ISSUE THREAD

**Issue by vanko0309** [pqina/filepond#157]
I am using FilePond to upload the file to my server with a web socket, I am updating the progress like so: progress(true, data.received, blobSize); and when the loader reaches 100% it stays there and it doesn't change the status to success. Is this a bug or is there a workaround? I am using the react plugin.

**Comment by vanko0309** [comment]
Can you give me an idea how can this happen? I am using the following code

handleProcessing(fieldName, file, metadata, load, error, progress, abort) {
   //doing some stuff here 
   if(socket is open){
   progress(true, data.received, blobSize);
  }
}

And my implementation of the FilePond looks like:

<FilePond ref={ref => this.pond = ref}
                    server={{
                        process: this.handleProcessing.bind(this)
                    }}...>
</FilePond>

**Comment by rikschennink** [comment]
```js
handleProcessing(fieldName, file, metadata, load, error, progress, abort) {
   //doing some stuff here 
   if(socket is open){
   progress(true, data.received, blobSize);
   // you could compare data.received with blobSize I guess?
   if (progress is at 100%) {
       load()
    }
  }
}
```

**Comment by vanko0309** [comment]
Thank you a lot!
