### ISSUE TITLE
Create typescript typing

### ISSUE THREAD

**Issue by hgenru** [pqina/filepond#159]
Typescript typings can help new users with your awesome library. Typing [used in VSCode](https://code.visualstudio.com/docs/languages/javascript) for IntelliSense for all javascript projects. Also, typescript is a very popular choice in the angular community.

Do you have plans about this?

I will create a simple typing for filepond because in my team typings is required. Or, if you have groundwork I can help with it.

**Comment by rikschennink** [comment]
I’ve got literally zero experience with typescript so I’m open to suggestions and pull requests. :)

**Comment by hgenru** [comment]
Hello @rikschennink! Sorry about long time response. I had too many works.

There is draft typing for FIlePond: https://gist.github.com/hgenru/7a7aa4af2dc0e9e704777655e9182cc8

If we consider using your library in our project I will update this typing and, maybe, create a PR.

**Comment by hgenru** [comment]
The bigger problem is plugins options in the main options object. Currently, I have no idea how to extend options with plugins options only when a plugin is connected.

But it not only typing problem btw.

**Comment by rikschennink** [comment]
I ran into similar problems with Angular. I don't know how to solve this. I would eventually like if everyone can write plugins, I see that might cause trouble with things like TypeScript?

**Comment by rikschennink** [comment]
Thanks, I'll look into that when I have some time, it's currently not one of my top priorities, to be honest.

**Comment by Hawxy** [comment]
@rikschennink Is this going to be worked on at some point? It's kinda a pain point as more and more people are using TS to write front-ends. The only typing's available for FP right now are for the [react wrapper](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-filepond/index.d.ts)

**Comment by rikschennink** [comment]
@Hawxy I've gained some more experience with TS while added a TypeScript definition file to [Doka](https://pqina.nl/doka/). It's simply a time consuming process of converting the options definition file and the public API to a .d.ts file, if you're experienced with TypeScript and are in need of this feature, please submit a PR, I'll get around to it eventually.
