### ISSUE TITLE
Need help getting started.

### ISSUE THREAD

**Issue by hazemati** [pqina/filepond#160]
Hey, 
I really wnat to use your library, but need help getting started. I looked at your example code on the following link, https://pqina.nl/filepond/#examples and can't get it to work (it seems like a copy paste job, so there's no way I could've misread anything). Is there something missing from that example?

**Comment by rikschennink** [comment]
You have to include the right CSS and JS files, that's it.

Best to use the codepen as a starting point:
https://codepen.io/rikschennink/pen/WXavEx
