### ISSUE TITLE
How to disable the Filepond Instance

### ISSUE THREAD

**Issue by nemo220** [pqina/filepond#161]
Hi, First off... amazing library! 

Usually you can disable <input> fields with the attribute disabled="disabled". How do you disable filepond via it's options. PS I'm using the Angular Filepond Version.

ie. I want the filepond instance to be a read-only input...

Thank you for your contribution 🖤

**Comment by rikschennink** [comment]
Hmm, good one! Would be nice to read the `readonly` and `disabled` attribute by default.

In the meantime you could use the `allowDrop`, `allowBrowse`, and `allowPaste` properties to disable file input. If you've got files in the list you might have to disable the remove buttons as well using CSS.

**Comment by kezek** [comment]
A readOnly or disabled prop (flag) would be useful for me as well , if you've got time to get to it :)

**Comment by rikschennink** [comment]
Just published version `4.2.0` which adds `disabled` feature. 

Set `disabled` as a property or as an attribute to the file input and the field will be disabled.

This means:
- Browsing, dropping, and pasting will no longer work.
- File buttons will be disabled.
- Hidden input fields will be disabled as well.
- Opacity on drop label is set to `0.5`.

Let me know if this solves the issue

**Comment by kezek** [comment]
Testing it right now , I'll let you know if I get into any issue. 

Thanks !!

**Comment by nemo220** [comment]
works as expected ✨✨

your dedication is everything 
thanks @[rikschennink](/rikschennink)

**Comment by rogeliotg** [comment]
just add it to the docs too

**Comment by rikschennink** [comment]
@rogeliotg done

**Comment by kulnaman** [comment]
when a file pond instance is disabled there is no way to re-enable it, setting option disabled=false; does not enable the file pond instance, is there a way of re-enabling that file pond instance.

**Comment by rikschennink** [comment]
@kulnaman fixed in `4.3.9`

**Comment by SalkiDixit** [comment]
@rikschennink Hi I am trying to use disabled property but its not working. Would please assist.
<file-pond #myPond
              (disabled)="uploadState === 'completed'"
              [options]="pondOptions"
              [files]="pondFiles"
              (oninit)="pondHandleInit()"
              (onaddfile)="pondHandleAddFile($event)">
</file-pond>

**Comment by TechMky** [comment]
@rikschennink Thanks for this great library. I had a use case where I didn't want the user to change any already uploaded file. 

I didn't know that it was as simple as just changing the property of the input tag.

**Comment by kirikintha** [comment]
> when a file pond instance is disabled there is no way to re-enable it, setting option disabled=false; does not enable the file pond instance, is there a way of re-enabling that file pond instance.

I had the same issue while using react and how we were controlling file input conditionally. You can use:

`pond.setOptions({ disabled: true|false }); // enable or disable.` - to enable and disable the pond instance you are using, so you do not have to re-create the instance.

**Comment by ranYaar** [comment]
while the instance is disabled and then become enabled, the browse (<span class="filepond--label-action">Browse</span>) will be needed to clicked twice.

**Comment by rikschennink** [comment]
@ranYaar can you create a test case on code sandbox? you can use this sandbox as a starting point: https://codesandbox.io/s/vanilla-filepond-2oltb?file=/src/index.js

**Comment by arc95** [comment]
For jQuery: `$("#filePondControl").filepond("disabled", true|false);`
