### ISSUE TITLE
Paste Feature uploads the HTML of the file not the image.

### ISSUE THREAD

**Issue by JelliottR** [pqina/filepond#162]
Hi, I'm using the latest CDN at https://unpkg.com/filepond/dist/filepond.js. I have a script at the bottom of my page: 

``` javascript
const pond = FilePond.create(document.getElementById('filepond'));
      pond.on('addfile', (error, file) => {
        if (error) {
          console.log('Oh no');
          return;
        }
        console.log('File added', file);
      });

    pond.setOptions({
      server: {
        process: './api/imageUpload',
      }
    });
```

Which works perfectly fine for drag and drop or 'Browse' of local files. I use Node.js + Express, and on my /api/imageUpload route, I'm using logging the file data to console and can see that normally these images have the correct mimetype.

However, when I copy and image online and paste it in, the file name is correct e.g. image.jpg, but the uploaded data is the HTML of the current page, as if I've viewed the page source and sent the content of that to the server.

I can't work out why it would do this or what I'm doing differently. 

### How to reproduce

``` html
<!DOCTYPE html>
<html>

<head>
  <title>FilePond from CDN</title>
  <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">

</head>

<body>
  <input type="file" class="filepond" id="filepond">

  <script src="https://unpkg.com/filepond/dist/filepond.js"></script>

  <script>
    const pond = FilePond.create(document.getElementById('filepond'));
      pond.on('addfile', (error, file) => {
        if (error) {
          console.log('Oh no');
          return;
        }
        console.log('File added', file);
      });

    pond.setOptions({
      server: {
        process: './api/imageUpload',
      }
    });

  </script>

</body>

</html>
```

### Expected behaviour

The pasted image uploads the image data - instead it uploads the HTML of the page. However, drag and drop and 'Browse' works fine.

Windows 10 - Chrome Version 70.0.3538.77 (Official Build) (64-bit)

Thank you for any help :)

**Comment by rikschennink** [comment]
Hi, unfortunately, `paste` is not a functionality that has been implemented by all browsers yet. So behavior will vary from functional to completely not working to pasting the file thumbnail instead of the file data.

If you can produce a functioning copy past set up on CodePen or JSBin I'm happy to take a look at the functionality again.
