### ISSUE TITLE
How to separate the place of file upload from the list?

### ISSUE THREAD

**Issue by alorenc** [pqina/filepond#164]
The point is that I would like the drop container to be in a different location than the list of loaded files.

**Comment by rikschennink** [comment]
You'd have to create two FilePond instances and move files between them, or have one and render the files outside of FilePond.

**Comment by alorenc** [comment]
I thought there was an implementation in which you only need to enter the container ID. But because it is not there, I will do it differently. Thank you for a quick response and hints.

**Comment by sherifomar** [comment]
Here's how I did it. Put the filepond element where you want the list of loaded files to display, and hide the filepond browse/upload button :

`.filepond--drop-label { display:none; }`

Then put a button where it is you want to launch the file selection from, for example : 

`<button class='filepond_browse'>Choose Files</button>`

Then launch the filepond file browser onclick that button : 

`document.querySelector('.filepond_browse').addEventListener('click', () => {
		pond.browse();
	})`

**Comment by hn1** [comment]
Much more helpful sherifomar than then developer himself. Thanks

**Comment by bronz3beard** [comment]
> Much more helpful sherifomar than then developer himself. Thanks

And this comment on your scale of helpful, where would you put it?
