### ISSUE TITLE
Incorrect file is reverted when multiple files have been uploaded and the instantUpload options is disabled

### ISSUE THREAD

**Issue by samrumley88** [pqina/filepond#167]
### Summary

When the option instantUpload is set to false and multiple files have been uploaded, reverting any of the files causes the first file to be reverted.

### How to reproduce

**Configuration**
- allowMultiple: true
- instantUpload: false
- allowRevert: true

1. Add multiple files and upload them all.
2. click the "undo" button on the second file

### Expected behaviour
The correct file is reverted.

### Additional information

The issue seems to be caused by line number **4842**. When instantUpload is disabled the 'REVERT_ITEM_PROCESSING' event is dispatched without any arguments. I assume that because the item.id is excluded that the default behaviour is to revert the first item.

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Device       | Desktop PC
| Browser      | Chrome 70.0.3538.102

**Comment by rikschennink** [comment]
You're absolutely right, tested and confirmed the problem. 

Published version `3.3.2` just now, should fix the issue (does so in my tests).

**Comment by samrumley88** [comment]
Thank you. I can confirm that the issue has been resolved.
