### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by samcov** [pqina/filepond#168]
On mobile, do I just add the  accept="image/*;capture=camera" to the input to capture camera shots?

**Comment by rikschennink** [comment]
You can add the capture attribute but unfortunately it’s not interpreted the same on each device. FilePond should copy it to its internal file input element.

**Comment by samcov** [comment]
That would be preferable. When you say it's not interpreted the same, do you mean it's not recognized on some devices?

**Comment by rikschennink** [comment]
Exactly. Some devices will respect the attribute settings others will simply ignore it, can't really rely on it.
