### ISSUE TITLE
Uploaded files with non word characters causes error

### ISSUE THREAD

**Issue by InvescoDev** [pqina/filepond#169]
### Summary
Files that have characters that are not string safe (eg. files with the % or ' signs) cause the following error:

```
filepond.js:4907 Uncaught URIError: URI malformed
    at decodeURI (<anonymous>)
    at formatFilename (filepond.js:4907)
    at create (filepond.js:5183)
    at filepond.js:1429
    at Object.createChildView (filepond.js:1172)
    at create (filepond.js:5599)
    at filepond.js:1429
    at Object.createChildView (filepond.js:1172)
    at create (filepond.js:5749)
    at filepond.js:1429
```

### How to reproduce
Upload any file that has invalid characters for a string (that has not been escaped using encodeURI()
(in this case there is a percent (%) sign and an apostrophe (') in the file name. 

Example File name:  
October 2018 1% Listing eNewsletter Hawaii what's my home worth low inventory  home prices and current interest rates for REALTO.pdf

### Bug Fix Suggestion

on line 2430 of filepond.js update the following:

```
      GET_ITEM_NAME: function GET_ITEM_NAME(query) {
        var item = getItemByQuery(state.items, query);
        return item ? item.filename : null;
      },
```

to be:

```
      GET_ITEM_NAME: function GET_ITEM_NAME(query) {
        var item = getItemByQuery(state.items, query);
        return item ? encodeURI(item.filename) : null;
      },
```

This resolved the error message in all cases that the error was produced

**Comment by rikschennink** [comment]
Should be fixed in version `3.3.3`
