### ISSUE TITLE
Max File callback in Jquery?

### ISSUE THREAD

**Issue by yukyolol** [pqina/filepond#170]
Hello, it's possible to use this feature in Jquery?

Tried this:
```
$("#ul").on('warning', (error, file) => {
	console.log('Warning', error, file);
});
```
Also:
```
$("#ul").on('Filepond:warning', (error, file) => {
	console.log('Warning', error, file);
});
```

But nothing happens, when the max file is 2, and I upload files one by one when I have 2 files the Browse file text disappears and I can't upload more until I remove one of them which is cool. But If I open the select files dialog, and select more than 2, the window just closes but nothing happens, no files are added and no console.log

Any ideas?
Thanks.

**Comment by chtsngn** [comment]
Yeah, i have same problem @rikschennink.

**Comment by rikschennink** [comment]
This works in my test case, can you give it a try?

```js
$('.my-pond').filepond({
    allowMultiple: true,
    maxFiles: 3
});

$('.my-pond').on('FilePond:warning', function(e) {
    console.log(e);
});
```

**Comment by yukyolol** [comment]
Hello, tested your test code and nothing, still the same.
Will post if possible today my code.

**Comment by nikans** [comment]
> $('.my-pond').on('FilePond:warning', function(e) {
>     console.log(e);
> });
> ```
