### ISSUE TITLE
File.size is working properly?

### ISSUE THREAD

**Issue by yukyolol** [pqina/filepond#171]
Hello, is File.size working properly?

When I add a file on the uploader (28KB)
https://puu.sh/C6p5T/bb794cd699.png

Console.log of the file property. (Returns 11026)
https://puu.sh/C6p6Z/02535d9fa7.png

What is supposed to be this 11026? I don't see any relation on the size, even I checked the size table.
https://puu.sh/C6p8g/1db4d05d5c.png

Thanks.

**Comment by chtsngn** [comment]
It's working properly for me. Try this:

```JS
$('.my-pond').on('FilePond:addfile', function(e) {
    console.log('file added event', e);
});
```
Maybe there are different size in the file object.

**Comment by rikschennink** [comment]
`file.size` is the filesize in bytes as reported by the browser, so if it doesn’t match the original file, I’m not sure, can you produce an online test case?

**Comment by yukyolol** [comment]
Hello I'm going to publish if I can today a demo of my code.
