### ISSUE TITLE
FilePond reload already uploaded files from server should turn the files to green

### ISSUE THREAD

**Issue by atishagrawal** [pqina/filepond#172]
Hello there, I am using FilePond to show already uploaded server files. And if the user wants, he/she can either remove already uploaded files or can upload new files. I have implemented load/restore functions and successfully able to fetch file information, but the FilePond instance is not turning green as it should when the files are uploaded. Also, when I press the 'x' mark, to remove files, no API is being hit in the background so that I can remove the files from the backend. Can you please help me with this?
I have uploaded screenshots for your reference

Actual Output:
![screenshot-localhost-2018 11 23-22-51-54](https://user-images.githubusercontent.com/6162950/48955174-ad716480-ef72-11e8-99f1-10deda35d684.png)

Required Output,(all files must be green)
![screenshot-localhost-2018 11 23-22-54-29](https://user-images.githubusercontent.com/6162950/48955196-ca0d9c80-ef72-11e8-81bd-f21f1058c934.png)

**Comment by rikschennink** [comment]
Please only post your issue once, I've removed two other instances.

**Comment by rikschennink** [comment]
Currently, files are green when they're in the temporary folder (revertable), local files are grey.

There's no remove endpoint for local files at the moment. If you want to remove files from the client you either have to do it in the callback or when submitting a parent form. 

It's a feature that a lot of devs are missing so it'll probably be added in a future release.

**Comment by jbmchd** [comment]
Acredito que isso vai resolver :)

/* the background color of the file and file panel (used when dropping an image) */
.filepond--item-panel {
    background-color: #369763
}

/* error state color */
[data-filepond-item-state*=error] .filepond--item-panel, 
[data-filepond-item-state*=invalid] .filepond--item-panel {
    background-color: #c44e47 !important;
}

**Comment by NishantSingh96** [comment]
@atishagrawal Did, you find the solution for this problem ?
