### ISSUE TITLE
Disable animation effects

### ISSUE THREAD

**Issue by Bert-Proesmans** [pqina/filepond#177]
Hi!

I'm building a web application that should be used both on mobile and desktop web browsers.
This application makes use of the ImagePreview and ImageExifOrientation plugins to improve usability.

The issue i encounter is with smartphones; nowadays the camera is always decent and image file sizes are huge, but the cpu performance isn't good enough to keep a smooth experience running.
The combination of image previewing + image sizes from mobile camera's are huge + animations + device rotations .. makes Chrome (test browser) on some (low and mid-range) mobile devices consistently crash. This is not an issue with FilePond per se, but i'd like to make my application as performant as possible because support for low-end smartphones is necessary.

Is there a possibility to disable filepond animations through config planned? I looked into the source but there is no 'set this to false and be done with it'. 
Maybe a plugin that dynamically disables animation features when a certain amount of megabytes is exceeded would be cool.

Since i'm also using the POST functionality, would it be a good idea to build a plugin that downloads a matching thumbnail for the recently pushed image and previews that thumbnail? Would this even improve rendering performance / prevent crashes?
At the moment i have disabled the ImagePreview plugin but i'd like to re-enable it again later. 

Please let me know what you think, thanks!

**Comment by rikschennink** [comment]
Hi,

First, please test this in a blank page with only FilePond running to determine if FilePond is indeed the cause of the crash, which is very much possible I don't want to point fingers. 😊

If so, there are a couple things you could do to determine if a device is "slow":

1. You can either write a script that measures the performance of the device by running a certain CPU intensive script.

2. You test features, define a set of features you require the device to have. FilePond does this already but you could make a more precise selection to filter out slow devices.

3. Detect old webviews by looking at the useragent string.

Unfortunately, it's currently not possible to disable animations. This is on my todo list, as it might be useful for accessibility purposes as well (motion sickness).

So when a slow device is detected you could:

1. Not load FilePond and fall back to a file input, this best aligns with your goal to support as many devices as possible as there are going to be devices that will be to slow to do GPU animation.

2. Register the Image Preview plugin conditionally, so only register it when a "fast" device has been detected.

**Comment by Bert-Proesmans** [comment]
Hi,

Thanks for the quick reply!
I have no evidence from testing that FilePond is the actual issue. The only lead is that crashes happen somewhere within the browse-select-upload-display-repeat flow with device rotations in between.
I understood that it's pretty hard to pinpoint a root cause because of fragmentation of versions/hardware/apps/OEM drivers/etc. within the Android market. I also need to learn more about dissecting performance flame graphs.

Taking your suggestions into consideration I feel like moving into a big grey zone where a matrix of features vs device capabilities determine the experience. This fragmentation is something I'd like to avoid (or at least abstract) because of my lack of skill, mostly.
So currently I'm keeping my situation black/white where I purposely reduce functionality to induce as little problems as possible. 
Although a perfectly valid suggestion, falling back to default file input is a step too far. :p

I haven't encountered any other javascript tools which focus on multiple file upload and pluggable architecture the way FilePond does. I'll eventually figure out what to do about the mentioned crashes.

Thanks for working on the project! I really like it.

**Comment by rikschennink** [comment]
Thanks @Bert-Proesmans, I very much appreciate the feedback.

Do let me know when you have more info on this, happy to assist.
