### ISSUE TITLE
Disable ctrl+v paste

### ISSUE THREAD

**Issue by followflydge** [pqina/filepond#178]
Hello, i'm using:
    "filepond-plugin-file-encode": "^1.0.5",
    "filepond-plugin-file-validate-size": "^1.0.4",
    "filepond-plugin-file-validate-type": "^1.2.0",
    "filepond-plugin-image-preview": "^2.0.1",
    "react-filepond": "^3.0.0",

And i can paste file using ctrl+v. How i can disable this function?

| Environment  | Version
|------------- | -----------
| OS           | Windows ...
| Browser      | Chrome..

**Comment by rikschennink** [comment]
```js
FilePond.create({
    allowPaste: false
});
```

See FilePond instance docs:
https://pqina.nl/filepond/docs/patterns/api/filepond-instance/

**Comment by followflydge** [comment]
@rikschennink TY!!!
