### ISSUE TITLE
image gradient overlay not showing properly on safari

### ISSUE THREAD

**Issue by 123mitnik** [pqina/filepond#179]
this is on safari Version 12.0.1 (14606.2.104.1.1)

![image](https://user-images.githubusercontent.com/1234337/49398919-6a6c7980-f748-11e8-9c5e-bac92639c1d8.png)

**Comment by 123mitnik** [comment]
just happened on chrome...( the same thing )
i'll try to locate it . or at least to give you some more info..

the interesting thing is that on chrome it is not happening every time .. but on safari it is permanent.
it must be something with when and how you apply the transparency gradient

**Comment by 123mitnik** [comment]
this has something to do with the blending .. the only workable solution for me for now is to lower the transparency of the blend color in  .filepond--image-preview-overlay-idle

**Comment by rikschennink** [comment]
Without a public test case, I can't help out, as I can't reproduce the problem.

**Comment by 123mitnik** [comment]
no problem

**Comment by rikschennink** [comment]
Can you try with the latest version `31.5` of the image preview plugin?
