### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by cmatzenbach** [pqina/filepond#18]
When following the instruction on the website about how to register filepond plugins, I found what seems to be an error in the documentation.  It says [here](https://pqina.nl/filepond/docs/patterns/plugins/introduction/#registering-plugins) that you should import plugins like this: `import FilepondPluginImagePreview from 'filepond-plugin-image-preview';` however, this was giving me errors.  Turns out you need to import them as such: `import * as FilepondPluginImagePreview from 'filepond-plugin-image-preview`.  

Not totally sure if this is a mistake or not, but thought I'd bring it up.  Maybe it's the way I set things up in Aurelia.

**Comment by rikschennink** [comment]
My guess is that this is an Aurelia thing, or maybe it's dependent on node or webpack version? I'm not sure. 

In all my test projects (Vue, React, vanilla Webpack), I can import the plugin as described in the docs without problems.

**Comment by cmatzenbach** [comment]
@rikschennink Ah ok, I see.  Seems it's not really an error then, just a.....javascript thing lol.

You can probably close this if you want.

**Comment by rikschennink** [comment]
@cmatzenbach Will do, if anyone knows how to make it so that it works everywhere, I'm all ears.

**Comment by SalkiDixit** [comment]
@rikschennink Hi, I am trying to use filepond with aurelia. not working, please assist.
