### ISSUE TITLE
FireFox aceptedFileTypes problem

### ISSUE THREAD

**Issue by followflydge** [pqina/filepond#180]
HI, i put in acceptedFileTypes only zip types: **'application/zip', 'application/x-compressed', 'application/x-zip-compressed', 'multipart/x-zip'**
In google chrome everywhere works well, but in FireFox **'multipart/x-zip'** break down acceptedFileTypes

in chrome:
![image](https://user-images.githubusercontent.com/36823884/49430868-2ebfc700-f7bd-11e8-9d81-3cc67de79cea.png)

in FF:
![image](https://user-images.githubusercontent.com/36823884/49430818-12238f00-f7bd-11e8-8252-6380667478f1.png)

"react-filepond": "^3.0.0"

| Environment  | Version
|------------- | -----------
| OS           |  Windows
| Browser      | Google Chrome Version 70.0.3538.110 (Official Build) (64-bit) / FireFox Quantum 63.0.3 (64-bit)  / ...

**Comment by rikschennink** [comment]
There's two options, either Firefox detects a different mime type, check with tool below:
https://codepen.io/rikschennink/details/NzRvbj/

Or, Firefox does not detect any type, in which case you can use custom type detection:
https://pqina.nl/filepond/docs/patterns/plugins/file-validate-type/#custom-type-detection

**Comment by followflydge** [comment]
@rikschennink FF detect *application/x-zip-compressed* like chrome 
problem in *multipart/x-zip*. Chrome show me other meme zip types, but FF show me all files.
it's FF problem, or i/you can fix this?

**Comment by rikschennink** [comment]
Oh now I understand, I don’t think there’s anything you can do about this (apart from leaving out the mime type but that will probably result in other issues) as it’s a browser thing.
