### ISSUE TITLE
How to define uniqueFileID on load() function

### ISSUE THREAD

**Issue by kodeine** [pqina/filepond#182]
This is the api situation for me.
`image url:` http://..../media/4a37-91cb-365a967328be.png
`post:` http://...api/v1/photos
`delete:` http://...api/v1/photos/{uniqueFileID}

Now, based on the above situation, i've modified the `process()` and `revert()` functions. 

I cant get my head around the `load()` function, the source would be `image url` but how can i define its `uniqueFileId` so it calls the appropriate url for deletion.

my init files are 
```
myFiles = [
        {
            // the server file reference
            source: '12345',
            // source: 'http://..../media/4a37-91cb-365a967328be.png', // doesn't work // Cannot read property 'name' of undefined.
            serverId: '67890',

            // set type to local to indicate an already uploaded file
            options: {
                type: 'local',
                // file: {
                //     name: 'my-file.png',
                //     size: 3001025,
                //     type: 'image/png'
                // }
            }
        }
    ];
```

**EDIT**
So, i found i could use `FilePoster` plugin, now it loads the image needed for display and i can keep the `source` with its id. Now the question is, how to make it delete? when i click on the X icon on image it just removes image locally, does not initiate delete api request. 

Also, i noticed that `FilePoster` needs file object with size property in it. I think `FilePoster` can get content-length when it loads the image url and use it as size. This way if we dont indicate the filesize manually, FilePoster can take care of it.

**Comment by rikschennink** [comment]
The `source` property is the `serverId` and will be passed to the `load` endpoint to restore the file from the server.

The server object has both a `remove` and `revert` endpoint for removal of the file.

FilePoster is for showing a preview image or different image from the actual file data. To show an image preview you need the ImagePreview plugin.

Please read the documentation carefully.
