### ISSUE TITLE
Missing documentation for stylePanelLayout

### ISSUE THREAD

**Issue by rovansteen** [pqina/filepond#185]
It would be great if there was some documentation about `stylePanelLayout`. The profile picture example on the homepage uses it but there's no mention of it in the documentation anywhere. Looking at the code I can see that `circle` change the shape (obviously) to a circle but I can't find anything about `compact` or the `integrated` that is mentioned in the code.

I'm specifically looking for a way to hide the file info, and setting the `stylePanelLayout` to `compact circle` does that but I don't want the circle in some cases. Unfortunately adding `compact` only makes the component smaller and causes the file info to overflow. As I can't find any documentation I'm not sure if this is a bug or not.

**Comment by rikschennink** [comment]
Oh, nuts! I totally forgot to document these properties, will get on it immediately, will probably be online on Thursday, will keep you posted.

**Comment by rovansteen** [comment]
@rikschennink awesome, thanks! 👍

**Comment by rikschennink** [comment]
@rovansteen I've updated the docs.

There's currently no setting to hide the file info, but you can use CSS to hide the element itself:

```css
.filepond--file-info { visibility:hidden !important; }
```
