### ISSUE TITLE
Add uploaded files to req.files for further processing by multer

### ISSUE THREAD

**Issue by letranger01** [pqina/filepond#186]
Hi, we've started using Filepond and are very impressed with it. However, we would rather use the front end aspect of it only, and not have it upload files directly to the server asynchronously. Instead, we would like the files that a user uploads to be stores locally in the DOM (in req.files once the form is submitted), then processed on the server side with multer, like we would with a regular input of type file.

When using Filepond, the normal procedure doesn't seem to be working. Any ideas why this may be the case? Our code:
JS:
```js
      FilePond.registerPlugin(
      FilePondPluginFileEncode,
      FilePondPluginFileValidateSize,
      FilePondPluginImageExifOrientation,
      FilePondPluginImagePreview
    );
    $('.uploadMainImg').filepond();
    $('.uploadMainImg').filepond('allowMultiple', false);
    $('.uploadMainImg').filepond('instantUpload', false);`
```
```html
                        <div class="form-group row">
                          <label for="uploadMainImg" class="col-3 col-form-label">DZ File*</label> 
                          <div class="col-9">
                            <input type="file" id="uploadMainImg" class="uploadMainImg" name="uploadMainImg" data-max-file-size="3MB" data-max-files="1" />
                          </div>
                        </div>
```

**Comment by rikschennink** [comment]
Unfortunately, browsers do not support setting files to a file input element. This means that once a file is dropped via drag and drop or somehow created in the browser (result of an image crop), the only way to upload the file is to either encode it as base64 data and store that data in hidden input elements (this can be done with the file encode plugin) or upload the file asynchronously via `fetch` or `XMLHttpRequest`, this is what the `server`property is for.

**Comment by letranger01** [comment]
Thanks @rikschennink , this is helpful! Would you happen to know another issue with detailed instructions on how to encode as base64 data and store in a hidden file input?

**Comment by rikschennink** [comment]
If you register the file-encode plugin it does it automatically for you.

**Comment by letranger01** [comment]
Thanks! We'll give it a try. Closing for now
