### ISSUE TITLE
File Pond missing 1 file on multiple upload

### ISSUE THREAD

**Issue by lebaphi** [pqina/filepond#193]
Hi,

### Summary

I'm using react-filepond (https://pqina.nl/filepond/docs/patterns/frameworks/react/) to upload file to S3, the behavior that I got:
- Drag 2 image files to dropzone : 1 file upload success, do not upload for the rest.
- Drag 5-6 images files to dropzone: 4-5 files upload success, always 1 files does not upload.

```
componentWillReceiveProps(nextProps) {
    if (nextProps.signedUrlObj) {
      const { signedURL } = nextProps.signedUrlObj;
      this.handleUploadFile(signedURL);
    }
  }

  handleUploadFile(signedURL) {
    const { fieldName, file, progress, load, error } = this.state.fileObject;
    const formData = new FormData();
    formData.append(fieldName, file, file.name);
    const request = new XMLHttpRequest();
    request.open('PUT', signedURL);

    request.upload.onprogress = (e) => {
      progress(e.lengthComputable, e.loaded, e.total);
    };

    request.onload = function () {
      if (request.status >= 200 && request.status < 300) {
        load(request.responseText);
      } else {
        error('oh no');
      }
    };

    request.send(formData);
  }

  render() {
    return (
      <UploaderContainer>
        <FilePond
          allowMultiple
          server={
          {
            process: (fieldName, file, metadata, load, error, progress, abort) => {
              this.setState({ fileObject: { fieldName, file, load, error, progress } });
              const { getSignedUrl } = this.props;
              getSignedUrl(file.name);
              return {
                abort: () => {
                  abort();
                },
              };
            },
          }
          }
        >
        </FilePond>
      </UploaderContainer>
    );
  }
}
```

### How to reproduce

- Drag 2 or more files to drop down zone and see always missing 1 files does not upload

### Expected behaviour

- upload all of files

### Additional information

I've tried to debug and see: as normal, when we drag the list of files to the drop down zone, the function **process** will be triggered for the first files uploading, when the upload is finished, the **process** will be trigger for the next file uploading and next. Currently I see on dragging 1st time, the **process** function will trigger **2 times continuously** and 1 files on them does not upload, after that it works as expected.

| Environment  | Version
|------------- | -----------
| OS           | MacOS 10.14.1
| Device       | Macbook Pro
| Browser      | Chrome 69

**Comment by lebaphi** [comment]
this issue does not happen when I restructure my code

**Comment by ivaqmo123** [comment]
hi @lebaphi , i am having exactly the same issue. Please could you let me know what you did in order to solve this?
Thanks

**Comment by lebaphi** [comment]
> hi @lebaphi , i am having exactly the same issue. Please could you let me know what you did in order to solve this?
> Thanks

Hi @ivaqmo123 , I just move the code of `handleUploadFile` to inside the `process` so this issue will resolved.
