### ISSUE TITLE
No file is uploaded even though there are no errors in the console and the UI reports success.

### ISSUE THREAD

**Issue by DigitalSolo** [pqina/filepond#194]
### Summary
No file appears in the directory I designate. 

### How to reproduce
I'm uploading to localhost/temp

### Expected behaviour
The file uploaded would appear in the localhost/temp directory.

### Additional information
I'm running it from localhost/p/MyDir/index.php
I've tried all manner of the server process line:

- server: {process: 'https://localhost/temp/'}
-      If I set the explicit URL it throws an error in filepond.js line 3051 "xhr.send(data);"
- server: {process: './'}
- server: {process: '/../temp'}
-      It reports uploaded in the UI, no errors in the console.  I search my entire web root for the file and it's nowhere.

-HTML
`<input type="file">`
-HTML

-JavaScript
```
<script type="text/javascript">
     const inputElement = document.querySelector('input[type="file"]');
     const pond = FilePond.create( inputElement );
     pond.setOptions({
          server: {process: '/../temp'}
     });
     const FilePondRoot = document.querySelector('.filepond--root');
     FilePondRoot.addEventListener('FilePond:processfile', e => {
          console.log('File added', e.detail);
     });
     pond.on('addfile', (error, file) => {
          if (error) {
               console.log('Oh no');
               return;
          }
          console.log('File added', file);
     });
</script>
```
-JavaScript
| WAMP Server | FilePond 3.7.4
|------------- | -----------
| OS           | Windows
| Device       | PC
| Browser      | Chrome

**Comment by rikschennink** [comment]
Hi

A server (or PHP files that accepts POST data) needs to be running at the server process location. See the [FilePond PHP boilerplate](https://github.com/pqina/filepond-boilerplate-php) for an example.

Configure it like this:

```js
const inputElement = document.querySelector('input[type="file"]');
const pond = FilePond.create(inputElement, {
    server: 'https://localhost/temp'
});
```

**Comment by DigitalSolo** [comment]
I appreciate the help.  To get the "PHP boilerplate" means I need to install and configure Vagrent and VirtualBox for this to work?  I really like the front end you've designed but I downloaded the two items above and I'm lost on what to do with them.  I already have Apache 2.4 and PHP 7.3 running on my system.  I guess I just need some sort of handler at the server: folder?

**Comment by DigitalSolo** [comment]
Are there any examples that point to how to utilize these files?  I’ve already downloaded the project and edited the config.php but I still can’t seem to get any files to the folder I select.  I’ve got all of the project files in the same folder I’m attempting to upload to.

**Comment by rikschennink** [comment]
@DigitalSolo Yes, that's what the [PHP boilertplate](https://github.com/pqina/filepond-boilerplate-php) project. If you install Vagrant and run `vagrant up` in the project folder it should automatically install and run the virtual machine and start a server so you can access the project.

**Comment by DigitalSolo** [comment]
I appreciate your time and patience.  I can't get it to work and I've already spent too much time on this.  I just wish there were better instructions on how to roll your own PHP handlers.  I can't seem to figure out what the front end scripting needs to hit so I can roll my own. I'm going to have to roll back to an old crusty abandoned upload handler :(

**Comment by rikschennink** [comment]
@DigitalSolo Sorry to hear that, I'm not really sure how I could help out further. Maybe it's an idea to check the server logs? Might be something up with folder permissions? 

FilePond basically POSTs the file object to your `server` end-point, so if the field name is `filepond` and the `server` property is set to `'http://localhost/my-server.php'` the file should appear in `$_FILES['filepond']` in the `my-server.php` file.

**Comment by DigitalSolo** [comment]
Wow, how stupid am I.  I thought that was already taken care of.  I wrote my own file handler in PHP and it works great.  Thanks!!!
