### ISSUE TITLE
Photos are not cropped after upload.

### ISSUE THREAD

**Issue by pathvine** [pqina/filepond#20]
Hi @rikschennink, 

I have set up the multipart/form-data upload and am able to accept the uploaded photos to my image server. However, the transformations are not applied to the photos upon upload. Can you please advise how the transformation, cropping, and resize plugins work upon the file upload?

All of the plugins are registered properly.
Here are my settings for `FilePond` instance:
```javascript
_pond = FilePond.create( _inputElement, {
      allowFileEncode: true,
      allowMultiple: true,
      maxFiles: 10,
      allowImageCrop: true,
      imageCropAspectRatio: '1:1',
      maxFileSize: '2MB',
      instantUpload: false,
      acceptedFileTypes: ['image/jpeg'], // Only allow jpeg file type.
      allowImageResize: true,
      imageResizeTargetWidth: Meteor.settings.public.image.maxWidth,
      imageResizeTargetHeight: Meteor.settings.public.image.maxHeight,
      allowImageTransform: true,
      imageTransformOutputMimeType: 'image/jpeg',
      imageTransformOutputQuality: 100
    });
```
Here is my XMLHttpRequest code.
```javascript
var _req = new XMLHttpRequest();
_req.open("POST", Meteor.settings.public.paths.formPostUrl, true);
_req.onload = function (_data) {
    
    var _output = JSON.stringify(_req.response, undefined, '\t');
    _output = _output.replace(/(\\")/g, "'");
};
 
 _req.send(_formData);
```
Thanks!

**Comment by rikschennink** [comment]
@pathvine This is difficult to debug. Uploading is done separate from transforming so how you upload should not matter. As you're using the file-encode plugin, it's best to see if the data is located in the hidden input field (as a base64 formatted string) and if it's less than what you'd expect for a big file.

If you have a public test case I'm happy to take a look.

**Comment by pathvine** [comment]
@rikschennink. I will see if I can setup a public test. I have printed out the items pertain to FilePond inside the form data with a file of about 1.8MB. 

The two FilePond form data parts have the following information:
```javascript
filepond
uploadForm.js:113 File(1758913) {name: "IMG_3389.jpg", lastModified: 1515554449000, lastModifiedDate: Wed Jan 10 2018 11:20:49 GMT+0800 (CST), webkitRelativePath: "", size: 1758913, …}lastModified: 1515554449000lastModifiedDate: Wed Jan 10 2018 11:20:49 GMT+0800 (CST) {}name: "IMG_3389.jpg"size: 1758913type: "image/jpeg"webkitRelativePath: ""__proto__: FilelastModified: 1515554449000lastModifiedDate: Wed Jan 10 2018 11:20:49 GMT+0800 (CST)name: "IMG_3389.jpg"size: 1758913type: "image/jpeg"webkitRelativePath: ""constructor: ƒ File()Symbol(Symbol.toStringTag): "File"get lastModified: ƒ ()get lastModifiedDate: ƒ ()get name: ƒ ()get webkitRelativePath: ƒ ()__proto__: Blobsize: 1758913slice: ƒ slice()arguments: (...)caller: (...)length: 0name: "slice"__proto__: ƒ ()[[Scopes]]: Scopes[0]type: "image/jpeg"constructor: ƒ Blob()Symbol(Symbol.toStringTag): "Blob"get size: ƒ ()get type: ƒ ()__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
uploadForm.js:114 
uploadForm.js:112 filepond
uploadForm.js:113 {"exif":{"orientation":1},"crop":{"rect":{"x":0,"y":0.14266666666666666,"height":0.7146666666666667,"width":1},"aspectRatio":1},"resize":{"mode":"cover","size":{"width":800,"height":800}}}
```
I don't see a base64 formatted string for the photo, is it in the `blob`? The rest looks fine to me, except that the hidden data (crop, aspectRatio, resize) did not get applied to the photo. You are right that the transform and upload should be separate operations; that's why I am trying to see if there is a transform function I can explicitly call to apply the transformations.

On the documentation, it says `The Image transform plugin applies the image modifications supplied by the Image crop and Image resize plugins before the image is uploaded.` This maybe true if FilePond is handling the upload. However, the transform plugin cannot apply the transformation if I am handling the upload manually.

**Comment by rikschennink** [comment]
Okay, I think I get it. You're requesting the `file` object manually and then uploading it? Are you not using the `process` callback? In that situation, you're basically using FilePond as a file drop area and indeed it will not apply transforms. It'll only apply transforms before upload or when storing the data as a base64 encoded file (using the file encode plugin).

There's currently no way to ask FilePond for the transformed file.

**Comment by pathvine** [comment]
Can you please point me to where the `process` callback is in the documentation? I may have missed that. Currently, I am using this:
```javascript
_pond.processFile(_fileID).then((error, file) => {
   // Callback goes to here.
});
```
I am not doing anything in this callback because I have handled everything in the:
```javascript
FilePond.setOptions({
  server: {
    process: { ... }
  }
});
```
I have registered the `allowFileEncode` plugin, but I can't find the data block that you've shown on the documentation [https://pqina.nl/filepond/docs/patterns/plugins/file-encode/](url).
This is the logic based on what I understand so far:
Include `allowFileEncode` => file will be converted to base64 => transmission issues such as speed, security, browser permission, etc.
Not include `allowFileEncode` => transformation won't work => for transformation to work, we must bear the pain of transferring files in base64 format.
Am I getting these right?

**Comment by rikschennink** [comment]
I meant the server.process property but set as a function.

If you're handling the upload in the `process` property of the `server` option then there's no need for the `file-encode`. File-encode is only there to allow uploading of files with the classic form post, if you're doing async uploading then you don't need the file-encode plugin.

`processFile` triggers FilePond to start the upload process (which will be automatically prepended with the transform process).

**Comment by pathvine** [comment]
I have disabled the file-encode. For now, the preference is to send the photos instead of the base64 format. I have converted the file to base64 and use `graphicsMagick` to crop and resize the photos on the image server.

**Comment by rikschennink** [comment]
No problem! Glad to hear you found a solution @pathvine, will close for now.
