### ISSUE TITLE
Open to remove file when reverting it

### ISSUE THREAD

**Issue by RicLeP** [pqina/filepond#200]
When reverting a file it remains in the list so can be uploaded again. If the user want’s to remove it then they also have to click the cancel icon. It would be great to have the option to skip this step, for instance if a user has decided to remove a file there is a good chance they will also want to remove it. This would improve the usability when there is a limit to the number of files that can be uploaded.

For example if there is a limit of 5 files the user may upload 5 then realise another one was better, now they must revert a file then remove it before they can add the replacement. It would be great to have the ability to automatically remove reverted files from the upload list.

**Comment by rikschennink** [comment]
If you set `instantUpload` to true the remove click will remove the item from the list. Would that solve the issue?
