### ISSUE TITLE
How do i refresh/update filepond instances when page component is mounted?

### ISSUE THREAD

**Issue by maverickpravin** [pqina/filepond#202]
So i am using filepond component in multiple places in my **Vue** application. For 1st instance instance i am using as single file upload (**circular layout**).  For 2nd  i am using for multiple file uploads(**rectangular layout**), 
when i change the routes back and forth, i notice that circular layout persists even for 2nd instance of filepond

This is my first component 
![c1](https://user-images.githubusercontent.com/11708491/51094824-49328a80-17d6-11e9-9444-196923491dd0.PNG)
This is my second component  (What happened)
![c2](https://user-images.githubusercontent.com/11708491/51094837-4e8fd500-17d6-11e9-9c08-a9fa64e9bc4b.PNG)

(Expected)
![c3](https://user-images.githubusercontent.com/11708491/51095027-b1ce3700-17d7-11e9-9337-75317f65915a.PNG)

**However, when i refresh the application page, it works normal !!**

I am not sure. Do you think its a conflict ?
So how do i update filepond instance on page mounted?
TIA

**Comment by rikschennink** [comment]
I think you might be setting the options for both components (using `setOptions`) instead of each separately (by passing the options to the component element).

**Comment by rikschennink** [comment]
Alright, that should work, I'll look into this.

**Comment by rikschennink** [comment]
I just published version `4.0.3` of the Vue FilePond Adapter, it fixes an issue where global options accidentally got merged with local options. Should fix the issue. Please confirm.

**Comment by maverickpravin** [comment]
I think it is becuase of the CSS 
In circular component i am using style as - `width:200px; height:200px;` (without vue - scoped css )
and that is actually conflicting with other instance of filepond

Any work around ideas?

**Comment by rikschennink** [comment]
Can you add a unique `class` or `id` to each FilePond instance and then use that to apply styles?

**Comment by maverickpravin** [comment]
@rikschennink 
I fixed just now by adding CSS using a class to individual instances.
It worked !!.
Thank you
