### ISSUE TITLE
image-preview classes missing

### ISSUE THREAD

**Issue by HapLifeMan** [pqina/filepond#203]
Hi, since I updated FilePond to the last release, I updated the CSS and the image-preview isn't working anymore because classes are missing in `filepond(.min).css`. Any fix? Thanks :)

**Comment by rikschennink** [comment]
Have you also updated the image preview plugin and other relevant plugins?

**Comment by HapLifeMan** [comment]
I forgot that I merged all CSS files in one, thanks!
