### ISSUE TITLE
Replace text-decoration-skip: ink to text-decoration-skip-ink: auto

### ISSUE THREAD

**Issue by jesserwright** [pqina/filepond#204]
https://github.com/pqina/filepond/blob/32ce4c386e2a5fbcf82723ffb94d292967b26629/dist/filepond.css#L99

CSS spec has been changed to text-decoration-skip-ink.

Please change
`  -webkit-text-decoration-skip: ink;` to `text-decoration-skip: ink;`

Old Spec:
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip

New Spec:
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink

**Comment by joshuathompson** [comment]
+1 this is pretty annoying because it shows up as a linting warning.

Based on the docs I think the example @jesserwright posted is supposed to be changed to `text-decoration-skip-ink: auto;`.

**Comment by rikschennink** [comment]
Fixed in `3.7.6`, please confirm

**Comment by joshuathompson** [comment]
Looks good to me!

**Comment by jesserwright** [comment]
It's good. Thank you! Awesome work on the library too, I love working with it 👍

**Comment by marcuschristiansen** [comment]
Has this also been updated in ant-design-vue?

**Comment by rikschennink** [comment]
No idea, you'd have to ask that question here I guess?
https://github.com/vueComponent/ant-design-vue

**Comment by JimmyLv** [comment]
@vueComponent

**Comment by BannyT** [comment]
> +1 this is pretty annoying because it shows up as a linting warning.

am failing to build on my server because of this warning, where can i change it
