### ISSUE TITLE
How to return the processed image type file, because I want to upload the image to firebase storage

### ISSUE THREAD

**Issue by applehong5013** [pqina/filepond#205]
Hello fellow developer!

💡 If you want to submit a feature request, go right ahead!

🐜 If you've found a bug, please use the template below to report it.

**The more details you provide, the more inclined others are to help you out and the faster the issue is resolved.**

If you're using one of the FilePond adapters and think the issue might be related to the framework, submit the issue in the adapter repository.

Please format code snippets using triple backticks and set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

### Summary

...

### How to reproduce

...

### Expected behaviour

...

### Additional information

...

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
FYI, supplying more information, clearly formatted code, the reasoning behind why you want to accomplish what you're asking, will make it easier for others to help you.
