### ISSUE TITLE
Multiple file uploads is missing some files in FilePond UI

### ISSUE THREAD

**Issue by ivaqmo123** [pqina/filepond#211]
### Summary

When I select 5 to 15 files into FilePond in a reactJs app, some of the files (2 or 3) are not shown in the FilePond UI or is shown in the UI but appears with a "X" as "...Deliverable 2..." file shown in image below. This behavior is random, sometimes file A is not shown, other times is file B. The extract of my filePond code is below (i am using transform, image preview, image exit and file rename plugins).
What i noticed debugging is that the files that doesn't appear in the UI goes twice to the "beforeAddFile" method and the files that appears correctly goes only once thru that same method.

Could you please provide help on this? 

![image](https://user-images.githubusercontent.com/30051512/51761557-694a2f80-209b-11e9-9a5f-3249c26bfbc2.png)
 
```
                              <FilePond
                                    imageTransformOutputMimeType='image/jpeg'
                                    imageTransformOutputQuality= {80}
                                    fileRenameFunction = {file => {return Date.now() + '_' + file.name}}
                                    maxParallelUploads = {5}
                                    maxFiles = {30}
                                    server={{ process: this.handleProcessing,
                                              revert: this.handleRevert,
                                              load: this.handleLoad }}
                                    onupdatefiles={(fileItems) => {
                                      //Always called when adding or removing Files.
                                      let files =  fileItems.map(fileItem => fileItem.file);
                                      const fields = {...this.state.fields, files};
                                      this.setState({fields, isUpdateButtonEnabled:true});
                                    }}
                                    >

                                    {this.state.fields.files.map((file, index) => (

                                        <File
                                              key={file.filename}
                                              src={file}
                                              origin="local"
                                              />
                                    ))}
```

...

### How to reproduce
drop 10-15 files in a shot into file pond react.
...

### Expected behaviour
All files should be shown in the FilePond UI and all of them should start processing.
...

### Additional information

...

| Environment  | Version
|------------- | -----------
| OS           |Windows 
| Browser      | Chrome

**Comment by rikschennink** [comment]
I've confirmed the issue, it's fixed locally, please update the react adapter to version `6.0.1` and the filepond core to `3.7.7` this should fix the issue.

Please note that the `<File>` component has been removed, you can now simply use the `files` prop to set the files.

Let me know if this resolves the problem on your side.
