### ISSUE TITLE
Filepond documentation doesn't display all content outside of print-view

### ISSUE THREAD

**Issue by docrinehart** [pqina/filepond#214]
When viewing the docs, (specifically https://pqina.nl/filepond/docs/patterns/plugins/introduction/) there's a link to read more about registering plugins. The anchor then shows in the browser url bar, but nothing is navigated to on the page. If you find the same link in the print-view version of the docs, the anchor works as expected, and there's documentation about registering plugins.

I was unable to find the content outside the print-view.

**Comment by rikschennink** [comment]
It should link to this page:
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#registering-plugins

Will update the docs.
