### ISSUE TITLE
Problem with stylePanelAspectRatio

### ISSUE THREAD

**Issue by Zwimber** [pqina/filepond#215]
### Summary

The setting `stylePanelAspectRatio: 'x:x'` does not work as expected. Using `allowMultiple: false` I'd expect a single uploaded image to fit exactly into the view. However it is slightly too large. You can see [an example here](https://codepen.io/anon/pen/xMdrMX).

Note: this problem does not exist with `stylePanelLayout: 'integrated'`.

### Images

Chrome

![In Chrome](https://i.ibb.co/5GhPjxw/Chrome-1.png)

Safari

![In Safari](https://i.ibb.co/yyh4kjV/Safari-2.png)

### How to reproduce

Click link, I have checked this on macOS (Chrome + Safari) and it turns out the problem only exists in Chrome.

### Expected behaviour

No scrollbar

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS 
| Device       | Macbook Pro
| Browser      | Chrome 72.0.3626.81 (Official Build) (64-bit)

**Comment by rikschennink** [comment]
To be honest this mode was only meant to be used in combination with the `'integrated'` setting.

I'll see if I can improve this in the future. But for now you can set a fixed height to the filepond root element and a fixed preview height to the image preview (`imagePreviewHeight`).

**Comment by Zwimber** [comment]
Seems this issue still exists; I have resolved the issue with a great function called `aspectRatioMakeSlightlyHigher`: 

```js
const aspectRatioMakeSlightlyHigher = (ratio) => {
  const ratioStable = ['1:1'].includes(ratio)
  if (ratioStable) return ratio
  
  const integratedIs = this.options && ['integrated'].includes(this.options.stylePanelLayout)
  if (integratedIs) return ratio
  
  const ratioNew = aspectRatioNumberTo(ratio) / 1.04
  return `${Math.round(ratioNew * 100000000)}:100000000`
}
```
