### ISSUE TITLE
Chrome: Folder drop does not work inside sandboxed iframe unless allow-same-origin enabled

### ISSUE THREAD

**Issue by eponymous301** [pqina/filepond#218]
### Summary

If filepond is inside a sandboxed iframe without "allow-same-origin", then folder drops do not work (file drops still work fine)

### How to reproduce
Set up 2 web servers on different ports, one serving up a page with only a filepond element, the other a page with only an iframe that uses the first web server's page as source, e.g.:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Filepond inside iframe</title>
  </head>
  <body>
    <iframe src="http://localhost:8080/filepond.html" 
                  sandbox="allow-scripts 
                       allow-forms 
                       allow-modals 
                       allow-pointer-lock 
                       allow-orientation-lock 
                       allow-popups 
                       allow-presentation
                       allow-top-navigation" >
    </iframe>
  </body>
</html>
```

In browser, load up the page that has the iframe, then try dragging folders onto the filepond drop target.

In Chrome, dragging and dropping folder does not result in items added. (no errors displayed in Javascript console). Dragging files works.

In Safari, dropping folders works.

If you add allow-same-origin to iframe sandbox setting, then folder drop in Chrome works.

### Expected behaviour

Folder drop works without allow-same-origin (like in Safari).

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS 10.14.1 (18B75)
| Device       | MacBook Pro
| Browser      | Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by rikschennink** [comment]
Thanks for the detailed issue report.

I wonder if this has to do with FilePond or that this is a cross-browser difference in handling these restrictions.

**Comment by eponymous301** [comment]
A bit more detail - when dragging folders (for Chrome), the dragover event seems to be processed fine, I get the darker circle following the mouse pointer around. The drop event also fires and invokes handler, but somehow the list of things dropped appears to be empty.

**Comment by rikschennink** [comment]
That will probably mean it's not there / stripped out by the browser.
