### ISSUE TITLE
Unmet peer dependencies for plugins

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [pqina/filepond#219]
Eager to implement the grid view feature I'm getting some NPM errors for unmet peer dependencies for various plugins. Looking at their repositories it seems like they stil require a filepond version ^3.x, some even explicitly require a version below 4 (https://github.com/pqina/filepond-plugin-image-validate-size/blob/master/package.json). Is it possible to bump these requirements or are the plugins incompatible with 4.x?

**Comment by rikschennink** [comment]
Plugins should all work with 4.0.0, I added this range 3 to 4 to make sure it would only be warnings and not crash the project. Will update the dependencies today.

**Comment by SanderVanLeeuwen** [comment]
Ok cool! I have the plugins as requirements in my own package configuration, so that's probably why it's breaking for us. But that's as expected :)

**Comment by rikschennink** [comment]
Should be fixed now, all adapters and plugins have been updated.

**Comment by SanderVanLeeuwen** [comment]
Works like a charm, thnx!
