### ISSUE TITLE
[React] Can't paste a snipped image in IE11

### ISSUE THREAD

**Issue by rhublard** [pqina/filepond#220]
Hi,

We are currently implementing the latest react version of your library in our application and we noticed that while we can copy/paste an image created using Windows snipped tool on Chrome and Firefox, we can't do it on IE11.

Is it a bug or is something not supported by filepond/IE and is there a fix, a workaround or a plan to support it?

### How to reproduce

1. Snip an image using Windows snipped tool
2. Paste it on the filepond component 

### Expected behaviour

The clipped image is processed by FilePond component.
![image](https://user-images.githubusercontent.com/40246041/52265328-b6e05b00-292b-11e9-9ba6-5a965ff044d6.png)

### Additional information

It was tested based on your examples and in a `create-react-app` example.

| Environment  | Version
|------------- | -----------
| Windows    | 10
| Browser      | IE 11.523.17134.0

**Comment by rikschennink** [comment]
Browser support for copy-pasting images is simply very bad at the moment.
