### ISSUE TITLE
How to get uploaded temp-images to upload folder

### ISSUE THREAD

**Issue by jonasneustupny** [pqina/filepond#222]
Hi. I´m sorry, my question is kind of basic, but I´m stuck.

Uploading a file to the temp-folder works well.
But I don´t understand point number 5 in the upload process:
> 5. client submits the FilePond parent form containing the hidden input field with the unique id

How????
If I do a `$('#form').submit()` on the form with the hidden filepond-input, nothing happens.

Can someone please give me a hint? I didn´t find a full example of an implementation with jquery (and php).

**Comment by rikschennink** [comment]
```html
<form method="POST" action="submit.php">
    <div class="filepond--root"><!-- FilePond and its hidden input fields live here --></div>
    <button type="submit">Submit</button>
</form>
```

When you upload a file (using the `server` property) the server returns (should return) a unique id for that file so you can identify the file in your backend when (and if) the form is submitted later on (in this case the submit button is clicked). The form submit will post a list of unique file ids to your server.

It's not required, you could deal with only temp files, but I find this is a nice way of confirming the user has made a definite selection and has confirmed it by submitting the form.

**Comment by jonasneustupny** [comment]
Hi @rikschennink, I did get the submitting part to work now. Thank you for the explanation!

I thought there was a function that would call a server-process to move the files from the temp folders to the target directory. I was wondering why the `config.php` has the constant `UPLOAD_DIR` in it since it won´t be used.

**Comment by rikschennink** [comment]
It’s also imported by another file, I believe submit.php which uses it to move the file

**Comment by rikschennink** [comment]
@jonasneustupny Please close the issue if the original problem has been resolved.
