### ISSUE TITLE
Adding additional metadata to file display

### ISSUE THREAD

**Issue by BobD** [pqina/filepond#224]
Hi there,

I'm using Filepond and it's pretty great, thanks. I have some additional file metadata to display however such as virus scan status, so i was wondering what the best way was to add some additional UI elements (icons and such) to a single file in the list?

**Comment by rikschennink** [comment]
You'd have to write a custom plugin.

I would advise looking at how the file-poster and image-preview plugins function. You can strip out a lot of their logic and then add back your own.

**Comment by BobD** [comment]
@rikschennink Thanks, i am going to check that option out, keep you posted.

**Comment by rikschennink** [comment]
Will close this as the original question has been answered
