### ISSUE TITLE
React: detect if file is local or remote

### ISSUE THREAD

**Issue by paianoa** [pqina/filepond#225]
beforeRemoveFile and onRemoveFile handlers have file as parameter but how can I detect if file is local (i.e. uploaded in the current session) or remote (uploaded in previuos sessions). I tried some console.log but can't figure it out.

**Comment by rikschennink** [comment]
A file item contains an `origin` property you can use the `FileOrigin` enum to compare it.
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#fileorigin-enum

**Comment by paianoa** [comment]
Thank you.
