### ISSUE TITLE
Plugin to unzip before add

### ISSUE THREAD

**Issue by RafaelLiendo** [pqina/filepond#226]
Hi, I'm working on a project that the user would be able to upload .xml files, or a folder, or .zip file containing .xml files.

Filepond already gives me most of what I need, it allows me to drag a directory, and I use the "File type validation" plugin to allow only .xml files.

Now I'm trying to create a plugin that intercepts a .zip and recursively extracts .xml files out of it.

My guess is that it would be somewhat like the "File rename" plugin that adds a filter for 'LOAD_FILE' and resolves into an array of extracted files.

Am I on the right track?

**Comment by rikschennink** [comment]
Hmm, you’d have to be able to prevent the load of the zip itself but then resolve it with multiple files. I’ll take a look at this tomorrow morning, not sure if this is possible now but more than willing to add additional plugin hooks to make it possible.

**Comment by rikschennink** [comment]
Haven't had time yet, sorry, it's been a crazy week. It's on the list.

**Comment by rikschennink** [comment]
Something like this should work, please note that detecting a zip like this is not the best way to go probably it's just for illustrative purposes.

```js
addFilter(
    'DID_LOAD_ITEM',
    (item, { query, dispatch }) =>
        new Promise((resolve, reject) => {

          // if it's not a zip, we're not interested
          if (!/.zip$/.test(item.file.name)) return resolve(item);

          // unzip file and put result in files array
          // ... unzipping
          const files = ['./data/by_border.jpg'];

          // remove the zip itself from the files list
          dispatch('REMOVE_ITEM', { id: item.id });

          // add unzipped items to the list (if the zip contains zips these will also be unzipped)
          dispatch('ADD_ITEMS', { items: files });

      }
    )
);
```
