### ISSUE TITLE
initial load Base64 image  from database

### ISSUE THREAD

**Issue by xmlking** [pqina/filepond#227]
My image data is stored in database as Base64 and exposed as JSON API. how do I load this data initially ?
### Summary
```js
files = [
    {
      source: '1234',
      options: {
        type: 'local', 
      },
    }
  ];

avatar = {
checksum: "f78b79f1fa9b805cf100ca09778b8d8f37a67f92"
createdAt: "2019-02-06T21:32:41.985Z"
data: "iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAACX"
id: 19
mimeType: "image/png"
size: 33068
title: "473791.png"
type: "profile"
}

 server = {
    load: (source, load, error, progress, abort, headers) => {
      console.log('test load');
      load(this.appProfile.avatar); // can I load base64 data here ?
      return { abort };
    },
}
```
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
The `load` method expects a File object to be returned. So you'll have to turn the base64 data into a file, this can be done quite easily, you can find some example snippets below:
https://stackoverflow.com/a/38935990/1774081

**Comment by xmlking** [comment]
Thanks,  that works. Wonder  if you could advice me how I can trigger process action with outside button. I have form data and image I have to submit together, and it make sense to have common external button to trigger  server action. Thanks

**Comment by rikschennink** [comment]
You can do this by calling `pond.processFile` where `pond` is an instance of FilePond.
