### ISSUE TITLE
Adding mock file throws error

### ISSUE THREAD

**Issue by kbst9** [pqina/filepond#228]
Adding a mock file throws an error. As per documentation:

```js
this.pond.addFile({
   source: file.url,
   options: {
        type: 'local',
        file: {
          name: file.name,
          size: file.size,
          type: file.type
        }
    }
})
```

Example payload:
```js
{
  "source": "https:\/\/storage.googleapis.com\/bucket_name\/1234.png",
  "options": {
    "type": "local",
    "file": {
      "name": "1234.png",
      "size": 16589,
      "type": "image\/png"
    }
  }
}
```

After triggering the above, the UI displays a file. But shows the file as `Loading 100%`, and misses the name:
<img width="541" alt="screen shot 2019-02-11 at 12 27 34 am" src="https://user-images.githubusercontent.com/32283725/52547201-e65fef00-2d93-11e9-8cb6-9fe642514cec.png">

When adding the file the following happens:
1. An error is thrown:
```
Uncaught TypeError: url.split is not a function
    at getFilenameFromURL (filepond.js:2514)
    at Object.request.onload (filepond.js:4145)
    at XMLHttpRequest.xhr.onload (filepond.js:2995)
```

2. A request is sent:
`<current-url>/%5Bobject%20Object%5D`

### Expected Behaviour
File is added and is displayed as `processing-complete`, without any Loading.

---
package.json:
- "filepond": "^3.7.3"
- "react-filepond": "^5.0.0"
- "react": "^16.3.0"

node: v8.12.0

usage:
```jsx
<FilePond 
  ref={ref => this.pond = ref}
  files={this.state.files}
  onupdatefiles={fileItems => this.setState({files: fileItems.map(fileItem => fileItem.file)}) }
  server={
    {
      url: API_ENDPOINT,
      process: {
        url: "/upload",
      },
      revert: null,
      restore: null,
      load: null,
      fetch: null,
    }
  }
  />
```

**Comment by rikschennink** [comment]
Adding a file is not done with an object definition, the `addFile` you show above should not be in the docs, if you can point out where it is I'll update it immediately.

This is how you can pass a mock file object to the addFile method

```js
pond.addFile('foo.jpg', {
    type: 'local',
    file: {
        name: 'bar.jpg',
        size: 1234,
        type: 'image/jpeg'
    }
})
```

This is how you set a mock file object to the `files` prop

```js
files: [
    {
        source: 'foo.jpg',
        options: {
            type: 'local',
            file: {
                name: 'bar.jpg',
                size: 1234,
                type: 'image/jpeg'
            }
        }
    }
]
```

**Comment by kbst9** [comment]
@rikschennink 

Thank you sir, all sorted. Seems like I was just confused by the docs, my apologies.
I rechecked and there's no explicit example with `pond.addFile` only with `FilePond.create`. 

Thanks again.

**Comment by rikschennink** [comment]
@kbst9 Fantastic, glad to hear that!
