### ISSUE TITLE
Event on upload Complete ?

### ISSUE THREAD

**Issue by ragshion** [pqina/filepond#230]
in jquery, how can add an event while upload complete ? thank you :D

**Comment by rikschennink** [comment]
This should work
```js
$('.my-pond').on('FilePond:processfile', function(e) {
    console.log('file added event', e.detail);
});
```

**Comment by ragshion** [comment]
oke that's work,, but.. how i use the json respon of request ? 
```
FilePond.setOptions({
	   server: {
	        url: '<?=base_url()?>',
	        process: {
	            url: '/import/import_excel',
	            method: 'POST'
	        }
             }
});
```

i see in the network, it's have a respon that i want.. but, i don't know how to get it to my page ?

**Comment by rikschennink** [comment]
The response is available in the `server.process.onload` callback, please note that this callback should return the file id. You can use it to access other data as well but it is not adviced.

**Comment by rikschennink** [comment]
As original question has been answered I’ll close this issue
