### ISSUE TITLE
Question: Custom preview image

### ISSUE THREAD

**Issue by bocanhcam** [pqina/filepond#231]
Does this package has any feature to custom preview images.

It would be great if we can make a custom preview images.

So we can do something like sort, crop images before upload its.

I just don't wanna upload images right away, just want to do something before uploading it's with another parameter input

**Comment by rikschennink** [comment]
Hi, I'm not a 100% sure what you mean, but let me try to answer the question

- If you mean cropping and resizing the image you can use the [image-preview](https://pqina.nl/filepond/docs/patterns/plugins/image-preview/), [image-crop](https://pqina.nl/filepond/docs/patterns/plugins/image-crop/), and [image-transform](https://pqina.nl/filepond/docs/patterns/plugins/image-transform/) plugins.
- If you mean showing a different image on a file item you can use the [file-poster](https://pqina.nl/filepond/docs/patterns/plugins/file-poster/) plugin.
- If you want to allow your users to edit the image you can use the [image-edit](https://pqina.nl/filepond/docs/patterns/plugins/image-edit/) plugin combined with [Doka.js](https://pqina.nl/doka/)

**Comment by bocanhcam** [comment]
Thank you for your reply @rikschennink 

I'm gonna try these plugins you recommend.

And the important thing I mean is about sort order images, Just like these pictures.

![screen shot 2019-02-14 at 11 44 54](https://user-images.githubusercontent.com/35592955/52768205-34187800-3070-11e9-846c-4a1427c811de.png)

![screen shot 2019-02-14 at 15 56 40](https://user-images.githubusercontent.com/35592955/52768554-2e6f6200-3071-11e9-9bd1-535475935ceb.png)

I want users can sort order images before upload so I can save the order of images exactly as they want in the database. I try to make this package to work with this one [https://github.com/SortableJS/Vue.Draggable](https://github.com/SortableJS/Vue.Draggable)

I don't know if it can work together or not.

**Comment by rikschennink** [comment]
Currently, users cannot manually sort items in the list. Vue.Draggable won't work. This has to be implemented in the core of FilePond itself.
