### ISSUE TITLE
Feature idea: Inline files upload

### ISSUE THREAD

**Issue by ThamrinPH** [pqina/filepond#235]
Can i request new feature when dropped they stand inline?
like dropzone.js, i love your works anyway
![new feature](https://user-images.githubusercontent.com/24406362/52841817-d21f4780-312f-11e9-8c17-84482ec939bc.gif)

so they don't take a lot of spaces going below and look more tidy, or is there options/features that i missed for styling
![takes lot of space](https://user-images.githubusercontent.com/24406362/52842024-5eca0580-3130-11e9-9118-30906853c0c9.gif)

**Comment by rikschennink** [comment]
Hi, see this topic on styling, by limiting the width of the item FilePond automatically creates a grid.
https://pqina.nl/filepond/docs/patterns/api/style/#grid-layout
