### ISSUE TITLE
Option to disable uploadButton and revertButton

### ISSUE THREAD

**Issue by HapLifeMan** [pqina/filepond#238]
Hey, is it possible to add a parameter to hide `uploadButton` and `revertButton`?

It would be very helpful if we want to handle the process when clicking on a submit form button, users will not be able to upload the file by clicking on the filepond button or revert once uploaded.

Actually buttons are displayed and users can trigger them with buttons.

Thanks! 😊

**Comment by Silver96** [comment]
My workaround for this was to use custom css to hide the process button, which is not safe by any chance but on a normal usage would prevent users from triggering single uploads. You would still need to provide a backend check to detect single-file uploads.

```css
.filepond--action-process-item{
    visibility:hidden;
}
```

The revert one should be removable through the instance option `allowRevert`, or at least that worked for me.

**Comment by HapLifeMan** [comment]
This is a good trick for the process button, thank you!

Maybe a `allowProcess` would be implemented as well as the `allowRevert`?

**Comment by rikschennink** [comment]
@HapLifeMan If I understand correctly users can add files and can only remove them. They click a separate control outside of FilePond and this control triggers FilePond to start uploading the files asynchronously to the server?

Some more information might be helpful to find a suitable solution. So I wonder why the user is not allowed to click the upload button?

**Comment by HapLifeMan** [comment]
Yes @rikschennink this is exactly what I want to do in this case!

Of course: I want only one button to update user information that will validate the entire form then update information if validation was correct. It is more understandable for the user and provides a better user experience because two different methods to save information (profile picture or username/email) is confusing. It also prevents to have multiple buttons with the "circle compact" version, very useful for a minimalist design 😊

**Comment by rikschennink** [comment]
But you don't want to upload automatically on drop?

**Comment by HapLifeMan** [comment]
Nope, I want to trigger manually the upload by clicking on the separate button :)

**Comment by rikschennink** [comment]
https://github.com/pqina/vue-filepond/issues/31

**Comment by jack2ky** [comment]
I also want and easy way to hold off the upload of the file until the user clicks a button. I want the user enter some data enter the file they want to upload then click a submit button. when the button is clicked all data should be sent via ajax. I want to get access to it with express using `req.body` or` req.files`. Thanks.

**Comment by timavaza** [comment]
Hi there,
+1
I'm looking for this too. An example of a well known product that uses this UI interaction would be Slack. Notice on file upload the user can add description, and start the upload on all files. The user cannot individually upload each file.

**Comment by Daviid-Perez-S** [comment]
Hi there too,

It´s just what I´m looking for ohhh 😱 !!
Also I´ve tried many ways to *"hide"* o *"disable"* **Upload Button** in the top right corner of card file, but I haven´t succeeded 😢. I´ve already tried with the property:

```javascript
FilePond.setOptions({
    allowProcess = false
});
```

, but this doesn´t work (at least when i wrote this comment).

The only thing that works right (or pretend resolve this one) is the @Silver96's answer just some comments above => https://github.com/pqina/filepond/issues/238#issuecomment-464344500.

I see this issue was opened over 1 year ago... I though this whould be resolved about these days, but not. I´d like that, if were possible, to add this new property to FilePond like the:

```javascript
allowRevert = false
```

property, this would be really helpfull please !!
Cheers.

**Comment by rikschennink** [comment]
`allowRevert` is now available in `4.17.0`
https://github.com/pqina/filepond/releases/tag/4.17.0

**Comment by HapLifeMan** [comment]
Thank you @rikschennink, great job 😊🙏🏻

**Comment by Daviid-Perez-S** [comment]
Thanks so much @rikschennink, this new version was released exactly in the perfect moment 👏🏻.

**Comment by Danscap** [comment]
Fantastic. This is a crucial functionality, thank you for adding it. I just updated my filepond version to the latest.

Would it be possible to update the docs, @rikschennink ? This does not appear in the Properties section

**Comment by rikschennink** [comment]
@Danscap Just added it to the [docs repository](https://github.com/pqina/filepond-docs), will be uploaded later.
