### ISSUE TITLE
Disable dropping URLs

### ISSUE THREAD

**Issue by paianoa** [pqina/filepond#240]
Is it possible to disable the "fetch" feature? In my app I don't want user to send remote url. I tried with {server: {fetch: null}} and {server: {fetch:""}} but it still accepts url dragged and dropped.

**Comment by rikschennink** [comment]
In version `4.4.0` the `beforeDropFile` hook has been added, you can use it to validate dropped items.
https://pqina.nl/filepond/docs/patterns/api/filepond-instance/
