### ISSUE TITLE
Custom / Alternate render for large number of files

### ISSUE THREAD

**Issue by CPritch** [pqina/filepond#241]
Hi there great component,

I would like to make a suggestion that I feel would make the component a smidgen more useful.

Requirement:
To be able to upload ~200 Files without a severe impact in rendering performance.

Suggested Solution:
Either provide a 'Custom Render' style prop that you can use to implement your own rendering of the FilePond progress. Or to have a single 'Multi-File' render with the progress for each uploads progress.
E.g. 1/100 Uploads complete and clicking into that allows for granular control over rendering.

I hope this makes sense, or maybe I'm incorrect in what the performance issue is caused by. When I attempt to upload ~200 files FilePond struggles a little as it's rendering hundreds of SVGs all added to the page in one go.

**Comment by rikschennink** [comment]
I'd love to fix this but I don't think the engine currently updating the FilePond view will be able to deal with this many files. I will close this for now. For the foreseeable future, it's just not suitable to handle that many files at the same time.
