### ISSUE TITLE
Grid view not working, i'm not using any template

### ISSUE THREAD

**Issue by ThamrinPH** [pqina/filepond#244]
i'm using laravel welcome page then added 

`.filepond--item {
    width: calc(50% - .5em);
}
` to style section on header
and i tried drag and drop some files, but it failed
and i got this instead
![missed something](https://user-images.githubusercontent.com/24406362/53062480-90a5e800-34f3-11e9-96b3-7de4614d71b1.gif)

### How to reproduce

Adding filepond's css and js, =>
 add
 `.filepond--item {
    width: calc(50% - .5em);
}
`
=>
browse image 

### Expected behaviour

![image](https://user-images.githubusercontent.com/24406362/53062395-4d4b7980-34f3-11e9-8000-08f252e6b8a6.png)

### Additional information
Laravel 5.7
no bootstrap
no template 
| Environment  | Version
|------------- | -----------
| OS           |  Linux .
| Browser      | Chrome 72.0.3626.109

**Comment by rikschennink** [comment]
It looks like the images are not the same height.

> Make sure that each item is the same height. FilePond currently calculates the height of the first item in the list and then uses that as the base height for each item. You can set the item height using `styleItemPanelAspectRatio`, `imageCropAspectRatio`, or by setting a fixed `imagePreviewHeight`.

Probably won't fix the issue, without a public test case I'm not sure why it's not working.

Also, which version of FilePond and plugins are you using?

**Comment by ThamrinPH** [comment]
for version i used from this cdn 
`<script src="https://unpkg.com/filepond/dist/filepond.js"></script>`
and i tried using images with same resolution but it ended like this
![same resolution](https://user-images.githubusercontent.com/24406362/53327280-1245ad80-391a-11e9-994d-8cf757bd9e71.gif)

**Comment by rikschennink** [comment]
Please supply an online test case
