### ISSUE TITLE
How to add something data to formData

### ISSUE THREAD

**Issue by Strenget** [pqina/filepond#246]
Hi!
I need help with additional some data to formData in react, I cant use headers for send external data.
Thank you.

**Comment by rikschennink** [comment]
Hi, thanks for using FilePond! Please use [StackOverflow](https://stackoverflow.com) to ask questions about FilePond.

**Comment by hanzlahabib** [comment]
What??????

**Comment by hanzlahabib** [comment]
> Hi, thanks for using FilePond! Please use [StackOverflow](https://stackoverflow.com) to ask questions about FilePond.

Whattt??????

**Comment by hanzlahabib** [comment]
> Hi!
> I need help with additional some data to formData in react, I cant use headers for send external data.
> Thank you.

Hi Strenget please try this

```
ondata: (formData) => {
                formData.append('Hello', 'World');
                return formData;
            }

```
it works for me

**Comment by rikschennink** [comment]
> > Please use [StackOverflow](https://stackoverflow.com) to ask questions about FilePond.
> 
> Whattt??????

There's an issue template to adhere to when submitting a new issue, if an issue doesn't follow the template, it's closed.

**Comment by hanzlahabib** [comment]
You can ask for more details, and wait until you get more detail, if they respond, answer the query if they don't you are free to ignore this issue and close this with tag incomplete details given,

**Comment by felixdenoix** [comment]
@hanzlahabib, Maybe since @rikschennink coded and offered the module for free to the community the people that are using it can make a tiny weeny bit of effort by respecting the authors guideline on asking a question ? Don't you think ?
