### ISSUE TITLE
How to hide file name and file size?

### ISSUE THREAD

**Issue by theqiwistylezz** [pqina/filepond#248]
Hello there and as usual - thank you for your great product!
I've got a question. How to hide the uploaded filename/filesize & "Loading" label?
Need to show only loading circle. Thank you very much!

**Comment by theqiwistylezz** [comment]
Also interested in how to make preview of video file?
Like mp4

**Comment by rikschennink** [comment]
> How to hide the uploaded filename/filesize & "Loading" label?

You'd have to use CSS and set the specific elements to `display:none`

> Also interested in how to make a preview of video file? Like mp4

In the future. Please create a single issue per item. This is currently not possible, You'd have to either fork the image preview plugin and add it or build a custom plugin.
