### ISSUE TITLE
Chunked uploads

### ISSUE THREAD

**Issue by jackttcoms** [pqina/filepond#249]
Hi, do you have an ETA for chunked uploads? Thanks

**Comment by SaphiLC** [comment]
i'd love to know that too

**Comment by jackttcoms** [comment]
Thanks. That looks good but my only concern is the endpoint.

It looks like it reveals the file location folder?
`endpoint: "http://localhost:3000/uploads/",`

To be honest, I will probably just wait for your update.

One other thing is with your uploader, is it possible to have multiple uploaders in one form? e.g. icon_img, preview_img, main_file

Thanks

**Comment by rikschennink** [comment]
@jackttcoms Yes, you can have multiple uploaders in one form.

`endpoint: "http://localhost:3000/uploads/"` this is the server end-point that handles the upload, it's not automatically the location the files are stored, it's wise to store the files somewhere else but that's up to the person implementing the backend.

**Comment by jackttcoms** [comment]
Hi, just thought I'd do a follow-up re: if you have an ETA yet?

Thanks so much.

**Comment by rikschennink** [comment]
@jackttcoms I'm sorry but not, I'm trying to find time. I also have a family to maintain so projects that yield actual income currently have priority, if you need this for a commercial project consider sponsoring FilePond (https://www.patreon.com/rikschennink). This would allow me to drop consulting work and eventually focus on my products full-time.

**Comment by ams-ryanolson** [comment]
@rikschennink Forgive me for "beating the dead horse" but right now We are looking at using doka and filepond for a project. What would you need Financially to complete chunks as it is something we will need when we get to video uploads

**Comment by rikschennink** [comment]
@ams-ryanolson No worries, I understand this is a much needed feature, can you contact me at info-at-pqina-dot-nl happy to discuss options

**Comment by rikschennink** [comment]
[It's happening](https://twitter.com/rikschennink/status/1169863361904775169?s=20) Thanks @ams-ryanolson

**Comment by jackttcoms** [comment]
YAYYYYYYYY. THANKYOU @ams-ryanolson

**Comment by rikschennink** [comment]
It's now available in version `4.7.0`, I'll leave this open for now in case there is immediate feedback.

Docs: https://pqina.nl/filepond/docs/patterns/api/server/#process-chunks

**Comment by ams-ryanolson** [comment]
Enjoy everyone!!!

**Comment by rikschennink** [comment]
Removed comments from sponsor as they didn't make the agreed payment.

**Comment by rikschennink** [comment]
Removed comments from (and related to) sponsor of this feature as they didn't make the agreed payment.

**Comment by Sopamo** [comment]
@rikschennink wow that's really unfortunate. We are using this feature now, so feel free to send me an email with the specifics of what was offered for this feature and we might be able to reimburse your for the feature (at least to some extend).

**Comment by rikschennink** [comment]
@Sopamo Hi Paul! Thanks for reaching out, I've sent you an email.

**Comment by rikschennink** [comment]
Paul came through and made the payment, thank you so much! 🙏
