### ISSUE TITLE
FilePond#addFiles ignores options.type

### ISSUE THREAD

**Issue by BudgieInWA** [pqina/filepond#253]
When calling `pond.addFiles(fileIds, { type: 'local' })`, the `type` is ignored and the files are `process`ed. I expect the files to be `load`ed instead, like `pond.addFile(fileId, { type: 'local' })`. The expected behaviour was observed in FilePond 3.7, but not in 4.2.

I am using Chrome 72 on Ubuntu 18.04.

**Comment by rikschennink** [comment]
`addFiles` should not be used for setting initial files only for adding new files, please use `files` for setting initial files.

**Comment by BudgieInWA** [comment]
In this case, we are also support adding new `local` files to the widget after FilePond has been initialised. Should we use `pond.setOptions({ files: allFileIds })` in this case, or this not supported?

For what it is worth, `pond.addFile(newId, { type: 'local' })` seems to work correctly, triggering `load` and all that.

**Comment by rikschennink** [comment]
Yes updating the files property should work. I'll look into the `addFile` thing just to be sure.

**Comment by rikschennink** [comment]
Confirmed the problem. Fixing now.

**Comment by rikschennink** [comment]
Fixed in version `4.3.0`
