### ISSUE TITLE
Absolute Path of Selected File

### ISSUE THREAD

**Issue by irfancnk** [pqina/filepond#254]
For people who or only interested in file path, can you please add an attribute to File object which contains the absolute path to file. I need `/home/user/Desktop/output.txt `rather than just `output.txt` since I will not use the server upload feature.

**Comment by rikschennink** [comment]
Will look into this.

**Comment by erozloznik** [comment]
That would be nice feature to have.

**Comment by erozloznik** [comment]
That would be nice feature to have.

**Comment by mytemizer** [comment]
Yea, I need that too

**Comment by rikschennink** [comment]
I've looked into this but it seems browsers do not expose this information, if someone can show me otherwise I'm happy to add this, but for now, it seems that this is impossible.

Will close for now.

**Comment by gildas15** [comment]
Me too I face this same issue. I just need the path of the uploaded image

**Comment by FBeraZulaloglu** [comment]
I have the same problem but is this problem relevant to filepnd or any file api in web ?

**Comment by rikschennink** [comment]
@FBeraZulaloglu see my earlier reply:

> I've looked into this but it seems browsers do not expose this information, if someone can show me otherwise I'm happy to add this, but for now, it seems that this is impossible.
