### ISSUE TITLE
FilePond Aspect Ratios For Type of Image

### ISSUE THREAD

**Issue by danielxu7** [pqina/filepond#255]
Hi, 

Currently we have `imageCropAspectRatio` property which sets the image to said ratio and if using Doka image editor it will also default to the ratio. I was wondering if it was possible to set individual ratios depending on whether an image is portrait or landscape, ie `3:2` ratio if it is landscape and `2:3` (or no set ratio) if it is portrait. Thanks!

**Comment by rikschennink** [comment]
Hi, This is currently not possible, what is the specific use case if I may ask? As in, why set a different crop ratio depending on image orientation?

**Comment by danielxu7** [comment]
The images we are uploading are pictures of housing properties for our clients. Our aspect ratio has always been 3:2 so for portrait images we don't cut out anything and just add enough whitespace padding on both sides of the image to make it 3:2. If the image is a square we also add padding. We've decided to strictly enforce 3:2 ratio even on portrait images after switching to FilePond but perhaps it could be a niche setting for others later on.

**Comment by rikschennink** [comment]
Thanks for the additional info. Padding the crop (adding whitespace) is on the roadmap so should become available somewhere in the future.

**Comment by rikschennink** [comment]
Will close this as "padding the crop" or "letterbox cropping" is on the Doka roadmap.
