### ISSUE TITLE
How to disable the shake animation when the upload fail ?

### ISSUE THREAD

**Issue by mazentouati** [pqina/filepond#257]
Hi there,
I'm using Filepond with Vue adapter and wondering how to disable the shake animation that occurs when the upload fail. I searched in the documentation API and did not find any property that control this animation.

![filepond](https://user-images.githubusercontent.com/14861869/53840903-b1624900-3f9b-11e9-9dc1-3ff16a15f215.gif)

I'm using the Image preview and validate type plugins.

**Comment by rikschennink** [comment]
You'd have to override the CSS `animation` property on the `li` with class `filepond--item`.

**Comment by mazentouati** [comment]
@rikschennink well disabling the animation within `filepond--item` seems to do nothing. Gladly, Chrome's animation inspector pointed out for me what elements are using the `shake` animation and they are `.filepond--file-wrapper` and `.filepond--panel.filepond--item-panel` after settings the `animation` value to `unset` for BOTH of them the shake is gone. Thanks for the hint.

**Comment by rikschennink** [comment]
Glad to hear you figured it out, to be honest, I wrote the reply on my phone so I wasn’t a 100% sure it was the right element :-)
