### ISSUE TITLE
Re-calling of browse() by ref does not work

### ISSUE THREAD

**Issue by alorenc** [pqina/filepond#258]
I needed to move the browse button beyond the Filepond component. In a big simplification, I did it so that in vuex I change the status of eg showBrowse after clicking the button.

The script from Filepond observes (watch) the state **showBrowse = TRUE**, then runs `this.$refs['pond'].browse()`
It works. The problem occurs when the `<file-pond>` is being wrapped in the display object depending on the value, eg showFilepond
```html
<div v-if="showFilepond">
  <file-pond ref="pond" ... />
</div>
```
**showFilepond == FALSE** - after sending files

After the first launch the upload works correctly. When you change the showFilepond to TRUE again, the browser opens, but the selected file is not sent (does not appear in the list)

To make it more interesting, after clicking the standard link in the component (open the browser), after selecting the file, everything works fine.

However, selecting the file by the browser running by **$refs** does not work, why and how to fix it?

**Comment by alorenc** [comment]
From what I've found yet. If the same filepond object (the same ref identifier) is displayed again, the problems are as above.

As before initializing the object I will generate a new ref key and give it to filepond, the problem will be solved.

Why it does not work on the same ID ?

**Comment by rikschennink** [comment]
I've just read the issue and am sorry but I don't understand the exact issue.

**Comment by alorenc** [comment]
If I find a free moment, I will prepare an example for you.

**Comment by rikschennink** [comment]
Closed in the mean time
