### ISSUE TITLE
Add Height Max-Height options to FilePondPluginFilePoster

### ISSUE THREAD

**Issue by mikeebowen** [pqina/filepond#259]
Because of the way we're saving files we can't use the FilePondPluginImagePreview to preview images. Fortunately FilePondPluginFilePoster does the job. However, unlike image preview, the poster does not have a height or max-height option. We are currently solving the problem with a wrapper element and setting the height on it, but an option on the poster would be a better solution. Thanks!

**Comment by robjbrain** [comment]
Just came here to post the same issue.

Can you share your current workaround?

**Comment by mikeebowen** [comment]
@robjbrain Right now I'm adding a `max-width` to the `.filepond--root` in css. I wanted to use height, but it doesn't work correctly. It's not perfect, but it works well enough, I would prefer to be able to use height.

**Comment by rikschennink** [comment]
Sourcecode of both the ImagePreview and Poster plugin are now on GH, feel free to submit a pull request.
