### ISSUE TITLE
How can I counter someone flooding the file system with temporary files?

### ISSUE THREAD

**Issue by Cohaven** [pqina/filepond#261]
### Summary

How can I counter someone continuously uploading files without submitting the form, effectively flooding the file system of the server with temporary files? 

[This article](https://twin.github.io/file-uploads-asynchronous-world/) mentions caching the files instead of creating temporary files, but I'm not seeing any documentation on it in filepond and the examples in the article are for ruby, not PHP.

The main way to prevent someone from spamming temporary files seems to be to set upload size limits on individual and groups of files by using [one of the plugins](https://pqina.nl/filepond/docs/patterns/plugins/file-validate-size/). Another, as mentioned in [this issue](https://github.com/pqina/filepond/issues/49#issuecomment-392514675), is to create server-side scripts to remove files that are older than a day from the temporary file directory. Are there any other approaches you would suggest?

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Device       | PC
| Browser      | Google Chrome
| Backend   | PHP

**Comment by rikschennink** [comment]
As far as I can read in that article it's exactly the same as creating temporary files, it's simply called caching instead.

You'd have to check this on the server. Everything on the client can be influenced. You could, for instance, register the user IP address, allow X amount of uploads, if it exceeds a certain amount prevent further uploads.
