### ISSUE TITLE
Feature request: Select file hook onSelectFile etc.

### ISSUE THREAD

**Issue by neno91** [pqina/filepond#264]
Hello.

I have been using Filepond for a while and i love what it can do.

But there is one small feature I miss, I would very much like to be able to select one of the files and get a reference to it in a callback event.

I would like to use this to mark files/image on my posts.

I have made edits to the node module to be able to do this but i would like to be able to update the plugin normally.

Thanks,
Neno

**Comment by rikschennink** [comment]
Would be a nice addition, I just marked the issue as an enhancement.

**Comment by neno91** [comment]
Superb! :) If i get satisfied with my current solution i will make a pull request.

**Comment by rikschennink** [comment]
@neno91 I appreciate it, but please note, the current "source" is a build target, so I would hold off on pull requests until I release the actual source and build scripts.

**Comment by neno91** [comment]
Okei 👍

**Comment by rikschennink** [comment]
`onactivatefile` was added in version `4.3.0`

**Comment by neno91** [comment]
Thanks allot 👍
