### ISSUE TITLE
VueJS - Reactive list of uploaded files

### ISSUE THREAD

**Issue by robjbrain** [pqina/filepond#266]
### Summary
I'm trying to get a list of the uploaded files that I can them loop through to request additional information for each file.

However I need to use the `serverId` to associate the extra inputs with a specific file, however the serverId is not populated in the array i'm receiving from the `updatefiles` callback and it isn't reactive so it doesn't get set later.

Here's an example:

```vue
<template>
    <div class="multi-file">
        <file-pond
                name="files"
                label-idle="Drop files here"
                allow-multiple="true"
                @updatefiles="updateFiles"
        />
        <h1>Description</h1>
        <div v-for="file in files">
            <h4>{{ file.filename }}</h4>
            <textarea :name="'descriptions[' + file.serverId + ']'"></textarea>
        </div>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                files: []
            }
        },
        methods: {
            updateFiles(files) {
                this.files = files
            }
        },
        computed: {
            uploadedFiles() {
                return this.files.filter(file => {
                    return !!file.serverId
                })
            }
        }
    }
</script>
```

`serverId` is always null because it gets set after `this.files = files`.

Is there any way to make it so that changes filePond makes to the file objects also happens to the file objects in my Vue Component?

Or is there another callback I can use for when the `serverId` is set?

**Comment by rikschennink** [comment]
I don't see any server property so FilePond won't be uploading/processing files and therefor the serverId will be null

**Comment by robjbrain** [comment]
I set the server property using setOptions not in the component.

It is uploading fine but the problem is updatefiles is called before the upload is finished so serverId is null. Then it is not updated because the object is not reactive.

**Comment by rikschennink** [comment]
can you use onprocessfile?

**Comment by robjbrain** [comment]
I think if an 'input' event was emitted on every event then v-model would work perfectly which would be great and solve the issue.

It would just need this change:

`vue-filepond.esm.js`
```
obj[value] = (...args) => {
                    this.$emit.(input, this._pond.getFiles())
                    this.$emit(value.substr(2), ...args);
                };
```

But i'm not sure how to test it. If I edit the file within node_modules (just to test) it doesn't seem to get picked up.

What's the right way to edit this file and test the change before submitting it to the repo?

**Comment by rikschennink** [comment]
You could copy the filepond files to your project and reference them there instead of in node_modules.

```js
import vueFilePond from './my-vue-filepond';
```
