### ISSUE TITLE
Supplying S3 Signed URL to 

### ISSUE THREAD

**Issue by michaelcuneo** [pqina/filepond#267]
I don't believe that this is a bug... maybe more a feature request, or ... it could just be a bug. But... 

I have Filepond working fine, to receive a file and upload it to an AWS S3... later I want to use the S3 URL as the existing state of the FilePond, to show people what the existing image is... and allow them the ability to change it. But I get "Error During Load" when supplying an signed URL to the Filepond object.

URL's are similar to this... and valid when pasted into a browser window.

https://fastlab-storage-fastlab.s3.ap-southeast-2.amazonaws.com/public/[filename].jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[mycreds]&X-Amz-Date=mydate&X-Amz-Expires=900&X-Amz-Security-Token=[securitytoken]&X-Amz-Signature=[signature]&X-Amz-SignedHeaders=host

How can I supply such a URL and allow it to load?

My existing FilePond object... 

If this.props.user.picture doesn't exist, it just creates it later during the upload creation.

```
            <FilePond
              ref={this.featurePond}
              allowMultiple={false}
              files={this.props.user.picture}
              maxFiles={10}
              onupdatefiles={fileItems => {
                this.setState({
                  user: {
                    mugshot: fileItems.map(fileItem => fileItem.file),
                  },
                });
              }}
            />
```

**Comment by rikschennink** [comment]
Is it possible that the developer console shows a CORS error?

**Comment by michaelcuneo** [comment]
I don't believe that I have any CORS errors. The URL is fine, the URL is accessible, it just won't display inside of FilePond's window, and errors instead.

**Comment by rikschennink** [comment]
Can you see the request of FilePond in your network tab and is it the same as the supplied URL?

**Comment by michaelcuneo** [comment]
The request that I'm looking at in the network tab is the request I'm supplying as the URL... so it appears as though Filepond is obtaining and loading the URL... but not displaying it.

**Comment by rikschennink** [comment]
I'd need a public test case to help out further

**Comment by ashishansurkartra** [comment]
I am facing the same issue. Is there a way to achieve this?

**Comment by michaelcuneo** [comment]
@ashishansurkartra I found out the solution to this ages ago and forgot to reply to this thread. Ensure that you're supplying a correct mime type when uploading to the S3, or it will default to application/octet-stream, which will generally always show you the image result when rendering into the browser, but filepond doesn't know what to do with it.

Here's my uploader.

```
export const uploadImage = async file => await Storage.put(file.name, file, {
    contentType: file.type,
  })
    .then(result => result)
    .catch(err => handleErrors(err));
```

**Comment by ashishansurkartra** [comment]
@michaelcuneo,
That fixed the problem. Super grateful. Thank you very much.
