### ISSUE TITLE
Server side validation and Customize file buttons

### ISSUE THREAD

**Issue by nguyendinhtuonguyen** [pqina/filepond#268]
I want to drag some files, it will automatically to server to check file existing validation, if file not exist, will upload. Otherwise will have 2 buttons 'override' or 'cancel'

One thing that Could you please add more and more example, the Document and API seems not enough. How I can add some button to file items?...

**Comment by rikschennink** [comment]
I'm not sure what you mean

**Comment by nguyendinhtuonguyen** [comment]
![image](https://user-images.githubusercontent.com/11214383/54737527-15634f00-4be3-11e9-8836-236d721dc861.png)

I just want to customize likes this, so I can server-side validation for each files then warning if need

**Comment by rikschennink** [comment]
You'd have to modify the source code to achieve this. Or write a custom plugin. You could use the image preview plugin as a starting point.

**Comment by nguyendinhtuonguyen** [comment]
Thanks alot, I have take one day to rewrite as the picture
