### ISSUE TITLE
Recursively add files in a directory and it's sub directories

### ISSUE THREAD

**Issue by TweeZz** [pqina/filepond#27]
The question says it all :)

**Comment by rikschennink** [comment]
@TweeZz Currently FilePond does not recursively read subdirectories. Added to the todo list.

**Comment by rikschennink** [comment]
@TweeZz Alright, that makes it a lot more difficult as FilePond would have to show the directory structure on the frontend as well and the server would have to be able to recreate it. This would be super nice but to be honest it's not a top priority right now.

I'm planning to release the source files in the near future, and describe the plugin API in the docs, a feature like this I think would be nice as a plugin instead of a core functionality.

**Comment by TweeZz** [comment]
@rikschennink 
- there is code which walks through the directory structure when doing a folder drag'n drop (`// the recursive function`)
- when debugging, I noticed that each `entry` has the relative path information. That info would somehow need to added to the already available properties in `e.detail.file`. (https://pqina.nl/filepond/docs/patterns/api/file/#properties)
- I personally don't think it's necessary (for now) to make any changes to the frontend

**Comment by rikschennink** [comment]
Will look into this.

I do think it's important to be able to see the structure of the directory on the front-end folders could have similarly named files, and it confirms visually that FilePond has parsed the directory structure and is sending that information to the server.

As I'm also offering a PHP solution and plan to add a NodeJS solution I want to make this work on the server as well.

**Comment by TweeZz** [comment]
Ok, I understand your argumentation for the front-end changes.

Currently, filepond walks through the directory structure, but it uploads the files in the first directory it bumps into which contains files.
Let me explain. 

I drag the 'mainDir'.
When I have the following structure:
```
[mainDir]
    [subDir1]
        file1.txt
        file2.txt
        [subDir1.1]
            file1.1.txt
    [subDir2]
        file3.txt
```
then file1.txt and file2.txt will be uploaded.

When I have the following structure:
```
[mainDir]
    [subDir1]        
        [subDir1.1]
            file1.1.txt
    [subDir2]
        file3.txt
```
then file1.1.txt will be uploaded.

I think this is because of the following line of code:
`if (totalFilesFound === files.length)`

I thought I could make it work by kinda collecting all the files (recursively) and then calling `resolve(files)`, but I guess I'm lacking some Promise knowledge. I wasn't able to get it to work.

**Comment by rikschennink** [comment]
Thanks for the additional details, will look into this further when I get the chance.

**Comment by rikschennink** [comment]
The feature is on the [backlog](https://wip.chat/products/191/pending), the request is pretty clear, so I'll close the issue.

**Comment by dclemenzi** [comment]
@TweeZz Did you come up with a solution to expose the relative path?

**Comment by TweeZz** [comment]
@dclemenzi Nope, I did not.

**Comment by majortom64** [comment]
It would be good to be able to send the directory structure as well as the files with data. In other words, if I have this structure:

[startDir]
      File1.pdf
      File2.pdf
      [emptyDir]
      [nonEmptyDir]
               File1.pdf

It needs to send startDir, emptyDir and nonEmptyDir, not just the files, as the use might want to upload a filesystem structure as well.

**Comment by louiselumapas** [comment]
Is it possible to upload a folder that contains multiple files without having to drag and drop ?? Like selecting a folder and instantly upload the files in it? There is nothing on the documentation for such or maybe i just missed it? @rikschennink

**Comment by rikschennink** [comment]
@louiselumapas Files already are added recursively, I think I've forgotten to resolve this issue, latest update also adds relative path info to the file object. `fileItem.file._relativePath`
