### ISSUE TITLE
Field name two times in the form data

### ISSUE THREAD

**Issue by yunda** [pqina/filepond#270]
### Summary

Field name (file in my case) inserted two times in the form data, the first one being an empty object. Server treats it as an empty object as a result.
Network tab shows:
```
Form Data:
file: {}
file: (binary)
```

### Expected behaviour

There should be only one field for a file.

| Environment  | Version
|------------- | -----------
| OS           Windows 7
| Browser    Chrome 71

**Comment by rikschennink** [comment]
FilePond posts both the file metadata and the binary. 

You can set up a [custom process method](https://pqina.nl/filepond/docs/patterns/api/server/#advanced) to work around this if needed.

**Comment by yunda** [comment]
@rikschennink thanks for the rapid response. That helped.
