### ISSUE TITLE
Uploading Empty File Fails

### ISSUE THREAD

**Issue by Banrion** [pqina/filepond#271]
### Summary
Attempting to upload an empty file causes the uploading on the UI to start showing, but never makes the upload request for the file. It then never times out.

### How to reproduce
Browse for a file using FilePond. Select a file with size 0 bytes.

### Expected behaviour
Uploads the file properly even when empty.

### Additional information
Noticed the bug in my own functionality and then tested using the examples on [https://pqina.nl/filepond/](https://pqina.nl/filepond/)

| Environment  | Version
|------------- | -----------
| OS           |  Windows
| Device       | Laptop
| Browser      | Chrome V72

**Comment by rikschennink** [comment]
Just published version `4.3.2`, should fix the issue.

**Comment by Banrion** [comment]
Tested, and it works. Thank you for the quick fix.

**Comment by rikschennink** [comment]
Fantastic! Thanks for confirming @Banrion!
