### ISSUE TITLE
Stop/cancel 'Loading' process

### ISSUE THREAD

**Issue by vince307** [pqina/filepond#272]
Hi,
I got a question in regards to have a custom upload method which is triggered via button after files are added to filepond. 
Is it possible to allow user to cancel the 'Loading' process that filepond is triggering when file is added. It looks that filepond is scanning, analyzing, loading to browser memory the file and afterwards allowing user to remove it from the list. Can this process be stopped with action "Tap to cancel" when Loading is performed. Is it possible to fetch ABORT_ITEM_LOAD event via filepond instance?

Below gif is presenting the case:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12682540/54767024-45671e00-4bf4-11e9-9592-b845b6903dfb.gif)

**Comment by rikschennink** [comment]
Can you confirm you have the file-encode plugin enabled? If so, it's encoding the file. 

I'm working on a fix.

**Comment by rikschennink** [comment]
Should be fixed in version `4.3.3`

**Comment by vince307** [comment]
Yes, file-encode plugin is enabled.
I just pulled v4.3.3 and it's working as expected, fix is working.
Thank you very much, for quick turnaround and quick respond.
I will close this thread now.

PS: awesome, great library, cheers for that

**Comment by rikschennink** [comment]
Glad to hear that! Thanks for confirming @vince307
