### ISSUE TITLE
Pass right data to filepond preview from own image editor.

### ISSUE THREAD

**Issue by phlegx** [pqina/filepond#273]
Hi!

### Summary

I have opened an issue on [pqina/filepond-plugin-image-edit#1](https://github.com/pqina/filepond-plugin-image-edit/issues/1) because there are many things unclear to me how to use an own editor with filepond.

### How to reproduce

I use the latest versions of filepond and its plugins.
I have followed this instructions [plugins/image-edit](https://pqina.nl/filepond/docs/patterns/plugins/image-edit/) to setup filepond. Assigned also the `imageEditEditor` property. It is unclear what type of data I have to pass to `output` for  `onconfirm: (output) => {}`. 

### What I want to do

I want to use cropperjs as editor. 

```js
data: {
  crop: {
    center: { // center relative to what? Pixel, percentage?
      x: .5,
      y: .5
    },
    flip: { // this is clear and works for me
      horizontal: false,
      vertical: false
    },
    zoom: 1,
    rotation: 0, // data range? -180 to 180 or 0 to 360?
    aspectRatio: null
  }
}
```

Any help is appreciated! Thx

**Comment by rikschennink** [comment]
Please don't open multiple issues. I've read your question and have simply had no time to respond yet.
