### ISSUE TITLE
onupdatefiles is called two times when using react-filepond

### ISSUE THREAD

**Issue by mrsamse** [pqina/filepond#274]
### Summary
The onupdatefiles function is called two times, when I add a file to the default filepond compontent.

### How to reproduce

Import the react-filepond component.
Add function to onupdatefiles and log it to the console.
You will see it two times.

### Expected behaviour
It only should be called one time.

**Comment by rikschennink** [comment]
I believe it's currently called twice so it's synced correctly when a file is rejected by one of the validation plugins. Will look into this, but for now, it manages to correctly sync the files list with a parent state ( in React, which is the main purpose of this method ).

**Comment by Tomo2** [comment]
When using filepond-jquery same thing happens.

**Comment by rikschennink** [comment]
It's run by the internal FilePond library so it will indeed happen everywhere. Will leave this as is for now.

**Comment by noelruault** [comment]
> ### Summary
> The onupdatefiles function is called two times, when I add a file to the default filepond component.
> 
> ### How to reproduce
> Import the react-filepond component.
> Add function to onupdatefiles and log it to the console.
> You will see it two times.
> 
> ### Expected behaviour
> It only should be called one time.

You can call your custom functions or trigger whatever you want using the "onaddfile" callback, and you will get a very similar behaviour.

Source: https://pqina.nl/filepond/docs/print-version/#callbacks

**Comment by louiselumapas** [comment]
Above only works when you've uploaded only one file.  I'm using onupdatefiles with the property allowMultiple: true (I'm trying to upload multiple).But it's rendering twice on console. any fix

**Comment by rikschennink** [comment]
@louiselumapas Indeed checking if the file is already in the array should suffice

**Comment by muhyilmaz** [comment]
How did you solve that, The problem continues on my code?

**Comment by yairkukielkazunzunegui** [comment]
`onupdatefiles` is called twice, and between those 2 calls, `onaddfile` is called once. Adding a working example with typescript:

`
import { FilePondFile, ActualFileObject } from 'filepond';
export type FileList = FilePondFile[];

const MyComponent: FC<MyComponentProps> = () => {
  const [files, setFiles] = useState<FileList>([]);

  const onAddFile = async () => {
    if (files && files.length > 0) {
      const file = files[0].file; // actual File API object
      const readBlobToText = (blob: ActualFileObject) =>
        new Promise((resolve, reject) => {
          const reader = new FileReader();
          reader.addEventListener('load', () => resolve(reader.result));
          reader.addEventListener('error', () =>
            reject(new Error('Reading file failed'))
          );
          reader.addEventListener('abort', () =>
            reject(new Error('Reading file aborted'))
          );
          reader.readAsText(blob);
        });

      const result = await readBlobToText(file);
      console.log('file contents', result);
    }
  };

  return (<DynamicUploadFiles
              files={[]}
              onaddfile={onAddFile}
              onupdatefiles={setFiles}
            ></DynamicUploadFiles>)
`

**Comment by timwm** [comment]
Alternatively you could use `onaddfile` and `onremovefile` with `pondInstance.getFiles()`

## Like:
```js
```

**Comment by timwm** [comment]
You could use `onupdatefiles` with `onaddfile`, `onremovefile` to maintain a tracked state.

## Like:
```ts

import "filepond/dist/filepond.min.css";
import { useRef, useCallback } from "react";
import { FilePond } from "react-filepond";
import { type FilePondFile } from "filepond";

type MyComponentProps = {
  onChange: (files: FilePondFile[]) => void;
};

function MyComponent({ onChange }: MyComponentProps) {
  const updateRef = useRef(false);

  const handleOnUpdate = useCallback(
    (files: FilePondFile[]) => {
      if (!updateRef.current) return;
      onChange(files);
      updateRef.current = false;
    },
    [onChange],
  );

  const handleAddOrRemove = useCallback(() => {
    updateRef.current = true;
  }, []);

  return (
    <FilePond
      onaddfile={handleAddOrRemove}
      onremovefile={handleAddOrRemove}
      onupdatefiles={handleOnUpdate}
    />
  );
}
```
