### ISSUE TITLE
Image size validation after crop

### ISSUE THREAD

**Issue by phlegx** [pqina/filepond#278]
Hi!

I have set `image-validate-size-min-width` and `image-validate-size-min-height` property in vue-filepond. It is the same as `imageValidateSizeMinWidth` and `imageValidateSizeMinHeight` using filepond without Vue.

After cropping the image and calling `onconfirm(output)` the cropped image is not re-validated. How can I re-validate the image after edit?

**Comment by rikschennink** [comment]
Hi, FilePond does not have a re-validation stage, the crop plugin itself should have a min image width and min image height setting. This makes sense as it would be weird to allow crops that are smaller than the required minimum quality.

**Comment by phlegx** [comment]
@rikschennink thank you very much! Now I validate cropped image dimension directly in the editor. :+1:

**Comment by rikschennink** [comment]
@phlegx Great! You can even pass the values straight to the editor if you wish (by reading out `imageValidateSizeMinWidth` and `imageValidateSizeMinHeight`).

**Comment by phlegx** [comment]
@rikschennink yep, already done! Thx
