### ISSUE TITLE
Documentation/Code issue: ondata not triggered

### ISSUE THREAD

**Issue by Tomo2** [pqina/filepond#280]
### Summary
Hello,
First of all - great plugin with many customization possibilities :). 
I'm trying to follow [documentation](https://pqina.nl/filepond/docs/patterns/api/server/#configuration) and it's written that 

> For brevity we’ll only look at the process property. All other properties can be configured with the same configuration object.

However, this seems to be not true as ondata is being triggered only for process property.

Looking into the code it seems to be true as only createProcessorFunction has sendRequest with wrapper data with ondata.

### How to reproduce
```
$(".message-attachment").filepond({
    server: {
        process: {
            url: "./UploadAttachments",
            method: "POST",
            ondata: function (formData) {
                console.log("load");
                return formData;
            }
        },
        load: {
            url: kendo.format("./LoadAttachment/{0}/", message.Id),
            method: "GET",
            ondata: function (formData) {
                console.log("load");
            }
        },
        revert: {
            url: "./RemoveAttachment",            
            method: "DELETE",
            ondata: function(formData) {
                console.log("revert");
            }
        }
    },
    files: files,
    allowMultiple: true
});
```
### Expected behaviour

Ondata is being triggered or documentation directly mentions that this property is useful only for process.

### Additional information

**Filepond version:** 4.2.0

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Browser      | Chrome 73.0.3683.86 (64-bit)

**Comment by rikschennink** [comment]
The `ondata` callback is indeed only available for the `process` end point. Please submit a PR to the docs repository with the necessary changes.
