### ISSUE TITLE
Set error.body on FilePond:error event

### ISSUE THREAD

**Issue by rtransat** [pqina/filepond#281]
### Summary
When I process an upload and I return a JSON response (when error occur) I would like to set a custom message in `FilePond:error` event

### How to reproduce
Use the process method to upload a file, return a status code different from 200 (422 in my case)

```php
public function processUploadImages(Request $request, TranslatorInterface $translator): Response
{
    /** @var \Symfony\Component\HttpFoundation\File\UploadedFile $file */
    $file = $request->files->get('images')[0];

    $validator = Validation::createValidator();
    $violations = $validator->validate($file,
        new Image([
            'maxSize' => '1k'
        ])
    );

    if (count($violations) > 0) {
        $errors = [];
        foreach($violations as $violation) {
            $errors[] = $translator->trans(
                $violation->getMessageTemplate(),
                $violation->getParameters(),
                'validators'
            );
        }

        $response = new JsonResponse([
            'errors' => $errors,
        ], 422);
        return $response;
    }

    $file->move($this->getParameter('path.tmp'), md5($file->getClientOriginalName() . time()));
    $response = new Response();
    $response->headers->set('Content-Type', 'text/plain');
    $response->setContent(md5($file->getClientOriginalName() . time()));
    return $response;
}
```

### Expected behaviour
I would like to set the body value to show my errors below my div containing the file which have the error.
![image](https://user-images.githubusercontent.com/1011503/55151383-6e386780-514e-11e9-82c4-4006aaacd0fa.png)

![image](https://user-images.githubusercontent.com/1011503/55151300-3b8e6f00-514e-11e9-8626-5aa9962b68b2.png)

I can use the `onerror` method on `process` event and return a JSON response but I can't have the `div` which contains the error.

The `body` key is empty and I don't know how to set my json response.

**Comment by rikschennink** [comment]
https://github.com/pqina/filepond/issues/229
