### ISSUE TITLE
Keep order

### ISSUE THREAD

**Issue by derFricklerDE** [pqina/filepond#282]
Hi,

is it possible to run the upload in the filename order? 

With resize and transform plugin it looks like the files to upload are randomly choosen (or first transformed).

In the docs i can´t find any var to keep the order on upload.

Thanks
David

**Comment by rikschennink** [comment]
Why do you need the uploads to be in order?

**Comment by derFricklerDE** [comment]
i want to give the user the option to label and sort the files while the uploader is still uploading the files.
The order is important for the gallery and the overall workflow

Any hack to keep the order for the transform plugin?

**Comment by rikschennink** [comment]
You could add the number of the file in the list as metadata to each file.

**Comment by derFricklerDE** [comment]
any example of this?

**Comment by rikschennink** [comment]
https://pqina.nl/filepond/docs/patterns/api/file/#methods
