### ISSUE TITLE
Loading uploaded local files in React

### ISSUE THREAD

**Issue by henok** [pqina/filepond#283]
### Summary
After uploading files to server, I am unable to load the files from server and have them display the desired information (logical file name, size, etc...) on the UI.  

Instead, this is what shows: 
![image](https://user-images.githubusercontent.com/498375/55304479-ae7f3a80-5419-11e9-8a93-774f6aeeb646.png)

Let me know if I am missing something obvious here.

### How to reproduce
Use FilePond tag with a server config containing "load" tag, like this: 

Helper method:
```js
convertToLocalFilePond(fileId) {
    return [{
        source: fileId,
            options: {
                type: 'local'
            }
        }]
}
```

FilePond tag: 
```jsx
<FilePond ref={ref => this.pond = ref} name="audioFile"
       server={{
              url: UPLOAD_SERVER_URL,
              process: {
                        url: '/files/upload',
                       withCredentials: true,
                       headers: authHeader,
                       timeout: 7000,
                       onload: this.handleUploadLoad,
                       onerror: this.handleUploadError
              },
              load: {
                       method: 'HEAD',
                       url: '/files/load/',
                       withCredentials: true,
                       headers: authHeader,
                       timeout: 7000,
              }
       }}

       files={this.convertToLocalFilePond(selectedEvent.audioFile)}></FilePond>
```

Have server response to HEAD method request with the values from [documentation](https://pqina.nl/filepond/docs/patterns/api/server/#restore). IE, header response contains: 

```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Disposition, Content-Length, X-Content-Transfer-Id
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: http://localhost:3000
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Disposition: inline; filename="audioFile-00f1877e-5966-4f0f-b982-3f3bcd6467b5.txt"
Content-Length: 10
Content-Type: image/jpeg
Date: Mon, 01 Apr 2019 04:43:00 GMT
Expires: 0
Pragma: no-cache
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
X-Content-Transfer-Id: 00f1877e-5966-4f0f-b982-3f3bcd6467b5
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
```

### Expected behaviour
Expected for the FilePond UI to show the file name and file size as returned by REST header values.

### Additional information
I've also tried using other HTTP Methods (GET and OPTIONS) and none seem to produce the desired results.

**Comment by rikschennink** [comment]
The `load` end point expects the file data (blob), I'm not sure if that is returned right now.

**Comment by henok** [comment]
So what is the best way to display the uploaded file logiclly, without writing the File data to the response body?

**Comment by rikschennink** [comment]
You can mock the file info using the `file` property.
```js
const pond = FilePond.create({
    files: [
        {
            // the server file reference
            source: '12345',

            // set type to local to indicate an already uploaded file
            options: {
                type: 'local',

                // mock file information
                file: {
                    name: 'my-file.png',
                    size: 3001025,
                    type: 'image/png'
                }
            }
        }
    ]
});
```

**Comment by henok** [comment]
Thanks. I will try this sometime today and update you on how it went.

**Comment by henok** [comment]
Hey, was too busy to try this last few days but finally did this evening. Looks like the above solved my problem. Thanks! 

![image](https://user-images.githubusercontent.com/498375/55664663-b5ce8b80-57ff-11e9-907d-01ebbf5287ca.png)

**Comment by rikschennink** [comment]
@henok Glad to hear that!
