### ISSUE TITLE
Set initial files with name instead of source

### ISSUE THREAD

**Issue by phlegx** [pqina/filepond#284]
Hi!

I load already stored images with filepond described like [here](https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files).

```js
files: [
        {
            source: 'long-signed-id',
            options: {
                type: 'local',
                file: {
                    name: 'my-file.png'
                }
            }
        }
    ]
```

and I don't want that filepond shows the source as filename in the field with CSS class `filepond--file-info-main` but I want, that filepond uses the filename supplied in options -> file -> name instead.

![asd](https://user-images.githubusercontent.com/111506/55329917-107a8700-5490-11e9-90ad-98ead413f5fd.png)

It is not so nice when the long secure id is displayed if a filename is given. Can this be changed?

**Another question:**

After filepond loads the images already stored on the server like described above:

1. How can the edit button be removed for this types of images?
2. If a uses clicks on the edit button an the file changes, then filepond should show the upload button to re-upload the new changed file. How can this be handled.

**Comment by rikschennink** [comment]
`file.name` only works if the other mock info is supplied as well. But at that point the file is not loaded (it's mocked) so your image preview will no longer work.

You could try using the file-rename plugin to rename the files. 

Please use StackOverflow for questions.

**Comment by phlegx** [comment]
Source property could be an URL or an unique server id. Using the unique server id as source property shows the unique server id as name. This could be solved if a developer can pass an option `filename`. If filename is present, show the filename instead of the ugly long unique server id.

**Comment by rikschennink** [comment]
The server should return the file name using the content disposition header.

**Comment by milewski** [comment]
@rikschennink returning the `Content-Disposition: inline; name="test" filename="test.jpg"` doesnt seem to be working, it randomly shows `test.jpg` upon several hard refreshes, I would say 1 out of 5 pages refreshes it display the correct `test.jpg` all the other times shows serverId instead.

**Comment by rikschennink** [comment]
I just tested to be sure (with Chrome 77 on MacOS), these are the headers I return in the [FilePond PHP API](https://github.com/pqina/filepond-server-php). No matter how much I refresh, have dev tools closed or open, add or remove the additional `name="test"`, it shows the name returned after `filename=`.

```php
header('Access-Control-Expose-Headers: Content-Disposition, Content-Length, X-Content-Transfer-Id');
header('Content-Type: ' . $file['type']);
header('Content-Length: ' . $file['length']);
header('Content-Disposition: inline; filename="' . $file['name'] . '"');
```

Maybe it has to do with the `Access-Control-Expose-Headers` header?

If you set a custom `server.load` method you can assign a name to the blob returned to FilePond and it'll use that name instead.

**Comment by starwarskidfan** [comment]
@rikschennink How did you manage to do that? I can find any documentation on the server.load method.

**Comment by rikschennink** [comment]
@starwarskidfan not sure I understand the question but: https://pqina.nl/filepond/docs/patterns/api/server/#load

**Comment by starwarskidfan** [comment]
@rikschennink You said that if you assign a custom sever.load method that you can assign a name to the blob. How did you manage to do that. I have not found a way to have a custom server.load method.

**Comment by rikschennink** [comment]
It's specified here: https://pqina.nl/filepond/docs/patterns/api/server/#advanced

**Comment by starwarskidfan** [comment]
@rikschennink Even, setting the headers is still not setting the name properly. Can you give me a string that worked for you?

**Comment by rikschennink** [comment]
@starwarskidfan See `content-disposition` snippet here: https://pqina.nl/filepond/docs/patterns/api/server/#load

**Comment by rikschennink** [comment]
FYI if you have set up a custom load method you need to make sure the file returned to FilePond had a name property with the name you want to show.

**Comment by pydrogo** [comment]
For me, the problem was with image-overlay plugin

**Comment by cata-code** [comment]
The easiest way is to make sure the source file url ends with the file name because filepond takes the filename from the url.
So if your URL is **https://example.com/download/611e2ec6-c742-4abe-8d0d-8f0afa2ae1d1**, then change it to **https://example.com/download/611e2ec6-c742-4abe-8d0d-8f0afa2ae1d1/file.pdf**

![image](https://github.com/user-attachments/assets/6b901650-fbec-4fea-9d0b-9a1112161e75)
