### ISSUE TITLE
Set a height and max-height (with scroll overflow) to the dropzone

### ISSUE THREAD

**Issue by HapLifeMan** [pqina/filepond#285]
Hi, is it possible to define a (max-)height while using FilePond? I cant get it work 🤔
Every height I try to apply with class/style is not working...

Somethink like this with the `label-idle` centered if there's no file:
```html
<file-pond :style="height: 100%; max-height: 500px;" />
```

Thanks!

**Comment by rikschennink** [comment]
You can target it using the `.filepond--root` selector.

**Comment by hasnatbabur** [comment]
@rikschennink The plugin is fine but. The plugin does not work with minimum height style and we are in trouble for this. Images are not shown if we use min-height on root. We also use Doka. We need a bigger height drop zone but not fixed height root with overflow scrollable area. Can this plugin support min-height drop zone?

**Comment by rikschennink** [comment]
@hasnatbabur you can set a bigger min-height to the `.filepond--root .filepond--drop-label` element.

```css
.filepond--root .filepond--drop-label {
    min-height: 10em;
}
```

**Comment by patra0o** [comment]
> @hasnatbabur you can set a bigger min-height to the `.filepond--root .filepond--drop-label` element.
> 
> ```css
> .filepond--root .filepond--drop-label {
>     min-height: 10em;
> }
> ```

This answer should be higher up and bolded in the docs somewhere.
