### ISSUE TITLE
File Action Buttons

### ISSUE THREAD

**Issue by Jayboy75** [pqina/filepond#286]
Is there a way to disable the File Action Buttons entirely? In our implementation, they are rendering as empty buttons invisible to the UI and triggering 508 compliance failures.

**Comment by Jayboy75** [comment]
Within each 'filepond--item' in the upload drop zone, there are 7 button elements, most of which contain disabled="disabled" attributes. These buttons are either entirely empty except for an ::after pseudo-element, or they contain svg paths (ie., the Cancel button's circle/x). Since these buttons contain no text, they do not meet accessibility standards. A button's text serves the same purpose as the label on an input field or dropdown (that is, to describe the purpose of the form control). More here:
https://www.w3.org/WAI/tutorials/forms/labels/#labelling-buttons

For symbol-based buttons that are not intended to display text, content can be hidden using 'screen-reader-only' styling. It would be as simple as wrapping the button text in a span tag that includes the requisite class. Bootstrap 4 accomplishes this like so:

```
.sr-only {
position:absolute;
width:1px;
height:1px;
padding:0;
overflow:hidden;
clip:rect(0,0,0,0);
white-space:nowrap;
-webkit-clip-path:inset(50%);
clip-path:inset(50%);
border:0
}
```

**Comment by rikschennink** [comment]
Thanks. 

Before releasing the initial version of FilePond I've successfully tested the current solution (using a `title` attribute) in both VoiceOver and NVDA. The action type and "button" are pronounced by both these assistive technologies. I don't have access to JAWS so I couldn't test with it.

I've just done a quick google search to check if this is a correct approach. Ended up on this page:
https://humanwhocodes.com/blog/2013/04/01/making-accessible-icon-buttons/

It lists these results for use of the `title` attribute.

- Chrome 25 (Win7/NVDA): “Email button”
- Internet Explorer 9 (Win7/NVDA): “Email button”
- Firefox 19 (Win7/NVDA): “Button email”
- Chrome 25 (Win7/JAWS): “Email Button”
- Internet Explorer 9 (Win7/JAWS): “Email Button”
- Firefox 19 (Win7/JAWS): “Email button”
- **Chrome 25 (Mac OS X/VoiceOver): “Button”**
- **Safari 6 (Mac OS X/VoiceOver): “Button”**
- Firefox 19 (Mac OS X/VoiceOver): “Email button”
- Mobile Safari (iOS 6/VoiceOver): “Email button”

It seems only older versions of Chrome and Safari had trouble dealing with the `title` attribute. I've ran some tests to be sure and all button names are pronounced correctly in recent versions of these browsers.

**Comment by Jayboy75** [comment]
@rikschennink The page you linked to specifically states, "_don’t_ use title as your button label." If you read on below that, (Update: 07-April-2013), the author of the article goes on to describe an optimal solution nearly identical to the one I've proposed above. A title tag on an empty button is not an accessible solution.

**Comment by rikschennink** [comment]
I know it says ''don’t use title as your button label". The article is however 6 years old, and my recent tests combined with the tests in the article seem to cover the screenreader use case. So unless there is another compelling case to have the text IN the button I'd rather leave things as they are.

**Comment by Jayboy75** [comment]
I almost mentioned the fact that you cited a relatively old resource; however, the age of the citation is not relevant in this case as the specific issue at hand has not changed in the last 6 years. Regardless of the results of your testing, using a lone TITLE attribute as the label on a button with no other text is simply not 508-compliant, nor does it meet WCAG standards:

https://www.w3.org/WAI/tutorials/forms/labels/#labelling-buttons ("The label of a <button> element is set _inside_ the element")

https://www.dhs.gov/sites/default/files/publications/Baseline_Tests_for_Software_and_Web_Accessibility_v2_0_2.pdf (Page 41, "The TITLE attribute cannot be the sole means of providing information.")

https://www.w3.org/TR/wai-aria-practices/#button ("The button has an accessible label. By default, the accessible name is computed from _any text content inside the button element_. However, it can also be provided with aria-labelledby or aria-label.")

https://stackoverflow.com/questions/41989399/how-to-mark-up-a-button-for-wcag-2-0-compliance ("Definitely do not use a title attribute. That does more harm than good.")

Accessibility is about providing to the lowest common denominator. Implementing a sub-optimal solution that does not meet requirements and calling it 'good enough' flies in the face of what it means to provide assistance those who need it. But ultimately, Filepond is your library, so of course you may do as you will with it. I opened this issue to help by highlighting a deficiency. Keep things as they are if that's what you want to do - hopefully myself and others in future will find ways to achieve accessibility despite the lack thereof.

**Comment by Jayboy75** [comment]
Fair enough. I didn't mean to put words in your mouth, but leaving things the way they were seemed to imply you felt that way. Clearly I was wrong; thanks for your attention to this - the enhanced implementation will be immensely useful.

**Comment by rikschennink** [comment]
`4.3.8` has `<span>` with label instead of using the `title` attribute. Tested on both VoiceOver and NVDA, should improve accessibility.

**Comment by hn1** [comment]
We are trying to use Filepond and have just logged a bug. There seems to be 100 issues outsatnding. Is this library maintained anymore?
