### ISSUE TITLE
CSS class for item status

### ISSUE THREAD

**Issue by phlegx** [pqina/filepond#287]
Hi,

I cannot find a CSS class in filepond, that helps to identify items by status in filepond. For example:

**Item status classes** (`<li class="filepond--item-[status]">`)

- dropped: file dropped in filepond, but not processed
- processed: file processed
- loaded local: file loaded from server (stored)
- loaded limbo: file loaded from server (limbo)
- edited: file edited but not processed

This could be very helpful to style filepond.

**Comment by rikschennink** [comment]
Every item in the list has a `data-filepond-item-state` attribute which you can use to identify the item status with in CSS (use attribute selectors).

**Comment by phlegx** [comment]
I know about this data attribute. But I cannot distinguish if the item status is only dropped but not uploaded, uploaded or always local and loaded from server.

**Comment by rikschennink** [comment]
```js
const StateMap = {
    DID_START_ITEM_LOAD: 'busy',
    DID_UPDATE_ITEM_LOAD_PROGRESS: 'loading',
    DID_THROW_ITEM_INVALID: 'load-invalid',
    DID_THROW_ITEM_LOAD_ERROR: 'load-error',
    DID_LOAD_ITEM: 'idle',
    DID_THROW_ITEM_REMOVE_ERROR: 'remove-error',
    DID_START_ITEM_REMOVE: 'busy',
    DID_START_ITEM_PROCESSING: 'busy',
    DID_REQUEST_ITEM_PROCESSING: 'busy',
    DID_UPDATE_ITEM_PROCESS_PROGRESS: 'processing',
    DID_COMPLETE_ITEM_PROCESSING: 'processing-complete',
    DID_THROW_ITEM_PROCESSING_ERROR: 'processing-error',
    DID_THROW_ITEM_PROCESSING_REVERT_ERROR: 'processing-revert-error',
    DID_ABORT_ITEM_PROCESSING: 'cancelled',
    DID_REVERT_ITEM_PROCESSING: 'idle'
};
```

These are the states available.

Why do you want to style them differently?

**Comment by phlegx** [comment]
I want to disable edit button, if the file is already uploaded to the server or loaded as local from the server because I'm not able to control edit button. 

**Example**

After uploading the file to the server or the file is loaded as local from server, the editor button is visible. If I click on the edit button I can crop the image an click save. After image edit save, the upload button should appear, so that I can re-upload the new cropped version of the file, but the upload button don't appear (if file is loaded as local from server).
