### ISSUE TITLE
Add a file icon (depending of the file extension) to the file instance

### ISSUE THREAD

**Issue by mharocsc** [pqina/filepond#290]
Trying to implement an upload files section in my site, using FilePond for React. I accept all kind of files (img, pdf, html, etc) and I want to associate a file icon to the file instance, using the React Component 'react-file-icon', this way user will see what kind of files he had in the list. Don't want to use the icon as a preview image, but besides the name or something like that inside the file instance. Is there a way to do this?

**Comment by rikschennink** [comment]
This is a question about FilePond please post these on [StackOverflow](https://stackoverflow.com/questions/ask?tags=filepond) (as requested in the issue template).
