### ISSUE TITLE
Default loading of image from S3 loads selectively

### ISSUE THREAD

**Issue by judemanutd** [pqina/filepond#291]
### Summary
I've setup the library and everything works fine but I'm facing a weird issue with loading an image from S3 as the default image. It loads when I do a full refresh on chrome aka SHIFT + F5 but when I try a simple refresh aka CTRL + R, it throws a cors error.
...

### How to reproduce
Try loading the given image as the default image in filepond.
[ <== Link to S3 Image ==> ](https://ofm-testing-images.s3.ap-south-1.amazonaws.com/images/restaurants/logo/1fadccda-fa7f-4479-802d-2e9f2707ae29.png)
...

### Expected behaviour
It should load all the times, irrespective of the type of refresh
...

### Additional information

File object config 

```ts
var obj = {
            // the server file reference
            source: image,

            // set type to local to indicate an already uploaded file
            options: {
              type: "local",

              // stub file information
              file: {
                name: "logo",
                size: size,
                type: type,
              },
              metadata: {
                poster: image,
              },
            },
          };
```

Load block
_this does not seem to get called on initial load but the image still loads sometimes_
```ts
load: function(source, load, error, progress, abort, headers) {
              axios({
                url: source,
                method: "GET",
                responseType: "blob", // important
              }).then(response => {
                console.log("TCL: response load", response);
                load(response);
              });
            },
```

### Error Log

```js
Access to image at 'https://ofm-testing-images.s3.ap-south-1.amazonaws.com/images/restaurants/logo/1fadccda-fa7f-4479-802d-2e9f2707ae29.png' from origin 'http://restaurant.octa-ofm.com:3010' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

```
Uncaught (in promise) Event {isTrusted: true, type: "error", target: null, currentTarget: null, eventPhase: 0, …}
```

S3 CORS Config

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>Access-Control-Allow-Origin</ExposeHeader>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>


```

| Environment  | Version
|------------- | -----------
| OS           | Linux 
| Device       | Laptop
| Browser      | Chrome

**Comment by rikschennink** [comment]
it sounds like this might be a caching issue. Can you add a unique URL to the image?

I believe this is related:
https://stackoverflow.com/questions/44865121/canvas-tainted-by-cors-data-and-s3

**Comment by judemanutd** [comment]
@rikschennink It was that, I had an `img` tag that was being loaded with the same resource before the filepond object fetched it, this caused the given resource to be **cached without any cors related headers** and when filepond requested this resource chrome being chrome picked up the cached object and tried to re-run it which didn't work since there were no cors headers.

I seem to have fixed the problem by adding just the `crossorigin` tag to the `img` element, this I presume tells chrome to fetch the resource with cors headers which makes it safe to use for all the following requests.
