### ISSUE TITLE
Multiple file upload pauses itself

### ISSUE THREAD

**Issue by ahmetcetin** [pqina/filepond#294]
### Summary
Multiple file upload pauses when you switch the tab.

### How to reproduce
Upload 100 or more files, each of which about 4-5 megs. While uploading, change the tab in browser, minimize it, or cover browser with another window and wait for a while. When you return back to the tab, you see that files are not uploaded, and paused.

### Expected behaviour
When I upload many files, it's natural that user switches the tab and do something else in the mean time, or goes to get cup of tea, but when user comes back, upload should finish, shouldn't pause.

### Additional information
Check this in stackoverflow: https://stackoverflow.com/questions/15871942/how-do-browsers-pause-change-javascript-when-tab-or-window-is-not-active

Browser is limiting setInterval and requestAnimationFrame when tab is inactive. If filepond is using one of those to upudate the animation, this could be the problem.

| Environment  | Version
|------------- | -----------
| OS           | MacOS 
| Device       | macbook pro
| Browser      | Chrome / Firefox, didn't test with safari

**Comment by rikschennink** [comment]
https://github.com/pqina/filepond/issues/239
