### ISSUE TITLE
Crashing on iPhone when using camera

### ISSUE THREAD

**Issue by gaiustemple** [pqina/filepond#295]
```js
FilePond.registerPlugin(
    FilePondPluginImageExifOrientation,
    FilePondPluginImagePreview,
    FilePondPluginImageResize
);
FilePond.setOptions({
    instantUpload: false,
    allowImageResize: true,
    server: {
        url: 'https://myapp.com',
        process: 'upload/images',
    }
});

var testImages = FilePond.create(
	document.querySelector('#xyz')
);

```

### Summary
When using iPhone camera as a source, after taking three pictures, the webpage crashes and reloads.  Using DropzoneJS.js I can add at least 10 I haven't tested how many I can add.  The file size for the images is 4-6.5mb, taking a photo directly from the webpage as this is how I want users to be able to add photos.
...

### How to reproduce
Added source just normally to the page.
Open page in Safari, take some pictures and add them until it crashes ~3 pics
...

### Expected behaviour
Keeps adding pictures
...

| Environment  | Version
|------------- | -----------
| OS           | iOS
| Device       | iPhone XS Max
| Browser      | Safari Latest

**Comment by rikschennink** [comment]
You have the `FilePondPluginImageResize` plugin registered but you're not setting a resize target?

**Comment by gaiustemple** [comment]
I've tried adding
```
var testImages = FilePond.create(
    document.querySelector('#xyz'),
    {
        imagePreviewHeight: 400,
        imageCropAspectRatio: '1:1',
        imageResizeTargetHeight: 300,
        imageTransformOutputQuality: 20
    }
);
```
and registering a couple more plugins
```
FilePond.registerPlugin(
    FilePondPluginFileValidateSize,
    FilePondPluginImageExifOrientation,
    FilePondPluginImagePreview,
    FilePondPluginImageTransform,
    FilePondPluginImageCrop,
    FilePondPluginImageResize
);
```
If I go to FilePonds landing page, the 'multiple' example on there crashes the page also after using the iPhone camera to add ~3 pictures so I don't think it's just my implementation..

**Comment by rikschennink** [comment]
Okay, that's good info. Looking into it ASAP.

**Comment by gaiustemple** [comment]
Great thank you,
I think the issue is with the `FilePondPluginImagePreview` plugin, I've done a test without the plugin registered and I could add 50+ images from camera.. as soon as I added it again it crashed after 2-3 images

**Comment by rikschennink** [comment]
Searched around a bit online. It seems the [iPhone XS Max has a devicePixelRatio of 3](https://stackoverflow.com/questions/53156259/detect-iphone-xr-and-iphone-xs-in-javascript), this might causes the image preview plugin to generate thumbnails that take up too much memory.

**Comment by gaiustemple** [comment]
Okay, that sounds right.
The height and width of the canvas element are 4032 and 3024 respectively.  Let me know if you'd like me to do any tests.
```
<canvas class="filepond--image-bitmap" width="3024" height="4032"
style="transform:scale3d(1, 1, 1) ;"></canvas>
```

**Comment by rikschennink** [comment]
Thanks for the info (very helpful), 4032 x 3024 is indeed way too big for a preview, I'll probably have some time to fix this later today.

**Comment by rikschennink** [comment]
Just published `4.0.6` of the image preview plugin, it should result in reduced preview image size, can you let me know if it fixes the issue?

**Comment by gaiustemple** [comment]
Just tested `4.0.6`

It doesn't crash the page anymore, but after adding ~6 images it just shows the grey box not the image.  When I try and use the debugger it does crash Safari after ~6 images.  The canvas element is still quite large..
```
<canvas class="filepond--image-bitmap" width="1427" height="1902" 
style="transform:scale3d(1, 1, 1) ;"></canvas>
```

**Comment by rikschennink** [comment]
What happens if you set `imagePreviewZoomFactor` to `1`.

**Comment by gaiustemple** [comment]
The canvas still stays the same height + width..

I'm setting it like so
```
var inputImages = FilePond.create(
    document.querySelector('#images'),
    {
        // imagePreviewHeight: 400,
        // imageCropAspectRatio: '1:1',
        // imageResizeTargetHeight: 400,
        // imageTransformOutputQuality: 20,
        imagePreviewZoomFactor: 1,
    }
);
```

**Comment by rikschennink** [comment]
Thanks, I'll run some additional tests.

**Comment by rikschennink** [comment]
Alright. Just published version `4.0.8` ( skipping `4.0.7` :D ) of the image preview plugin.

- Fixes an issue where the preview image was accidentally redrawn when a new image was added to the list. Causing double the memory use and serious slow downs on older browsers that don't support `createImageBitmap`.
- The initial preview uses a single canvas and no longer clones a "backbuffer" canvas.
- When updating the aspect ratio of the image (using [Doka](https://pqina.nl/doka/), another image editor, or the image crop API) a maximum of two canvases can be active at the same time (one for animating in and one for animating out, older canvases are discarded.
- Width and height of discarded canvas elements (that should automatically be released by Safari) are set to `1` so they take up less memory.

This should result in a serious performance and memory usage improvement.

**Comment by gaiustemple** [comment]
That's great Rik,
I've done one test and noticed a big improvement - managed to add ~40 images before a noticeable lag, but no crashes.

**Comment by rikschennink** [comment]
Fantastic! I’ll close the issue then.

**Comment by gaiustemple** [comment]
Hey Rik,

I just thought I would mention I have had it crash again once, but it's probably as I need to use it to upload a lot of pictures on one page.  As I only really need a thumbnail, I've been setting `imagePreviewMaxHeight: 100` but it is creating a canvas with a height of 915.  Is there a better way of doing this?  Also, would you consider adding a 'thumbnail' feature like this?

![Artboard](https://user-images.githubusercontent.com/26857336/55874840-7a2f1b00-5b8b-11e9-91c5-edd0629641e9.png)
![Artboard Copy](https://user-images.githubusercontent.com/26857336/55874851-81562900-5b8b-11e9-8f8a-9d598180efd7.png)


Here is the code it is producing on iPhone:
```
<div class="filepond--image-preview" style="transform:translate3d(0px, 0px, 0) scale3d(1, 1, 1) ;opacity:1;">
    <div class="filepond--image-clip" style="opacity:1;height:100px;width:74.97371188222924px;">
        <div class="filepond--image-canvas-wrapper" style="transform-origin: 356.5px 475.5px;transform:translate3d(-319.01314405888536px, -425.5px, 0) scale3d(0.10515247108307048, 0.10515247108307048, 1) rotateZ(6.283185307179586rad) ;opacity:1;height:951px;width:713px;">
            <div class="filepond--image-bitmap" style="transform:scale3d(1, 1, 1) ;">
                <canvas width="713" height="951"></canvas>
            </div>
        </div>
    </div>
</div>```

**Comment by rikschennink** [comment]
Hmm 915 seems overkill.

It scales to: 
max height * zoomFactor * pixeldensity * .75

Max height 100 determines the preview item max height. The internal canvas has a higher resolution (certainly on retina displays), and the zoom factor allows further zoom in of the image (but can be 1 when the image cannot be edited).
