### ISSUE TITLE
Bad widget rendering

### ISSUE THREAD

**Issue by raulferras** [pqina/filepond#296]
### Summary
Cannot manage to render the widget properly as seen in the demo.
There seems to be a problem calculating the height as explained below.

<img width="454" alt="imagen" src="https://user-images.githubusercontent.com/1103977/55667860-3b832300-5862-11e9-85e1-52b9d7c9bf23.png">

### How to reproduce
The following example, saved as an html and loaded in the browser reproduces the issue I'm having.
However, testing it as it is in jsfiddle.com seems to work properly: https://jsfiddle.net/k9wvbq10/

In jsfiddle I've noticed that the element `filepond--root` has inline setted a height `76px` that I suspect is set by javascript. This does not happen in my local example.
As soon as I set the height in my example to `76px`, then it looks correct.

I don't see any errors/warnings being displayed in the console of the browser that could indicate there is a problem.

```
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
<script src="https://unpkg.com/filepond/dist/filepond.js"></script></head>
<body>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">title</h5>
    <p>blabalbalbalabla</p>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">title 2</h5>
    <p>blabalbalbalabla</p>
    <p>    <input type="file" />    </p>
  </div>
</div>
</body>
<script>
      var pond = FilePond.create(document.querySelector('input[type="file"]'));
</script></html>
```

### Expected behaviour
![imagen](https://user-images.githubusercontent.com/1103977/55667834-df200380-5861-11e9-9003-89f9935a67df.png)

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Browser      | Chrome v73

**Comment by rikschennink** [comment]
This is how the fiddle looks in Chrome 73 on MacOS 10.14 

![Screenshot 2019-04-08 at 09 12 25](https://user-images.githubusercontent.com/1132575/55705180-7742f780-59de-11e9-8a92-d8b157bed381.png)

**Comment by raulferras** [comment]
Sorry maybe I did not explain me well.
In fiddle works as expected, where it fails is in local, if you try to save an html file with the code I pasted and open it with chrome, it behaves as I described.

I recognize is really strange tha same code works on jsfiddle and not from a raw html file loaded...

I tested it in different computers and they all suffer from the same issue.

**Comment by rikschennink** [comment]
I notice you're missing a doctype in your local file.

**Comment by raulferras** [comment]
Wow that was it...
How can that affect the rendering?  
With doctype:
<img width="371" alt="imagen" src="https://user-images.githubusercontent.com/1103977/55714914-d7906400-59f3-11e9-8cf7-520a3264a651.png">

Without:  
<img width="244" alt="imagen" src="https://user-images.githubusercontent.com/1103977/55714929-e0813580-59f3-11e9-8113-7daeda7889c2.png">

Notice the calculated inlined `height` is missing in the second example.
I'm just being curious here, never experienced this change of behaviour.

**Comment by rikschennink** [comment]
Without doctype your browser will just try to make the best of it / run in quirks mode.
https://stackoverflow.com/questions/5595073/is-it-neccessary-to-add-html-doctype-at-the-starting-of-the-web-page
