### ISSUE TITLE
Filepond 'add' and 'remove' events returns null

### ISSUE THREAD

**Issue by chtsngn** [pqina/filepond#297]
Hey @rikschennink,

I just started to use the 4.3.7 version of Filepond. I was using 3.9 before. In version 4.3, the 'addfile' and 'removefile' events return null.

I'm using VueJS, but I think the problem has nothing to do with it.

###### HTML:
```html
<file-pond
  @addfile="pond_dosya_eklendi('', $event, 'pond')"
  @removefile="pond_dosya_kaldirildi($event, 'pond')"
></file-pond>
```

###### VueJS:
```js
methods: {
    pond_dosya_kaldirildi(event, ref) {
      console.log(event);
      console.log(ref);
      // Output => null, "pond"
    },
    pond_dosya_eklendi(error, event, ref) {
      console.log(event);
      console.log(ref);
      // Output => null, "pond"
    }
  }
```
##### CodePen Link:
[CodePen - FilePond events returns null](https://codepen.io/chtsngn/pen/PgWZxZ)

### Summary

@addfile, @removefile events, returns null.

### Expected behaviour

In version 3.9 of Filepond, the first argument was 'event'. But now returning null.

| Environment  | Version
|------------- | -----------
| OS           | Ubuntu
| Device       | Lenovo
| Browser      | Chrome 73

**Comment by chtsngn** [comment]
@rikschennink '$event' doesn't work anymore, I guess. But i need to send parameters with the event.

**Comment by rikschennink** [comment]
@chtsngn I've never used `$event` so I wouldn't know how that is supposed to function. :-)

**Comment by chtsngn** [comment]
Check out [this](https://codepen.io/chtsngn/pen/PgWZxZ).
