### ISSUE TITLE
Filepond documentation list availaible events

### ISSUE THREAD

**Issue by AmauryLnd** [pqina/filepond#298]
Hi,

I've been using Filepond for a couple of days and it's a really good and helpful plugin, big up to all the devs.

Nevertheless i discovered the following code on StakOverflow :

```
$('#my-element').on('FilePond:processfile', function(e) {
	console.log('file added event', e.detail);
});
```

This means that many different event bindings are availaible for the pluging but are not referenced in the documentation.
I searched for it in que Jquery section and only found the "addFile"  event.
I think they all deserve to be mentioned in the "Jquery" section of the documentation :)

**Comment by rikschennink** [comment]
The jQuery section is only an adapter, you can view the full API to see what is possible.

https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#events

> FilePond exposes the following events, they’re the same as the callback methods. The event detail property will contain the relevant event information. We can subscribe to them by listing on the root node.
