### ISSUE TITLE
Ignoring filetype validation when FilePond is disabled

### ISSUE THREAD

**Issue by chtsngn** [pqina/filepond#299]
Hi again Rik,

I'm using FileTypeValidation plugin with FilePond. When FilePond is disabled, FileTypeValidation is ignored (sometimes it doesn't work) when activated again.

![Filepond bug](https://user-images.githubusercontent.com/18267195/55859866-a17dec00-5b7b-11e9-9c4d-dfe1f84cee2a.gif)

I'm still using VueJS :)

### Summary

Ignoring filetype validation when FilePond is disabled.

### Expected behaviour

Implementation of validation

### Additional information

[CodePen Link](https://codepen.io/chtsngn/pen/Pgpogx)

| Environment  | Version
|------------- | -----------
| OS           | Ubuntu
| Device       | Lenovo
| Browser      | Chrome 73

**Comment by rikschennink** [comment]
I’m but sure I understand the problem, please elaborate.

**Comment by chtsngn** [comment]
OK. I write step by step:

#### FilePond doesn't work:
##### 1- I disabled FilePond.

```html
<file-pond
   ref="pond"
   :disabled="disabled"
   :accepted-file-types="['image/*']"
></file-pond>
<v-btn color="primary" @click="disabled = !disabled">de/active</v-btn>
```

```js

let vm = new Vue({
  el: '#app',
  components: {
    FilePond: vueFilePond.default(FilePondPluginFileValidateType)
  },
  data: () => ({
    disabled: false,
  }),
})
```
I clicked "de/active" button and i disabled FilePond.
![1](https://user-images.githubusercontent.com/18267195/55864348-fd00a780-5b84-11e9-86cf-a224d1bd601b.gif)

##### 2- I reactivated.
I clicked "de/active" button again and i reactivated FilePond.
![2](https://user-images.githubusercontent.com/18267195/55864374-08ec6980-5b85-11e9-81e1-df0696b2b094.gif)

##### 3- I clicked Browse button. Nothing happened.
Note: This is happening sometimes.
![3](https://user-images.githubusercontent.com/18267195/55864382-0be75a00-5b85-11e9-975a-4a23f28abe3c.gif)

#### FileTypeValidation doesn't work:
##### 1- I disabled FilePond.
##### 2- Reactivated.
##### 3- I clicked Browse button. Browse dialog opens but fileTypeValidation doesn't work..

Sorry for the bad english. I hope I can tell you my problem.

**Comment by rikschennink** [comment]
Probably fixed in version `4.3.9`

**Comment by chtsngn** [comment]
I've opened a one issue because both issues are related to the disabled feature. Both solved. Thanks for your kindness.

**Comment by rikschennink** [comment]
Fantastic, glad to hear that 👍
