### ISSUE TITLE
Can filepond upload to amazon s3?

### ISSUE THREAD

**Issue by bonesoul** [pqina/filepond#3]
with the help of a hosted server side api?

**Comment by rikschennink** [comment]
Yes, shouldn't be a problem.

Looking at [S3 this upload example](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html#s3-example-photo-album-adding-photos) it should be possible to do it straight from the webpage with a custom [process function](https://pqina.nl/filepond/docs/patterns/api/server/#advanced).

**Comment by rikschennink** [comment]
Will close for now, if you have any further questions let me know. :-)
