### ISSUE TITLE
Disabling Undo option

### ISSUE THREAD

**Issue by snuuve** [pqina/filepond#30]
How to disable Undo feature?

**Comment by rikschennink** [comment]
What do you mean by Undo feature.

**Comment by snuuve** [comment]
This button "undo"
![image](https://user-images.githubusercontent.com/9519759/38628905-d827b2c8-3db2-11e8-9562-83a4db4e67b0.png)

**Comment by rikschennink** [comment]
It's currently not possible to disable this feature (only the revert action that removes the temp file from the server can be disabled), why do you want to disable it? What is the use case?

**Comment by snuuve** [comment]
Because we don't want to let users delete files from this component

**Comment by rikschennink** [comment]
Existing files? I assume a user can remove files they themselves dropped?

**Comment by snuuve** [comment]
Yes, but not from this component :)

**Comment by rikschennink** [comment]
Okay, thanks for clarifying! Final question, if you don't mind, how are you using FilePond? It helps to know the use case to determine how to best integrate this feature.

**Comment by rayax86** [comment]
Please, this is very important. There are many many cases you just want to avoid this, for example whenever a file is uploaded, it is processed and takes effect immediately. It would be meaningless to allow the user to revoke this file.

**Comment by rikschennink** [comment]
@rayax86 That would mean there's no way for the user to alter the interface state? The file is uploaded and stays green? Is that correct?

**Comment by rayax86** [comment]
@rikschennink That's the idea. Just need to show a tick in the button and don't register any `onclick` handlers on it.

**Comment by rikschennink** [comment]
@rayax86 The *Just* in your sentence is where the problem is. It's never just doing something. 😊

If I leave the button, it indicates the user can click it, but it won't do anything ( as it does not trigger any events ). The subtext shows to "tap to undo" but as there's no button there's nothing to tap. Removing the subtext makes the design look unbalanced, etc.

I've set up the situation on my dev machine but it's weird to upload a file and not be able to then remove it or revert your decision. It's like if this text box I'm typing this comment in would not allow me to use my backspace button.

**Comment by rikschennink** [comment]
@snuuve @rayax86 I just published version `1.4.0` which now has a `allowRevert` setting which defaults to `true`, set it to `false` to disable the undo feature.

**Comment by rayax86** [comment]
@rikschennink Thanks for the update 👍 

By "leaving the button" I actually mean "show something that looks the same as the button but don't allow the user to click it". Sorry I didn't make it clear.

As for your statement "It's like if this text box I'm typing this comment in would not allow me to use my backspace button", please consider cases similar to Google Instant: whenever you type in something, it triggers a change of state in the application. It might not be your case but is indeed my case.

All in all thanks for the update, this is such an awesome component. Keep up the great work!

**Comment by rikschennink** [comment]
@rayax86 No problem! 

I'm still struggling to understand the use case :)

**Comment by LordRampantHump** [comment]
i would like to be able to change the text from tap to undo to tap to continue or something

**Comment by rikschennink** [comment]
@LordRampantHump you can do so with the `labelTapToUndo` property
https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#labels

**Comment by nehadhiman6** [comment]
Please provide this feature.. for disabling remove/undo button.. sometime i need that user can only see initial files but has no right to remove those files..

**Comment by rikschennink** [comment]
@nehadhiman6 `allowRemove` and `allowRevert` should cover that

**Comment by remotemerge** [comment]
I changed `revert` to `null` and updated the tap label. This works for my use case.
```
server: {
  revert: null,
},
labelTapToUndo: 'tap to close',
```
Between, I don't understand who looks for the file delete feature in the upload component? Still, thank you for the plugin.
