### ISSUE TITLE
FilePond's created after page load not using FilePondPluginImagePreview

### ISSUE THREAD

**Issue by gaiustemple** [pqina/filepond#301]
### Summary
When creating a FilePond on the fly it doesn't seem to let me upload from iPhone camera.  Also even if FilePondPluginImagePreview is registered, the new FilePonds do not show the preview images.  Am I doing it wrong?

It will upload from the 'on the fly' FilePond if I select "Photo library", "Files".  Also other FilePond's that were initially on the page will allow uploading photo's directly from iPhone camera, just not the newly created ones.
...

### How to reproduce
```js
var html = '<input name="tag_' + inputNumber + '_images[]" id="tag_' + inputNumber + '_images" class="filepond" type="files" multiple>';
el.innerHTML = html;
anotherEl.appendChild(el);
window['tag_' + inputNumber + '_images'] = FilePond.create(
    document.querySelector('#pumptag_'+inputNumber+'_images'),
    {
        allowImageResize: true,
        acceptedFileTypes: ['image/*'],
        server: {
            url: appUrl,
            process: 'upload/images/pumptag_'+inputNumber+'_images',
            revert: 'upload/revert',
        },
        labelIdle: 'Add images or <span class="filepond--label-action"> Browse </span>',
        imagePreviewMaxHeight: 100,
        imageResizeUpscale: false,
        imageResizeTargetHeight: 1000,
        imageTransformOutputQuality: 80,
        imagePreviewZoomFactor: 1,
    }
);

```
PHP `var_dump($_FILES)` shows this
```php
array(1) {
  ["tag_2_images"]=>
  array(5) {
    ["name"]=>
    array(1) {
      [0]=>
      string(9) "image.jpg"
    }
    ["type"]=>
    array(1) {
      [0]=>
      string(0) ""
    }
    ["tmp_name"]=>
    array(1) {
      [0]=>
      string(0) ""
    }
    ["error"]=>
    array(1) {
      [0]=>
      int(1)
    }
    ["size"]=>
    array(1) {
      [0]=>
      int(0)
    }
  }
}
```
...

### Expected behaviour
Uploads from camera successfully
...

### Additional information

...

| Environment  | Version
|------------- | -----------
| OS           | iOS
| Device       | iPhone XS Max
| Browser      | Safari 12.1

**Comment by gaiustemple** [comment]
Ah.  My apologies, it is uploading from camera - I forgot to increase the `upload_max_filesize` `post_max_size` in `php.ini`.

**Comment by gaiustemple** [comment]
Also, I've just tested the `FilePondPluginImageExifOrientation` plugin.  This works as expected so the issues may be specific to the `FilePondPluginImagePreview`.  I haven't tested the other plugins..

**Comment by rikschennink** [comment]
Can you rewrite the issue to fit the title? It currently is a very confusing story.

**Comment by rikschennink** [comment]
Closed as was inactive for 12 days.

**Comment by gaiustemple** [comment]
Sorry I have been busy.
I got it to work in the end but when I get the chance I'll explain it better in case it is of any interest.
