### ISSUE TITLE
load current file...

### ISSUE THREAD

**Issue by erikdemarco** [pqina/filepond#302]
Hi, I want to use filepond as my product editor.

How to load current images that is stored on the server? So visitor can decide wheter to change the current images or add a new image.

It's like this form:
=>https://github.com/settings/profile

prefill some data if it has been filled before, but shows nothing when its hasnt been filled before.

**Comment by rikschennink** [comment]
Hi, thanks for your interest in FilePond.

🧠 If you have a question, please ask it on StackOverflow:
https://stackoverflow.com/questions/ask?tags=filepond

**Comment by erikdemarco** [comment]
@rikschennink hi, i have made a thread here:
=> https://stackoverflow.com/questions/55652465/filepond-load-default-image-files
