### ISSUE TITLE
styling should be optional. not forced.

### ISSUE THREAD

**Issue by erikdemarco** [pqina/filepond#303]
when you try the demo here:
=> https://pqina.nl/filepond/#multi-file-code

And if we dont do any styling, The button will automatically be on center.

The default should be on the left. If the developer want to change the position they can do it themself. 1000 person will have 1000 different style preference also. you cant generalize it to one styling.

I spent hours trying to figure out how to make it to unstyle the button.

**Comment by rikschennink** [comment]
FilePond styles are as is. You can customise them a bit, but it's quite opinionated. If things are illogical I'm always happy to consider changes. From your issues description it's not clear which button you're talking about.

**Comment by rikschennink** [comment]
Closed as was inactive for 9 days.
