### ISSUE TITLE
Changing colour of individual files for different errors

### ISSUE THREAD

**Issue by yewwoei** [pqina/filepond#304]
### Summary
Filepond currently does not seem to have an ability to customize the file color depending on various situations.

There is only one way to customize the color, by using the component-wide css classes like this:

```
[data-filepond-item-state*=error] .filepond--item-panel, [data-filepond-item-state*=invalid] .filepond--item-panel {
    background-color: darkgoldenrod;
}
```
Is there a way to program different colors for different errors?

E.g.
One type of error:
![image](https://user-images.githubusercontent.com/21275222/56240050-549c8880-6047-11e9-8153-a1359207bad3.png)
Another type of error:
![image](https://user-images.githubusercontent.com/21275222/56240116-785fce80-6047-11e9-8ae7-344c3ad2fe29.png)

Thank you!

**Comment by rikschennink** [comment]
Hi, I don't think this is currently possible without forking the library and modifying the code.

**Comment by rikschennink** [comment]
Closed because it's not something I'm considering to add in the near future. Of course this can change if other devs are interested or present other use cases.
