### ISSUE TITLE
FilePondPluginImageTransform hangs on safari iPhone x and above model

### ISSUE THREAD

**Issue by weijiegh** [pqina/filepond#309]
Filepond hangs in iPhone X and above with browser safari.

This is the final FilePond object:

```js
<FilePond ref={ref => this.pond = ref}
        files={this.state.files}
        allowMultiple={true}
        imageResizeTargetWidth="200"
        imageResizeTargetHeight="200"
        server={{
            // fake server to simulate loading a 'local' server file and processing a file
            process: (fieldName, file, metadata, load) => {
                // simulates uploading a file
                setTimeout(() => {
                    load(Date.now())
                }, 1500);
            },
            load: (source, load) => {
                console.log(source);
                console.log(load);
                // simulates loading a file from the server
                fetch(source)
                .then(res => { console.log(res); return res.blob();})
                .then((blob) =>{console.log(blob); return load(blob);});
            }
        }}
        oninit={() => this.handleInit() }
        onupdatefiles={fileItems => {
            // Set currently active file objects to this.state
            this.setState({
                files: fileItems.map(fileItem => fileItem.file)
            });
        }}>
</FilePond>
```

### Summary
FilePondPluginImageTransform hangs on safari iPhone x and above model

### How to reproduce

You can reproduce it using sample code from here:
https://github.com/pqina/react-filepond/blob/master/example/src/App.js

Add filepond-plugin-image-resize and filepond-plugin-image-transform
Change the sample code to add two more properties:
imageResizeTargetWidth="200"
imageResizeTargetHeight="200"
Run the sample code, use iPhone x and above model to browse to the url with "Safari" and try to upload a picture, it will hang forever with status "Uploading...".

### Expected behaviour
Should upload file correctly without hanging.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS  / iOS  / 
| Device       | iPhone X and above / 
| Browser      | Safari 11.1.1  /

**Comment by rikschennink** [comment]
Closed because double post.
https://github.com/pqina/filepond-plugin-image-transform/issues/6
