### ISSUE TITLE
Advanced server

### ISSUE THREAD

**Issue by jamesblasco** [pqina/filepond#31]
Hi!, I am trying to use filepond with firebase and I am having troubles using advanced server, it would awesome to have an example of it. For example my process function would be 

 ```
process  (fieldName, file, metadata, load, error, progress, abort)  {
               console.log('process')
                var uploadTask = this.$storage.child('images/' + file.name).put(file, metadata);
                uploadTask.on(this.$storage.TaskEvent.STATE_CHANGED,
                    function(snapshot) {
                        var progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
                        console.log('Upload is ' + progress + '% done');
                        progress(true, snapshot.bytesTransferred, snapshot.totalBytes)
                    }, function(e) {
                        console.log('error')
                        error(e.message)
                    }, function() {
                        console.log('done')
                        load(uploadTask.snapshot.ref)
                    });
                return {
                    abort: () => {
                        uploadTask.cancel();
                        abort()
                    }
                }
 },

```
But doesn´t work and abort method neither.

**Comment by jamesblasco** [comment]
I have fixed the problem, but firebase storage doesn´t allow to move files in its servers so I would like to avoid restore function.

**Comment by rikschennink** [comment]
Hi! Currently on a short vacation, so can’t do a lot of support, if you meant the “revert” functionality than you can disable it by passing null as the property value.

**Comment by jamesblasco** [comment]
Thanks

**Comment by JoaquimLey** [comment]
Hey @jamesblasco if you found an issue to your problem it would be considered best practice to post it here :P so future guys like myself don't have to open a duplicate issue :D 

I'm trying to use filepond as a UI component only (vue) and I'm currently having some trouble passing the progress through my own implementation.
