### ISSUE TITLE
filepond - submit.php not receiving files when called with form.submit();

### ISSUE THREAD

**Issue by alexxmed** [pqina/filepond#311]
Hello fellow developer!

🧠 If you have a question, please ask it on StackOverflow -> https://stackoverflow.com/questions/ask?tags=filepond

🐜 If you think you have found a bug, please use the template below to report it.

**The more details you provide, the more inclined others are to help you out and the faster the issue is resolved.**

If you're using one of the FilePond adapters for React, Vue, Angular or jQuery and think the issue might be related to the framework, submit the issue in the specific adapter repository.

Please format code snippets using triple backticks and set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

```js
const foo = 'bar';
```

### Summary

...

### How to reproduce

...

### Expected behaviour

...

### Additional information

...

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
Insufficient details supplied.

**Comment by alexxmed** [comment]
My submit.php is basically the one contained in filepond-boilerplate-php/public/api. The only modifications are the addition of two echo statements to help me see what is going on.

My main page (instead of index.php) contains a bunch of text inputs, a few check boxes and the filepond[] object as shown in my post.

I do not have a "submit" input/button. Instead I have a button that performs a function "onclick". Within that function are lines to write the record to the mySQL table and at the end, are the lines I show that get the form object and submit it.

My tree is like this:
[ /(project root)
    - (filepond boiler plate root)
    -- public
    --- index.html
    --- api
    ---- Doka (dir)
    ---- FilePond.class.php
    ---- Helper (dir)
    ---- tmp (dir)
    ---- uploads (dir)
    ---- README.md
    ---- Vagrantfile
    ---- config.php
    ---- config_doka.php
    ---- index.php
    ---- package.json
    ---- submit.php    
](url)

My submit.php looks like this:
[](<?php

// Comment if you don't want to allow posts from other domains
header('Access-Control-Allow-Origin: *');

// Allow the following methods to access this file
header('Access-Control-Allow-Methods: POST');

// Load the FilePond class
require_once('FilePond.class.php');

// Load our configuration for this server
require_once('config.php');

echo "submit.php - Line 15" . PHP_EOL;
$myFilePond = $_POST['filepond[]'];
echo "Line 17[" . $myFilePond . "]";
// $myFiles = $_POST['filepond[]']['files'];
// echo $myFiles;
// Catch server exceptions and auto jump to 500 response code if caught
FilePond\catch_server_exceptions();
FilePond\route_form_post(ENTRY_FIELD, [
    'FILE_OBJECTS' => 'handle_file_post',
    'BASE64_ENCODED_FILE_OBJECTS' => 'handle_base64_encoded_file_post',
    'TRANSFER_IDS' => 'handle_transfer_ids_post'
]);

echo $files;

function handle_file_post($files) {

    // This is a very basic implementation of a classic PHP upload function, 
    // please properly validate all submitted files before saving to disk or 
    // database, more information here
    // http://php.net/manual/en/features.file-upload.php
    
    foreach($files as $file) {
        FilePond\move_file($file, UPLOAD_DIR);
        echo $file . PHP_EOL;
    }
}

function handle_base64_encoded_file_post($files) {

    foreach ($files as $file) {

        // Suppress error messages, we'll assume these file objects are valid
        /* Expected format:
        {
            "id": "iuhv2cpsu",
            "name": "picture.jpg",
            "type": "image/jpeg",
            "size": 20636,
            "metadata" : {...}
            "data": "/9j/4AAQSkZJRgABAQEASABIAA..."
        }
        */
        $file = @json_decode($file);

        // Skip files that failed to decode
        if (!is_object($file)) continue;

        // write file to disk
        FilePond\write_file(
            UPLOAD_DIR, 
            base64_decode($file->data), 
            FilePond\sanitize_filename($file->name)
        );
        echo FilePond\sanitize_filename($file->name) . " uploaded." . PHP_EOL;
    }

}

function handle_transfer_ids_post($ids) {

    foreach ($ids as $id) {
        
        // create transfer wrapper around upload
        $transfer = FilePond\get_transfer(TRANSFER_DIR, $id);
        
        // transfer not found
        if (!$transfer) continue;
        
        // move files
        $files = $transfer->getFiles(defined('TRANSFER_PROCESSOR') ? TRANSFER_PROCESSOR : null);
        foreach($files as $file) {
            FilePond\move_file($file, UPLOAD_DIR);
            echo $file . ' moved.' . PHP_EOL;
        }

        // remove transfer directory
        FilePond\remove_transfer_directory(TRANSFER_DIR, $id);
        echo $id . ' removed.' . PHP_EOL;
    }

})

**Comment by alexxmed** [comment]
Hi Rik --

Please, how can I provide additional details since the case has been closed.
I am trying, but it doesn't look like it's letting me.

I will provide all the info I can. Here is what I tried to add:

My submit.php is basically the one contained in 
filepond-boilerplate-php/public/api. The only modifications are the 
addition of two echo statements to help me see what is going on.

My main page (instead of index.php) contains a bunch of text inputs, a 
few check boxes and the filepond[] object as shown in my post.

I do not have a "submit" input/button. Instead I have a button that 
performs a function "onclick". Within that function are lines to write 
the record to the mySQL table and at the end, are the lines I show that 
get the form object and submit it.

My tree is like this:
/(project root)
- (filepond boiler plate root)
-- public
--- index.html
--- api
---- Doka (dir)
---- FilePond.class.php
---- Helper (dir)
---- tmp (dir)
---- uploads (dir)
---- README.md
---- Vagrantfile
---- config.php
---- config_doka.php
---- index.php
---- package.json
---- submit.php
<https://github.com/pqina/filepond/issues/url>

My submit.php looks like this:
[](<?php

// Comment if you don't want to allow posts from other domains
header('Access-Control-Allow-Origin: *');

// Allow the following methods to access this file
header('Access-Control-Allow-Methods: POST');

// Load the FilePond class
require_once('FilePond.class.php');

// Load our configuration for this server
require_once('config.php');

echo "submit.php - Line 15" . PHP_EOL;
$myFilePond = $_POST['filepond[]'];
echo "Line 17[" . $myFilePond . "]";
// $myFiles = $_POST['filepond[]']['files'];
// echo $myFiles;
// Catch server exceptions and auto jump to 500 response code if caught
FilePond\catch_server_exceptions();
FilePond\route_form_post(ENTRY_FIELD, [
'FILE_OBJECTS' => 'handle_file_post',
'BASE64_ENCODED_FILE_OBJECTS' => 'handle_base64_encoded_file_post',
'TRANSFER_IDS' => 'handle_transfer_ids_post'
]);

echo $files;

function handle_file_post($files) {

|// This is a very basic implementation of a classic PHP upload 
function, // please properly validate all submitted files before saving 
to disk or // database, more information here // 
http://php.net/manual/en/features.file-upload.php foreach($files as 
$file) { FilePond\move_file($file, UPLOAD_DIR); echo $file . PHP_EOL; } |

}

function handle_base64_encoded_file_post($files) {

|foreach ($files as $file) { // Suppress error messages, we'll assume 
these file objects are valid /* Expected format: { "id": "iuhv2cpsu", 
"name": "picture.jpg", "type": "image/jpeg", "size": 20636, "metadata" : 
{...} "data": "/9j/4AAQSkZJRgABAQEASABIAA..." } */ $file = 
@json_decode($file); // Skip files that failed to decode if 
(!is_object($file)) continue; // write file to disk FilePond\write_file( 
UPLOAD_DIR, base64_decode($file->data), 
FilePond\sanitize_filename($file->name) ); echo 
FilePond\sanitize_filename($file->name) . " uploaded." . PHP_EOL; } |

}

function handle_transfer_ids_post($ids) {

|foreach ($ids as $id) { // create transfer wrapper around upload 
$transfer = FilePond\get_transfer(TRANSFER_DIR, $id); // transfer not 
found if (!$transfer) continue; // move files $files = 
$transfer->getFiles(defined('TRANSFER_PROCESSOR') ? TRANSFER_PROCESSOR : 
null); foreach($files as $file) { FilePond\move_file($file, UPLOAD_DIR); 
echo $file . ' moved.' . PHP_EOL; } // remove transfer directory 
FilePond\remove_transfer_directory(TRANSFER_DIR, $id); echo $id . ' 
removed.' . PHP_EOL; } |

})

-- Alex

**Comment by rikschennink** [comment]
I advise to inspect the network tab of your developer tools to see if you can find the post data in the response of the page when it loads. That way you know if FilePond is sending the data, and what name the fields have. You can then line up the backend.

**Comment by alexxmed** [comment]
Thanks Rik.
I’ll try that.
