### ISSUE TITLE
Remote Service Images upload to server again after calling processFiles

### ISSUE THREAD

**Issue by northkode** [pqina/filepond#312]
I am adding in files via the config files array and this all works great via the load function. 
But later in my UI the user clicks a button that does a batch processFiles on the component and for some reason the remote images try and upload again.

This seems like a bug considering on initial load the upload button from all loaded images is invisible cause it knows its remote. But the processFiles function doesn't seem to know. 

I was going to try and hack and set the status to the PROCESS_COMPLETE value but that doesnt seem to be a elegant solution.

Version 4.4.2

**Comment by rikschennink** [comment]
Should be fixed in version `4.4.6`, please confirm.

**Comment by philgoeschl** [comment]
@northkode for me the workaround was to initially set the instant upload to true and then check if a profile image is available => if available set this.pondOptions.instantUpload to false else to true 

I put this into the section where I set the values of the modelForm 

I use Angular and the version 4.4.0

**Comment by northkode** [comment]
@rikschennink seems to be resolved in 4.4.6, thanks!
