### ISSUE TITLE
calling load() with a Blob, overrides filename from header

### ISSUE THREAD

**Issue by khoanguyen96** [pqina/filepond#315]
### Summary
I'm configuring the `load` endpoint as a function, as the API I'm working needs the `id` to be set as part of the URL `GET /api/uploads/<serverId>/load`.

It seems no matter what I try to do it uses the URL as the filename?

![image](https://user-images.githubusercontent.com/7454142/57561465-b1d2e380-7340-11e9-8203-97a2929037ad.png)

### How to reproduce
Set server options for `load` (I'm using [`axios`](https://github.com/axios/axios)):
```js
import axios from 'axios';

const $http = axios.create({ baseUrl: 'https://some.api.here' });

// filepond accepts the headers as a string (?)
const headersToString = headers => Object.keys(headers)
  .map(h => `${h}: ${headers[h]}`)
  .join('\r\n');

const load = (source, load, error, progress, abort, headers) => {
  // allow cancellation
  const { CancelToken } = axios;
  const cancelSource = CancelToken.source();

  const r = $http.get(`uploads/${source}/load`, {
    cancelToken: cancelSource.token,

    responseType: 'blob',

    onUploadProgress: (e) => {
      progress(e.lengthComputable, e.loaded, e.total);
    },
  });

  r.then(response => headers(
    headersToString(response.headers),
  ));

  // call the load method with a file object/blob when done
  r.then(({ data }) => load(data));

  r.catch((e) => {
    // if it's a cancelled request ignore it
    if (!axios.isCancel(e)) {
      error(e);
    }
  });

  return {
    abort: () => {
      cancelSource.cancel();
      abort();
    },
  };
};
```

Set the desired file on filepond (I'm using Vue.js):
```html
 <file-pond
      v-bind="serverOpts"
      :files="desiredFiles" />
```

```js
export default {
  data() {
    return {
	  desiredFiles: [
        { source: <serverId>, type: 'local' },
      ],
	};
  },
};
```

### Expected behaviour
Uses the filename from the `content-disposition` header

### Additional information
I spent some time debugging, but I suspect it might be overwriting the filename from the returned `Blob` in `load()`

from [`src/js/app/utils/createFileLoader`](https://github.com/pqina/filepond/blob/master/src/js/app/utils/createFileLoader.js#L79)

However, setting a breakpoint at the call for [`getFileInfoFromHeaders()`](https://github.com/pqina/filepond/blob/master/src/js/app/utils/createFileLoader.js#L125) seems to parse the headers properly.

![image](https://user-images.githubusercontent.com/7454142/57561818-f6f81500-7342-11e9-92cc-bbf8700ff1f9.png)

My Headers:
```
HTTP/1.1 200 OK
X-Powered-By: Express
server: nginx/1.14.0 (Ubuntu)
content-type: application/octet-stream
content-length: 255
connection: close
cache-control: no-cache, private
date: Fri, 10 May 2019 23:41:37 GMT
access-control-expose-headers: Content-Disposition, Content-Length, X-Content-Transfer-Id
content-disposition: inline; filename="client.wys"
x-content-transfer-id: 1183
x-ratelimit-limit: 60
x-ratelimit-remaining: 55
access-control-allow-origin: *
access-control-allow-methods: POST, GET, OPTIONS, PUT, PATCH, DELETE
access-control-allow-credentials: true
access-control-max-age: 86400
access-control-allow-headers: Content-Type, Authorization, X-Requested-With, Cache-Control
```

| Environment  | Version
|------------- | -----------
| OS           | Linux
| Device       | PC
| Browser      | Chrome Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by rikschennink** [comment]
I'm not sure why this happens. It's difficult to reproduce quickly. I advise to load the uncompressed version of FilePond and simply debug through it to find what happens. I might have time to test this later this month.

**Comment by khoanguyen96** [comment]
Hey, I made a [repository](https://github.com/khoanguyen96/express-filepond-basic-ex) where this can be reproduced.

In the meantime, I'll try to debug it myself (once I have time later this month as well)

Thanks!

**Comment by milewski** [comment]
For me the filename is only taken from `content-disposition: inline; filename="file.jpg"` if my devtools is open o.o

**Comment by rikschennink** [comment]
@milewski Fantastic, glad to hear that. 

> @rikschennink actually that is it!! it only happens if I enable `filepond-plugin-image-overlay` if I remove it I get the right filename every time!

@nielsboogaard might want to look into this.

**Comment by nielsboogaard** [comment]
Thanks for notifying me @rikschennink , that's indeed something I can look at.
@milewski would you be so kind to create an issue here https://github.com/nielsboogaard/filepond-plugin-image-overlay/issues?

**Comment by milewski** [comment]
Done!

**Comment by rikschennink** [comment]
Please note that if you set up a custom load method and you return a `blob`, FilePond can't know the filename as the `blob` doesn't have a `name` property. Content disposition parsing is only handled by FilePond if there's no custom load method defined.

Will close this.

**Comment by Naghal** [comment]
`Access-Control-Expose-Headers: Content-Disposition` worked for me
