### ISSUE TITLE
Image preview doesn't honor EXIF rotation

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [pqina/filepond#316]
The image upload preview doesn't seem to honor EXIF rotation values. For example, see:

 ![Screenshot 2019-05-13 11 41 51](https://user-images.githubusercontent.com/1685007/57611895-1de95d80-7574-11e9-9b15-47ab2e3e0a95.png)
 
Expected behavior for all images is to display like the top left image. Some EXIF rotation values are a bit exotic (mirrored) but it would be nice to have at least correct behaviour for the 90deg (counter) clockwise rotations.

There's a nice repository with test images: https://github.com/recurser/exif-orientation-examples

**Comment by rikschennink** [comment]
Have you registered the exif orientation plugin?

**Comment by SanderVanLeeuwen** [comment]
Oh wow. No I did not 🙈

Works like a charm now. My apologies!
