### ISSUE TITLE
Incorrect height of root with grid thumbnail

### ISSUE THREAD

**Issue by smickar** [pqina/filepond#317]
Hi, height of root counts only first image added. If you add second (and so on)image with larger height it will overflow.

![filepond](https://user-images.githubusercontent.com/45596334/57693399-66267f80-7649-11e9-9e16-bfec845ef1f8.jpg)

Thank you
Radim Smicka

**Comment by rikschennink** [comment]
Please see the entry on [Grid layout in the docs](https://pqina.nl/filepond/docs/patterns/api/style/#grid-layout), especially the note.

> Make sure that each item is the same height. FilePond currently calculates the height of the first item in the list and then uses that as the base height for each item. You can set the item height using styleItemPanelAspectRatio, imageCropAspectRatio, or by setting a fixed imagePreviewHeight.

**Comment by mirraj2** [comment]
@rikschennink I'm having the same issue.  Seems like it should just compute the max height of all the items in the list and use that instead of just using the height from the first one.

**Comment by rikschennink** [comment]
> @rikschennink I'm having the same issue. Seems like it should just compute the max height of all the items in the list and use that instead of just using the height from the first one.

It isn't

**Comment by stunaz** [comment]
@rikschennink that's a bigger issue on my side... especially if the first item has an error:
![image](https://user-images.githubusercontent.com/1305483/127404053-f4674cd5-380d-4408-9889-9662ff9844bb.png)
any suggestions or temporary workaround?

**Comment by rikschennink** [comment]
@stunaz see this reply https://github.com/pqina/filepond/issues/317#issuecomment-492194409

**Comment by stunaz** [comment]
@rikschennink well it is not an issue with the height per se. I understand that I can set the height from the 1st item.. But its a little different when I have error, it will take the 44px of red error (as first item).

**Comment by rikschennink** [comment]
@stunaz have you set `styleItemPanelAspectRatio` ?

**Comment by stunaz** [comment]
Thanks a lot @rikschennink .... that is way better:
![image](https://user-images.githubusercontent.com/1305483/127599762-c05fed6a-b636-4938-9deb-7033b2caa316.png)
