### ISSUE TITLE
I need access to the File id in the server.process method

### ISSUE THREAD

**Issue by nilsegger** [pqina/filepond#318]
Currently a custom process function only receives the blob of the file and not the FilePond File object. My custom process function uploads images bigger than 1mb in chunks, hence it sometimes takes a bit longer. My FilePond instance takes multiple files. On process I store each file in a map using the file name as the key. The problem here is that when there are multiple files with the same file name uploaded from different directories this wont work.

Pseudo Code:
```js
class UploadingImage {
    bool uploadAborted;
    FilePond file;
}

Map<String, UploadingImage> files;

filePond.on('addFile', (error, filePondFile) {
    // Here I'd love to use the filePondFile.id instead of filePondFile.file.name
    files[filePondFile.file.name] = new UploadingImage(false, filePondFile)
    filePond.processFile(filePondFile.file);
})

filePond.on('processfileabort', (error, filePondFile)) {
   // filePondFile.id would be accesable
    files[filePondFile.file.name].uploadAborted = true;
}

//FilePond Custom Process Function
processFile(fieldName, file, metadata, load, error, progress, abort) {
     // Here I do not get the file id, hence have to use file.name, which I believe will cause problems with files having the same name, but uploaded from different directories.
    if(files[file.name].uploadAborted) abort();
    else {
         abort();
    }
}
```

I just need to be able to identify which Image in the map is currently being used by process and I think it would be helpful to have the FilePond File id.

The function I'm talking about:
![image](https://user-images.githubusercontent.com/19248965/57853230-7bd0ac00-77e5-11e9-8058-756e75e61373.png)

**Comment by rikschennink** [comment]
Hi @nilsegger,

You can use the `metadata` property to store a unique id per file and add it to the file item (use the `setMetadata` method). The `metadata` is received in the `server.process` method.

**Comment by nilsegger** [comment]
Thank you for your answer.

**Comment by lolo888** [comment]
Hi rik,
i also need this file.id in the "process:" for each file, i find that this function will be needed.
https://user-images.githubusercontent.com/19248965/57853230-7bd0ac00-77e5-11e9-8058-756e75e61373.png

if I understand the metadata apply to all objects, then it should be possible to apply a different metadata (id) for each object

**Comment by markocupic** [comment]
Hi @rikschennink 

How can I access the `itemId` (-> aq1202k5r) in the process method?

`process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {}` 

 After I have received the response from the server, it would be nice to target the correct list item, to inject some error messages.

<img width="703" alt="image" src="https://github.com/user-attachments/assets/0a2347c8-38f7-435b-a6b2-79b2b77d8e5f">

**Comment by rikschennink** [comment]
> How can I access the itemId (-> aq1202k5r) in the process method?

AFAIK you cannot. The process method should return the server file id. That's its main purpose.

> After I have received the response from the server, it would be nice to target the correct list item, to inject some error messages.

You can return error messages using the process hook `error` callback.
https://pqina.nl/filepond/docs/api/server/#process-1
