### ISSUE TITLE
Boilerplate Express/Node

### ISSUE THREAD

**Issue by chewtoys** [pqina/filepond#32]
Anyone has example how to handle the upload process?

**Comment by rikschennink** [comment]
Hi! Don’t have this yet but am planning to build a node version of the PHP boilerplate in the near future. I’ve played around with Multer and that makes handling the upload a lot easier so it might be of help to you.

**Comment by David-Melo** [comment]
@chewtoys https://gist.github.com/David-Melo/4b36e969b9cfcda8f065156e056ddaab

I just set this up for use with feathers.js which is based on express.
