### ISSUE TITLE
filepond--root's height doesn't seem to be updating on window resize

### ISSUE THREAD

**Issue by gaiustemple** [pqina/filepond#320]
```js
const avatarInput = FilePond.create(
  document.querySelector('.filepond'),
    {
      server: {
        ...
      },
      labelIdle: `Drag & Drop your avatar or <span class="filepond--label-action">Browse</span>`,
      imagePreviewHeight: 170,
      imageCropAspectRatio: '1:1',
      imageResizeTargetWidth: 200,
      imageResizeTargetHeight: 200,
      stylePanelLayout: 'compact circle',
      styleLoadIndicatorPosition: 'center bottom',
      styleButtonRemoveItemPosition: 'center bottom',
      files: [
        {
          source: 'user_avatar_file.jpg',
          options: {
            type: 'local'
          }
        }
      ]
    }
);
```

### Summary
When the size of the FilePond is relative to the viewport (i.e. 20vw) meaning that it will change width on window resize, the `.filepond--root` element doesn't seem to update it's height.  The `.filepond--item` does however resize correctly (but it means that the border sticks out from the edge, or cuts off the image depending on which way the browser is resized as per images).
Refreshing the page sets it back to normal.
<img width="132" alt="Screenshot 2019-05-20 at 10 39 33" src="https://user-images.githubusercontent.com/26857336/58014502-e852f000-7af0-11e9-82c3-75c5741a19d3.png">
<img width="122" alt="Screenshot 2019-05-20 at 10 39 42" src="https://user-images.githubusercontent.com/26857336/58014504-e8eb8680-7af0-11e9-8807-01221680747c.png">
<img width="125" alt="Screenshot 2019-05-20 at 11 12 37" src="https://user-images.githubusercontent.com/26857336/58014505-e8eb8680-7af0-11e9-9ec0-f062bb74a67c.png">

### Expected behaviour
`.filepond--root` should resize too?

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Device       | MacBook Pro
| Browser      | Safari 12.1

**Comment by rikschennink** [comment]
It should update but I believe it currently doesn't

**Comment by rikschennink** [comment]
Should be fixed in latest release
https://github.com/pqina/filepond/releases/tag/4.4.8

**Comment by gaiustemple** [comment]
Yep, spot on works great
