### ISSUE TITLE
FilePond and Wordpress Plugin

### ISSUE THREAD

**Issue by dskurth** [pqina/filepond#321]
I am attempting to blend the file point within a custom WordPress plugin that I have written.  It is using the CBM2..another Javascript based  workset.   However, the result is just a normal <input type="File"> box.  And I have yet to figure out how to do register the plugin without it causing problems with the CBM2 work set.

Do you have any working examples of how I can blend the two?

**Comment by rikschennink** [comment]
Hi, I don't have a lot of experience with both WordPress and CBM2 so I'm afraid I can't help. Maybe CMB2 has a support forum? I'll close this for now.
