### ISSUE TITLE
[Feature Request] Add option to disable upload button

### ISSUE THREAD

**Issue by HapLifeMan** [pqina/filepond#323]
Hello,

I was wondering if you can add an option like `allowXXX` to hide/disable the upload button?
I'm triggering this programmatically and I don't want to allow the user to do it with the UI :)

No idea how to name it because `allowUpload` would mean that if set to `false`, the upload can't be possible, even programmatically, right?

Thanks! :)

**Comment by rikschennink** [comment]
I think this is a duplicate issue, I'll open it if I'm wrong, but it seems the same.
https://github.com/pqina/filepond/issues/238
