### ISSUE TITLE
filepond to accept geojson filetype

### ISSUE THREAD

**Issue by GeethaSantoshiAddala** [pqina/filepond#329]
Hello fellow developer!

🧠 If you have a question, please ask it on StackOverflow -> https://stackoverflow.com/questions/ask?tags=filepond

🐜 If you think you have found a bug, please use the template below to report it.

**The more details you provide, the more inclined others are to help you out and the faster the issue is resolved.**

If you're using one of the FilePond adapters for React, Vue, Angular or jQuery and think the issue might be related to the framework, submit the issue in the specific adapter repository.

Please format code snippets using triple backticks and set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

```js
const foo = 'bar';
```

### Summary

...

### How to reproduce

...

### Expected behaviour

...

### Additional information

...

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
Closed -> Missing issue details

> The more details you provide, the more inclined others are to help you out and the faster the issue is resolved.
