### ISSUE TITLE
Is 'server' prop mandatory for using 'addFile()' ? 

### ISSUE THREAD

**Issue by gterras** [pqina/filepond#330]
Hi and thanks for your nice plugin, 

I'm trying to programmatically add a file to a FilePond instance in the simple way possible : I don't want to use the `server` prop at all because I don't want any logic to live inside this component. 

With `instantUpload:false`, using `pond.addFile('http://example.org/myfile.jpg')` will not trigger any request until `server` is defined. If anything is declared in `server` the image URL will be prefixed with it, which I do not want at all. Is it intended behavior ? 

More generally if feel like it is very hard to use the plugin without defining `server` first, am I missing something ? 

Thank you

**Comment by rikschennink** [comment]
If you don't want to use the `server` property then don't set it. 

Use `getFiles` to request all current files and manually upload them. You'd have to add your own upload logic and progress indicator though.

**Comment by rikschennink** [comment]
closed due to inactivity (no reply in 10 days)
