### ISSUE TITLE
Dragging and dropping directory of 100 files skips a file

### ISSUE THREAD

**Issue by mehri-amin** [pqina/filepond#331]
### Summary
When I drag and drop a folder containing 100 files it only takes 99 of the files, the one it misses seems arbitrary? When I select all the individual files and drag and drop it works perfectly fine so it seems unique to directories. I've checked if there are any hidden files, there's only one .DS_Store and that is being ignored correctly. A directory with less files, say 50, works fine, it seems to only happen with 100 files.

### How to reproduce

Drag and drop a folder containing 100 files [file types: png, pdf, jpg]. I can't share the files that I'm uploading but they are 100 files of pdfs and images. 

### Expected behaviour

Upload all 100 files.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS 
| Device       | Macbook Pro 2017
| Browser      | Google Chrome
| react-filepond | 7.0.1
|filepond | 4.4.7

**Comment by rikschennink** [comment]
Closed till test case supplied

**Comment by eemed** [comment]
I've set `maxParallelUploads` to 100 and everytime I drag and drop a folder with over 100 files it takes just the first 100.

**Comment by eemed** [comment]
I believe the limit is 100 files. If I drag and drop a directory containing over 100 files, only the first 100 are uploaded. In your case it counts the `.DS_Store` as one of the 100 files thus ignoring the last image file.

**Comment by mehri-amin** [comment]
@rikschennink I've provided the method to reproduce the error, I can't provide files for you. You can create them yourself.

**Comment by mehri-amin** [comment]
> @mehri-amin  In your case it counts the `.DS_Store` as one of the 100 files thus ignoring the last image file. 

I have it set so .DS_Store file is ignored. So are you saying that even though it ignores the .DS_Store file, it does it only after 100 files are selected for upload thus causing only 99 files being uploaded?

**Comment by mehri-amin** [comment]
@rikschennink unsure what you mean by test case needed, i've provided the method to reproduce the issue, i cannot provide any files to you sorry.

**Comment by rikschennink** [comment]
@mehri-amin I tried to reproduce it in June and wasn't able to. From the issue it's unclear how you've configured FilePond. The more work needed to reproduce the issue the longer it takes to resolve it. In this case setting up a test version without knowing your FilePond configuration parameters and populating a folder with the described selection of files is time consuming.

A test case on https://codesandbox.io would be appreciated.

**Comment by eemed** [comment]
I made an example for you. [Codepen](https://codepen.io/eemed/pen/ExYLVjQ)
[files.zip](https://github.com/pqina/filepond/files/3599553/files.zip)

**Comment by rikschennink** [comment]
Resolved in `4.7.1`
