### ISSUE TITLE
addFile with silent error

### ISSUE THREAD

**Issue by alexandernst** [pqina/filepond#333]
It would be nice to be possible to call `addFile` with an option that will silently discard the file if it doesn't meet the requirements imposed to be loaded plugins (type, image size, etc...)

An acceptable alternative would be to be able to do something like

```
addFile(foo).then().error(f => f.remove())
```

The use case for this:

I have several filepond areas/zones/widgets, and each of those widgets accept files with specific names. I want to create a drop zone/area/widget that will let users to drop all files and let the code distribute/assign each file to it's designated filepond instance. I plan to do so by iterating over all filepond instances and calling `addFiles` on each of them with the array of files that the user dropped in the "general" widget and passing that `silentError` option that I'm requesting.

**Comment by rikschennink** [comment]
The `Promise` returned by `addFile` is currently not rejected, you'd have to use `onaddfile`
https://codesandbox.io/embed/filepond-addfile-catch-imlhn

**Comment by alexandernst** [comment]
But that way I'll hide all errors. I want to hide the errors only when I'm programatically adding files.

**Comment by alexandernst** [comment]
@rikschennink I'm willing to provide a patch either for the promise of `addFile` being rejected so I can handle it, or an option for `addFile` to silently ignore errors, whichever best fits your vision.

**Comment by rikschennink** [comment]
@alexandernst Appreciate the offer, I've taken a quick look and have added the Promise rejection, should be online later today.

**Comment by rikschennink** [comment]
Just published `4.4.10` should fix the issue.

**Comment by alexandernst** [comment]
This is perfect! Thank you! I'm closing this as now I'm able to achieve what I wanted.
