### ISSUE TITLE
I can't upload specific type such as .stl

### ISSUE THREAD

**Issue by AliYmn** [pqina/filepond#334]
i how to upload specific type such as .stl, my code doesn't work why? What about acceptedFileTypes? ( note, just i can't upload it on mac )

    <FilePond
    acceptedFileTypes={['model/*']}
    labelIdle={gettext('Üst çene stl tarama dosyasını alana sürükleyin ya da tıklayarak seçim yapınız ')}
    server={
        {
            url: '/api/v1/case/impression/upload/' + t.props.match.params.id + '/?name=upperjawstl',
            process: {
                method: "POST",
                headers: {
                    Authorization: `Token ${localStorage.getItem('token')}`,
                    'X-CSRFToken': $.cookie('csrftoken'),
                },
            }
        }
    } />
    }

**Comment by rikschennink** [comment]
have you registered the file validate type plugin?

**Comment by rikschennink** [comment]
Closed because no response for 4 days.
