### ISSUE TITLE
Support For Cordova using FilePond 

### ISSUE THREAD

**Issue by siddmegadeth** [pqina/filepond#337]
Hello fellow developer!

🧠 If you have a question, please ask it on StackOverflow -> https://stackoverflow.com/questions/ask?tags=filepond

🐜 If you think you have found a bug, please use the template below to report it.

**The more details you provide, the more inclined others are to help you out and the faster the issue is resolved.**

If you're using one of the FilePond adapters for React, Vue, Angular or jQuery and think the issue might be related to the framework, submit the issue in the specific adapter repository.

Please format code snippets using triple backticks and set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

```js
const foo = 'bar';
```

### Summary
Support For Cordova using FilePond as Cordova File-Tranfer is depreciated . As of now we cannot use FileTranfer Plugins from Cordova. Cordova has suggested to use JS XHR based request for File Tranfer . However i do not get my files using Input bit is using a Media Picker which return files as an Object. How can i use filepond in this scenario
...

### How to reproduce

...

### Expected behaviour

...

### Additional information

...

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
Closed because did not fill in issue template.
