### ISSUE TITLE
Let revert / remove cancelable.

### ISSUE THREAD

**Issue by joonhocho** [pqina/filepond#338]
I want to confirm with users before remove or revert like the following code.
It seems currently cancel is not an option.

```js

    remove: (source, load, error) => {
      if (
        confirm(t('Are you sure you want to permanently delete this file?'))
      ) {
        deleteFromServer(source).then(load, error);
      } else {
        error('canceled');
      }
    },

**Comment by rikschennink** [comment]
Use `beforeRemoveFile` https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#Hooks

**Comment by joonhocho** [comment]
@rikschennink Just letting you know this only works for `remove` not `revert`.

**Comment by rikschennink** [comment]
With `revert` the file was just uploaded and only the upload is reverted, the file is still in the list and on the users system, I think this makes the action non-destructive.
