### ISSUE TITLE
File pond behave differently on chrome and safari.

### ISSUE THREAD

**Issue by aqueeel** [pqina/filepond#339]
### Summary
File pond behave differently on chrome and safari. I think the issue is with height of the root element.
![image](https://user-images.githubusercontent.com/8208572/60704151-3dbc5280-9f21-11e9-9b10-26faa31f293b.png)

| Environment  | Version
|------------- | -----------
| OS           | MacOS / ...
| Device       | MacBook Pro late 2016/ ...
| Browser      | Safari 12.0.3

**Comment by aqueeel** [comment]
Commenting a line of code in `filepond.js` file solved this issue for me.
![image](https://user-images.githubusercontent.com/8208572/60704455-22057c00-9f22-11e9-9437-a78e3178e7d2.png)

**Comment by rikschennink** [comment]
Can you reproduce this in an isolated test case?

**Comment by rikschennink** [comment]
Closed because no response for 4 days.

**Comment by alexandernst** [comment]
I have this same problem, but I can't isolate the bug. What I do know for sure is that it happens when I put the filepond widget inside a tab (bootstra's tab widget).

**Comment by rikschennink** [comment]
Sounds like it might be a style collision.
