### ISSUE TITLE
Error not triggering on incorrect file type uploaded through drag and drop

### ISSUE THREAD

**Issue by cmatzenbach** [pqina/filepond#34]
Everything works perfectly fine when uploading via the "Browse" link provided by the plugin, but when I drag and drop a file that is an invalid type, nothing happens.  Filepond does not produce the same red error component as it does when uploading via the link.  However, drag and drop does work perfectly fine for uploading - the issue lies only with producing the error component.  Is this a known bug, or could it possibly be a configuration issue?  I'd be happy to dive in deeper if you need more information regarding the error/anything else I can do to help.

**Comment by rikschennink** [comment]
Hi! I’m currently on a short trip, will look into this later this week.

**Comment by rikschennink** [comment]
@cmatzenbach The drop is automatically prevented when the file is not allowed (fails validation). I'm planning to make this behaviour optional and make the default to add all files and show error states.

**Comment by rikschennink** [comment]
Just added the `dropValidation` property. Validation is now disabled by default.

Enable it to validate files before they are dropped.
```js
pond.dropValidation = true;
```
