### ISSUE TITLE
Uncaught TypeError: state.request.abort is not a function

### ISSUE THREAD

**Issue by joonhocho** [pqina/filepond#340]
### Summary

Sometimes during destroy(), it generates an error

### How to reproduce

 - Drag and drop remote url file, but it fails to get the file (maybe server error).
 - Filepond will show "Error during load" message on the file
 - destroy() will make error now.

### Expected behaviour

no error

### Additional information

```
helpers.js:86 Uncaught TypeError: state.request.abort is not a function
    at Object.abort (filepond.js:2835)
    at Object.abortLoad (filepond.js:3851)
    at filepond.js:4325
    at Array.forEach (<anonymous>)
    at Object.ABORT_ALL (filepond.js:4323)
    at Object.dispatch (filepond.js:80)
    at Object.destroy (filepond.js:9320)
    at FilePond.componentWillUnmount (react-filepond.js:102)
    at callComponentWillUnmountWithTimer (react-dom.development.js:17169)
```

```js
  var createFileLoader = function createFileLoader(fetchFn) {
    var state = {
      source: null,
      complete: false,
      progress: 0,
      size: null,
      timestamp: null,
      duration: 0,
      request: null
    };

    var getProgress = function getProgress() {
      return state.progress;
    };
    var abort = function abort() {
      if (!state.request) {
        return;
      }
      state.request.abort();
    };
```

It's this line: https://github.com/pqina/filepond/blob/895e1e8681ccacc7fffa3b96770d4b52552cbe74/src/js/app/utils/createFileLoader.js#L24

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Device       | Mac
| Browser      | Chrome

**Comment by joonhocho** [comment]
Figured out the step to reproduce.

**Comment by roooby** [comment]
@joonhocho I am facing this similar issue

` Uncaught TypeError: this.state.lastRequest.abort is not a function `

```
index(request) {
    if (this.state.lastRequest) {
      this.state.lastRequest.abort();
    }
    this.setState({lastRequest: request.request});
  }
```

Do you have any idea?

**Comment by joonhocho** [comment]
@roooby where you get that code? I can't find code searching 'lastRequest'

**Comment by rikschennink** [comment]
@joonhocho Published.

@roooby This is react logic (see `setState`) I don't think it's related to this FilePond issue.
