### ISSUE TITLE
Plugins: Size validation triggering before image resize

### ISSUE THREAD

**Issue by AustP** [pqina/filepond#342]
### Summary

I'm using both the Image Resize and File Validate Size plugins. I want to resize images before validating size so I loaded the Image Resize plugin before the File Validate Size plugin. Unfortunately the size validation takes place first which prevents the image resizing.

### How to reproduce

```
FilePond.registerPlugin(
  FilePondPluginImageResize,
  FilePondPluginFileValidateSize
);

FilePond.setOptions({
  imageResizeTargetHeight: 2160,
  imageResizeTargetWidth: 3840,
  imageResizeUpscale: false,
  maxFileSize: '5MB'
});

FilePond.create(document.getElementById('filepond'));
```

[Demo here](https://jsfiddle.net/s683vjm4/)

### Expected behaviour

The image should be resized before the size validation takes places. In this case, the resizing would reduce the size below the threshold and the image would be allowed.

**Comment by rikschennink** [comment]
As image resizing is a big strain on the CPU images are only resized right before upload.

If you're setting a target width and height, the size of the final output file will average around a certain amount of kilobytes/megabytes, no need to validate the max file size.

**Comment by AustP** [comment]
The reason I want to validate file size is because I am also allowing PDFs to be uploaded.

**Comment by rikschennink** [comment]
Hm then maybe it would be more logical to be able to filter the files that require size validation. I’ll see if I can add this to the plugin.

**Comment by rikschennink** [comment]
Just published a new version of the file size validation plugin. It now exposes the `fileValidateSizeFilter` hook. You can use it to filter the files that should be validated.

See code example in release:
https://github.com/pqina/filepond-plugin-file-validate-size/releases/tag/2.2.0

**Comment by AustP** [comment]
Awesome thanks rikschennink! It looks perfect.
