### ISSUE TITLE
filepond UI is broken with Bootstrap 3.3.7 enabled

### ISSUE THREAD

**Issue by WhiteAls** [pqina/filepond#343]
### Summary

My app is using Bootstap 3.3.7. Everything works fine, but filepond UI do not work properly when I load bootstrap css. It looks totally fine without bootstrap css.

### How to reproduce

https://codepen.io/anon/pen/KjrZdN

### Expected behaviour

Working filepond UI regardless of css framework.

### Additional information

ofc I'm using more than just bootstrap. I can replicate a whole page of my app at codepen, but as soon as i'm removing exactly bootstrap css everything start behaving as it should.

**Comment by rikschennink** [comment]
Remove the `.form-control` class from the `input` element. And set the `.filepond--root` font-size to `16px`

```css
.filepond--root { font-size: 16px; }
```
