### ISSUE TITLE
Request to move plugin to FilePond Instance instead of FilePond Object

### ISSUE THREAD

**Issue by sknair** [pqina/filepond#345]
### Summary
Possibility of moving the option to register a plugin to the FilePond Instance instead of the FilePond Object.  This request is due to have multiple instances of FilePond on a page which require different plugins.
### How to reproduce
Plugins can only be registered through FilePond Object
### Expected behaviour
Able to register plugin through FilePond Instance

**Comment by rikschennink** [comment]
You can enable/disable plugins per instance using their respective toggle properties. For example `allowImagePreview`.

**Comment by sknair** [comment]
Thanks.  This is exactly what I saw looking for.
