### ISSUE TITLE
Error during upload, but its not an error

### ISSUE THREAD

**Issue by tarikrsma** [pqina/filepond#346]
Im trying to do a simple upload file to a server, ok, he does that correctly. But, when I send a document with size 1MB or more it returns an error but the file appears on the server anyway. It succeed. But he says "Error during upload" (on red) on the screen How I fix that? (sorry for the bad english)

I've tried to put "onload: (response) => response.key" But not happen.

This is my upload.js It works, but if the file has 1MB or more will show an error and its bad because the doc was send correctly on the server.

FilePond.setOptions({
    server: {
      url: 'https://server.example.com',
        process: {
            url: '/upload-file',
            method: 'POST',
            withCredentials: false,
            headers: {},
            timeout: 7000,
            onload: null,
            onerror: null,
            ondata: fd => {
              fd.append('first_id', '08711913000128');
              fd.append('second_id', '222222223');
              fd.append('third_id', 4);
              return fd
            }
        },
        revert: null,
        restore: null,
        load: null,
        fetch: null
    }
});
Shows "Error during upload" But should be an "Upload complete" Because its upload to the server with no problem, like its complete.

**Comment by rikschennink** [comment]
It sounds like the server is not responding with a 200 http status, best to inspect the request in the network tab of your dev tools

**Comment by tarikrsma** [comment]
Its wierd, he just do not send any Status.
other are 200 ok but more than 1MB dont show any Status, its blank

**Comment by rikschennink** [comment]
sounds like a server error, maybe inspect the server logs?

Will close for now as it's not related to FilePond

**Comment by tarikrsma** [comment]
Yes, it was a problem with the Django/server
its was a timeout problem.
IT WORKS!

Thanks for all the support :)

**Comment by kinsokafor** [comment]
Sorry for replying to this closed ticket. Unlike @rikschennink said, it has everything to do with your FilePond settings. If your upload takes longer than the specified timeout on FilePond server configuration, you will encounter "Error during upload". You can increase the timeout:

server: {
url: 'https://server.example.com/',
process: {
url: '/upload-file',
method: 'POST',
withCredentials: false,
headers: {},
timeout: 15000,
onload: null,
onerror: null,
ondata: fd => {
fd.append('first_id', '08711913000128');
fd.append('second_id', '222222223');
fd.append('third_id', 4);
return fd
}

alternatively, you can set the timeout to null.
