### ISSUE TITLE
Sorting items for multiple files

### ISSUE THREAD

**Issue by ahmedfaical** [pqina/filepond#347]
Hello,
First thank you for this awesome plugin.
I'm using the vue js version and i would like to be able to sort items with multiple upload. How to do that?

**Comment by rikschennink** [comment]
Use the `sort` method or the `itemInsertLocation` property.
https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#sorting-files

**Comment by ahmedfaical** [comment]
Thank you for your answer, i mean drag and drop sorting inside filepond container.

**Comment by rikschennink** [comment]
That's on the roadmap for a future release.

**Comment by rikschennink** [comment]
https://github.com/pqina/filepond/issues/146

**Comment by ahmedfaical** [comment]
Thank you so much. I really appreciate your work and your quick replies. 
Juste one last thing please, can you give me approximatively on which version or date we will find this feature?

**Comment by rikschennink** [comment]
@ahmedfaical version 4.x
