### ISSUE TITLE
Memory leak in main library due to event listeners

### ISSUE THREAD

**Issue by LazaroOnline** [pqina/filepond#353]
### Summary

Memory is not being released properly after the "destroy()" method of filePond.

### How to reproduce

https://codesandbox.io/embed/frosty-sea-1u5sm
https://1u5sm.csb.app/

Create and destroy instances of FilePond, every time it is destroyed with the method "destroy()" it is not releasing the memory properly. You can profile it with Chrome's devTools using the "Memory" tab, using the "Allocation instrumentation on timeline" option recording while creating/destroying instances, in a playground if you see the memory allocation charts shows the bars still in blue after destroying the filePond instance indicating that the memory is not being garbage collected.

All event listeners should be removed during the execution of the destroy method.

Tested using plain vanilla flavour js with FilePond.js and no plugins (no vue/react/angular...).
There might be more leaks in the plugins and adapters.

### Expected behaviour
In above's code sandbox, after clicking in "Toggle Filepond uploader" multiple times, the filepond objects should not have remaining references (especially the event listeners as a common cause), so when the garbage collection occurs, the blue bars become white in Chrome's devTools indicating proper memory disposal.

### Additional information
| Environment  | Version
|------------- | -----------
| OS           | Windows 10, but the same will happen in all platforms: MacOS  / iOS / Linux / ...
| Device       | Microsoft Laptop, but this bug is device independent.
| Browser      | Chrome 75.0.3770.142 (Official Build) (64-bit)

To solve this please accept the following pull request:
https://github.com/pqina/filepond/pull/352
That should fix some memory leaks.

Thank you.

**Comment by rikschennink** [comment]
Thanks!

I've inspected the pull request. You can't destroy the painter process as you could have multiple active FilePond instances bound to the same painter (also the paint loop is shared with [Doka](https://pqina.nl/doka/) to group read/writes)

**Comment by rikschennink** [comment]
I've applied the fixes to the dropLabel.js and app index.js and that seems to solve the issue, see chart below, this is 2 minutes of creating and destroying FilePond each 2 seconds.

![Screenshot 2019-08-01 at 08 45 49](https://user-images.githubusercontent.com/1132575/62271635-6c9ee900-b439-11e9-9869-f1d425c10eea.png)


I will decline the pull request because of the painter modifications, those are breaking.

**Comment by LazaroOnline** [comment]
Great job! plus you also took care of dropLabel, awesome! the painter object is fine both ways for me, and the memory is not leaked anymore, so problem solved.
Thank you for your fast response and release!

By the way, what memor profiler are you using? I don't recognize it in the screenshot above.

**Comment by rikschennink** [comment]
@LazaroOnline Fantastic! This is the Chrome dev tools performance tab.
