### ISSUE TITLE
Open file uploaded onclick

### ISSUE THREAD

**Issue by provalinf** [pqina/filepond#357]
Hi guys,
I'm implementing this great plugin on my site (framework codeigniter), everything works fine, but I'm missing something.

I try to add the opening of the uploaded file when I click on it, except I can't get that click to trigger an event. I read that the callback **server.process.onactivatefile** or server.process.onaddfile should allow this action, but I don't get any message via console.log when I click on it.
#256 

Do you have more details to provide me?

Thank you very much.

**Comment by rikschennink** [comment]
The callbacks should be added to the filepond instance or options object, not the server.

```js
FilePond.create(element, {
   onaddfile: () => {},
   onactivatefile: () => {}
});
```

**Comment by provalinf** [comment]
Oh yes, thank you for that clarification, I tried to put it in the filepond instance, but I didn't have to do it right.
Everything is working now!

**Comment by souhaiebtar** [comment]
@provalinf would you please share how you integrated with codeigniter ??

**Comment by provalinf** [comment]
> @provalinf would you please share how you integrated with codeigniter ??

Gift

	header_filepond += '<input type="file" class="filepond" name="filepond" multiple data-max-file-size="20MB"  >';

	Swal.fire({
		title: data['proc']['nom_procedure'],
		html: header_filepond,
		onOpen: function () {
			FilePond.registerPlugin(FilePondPluginFileRename);
			FilePond.setOptions({
				fileRenameFunction: function (file) {
					return file.basename.sansAccent() + "_" + Date.now() + file.extension;
				},
				allowRevert: !consult,
				allowProcess: !consult,
				server: {
					url: '<?=base_url('consultation')?>',
					process: {
						url: '/FPprocess/' + id_procedure_enr,
						instantUpload: true,
						onload: function (response) {
							return response.key;
						},
						ondata: function (formData) {
							return formData;
						},
					},
					revert: null,
					/*load: function (source, load, error, progress, abort, headers) {
						var myRequest = new Request(source);
						fetch(myRequest).then(function (response) {
							console.log(response);
							response.blob().then(function (myBlob) {
								load(myBlob)
							});
						});
					},*/
					load: function (uniqueFileId, load, error) {
						fetch(uniqueFileId)
							.then(function (res) {
								return res.blob();
							})
							.then(load)
							.catch(error)
					},
					fetch: null
				}
			});
			var pond = FilePond.create(
				document.querySelector("input[name='filepond']"),
				{
					labelIdle: "Glisser déplacer un fichier ou <span class=\"filepond--label-action\"> Parcourir </span>",
					onactivatefile: function (file) {
						var win = window.open("<?=base_url('resultats')?>/" + file.file.name, '_blank');
						win.focus();
					}, onremovefile: function (error, file) {
						$.ajax({
							url: "<?=base_url('consultation/FPDelete') ?>/" + id_procedure_enr,
							type: 'post',
							dataType: 'json',
							complete: function (resultat, statut) {
								return statut != 'success';
							},
							contentType: "application/json",
							data: generate_json({'filename': file.file.name})
						});
					},
					files: files_loaded
				}
			);
		},
		showConfirmButton: false
	});
`

**Comment by souhaiebtar** [comment]
@provalinf thanks for sharing :+1:
