### ISSUE TITLE
Strange behaviour of filepond js

### ISSUE THREAD

**Issue by ThatDeveloper** [pqina/filepond#359]
### Summary

Strange behaviour of filepond when creating a new instance.
Following PageA is working, PageB is not working.

Both pages have the same filepond related code, styles, js, etc.

Base setup:
```
<input type="file" class="filepond" id="file" />
```
```js
FilePond.registerPlugin(
            FilePondPluginImageExifOrientation,
            FilePondPluginFileValidateSize
        );

        FilePond.setOptions({
            server: {
                process: '/api/v1/filepond/process',
                revert: '/api/v1/filepond/revert',
                restore: '/api/v1/filepond/restore/',
                load: '/api/v1/filepond/load/',
                fetch: '/api/v1/filepond/fetch/'
            }
        });

        window.addEventListener("load", function () {
            FilePond.create(document.getElementById("file"));
        });
```

On PageA the result main wrapper looks like this:
```
<div class="filepond--root filepond--hopper" id="file" data-style-button-remove-item-position="left" data-style-button-process-item-position="right" data-style-load-indicator-position="right" data-style-progress-indicator-position="right" style="height:76px;">
```

On PageB the result main wrapper looks like this:
```
<div class="filepond--root filepond--hopper" id="file" data-style-button-remove-item-position="left" data-style-button-process-item-position="right" data-style-load-indicator-position="right" data-style-progress-indicator-position="right">
```

As you can see, PageB does not have a height set by filepond.
Same goes for transform of "filepond--panel-center filepond--panel-root".

There is no exception / error in console. 

PageA:
![image](https://user-images.githubusercontent.com/12497431/63692388-dc727a80-c811-11e9-875d-43d918c9b1b1.png)

PageB (no color => no height, drag and drop does not work):
![image](https://user-images.githubusercontent.com/12497431/63692444-f57b2b80-c811-11e9-8985-fda8b7ee1276.png)

PageA works with the Drag Events.

PageB fires Drag Events every Xms while hovering (no movement) over it switching between copy and move (changing dom data-hopper-state attribute each time)

### How to reproduce

I can not tell how, i tried to remove everything but it is a very strange behaviour!

### Additional information

JQuery but no jquery wrapper for filepond, tested both.

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Device       | Laptop (Surface Book 2)
| Browser      | Chrome 76

**Comment by rikschennink** [comment]
Do both pages have a DOCTYPE?

**Comment by ThatDeveloper** [comment]
You are a god. How? How did you know this?
So PageA and PageB did not have DOCTYPE set. But after adding, both did work.

Can you explain me more? Why is this? Reference to code? I am soo interested about this. I tried this for soo long.

Thank you! @rikschennink

**Comment by rikschennink** [comment]
@ThatDeveloper Haha, thanks ;)

A missing doctype will trigger the browser to switch to Quirksmode, and indeed that's as bad as it sounds, it results in all kinds of weird layout behaviour. More [about quirksmode on quirskmode.org](https://www.quirksmode.org/css/quirksmode.html)

**Comment by ThatDeveloper** [comment]
Thank you very much! Closing this.
