### ISSUE TITLE
File upload status design and progressbar

### ISSUE THREAD

**Issue by momin-ctg** [pqina/filepond#36]
I am trying to keep file uploading status on right and design like this screenshot . Can i do this with __filepond__ ? 

Here is the Screenshot
![upload](https://i.imgur.com/swrTzIx.png)

Please ! Thanks in advance

**Comment by rikschennink** [comment]
I don’t think that would really work. FilePond is quite rigid from a design perspective. I think the only way would be to set display to *none* on all the filepond items and then use the event API to rebuild the file list on the right.

I’ll add different layout options to my todo list.

**Comment by DamSenViet** [comment]
You'd probably be better off writing your own API for this. I recommend using jquery ajax and from the xhr factory, modify it by adding an onprogress event listener so you can monitor the progress. Use css and html to create a loading bar.
