### ISSUE TITLE
Drag and drop from Firefox downloads menu gives "Error during load"

### ISSUE THREAD

**Issue by adriaanvanrossum** [pqina/filepond#360]
### Summary

When you drag and drop from the Firefox download menu you get an error: "Error during load".

### How to reproduce

<img src="https://user-images.githubusercontent.com/1079135/63693194-b4841680-c813-11e9-8952-03d7f6cf2ea2.gif" width="100%">

### Expected behaviour

No error and same behavior when drag and drop for finder.

### Additional information

https://whatismybrowser.com/w/8YY9Y4K

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Device       | MacBook Pro
| Browser      | Firefox

**Comment by rikschennink** [comment]
Should be fixed in `4.5.1`
