### ISSUE TITLE
serverid in FilePond:removefile

### ISSUE THREAD

**Issue by ThatDeveloper** [pqina/filepond#361]
Dear @rikschennink,

FilePond:removefile does not contain serverid => i.e. it is always null.
I urgently need to know the serverid of the removed file.

```js
var x = document.getElementById('fpo-file');

x.addEventListener('FilePond:removefile', e => {
    console.log('File r', e.detail);
});
```

Using newest version of filepond on Windows, Chrome 76.

I hope you are able to help me out here as I am kind in a very pressured time environment. :/

Best,
Manuel

**Comment by rikschennink** [comment]
You can find the server id here:
```js
document.body.addEventListener('FilePond:removefile', e => {
  console.log('File r', e.detail.file.serverId);
});
```

**Comment by ThatDeveloper** [comment]
No, as shown above, this does not work. is always null.
Tested it with window, document.body and as shown above with the element itself.

**Comment by rikschennink** [comment]
Then you're probably not returning it in your server.process method?
https://codesandbox.io/s/vanilla-filepond-2oltb

**Comment by ThatDeveloper** [comment]
I am returning in the process call and I see & get it fom FilePond:processfile.
When I am clicking the undo cross in UI the call gets to the server, reverts and in JS I get the FilePond:removefile callback. In this callback the serverid is null.

Per your docs I have to return an empty resonse: https://pqina.nl/filepond/docs/patterns/api/server/#revert

**Comment by ThatDeveloper** [comment]
@rikschennink Further information, I have deleted all sensitive data:

```js
        FilePond.registerPlugin(
            FilePondPluginImagePreview,
            FilePondPluginImageExifOrientation,
            FilePondPluginFileValidateSize
        );

        FilePond.setOptions({
            server: {
                process: '/api/v1/filepond/process',
                revert: '/api/v1/filepond/revert',
                restore: '/api/v1/filepond/restore/',
                load: '/api/v1/filepond/load/',
                fetch: '/api/v1/filepond/fetch/'
            }
        });
```

```c#


        [HttpDelete("revert")]
        public async Task<IActionResult> Revert()
        {
            return Ok();
        }

        [HttpPost("process")]
        public async Task<IActionResult> Process(IFormFile file)
        {
            return Ok("test");
        }
```

**Comment by ThatDeveloper** [comment]
@rikschennink Did further testing. 
When I only have:
```
FilePond.setOptions({
            server: {
                process: '/api/v1/filepond/process'
            }
        });
```

... the FilePond:removefile file element contains serverid correct, but then it does not call my revert method on the server.
If I add the 
```
FilePond.setOptions({
            server: {
                process: '/api/v1/filepond/process',
                revert: '/api/v1/filepond/revert'
            }
        });
```

... the serverid is null in the element of FilePond:removefile.

**Comment by rikschennink** [comment]
Hm, weird, will take a look later this week.

**Comment by ThatDeveloper** [comment]
@rikschennink But I am collecting the serverid's I get from processing (uploading) the files so I can provide them on form submit. If a user removes the file, I have to remove the file too from the form, right?

**Comment by rikschennink** [comment]
If the upload has been reverted the file is no longer on the server so it doesn't have to be in the list when the form is submitted (FilePond also generates hidden input fields with the file server ids).

**Comment by ThatDeveloper** [comment]
@rikschennink Thank you! It was exactly this. I also figured this out. Gosh I feel soo stupid. Anyway, thank you very much.

But just to give you  a feedback on this:
If the revert http call is denied / fails / Bad Request / whatever, the serverid field is still set. That was what confused me. Maybe it still would be nice to have the serverid on the remove event. :)

**Comment by fbruffaert** [comment]
A follow up almost three years later :stuck_out_tongue_winking_eye: 
I also encountered the same "issue" after migrating from a very old version (1.8.8), which I was using with the vue adapter (2.1.6).
In the previous versions, the serverId was provided in the remove event.
It was useful to me, since I am maintaining a store with enriched infos on my media. So I need a way to know which media has successfully been removed, to keep my store up to date, which does not seem possible with this "new" behaviour.

**Comment by rikschennink** [comment]
@fbruffaert I'll take this into account when designing a new api for v5

**Comment by blazorin** [comment]
You can use the revert property and run your uniqueId removal logic, remember to call load(), like this example:

```ts
        revert: (serverId, load, error) => {
            fileUrls.current = fileUrls.current.filter((url) => url !== serverId);
            props.fileUploaded(fileUrls.current);

            setUploadedBefore(fileUrls.current.length > 0);
            load();
        }
```

Hope it helps.
