### ISSUE TITLE
"Remove" tool on image preview: Inconsistent positioning and ability to hide/disable

### ISSUE THREAD

**Issue by Eric24** [pqina/filepond#366]
The position of the "remove" tool is inconsistent between "initial" and newly-uploaded files. See this partial screenshot:
![image](https://user-images.githubusercontent.com/685316/63861296-430daa80-c970-11e9-8dc2-b4f0811fd394.png)

The left image is newly-uploaded, with the "remove" tool on the right, while the right image is an "initial" file with the "remove" tool on the left.

I suggest that the remove tool always be on the right, for UI consistency.

Also, in relation to the remove tool, I would like to see it be possible to hide or disable it for "initial" files (i.e. so the user can not remove an initial file, but is free to remove one that they uploaded). I've not found a clean way to do this via the component options.

**Comment by rikschennink** [comment]
The left X is for removing items from the list, the right one is for undo-ing a server upload (in which case it's a counter clockwise arrow) or removing an item from the server. It turns into a cross when `instantUpload` is true, as removal from the server will then also remove the item from the list. 

I'll see if I can streamline this further in a future release.

**Comment by Eric24** [comment]
Yes, I understand the difference, but I think this is a case where it doesn't matter to the user, so a single tool that removes either existing items from the list or undoing an upload (even though the back-end functionality between them maybe different, the end result from the user's perspective is the same).

That is also why I'm wanting a way to disable the "delete of initial files". I can see (and have this use-case myself) of wanting to show some existing files but not allow them to be deleted.

**Comment by dee0byrne** [comment]
We're also experiencing issues with the consistency of the positioning of the remove icon. 

Through user testing, we've found that our users are getting confused as to why the location of the remove icon keeps switching from right to left - they do not understand the difference between the two icons as to them they are functionally the same.

Our preference would be to always keep the icons on the left. Our attempts to implement this using filepond style configuration (such as styleButtonProcessItemPosition) are causing issues with overlapping labels.

Could the consistent alignment of these icons be looked into?

**Comment by rikschennink** [comment]
@Eric24 @dee0byrne will see if I have some time to take a look at this next week.

**Comment by rikschennink** [comment]
Added in https://github.com/pqina/filepond/releases/tag/4.12.0

Set `styleButtonRemoveItemAlign` to `true` to align all remove buttons to one side, let me know if this solves the issue.

**Comment by dee0byrne** [comment]
@rikschennink Thanks for your help - the remove buttons are aligned as expected now.

**Comment by jacklimwenjie** [comment]
> By the way, we tried setting the config property `styleButtonRemoveItemPosition='right'`. This does move the "remove" tool to the right of the thumbnail, but it also apparently moves the header text along with it (i.e. with the "remove" tool on the right, there is no header text at all).

This is still an issue though. 

Example to reproduce the issue: https://codesandbox.io/s/react-filepond-live-demo-forked-076gt?file=/src/index.js
