### ISSUE TITLE
Roadmap Questions: Better camera support and alternative "fetch" sources

### ISSUE THREAD

**Issue by Eric24** [pqina/filepond#367]
I'm curious about whether any of these items are on your roadmap:
- Better camera support (i.e. direct camera support, including webcams on a laptop, not just phone/table support where the camera is "offered" when you browse)
- Support for alternative sources for "fetched" files, such as Google Drive, Dropbox, etc. (I realize that some sources could potentially be implemented entirely server-side, but others require some user interaction, like authenticating to Google Drive, for example)

**Comment by rikschennink** [comment]
Currently these are not on the roadmap, not saying that won't change but for now it's fine as it is.

- You can add a "camera" button outside of FilePond quite easily and then send the resulting capture to FilePond.
- Same thing with files from different origins, you can create controls outside of FilePond that feed the files to FilePond.

**Comment by rikschennink** [comment]
closed because no response for 6 days
