### ISSUE TITLE
Unable to set default image with react- filepond

### ISSUE THREAD

**Issue by Qubra1** [pqina/filepond#368]
Hello ,

**I am unable to set initial file to react file pond**
getting below error message
Uncaught TypeError: url.split is not a function
    at getFilenameFromURL (filepond.js:2230)
    at Object.request.onload (filepond.js:3571)
    at XMLHttpRequest.xhr.onload (filepond.js:2635)
<img width="1208" alt="Screenshot 2019-08-30 at 1 35 32 AM" src="https://user-images.githubusercontent.com/54686238/63972485-7febb580-cac6-11e9-81f9-d0b350ed80ea.png">

my current code reference: 
 constructor(props) {
        super(props);

        this.state = {
            files: [
                {
                    // the server file reference
                    source: 'https://image.shutterstock.com/image-photo/bright-spring-view-cameo-island-260nw-1048185397.jpg',

                    // set type to local to indicate an already uploaded file
                    options: {
                        type: 'local',

                        file: {
                            name: 'bar.jpg',
                            size: 1234,
                            type: 'image/jpeg'
                        }
                    }
                }
            ]

        };
 
    }
  handleInit() {
  
        console.log('FilePond instance has initialised', this.pond);
        this.pond.addFile('https://image.shutterstock.com/image-photo/bright-spring-view-cameo-island-260nw-1048185397.jpg', {
            type: 'local',
            file: {
                name: 'bar.jpg',
                size: 1234,
                type: 'image/jpeg'
            }
        })

    }
    render() {
        return (
            <div>
                <FilePond
                    className="addProfile"
                    ref={ref => (this.pond = ref)}
                    files={this.state.files}
                    allowMultiple={false}
                    imageCropAspectRatio="1:1"
                    name="filepond"
                    class="filepond"
                    labelIdle="<div><span>+</span>
                                <span>Add a profile</span><br/>
                                <span>picture</span></div>"
                    allowFileTypeValidation="true"
                    instantUpload="false"
                    acceptedFileTypes="image/png, image/jpeg, image/gif"
                    allowImagePreview="true"
                    allowImageCrop="true"
                    allowImageEdit="true"
                    allowImageResize="true"
                    allowImageTransform="true"
                    allowReplace="true"
                    allowImageExifOrientation="true"
                    checkValidity="true"
                    maxFiles="1"
                    oninit={() => this.handleInit() }
                    imageResizeTargetWidth="150"
                    imageResizeTargetHeight="150"
                    stylePanelLayout="compact circle"
                    styleLoadIndicatorPosition="center bottom"
                    styleProgressIndicatorPosition="right bottom"
                    styleButtonProcessItemPosition="right bottom"
                    styleButtonRemoveItemPosition="left bottom"
                    imageEditEditor={doka}
                    onupdatefiles={fileItems => {
                        this.onSelectImage(fileItems);
                    }}
                />
            </div>
        );
    }
}

I just get processing icon the image never loads.
Please help me with this and let me know what i am doing wrong.
I want set default image 
**And the doka edit button is also disabled** with no defaultimage. I dont understand why?
<img width="343" alt="Screenshot 2019-08-30 at 1 23 10 AM" src="https://user-images.githubusercontent.com/54686238/63971726-d0621380-cac4-11e9-875b-2951c9d5a433.png">

Please  view the screen shot for reference.
Unable to understand from documentation used below link already:
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

Please help...

**Comment by rikschennink** [comment]
Local files have to be set in the `files` array, addFile is only for new files.

**Comment by Qubra1** [comment]
It works...

Thank you so much... :-) It was really helpful..

Another question would be is there any possible way to set remote URL as the source.
Please let me know. As my default image will not be in my local.

**Comment by rikschennink** [comment]
That's possible but that would require the remote server to allow cross origin requests. Otherwise you might have to set up a proxy on your local server.
https://pqina.nl/filepond/docs/patterns/api/server/

**Comment by Qubra1** [comment]
ok. I want to display users profile image here. And the profile images are stored in amazon s3 bucket, hence what i receive in response is some URL. So if i pass this url directly in files[] source it does not work. 
could you please share me any some sample code snippet to setup my server without any cors issues and where exactly should i be setting these options (call setOptions method) and how i can set this url to source.

**Comment by rikschennink** [comment]
You'll have to implement the server.load end point.

**Comment by Qubra1** [comment]
Ok . Thank you for help...
I will try that out.
