### ISSUE TITLE
How to disable the ‘tab to cancel’

### ISSUE THREAD

**Issue by igwen6w** [pqina/filepond#369]
There is a delay in the upload process.

If the user clicks the cancel button when the file has just been uploaded, the status will not be updated and the uploaded file will not be deleted.

**Comment by igwen6w** [comment]
When the user clicks Cancel, a request should be sent to check the file has been uploaded.

**Comment by rikschennink** [comment]
Cannot reproduce.

1. cancelled request
2. upload
3. reverted upload

![Screenshot 2019-08-30 at 09 13 11](https://user-images.githubusercontent.com/1132575/64000630-6bc7a880-cb06-11e9-908a-ff225b83a080.png)

As the issue report doesn't contain any further information (as requested in the issue template) will close now.

**Comment by igwen6w** [comment]
allowRevert:false

**Comment by igwen6w** [comment]
cancelled request
![image](https://user-images.githubusercontent.com/24996622/64005757-95eb8b80-cb43-11e9-99db-7c206a711411.png)

The file has been uploaded successfully
![image](https://user-images.githubusercontent.com/24996622/64005903-cd5a3800-cb43-11e9-8f95-057bade63cbd.png)

**Comment by igwen6w** [comment]
![test](https://user-images.githubusercontent.com/24996622/64007467-d26cb680-cb46-11e9-8552-f877078518bb.gif)

**Comment by rikschennink** [comment]
Do you have all the server end points configured?
