### ISSUE TITLE
Translations (i18n) ...

### ISSUE THREAD

**Issue by jdriesen** [pqina/filepond#37]
Hi Rik,

First of all, CONGRATZ with this software.
I'm currently using it within my Vue Apps, and it works like a charm !

My question:
Do you plan to implement translations ?
e.g. currently, (when trying to upload an invalid FileType), I see the message "File is of invalid type".

It would be great if this string can become language dependent...

It's just a question, but do you have any plans to implement this ?

Thanks in advance for your reply,

Kind regards,
Johnny (Belgium, and speaking Dutch as well :) )

**Comment by jdriesen** [comment]
Apologies !!!
Forget my question.

Just found "labelFileTypeNotAllowed"

Problem solved. (feel free to delete this question)

Grtz,
Johnny

**Comment by rikschennink** [comment]
No problem! Was about to reply, glad you found the right property :-)

I’ll keep it around, might always be useful for someone else.
