### ISSUE TITLE
Sort by name

### ISSUE THREAD

**Issue by Flowfo** [pqina/filepond#370]
Alphanumeric order
Hi.
When uploading many files, I would like filepond to start by the 'first' file (sorted by name : file018.jpg then file019.jpg then file020.jpg...)
I don't see the right option in the doc.
Thanks for your help.

**Comment by rikschennink** [comment]
https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#sorting-files ?

**Comment by rikschennink** [comment]
closed because no response for 5 days
