### ISSUE TITLE
Firefox problems gui

### ISSUE THREAD

**Issue by neno91** [pqina/filepond#374]
Hello,

I think there is gui problems in firefox. On a plain install i cant seem to see the text on firefox.

Is this a known issue?

Is there any quickfix for this ?

Thanks ;)

**Comment by rikschennink** [comment]
I just opened https://pqina.nl/filepond/ in Firefox 68.0.2 MacOS and it's looking fine

![Screenshot 2019-09-03 at 20 21 08](https://user-images.githubusercontent.com/1132575/64198400-724c7c00-ce88-11e9-9004-dcc6b7ae42e4.png)

Will close because of lack of detailed information.

**Comment by neno91** [comment]
Sorry for being short.

Im running Firefox version 68.0.2  fresh install, no plugins on Windows 10.

And it looks like this:
![bilde](https://user-images.githubusercontent.com/2036405/64241550-42db5500-cf04-11e9-8d54-b5f870a356ca.png)

We have multiple firefox users reporting the same on our website.

Thanks,
Neno

**Comment by rikschennink** [comment]
Weird, I don't see it, just tested with Windows 10, Firefox 68

**Comment by rikschennink** [comment]
Does it turn red on error, or is it red from the start? Can you shoot a video of what happens?

**Comment by neno91** [comment]
The red box was gray with just the browse link, as soon as you select a file the text disapeers both in error and success view.


The strange thing is that it works now. I see that firefox just updated something, its firefox 69 now.

Im not sure if the problem still persists but it works right now on both our internal site and pqina.nl.

Ill post a video if the problem returns.

**Comment by rikschennink** [comment]
Alright glad to hear that! Will re-open if it returns.
