### ISSUE TITLE
[question] Get file name when uploading to a remote server with filepond

### ISSUE THREAD

**Issue by carterminearIMT** [pqina/filepond#375]
I am using the basic php boilerplate backend server to handle the uploads which works great. I get returned the hash of the folder it is stored in so I do know the path. But what I dont get is how to get a filename back to the server where the parent form is being submitted to? Is that built in somewhere that I am not seeing?

**Comment by rikschennink** [comment]
FilePond will store the ids of the folders in hidden input elements, when the form is submitted those are posted and thus your server knows which uploaded files need to be moved to final folders.

**Comment by carterminearIMT** [comment]
Ok I get that but that id is only the folder they reside in. I would like a file path so I can generate a url that points to the remotely uploaded file.

Maybe I am thinking about it wrong and on the submit step I need to make a custom method that moves the files from the tmp fold to the upload folder and returns their filepath with json or something.

Basically my use case is something very similar to a s3 bucket. Upload a file, get a url back to where the file is being stored.

**Comment by rikschennink** [comment]
It should be in the filepond php api, if you know the folder the file is in, you can get the files inside the folder with a glob and you can build the path.

**Comment by carterminearIMT** [comment]
Ok I think that puts me on the right track. I will just edit the submit.php of the boilerplate and have it return filepaths instead of just the folder id. Thanks for your help and great project!
