### ISSUE TITLE
imageTransformOutputQuality does not work on iOS

### ISSUE THREAD

**Issue by lolo888** [pqina/filepond#376]
Hello!
once the image resized the compression ratio is equal to 95 from an iOS mobile, not 85

```js
    	
    	imagePreviewMaxHeight: 170,
    	allowImageResize: true,
    	imageResizeTargetWidth: 682,
    	imageResizeUpscale: true,
    	maxParallelUploads: 1,
    	imageTransformOutputQuality: 85,

FilePond.registerPlugin(
		FilePondPluginFileRename,
		FilePondPluginFileValidateType,
		FilePondPluginFileValidateSize,
		FilePondPluginFileEncode,
		FilePondPluginImageResize,
		FilePondPluginImagePreview,
		FilePondPluginImageExifOrientation,
		FilePondPluginImageTransform
	);
```

...

| Environment  | Version
|------------- | -----------
| OS           | iOS | 12.1.13 ...
| Device       | iPad  / ...
| Browser      | Safari  / Chrome / ...

**Comment by rikschennink** [comment]
How did you measure that?

**Comment by lolo888** [comment]
sorry : on iOS 12.1.13

**Comment by lolo888** [comment]
with this link https://www.imgonline.com.ua/eng/determine-jpeg-quality.php and also by the file weight between MacOS and iOS

**Comment by rikschennink** [comment]
The compression ratio is simply passed to the toBlob method, how much compression is applied is handled by the browser. There's not much we can do about that. Can you see the compression being applied when it's set to a low value like 40?

**Comment by lolo888** [comment]
ok!
I just tested at 40, the file weight is well diminished, and the compression ratio shows 64, why such a difference in rate?

**Comment by rikschennink** [comment]
I don't know to be honest. It's browser specific, some will apply different compression techniques than other perhaps? For instance favouring speed over compression?

**Comment by lolo888** [comment]
On Chrome MacOS the rate is 40

**Comment by lolo888** [comment]
could we apply specific setting only for iOS ?

**Comment by rikschennink** [comment]
You could detect the browser/device and then pass a different compression value to FilePond

**Comment by lolo888** [comment]
would you have an example to send the variable dynamically to FilePond.create?

**Comment by rikschennink** [comment]
I don’t, but it’s basic navigator agent sniffing and then setting the result to the settings object that is passed to FilePond. 

Will close because this is not related to FilePond

**Comment by lolo888** [comment]
yes, thank you so much !
