### ISSUE TITLE
addFile via file_id

### ISSUE THREAD

**Issue by brain2xml** [pqina/filepond#378]
Hi!

According docomentation 

> Step one and two now look like this.
> 
> FilePond requests restore of file with id 12345 using a GET request
> server returns a file object with header Content-Disposition: inline; filename="my-file.jpg"
> 

I try to make this by set settings

```
pond.setOptions({

        server: {
            url: './',
            process: {
                headers: {
                    "X-CSRF-Token": document.querySelector('input[name=_token]').value,
                },
                url: '/uploadimage',
            },
            revert: './revert/',
            load: './load',
            fetch: './fetch/'
        },
    });


```

and try to add file

```
pond.addFiles([{
  serverId:1235,
            options: {
                type: 'local'
            }
}]);
```
byt it makes xdr /news/load/%7B%22serverId%22%3A1235%2C%22options%22%3A%7B%22type%22%3A%22local%22%7D%7D

plase give my example to show already upload file in list
I do not to need upload them again, just have delete options

**Comment by rikschennink** [comment]
You can set existing files using the `pond.files` property.
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#Setting%20initial%20files

**Comment by brain2xml** [comment]
Same 
/news/load/%7B%22serverID%22%3A1235%2C%22options%22%3A%7B%22type%22%3A%22local%22%7D%7D
object use as string

**Comment by rikschennink** [comment]
```js
const pond = FilePond.create({
    files: [
        {
            // the server file reference
            source: '12345',

            // set type to limbo to tell FilePond this is a temp file
            options: {
                type: 'limbo'
            }
        }
    ]
});
```

**Comment by brain2xml** [comment]
Error during load, 400 (Can't load URL)
It do not send any ajax to server. 
I trid **type: local** too
Server must return file object, means json?

**Comment by rikschennink** [comment]
No, it needs to return binary data

**Comment by brain2xml** [comment]
Error during load, 400 (Can't load URL) on page
No any requests to server.

**Comment by brain2xml** [comment]
Sorry, code working, I put settings after init plugin. now working. thank you
