### ISSUE TITLE
Questions about Filepond that are not clear from the documentation

### ISSUE THREAD

**Issue by simioluwatomi** [pqina/filepond#38]
I currently use Slim image cropper to handle image uploads in a project. And with what I have read so far, implementing this in lieu of Slim would be a walk in the park. But I have some questions.

- In the profile picture selection example, can I pass an external URL of an image (say from S3 or CloudFront) to the preview area and have the image loaded into the preview area? I know this is possible with Slim but Slim downloads the image onto the server first before rendering it in the preview. I don't want the images downloaded to the server before rendering. Is this possible?

- I use [Dropzone](http://www.dropzonejs.com/) to directly upload audio files (file size ranges between 100 - 200MB) to S3 and use callbacks to get the filename of the uploaded file and its full S3 URL, then pass these as hidden fields to a form that user then submits. Which callbacks in the documentation should I implement to get this same functionality?

Thanks for doing a great job...

**Comment by rikschennink** [comment]
Hi! Currently on a short trip, will get back to you on Wednesday.

**Comment by rikschennink** [comment]
Hi!

- You can't, you need a server to load the remote file and return it to the front-end. Front-end can't do cross domain requests without authorization.

- You should pass a custom `process` method, see the [server docs](https://pqina.nl/filepond/docs/patterns/api/server/). This allows you to then use the name of the file as a unique identifier.
