### ISSUE TITLE
Remove File from File pond control

### ISSUE THREAD

**Issue by drferg1954** [pqina/filepond#380]
Hello fellow developer!

🧠 If you have a question, please ask it on StackOverflow -> https://stackoverflow.com/questions/ask?tags=filepond

🐜 If you think you have found a bug, please use the template below to report it.

**The more details you provide, the more inclined others are to help you out and the faster the issue is resolved.**

If you're using one of the FilePond adapters for React, Vue, Angular or jQuery and think the issue might be related to the framework, submit the issue in the specific adapter repository.

Please format code snippets using triple backticks and set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

```js
const foo = 'bar';
```

### Summary
I would like to reset my all controls in my form to the original state.
Filepond is not being used to send files to the server but just to provide the input for a subsequent Rest request. 
If a file is dragged to filepond it remains visable after the reset. 
I have tried using a ref to remove the file but I suspect that is intended for removing the file from server not the UI.
...

### How to reproduce
This is what I have tried.
In render
                            <FilePond ref= "pond" 
                                    disabled = {this.state.useDefaultISF}
                                            onupdatefiles={fileItems => {
                                                console.log('UpdateFiles')
                                                // Set currently active file objects to this.state
                                                this.setState({
                                                    files: fileItems.map(fileItem => fileItem.file)
                                                }
                                                )
                                                
                                             
                                                //console.log('uploaded file  ' + this.state.files[0].name)
                                                this.readFileContents(this.state.files[0])
                                            }}>
                                  </FilePond>

etc.... 
<Button variant='outlined' onClick={this.reset} style={{ marginRight: '1rem' }}>Reset</Button>

Reset function:
    //resets the page with it's default state (values)
    reset() {
        this.setState({ ...this.defaultState })
        this.setState({payment_types:[]})
        this.fetchPaymentTypes();
        this.$refs.pond.removeFile();
    }

### Expected behaviour
File no longer visible in filepond control
...

### Additional information

...

| Environment  | Version
|------------- | -----------
| OS             Windows 
| Device       PC
| Browser     Chrome

**Comment by rikschennink** [comment]
Closed

Reason: the issue is not formatted correctly.
