### ISSUE TITLE
Step by Step undo process once the image is edited

### ISSUE THREAD

**Issue by Qubra1** [pqina/filepond#384]
Hello,

When the user edits any image with doka .The user must have made lot of edits and might want to revert only few of the changes made .Hence i wanted to know if there is a way we can provide step by step undo to the user with doka to revert the changes .
If Yes, how can i enable the same. Please let me know.

Thank you in advance.

Regards

**Comment by rikschennink** [comment]
Hi, this is not possible at the moment, Doka only features a reset method. 

FYI a new (from the ground up rewritten) version is in development that will feature undo/redo functionality.

**Comment by Qubra1** [comment]
Thank you Rik for your immediate response.
