### ISSUE TITLE
"Unable to delete property" in iOS Safari 10

### ISSUE THREAD

**Issue by mstratman** [pqina/filepond#385]
### Summary

Javascript error on Mobile Safari 10

```
TypeError
Unable to delete property.
```

### How to reproduce

On Mobile Safari 10 (I reproduced via Browserstack, iOS 10.3.3) drop an image in the drop zone. 

### Additional information

This is the line of the error:

https://github.com/pqina/filepond/blob/0e5e608785549bc750472ae1d225ab5679b5e643/src/js/app/view/root.js#L584

**Comment by rikschennink** [comment]
Should be fixed in `4.7.2`
