### ISSUE TITLE
filename of pasted image is always 'image.png'

### ISSUE THREAD

**Issue by edant92** [pqina/filepond#386]
### Summary
The filename of a pasted image is always 'image.png'
...

### How to reproduce
Copy and paste an image into filepond
...

### Expected behaviour
Pasted image/file should contain the filename of the pasted image.
...

### Additional information
Not sure if this is a library limitation or a browser limitation - I couldn't find much on it. If it's a browser limitation then please close this!
...

| Environment  | Version
|------------- | -----------
| Browser      | Chrome / Mozilla Firefox

**Comment by rikschennink** [comment]
This unfortunately is a browser limitation.

If someone has ideas on how to work around this, all ears, till that time, I'll close this.
