### ISSUE TITLE
Animated GIFs being converted to PNG

### ISSUE THREAD

**Issue by chrismitchell** [pqina/filepond#387]
### Summary

We are currently seeing animated GIFs being converted to PNG files before being sent to ActiveStorage.  

We recently updated FilePond and some of the plugins to the following versions:

```json
"filepond": "^2.1.1" -> "^4.2.1"
"filepond-plugin-file-poster": "^1.0.0" -> "^2.2.0"
"filepond-plugin-file-validate-size": "^1.0.4" -> "^2.2.0"
"filepond-plugin-image-preview": "^2.0.1" -> "^4.4.0"
"filepond-plugin-image-transform": "^2.0.1" -> "^3.4.3"
```

We also use `"filepond-plugin-file-validate-type": "^1.1.0"` and `"filepond-plugin-image-resize": "^2.0.1"` however those versions didn't change. 
 
Before the updates when we uploaded animated GIFs they would remain as such and when render to the browser...animated. However with the recent update animated GIFs get converted to PNG files. 

Is there away to prevent this?

I apologize if this is documented somewhere but I was unable to find anything around this.

Thanks for the great library 👍

**Comment by chrismitchell** [comment]
@rikschennink thanks I just tested the new version against out codebase and uploaded animated gifs remained animated. 

Thank you

**Comment by rikschennink** [comment]
Glad to hear that Chris, thanks!

**Comment by dsgipe** [comment]
I am running into the same problem. And I couldn't figure out which package needs to be 3.5.1. Which one needs to be upgraded? Thanks!

**Comment by chrismitchell** [comment]
@dsgipe it was for the `filepond-plugin-image-transform` plugin. 

See commit https://github.com/pqina/filepond-plugin-image-transform/commit/d59d675f388794192a8c4235c231e37f7c336d75

**Comment by kezek** [comment]
I'm having the same issue. Updated `filepond-plugin-image-transform` to 3.6.0 but still having the issue.

These are the currently installed packages: 

"filepond": "^4.2.0",
    "filepond-plugin-file-poster": "^2.2.0",
    "filepond-plugin-file-validate-size": "^2.2.0",
    "filepond-plugin-file-validate-type": "^1.2.0",
    "filepond-plugin-image-crop": "^2.0.0",
    "filepond-plugin-image-edit": "^1.0.1",
    "filepond-plugin-image-exif-orientation": "^1.0.3",
    "filepond-plugin-image-preview": "^3.1.4",
    "filepond-plugin-image-resize": "^2.0.1",
    "filepond-plugin-image-transform": "^3.5.1"

Suggestions ?

**Comment by rikschennink** [comment]
@kezek Please update everything to latest version. FilePond for instance is at 4.7.4

**Comment by kezek** [comment]
Updated everything to latest version and still having this issue. 

We also use vue-filepond (also updated to latest version). I'm 99% sure it's a bug on your side because I've added a callback to `server` and console.log the uploaded file. 

The image type is `image/gif` but in the console.log it appears as `image/png`.

**Comment by kezek** [comment]
We also use Doka. I'll try to update that as well and see if we can resolve it.

**Comment by rikschennink** [comment]
@kezek Alright keep me posted. You could also disable Doka for a moment and see if that solves it.

**Comment by dlynam01** [comment]
@kezek has this been resolved for you ? We are also experiencing the same issue and I can see it happening on the filepond website.

**Comment by kezek** [comment]
@dlynam01 I did not. Last thing I tried was updating all libraries to latest stable but that did not solve the issue. 

Please let me know if you find a solution ,thanks

**Comment by rikschennink** [comment]
You can use the `imageTransformImageFilter` to filter out gifs from transforming.

**Comment by dlynam01** [comment]
@rikschennink , I'll give this a go

**Comment by dlynam01** [comment]
The imageTransformImageFilter worked for me https://stackoverflow.com/questions/58874156/make-filepond-image-transform-plugin-ignore-animated-gifs

**Comment by stevendprinsloo** [comment]
Does anyone know how this can be achieved in Vue Js, but with the **Image Resize** plugin?
@rikschennink
