### ISSUE TITLE
How can i get a blob or reference to the uploaded image to show a custom preview?

### ISSUE THREAD

**Issue by idrislab** [pqina/filepond#388]
Hello,

I'm trying to show a custom preview of the uploaded image outside of filepond before submitting the form, but i'm unable to get a reference to it. Is it possible to do?

I've done it before using Dropzone, but with filepond i'm having a bit of trouble figuring it out.

**Comment by rikschennink** [comment]
Yes that should be possible with the `onprocessfile` callback, it gives you access to the file item and the file.

**Comment by idrislab** [comment]
@rikschennink i might be missing something but onprocessfile i'm only getting an object with basic information about the file (filename, filesize), not the actually file/blob.

Do you have a simple example (can be pseudo code) of how this can be achieved?

Thanks

**Comment by idrislab** [comment]
@rikschennink thanks i got it.

**Comment by rikschennink** [comment]
For future reference: https://codesandbox.io/s/vanilla-filepond-onprocessfile-8od1t
