### ISSUE TITLE
Bug: stylePanelLayout='integrated' with allowMultiple=true causes unintended behavior

### ISSUE THREAD

**Issue by drone1** [pqina/filepond#389]
Please view this jsfiddle: https://jsfiddle.net/ycj1ns4v/

Upload a file and the control grows its height forever. I'm pretty sure this is not the intended behavior. If it is, I don't see anything about it in the documentation. If allowMultiple is set to false, this behavior does not occur.

I'm testing on Chrome 77, Mac OS Mojave 10.14.6.

**Comment by rikschennink** [comment]
It's not to be used with `allowMultiple`

**Comment by drone1** [comment]
Just updated to 4.13.1 and this still happens. Perhaps a console.error() is needed in this case. :)

**Comment by rikschennink** [comment]
@drone1 again, it's not to be used in this manner. Adding a `console.error()` would add additional weight to the package that is not needed IMHO

**Comment by drone1** [comment]
I understand that, but it’s still not documented so I ran into it again.

Re package size: I can’t tell if you’re serious.

**Comment by rikschennink** [comment]
I’m serious.

You can add a PR on the docs repo.
https://github.com/pqina/filepond-docs

**Comment by nikans** [comment]
Maybe it should be documented [here](https://pqina.nl/filepond/docs/api/instance/properties/#disabling-credits) or somewhere else...
