### ISSUE TITLE
Bug: stylePanelLayout='circle' with allowMultiple=true causes unintended behavior

### ISSUE THREAD

**Issue by drone1** [pqina/filepond#390]
Please view this jsfiddle: https://jsfiddle.net/z513k7vq/

Upload a file and the control shows no progress indication or other apparent UI change. I'm pretty sure this is not the intended behavior. If it is, I don't see anything about it in the documentation. If allowMultiple is set to false, the UI changes to indicate progress (although no progress here since it's not hooked up to a real server).

I'm testing on Chrome 77, Mac OS Mojave 10.14.6.

**Comment by rikschennink** [comment]
It's not to be used with `allowMultiple`

**Comment by drone1** [comment]
Is this documented? Perhaps an exception should be thrown or a warning
should be printed?

**Comment by rikschennink** [comment]
It should be documented here https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#properties but it seems it isn't. 

Feel free to submit a PR https://github.com/pqina/filepond-docs
