### ISSUE TITLE
Too heavy animations.

### ISSUE THREAD

**Issue by KilledDebtor** [pqina/filepond#391]
I wrote a hack for manual sorting that uses the sort function, but if there are more than 20 pictures, or on weak systems, animations begin to lag. Especially in Firefox. (Drag and drop function is laggy too)

Can you give any optimization tips? I'm not very good at JS, i'm a PHP developer :( .

Maybe reduce frame rate or something like that.

**Comment by rikschennink** [comment]
I'm not sure, there's a lot of internal logic in FilePond to make sure everything runs smoothly. If it's choppy, make sure you don't read from the DOM. Will close this for now.
