### ISSUE TITLE
Unable to scroll when filepond is disabled

### ISSUE THREAD

**Issue by milewski** [pqina/filepond#392]
Hello, if the max height is set as described here: https://pqina.nl/filepond/docs/patterns/api/style/#limiting-the-height-of-filepond

When the filepond is disabled, it`s not possible to scroll, I can see the scrollbar but im stuck it doesn't scroll. 

![image](https://user-images.githubusercontent.com/2874967/66710876-b39f4800-edb3-11e9-8f0d-0e022d648162.png)

**Comment by rikschennink** [comment]
Will look into this as soon as I have some time

**Comment by rikschennink** [comment]
Fixed in https://github.com/pqina/filepond/releases/tag/4.12.0
