### ISSUE TITLE
Disabling User's ability to cancel file upload

### ISSUE THREAD

**Issue by bminner** [pqina/filepond#394]
Is it possible to disabled a user's ability to cancel the file upload? I am referring to this: 
![filepond upload](https://user-images.githubusercontent.com/13971723/66964517-deec9600-f044-11e9-863a-05f04f44fc85.png)

My current Filepond setup looks like this:

```
<FilePond
  acceptedFileTypes={['application/zip']}
  maxFileSize={'100MB'}
  allowMultiple={false}
  server="/controller/method"
  labelFileProcessingError="Unable to upload file. Please make sure format is correct."
  allowRevert={false}
  instantUpload={false}
  onaddfile={() => {
    this.getProgress();
    this.setState({ fileAdded: true });
  }}
/>
```

Currently, when a file is uploading, it has already made it to my controller method before it "shows" that is has uploaded 100%. This is an issue for me because currently we do not handle the functionality of canceling an upload after it has started.

Ideally there would be a way to disable the ability to cancel the upload. But if not, could you point me in a direction to proceed?

Thanks

**Comment by rikschennink** [comment]
> This is an issue for me because currently we do not handle the functionality of canceling an upload after it has started.

I think if you set `server.revert` to `null` it will just remove the file from the list but won't call the revert method.

**Comment by bminner** [comment]
Thank you for the response.

If I chose to do that, then the file would still be processed within the system. But to the user it would look like they removed the file as well as stopped the processing of the item.

Is it possible to only send the file down to the server after it has completed the upload process?

**Comment by rikschennink** [comment]
You can do that by not setting the server property and manually uploading the files when the user clicks the form submit button.

**Comment by rikschennink** [comment]
Closed as inactive

**Comment by Herz3h** [comment]
It would still be useful to simply disable the cancel button, as your workaround sounds more complicated.

In my case I first upload to a php server, which then uploads to sharepoint, so cancelling doesn't work since it cancels only the first part, while the file is actually being uploaded to sharepoint

**Comment by rikschennink** [comment]
@Herz3h what would happen if the user refreshes the page?

**Comment by Herz3h** [comment]
If upload reaches server before being canceled, upload still goess through I guess (not sure tbh). Either way I just hide the cancel button with css 👍
