### ISSUE TITLE
how to reset filepond instance?

### ISSUE THREAD

**Issue by neozhu** [pqina/filepond#397]
`````
    let pond;
   //open popup modal window select files
    function importpic() {
      $('#importModal').modal('toggle');
      $('#label').val('');
      $('#description').val('');
      const inputElement = document.querySelector('input[type="file"]');
      pond = FilePond.create(inputElement);
    }
   //execute upload files
    function uploadfiles() {
      if (pond) {
        var v = $('#uploadfiles-form').valid();
        var files = pond.getFiles();
        console.log(files, v);
        if (v && files.length > 0) {
          pond.processFiles().then(() => {
            $('#importModal').modal('toggle');
            reload();
            pond.removeFiles();
          });
        }
      }
    }
 `````
first open poup modal upload files is work!but completed first upload process,second time open popup model,and select files, click uploadfiles pond.getFiles() is empty.so not process upload file,
why?how to solve this problem

**Comment by rikschennink** [comment]
As stated in the issue template, please use SO for questions

**Comment by neozhu** [comment]
> As stated in the issue template, please use SO for questions

？

**Comment by rikschennink** [comment]
Click on "New issue", it's right there:

> 🧠 If you have a question, please ask it on StackOverflow -> https://stackoverflow.com/questions/ask?tags=filepond

**Comment by neozhu** [comment]
https://stackoverflow.com/questions/58522474/why-unable-to-upload-file-twice-use-filepond-component
