### ISSUE TITLE
FilePond is now available on PageCDN

### ISSUE THREAD

**Issue by alebcay** [pqina/filepond#398]
I'm not sure what is the best way to communicate this, but FilePond and its adapters are now available via [PageCDN](https://pagecdn.com):
- [FilePond](https://pagecdn.com/lib/filepond)
- [React adapter](https://pagecdn.com/lib/react-filepond)
- [Vue adapter](https://pagecdn.com/lib/vue-filepond)
- [jQuery adapter](https://pagecdn.com/lib/jquery-filepond)

I don't know if it would be desirable to publicize this in any documentation, but I figured I'd just mention it here.

_I'm not affiliated with PageCDN._

**Comment by rikschennink** [comment]
Thanks! I'll add it to the readme.
