### ISSUE TITLE
File uploaded to server success or failure events?

### ISSUE THREAD

**Issue by kailashvele** [pqina/filepond#4]
How can I get the event where file was successfully uploaded to server or failed to upload to server event.

**Comment by rikschennink** [comment]
Hmm, seems I've forgotten to document this. It's the `"processfile"`event. There's a generic `"error"` event that is triggered when something goes wrong. Might be handy to have a specific `"processfileerror"` event.

```
const pond = FilePond.create();
pond.on('processfile', file => {
    console.log('File processed', file);
});
```

I'll run some tests tomorrow morning just to be sure.

**Comment by rikschennink** [comment]
@kailashvele I've pushed a new version to npm (1.2.0) and have [updated the docs](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#events).

You can handle the `processfile` event like this.

```js
pond.on('processfile', (error, file) => {
    if (error) {
        console.log('Oh no');
        return;
    }
    console.log('File processed', file);
});
```

Or

```js
pond.onprocessfile = (error, file) => {
    if (error) {
        console.log('Oh no');
        return;
    }
    console.log('File processed', file);
}
```

Or

```js
element.addEventListener('FilePond:processfile', e => {
    if (e.detail.error) {
        console.log('Oh no');
        return;
    }
    console.log('File processed', e.detail.file);
});
```

**Comment by kailashvele** [comment]
@rikschennink Thats great, thanks for quick response and many thanks for the library I loved it. Cheers. If you need any assistance in future do let me know :)

**Comment by rikschennink** [comment]
Awesome, glad to hear that! And, will do ;-)
