### ISSUE TITLE
Re-Upload a file after a process-error Or reset FileStatus

### ISSUE THREAD

**Issue by Aspect96** [pqina/filepond#402]
Hey,

I am currently using the filepond with Vue to upload some files. I am currently a bit helpless to how I can reset the filestatus or if the user re-uploads the file that it will upload the file again(after a processing error), but it does nothing at all, it is not uploading the file again.

I am using a custom processing method, that is set during the initialization of my component.
```js
setOptions({
    server: {
    process: this.process,
  }
});
```
The process method simply makes a formData and sends it to the server.
I await a status code as a response by my server.

Now if the server would send back a bad status code, how can I make it that the user can press the upload button again to upload the file. (Where either FileStatus is reset for `this.$refs.filepond.processFiles();` to work again)

FYI, I do not want to use the controls from filepond, that is not possible with how my form is setup.

How can I with my custom processing method properly re-upload a file that had a processing-error fired. I want to be able to press upload again with this code `this.$refs.filepond.processFiles();`, also if there was a processing-error, he should just try again. Is that possible for my situation?

**Comment by rikschennink** [comment]
You can use the `error` callback to return an error state to FilePond.
https://pqina.nl/filepond/docs/patterns/api/server/#process-1

Please also make sure you return a uniqueId along with the `load` callback.
