### ISSUE TITLE
Add additional header 'Upload-Name' during first POST request when processing Chunks

### ISSUE THREAD

**Issue by prince272** [pqina/filepond#409]
Filepond only adds 'Upload-Length' header to  first POST request. I would like an additional header like 'Upload-Name'  to determine the name and the type of file which is going to be processed. 

In short:
FilePond will send a POST request (without file) to start a chunked transfer, expecting to receive a unique transfer id in the response body, it’ll add the 'Upload-Length' and 'Upload-Name'  header to this request.

**This section is based on my requirements.**
Server creates a temporary file with this extension eg: my-file.jpg.upload and chunks until all chunks have been uploaded succesfully. Now server removes the .upload extension.

**Comment by rikschennink** [comment]
Hi, you can set `server.process.headers` to a *function* and return your own header object which FilePond will then use instead.

```js
server.process.headers = (file, metadata) => {
    return {
        'Upload-Length': file.size
        // your header properties here
    }
} 
```

**Comment by prince272** [comment]
Thanks for your support.
