### ISSUE TITLE
Access to the raw response object

### ISSUE THREAD

**Issue by gabaum10** [pqina/filepond#41]
I'm uploading a file to a temp bucket in my app.  I'm trying to integrate filepond but am having a hard time getting access to the raw response object on upload success.  As part of that payload there is a temp file ID I need to get to submit with a later request.  Is there a way to do that?  It's kind of a deal breaker for using filepond.

**Comment by gabaum10** [comment]
I'm trying to step through the source, but I just straight up don't see a way of getting the raw response.  I see the event fire for the `process-complete` event, but that never makes it to my client listener.  I'm using the Vue component, but that shouldn't matter really.  

```vue
this.$refs.pond._pond.on('process-complete', () => {
        debugger
      })
```

Is there really no way to access this thing?

**Comment by rikschennink** [comment]
Hi @gabaum10!

There's no public `process-complete` event, the one you found is only used internally. See this list for a complete overview of all available events:
https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#events

You can access the returned id through the file object API.
```js
pond.onprocessfile = (error, file) => { console.log('done', file.serverId) };
```

From the top of my head, that would convert to Vue in the following manner:

```vue
<template>
  <div id="app">

    <file-pond
        name="test"
        ref="pond"
        server="/api"
        v-on:processfile="handleProcessFile"/>

  </div>
</template>

<script>
// Import Vue FilePond
import vueFilePond from 'vue-filepond';

// Import FilePond styles
import 'filepond/dist/filepond.min.css';

export default {
    name: 'app',
    methods: {
        handleProcessFile: function(error, file) {
            console.log('done', file.serverId);
        }
    },
    components: {
        FilePond: vueFilePond()
    }
};
</script>
```

**Comment by gabaum10** [comment]
Thanks but that's not what I was asking.  I saw the docs and tried all the events and callbacks.  We return a special attribute called "key" in the response.  I need that somehow in my component.  It seems the raw response object is not returned anywhere which seems like kinda an oversight.  Can we do something like at least add the response to the file metadata or something?

**Comment by rikschennink** [comment]
@gabaum10 The server response should automatically be stored in the `file.serverId` value. Is it empty? What does the server response look like?

**Comment by gabaum10** [comment]
@rikschennink This is what the response looks like:

![fileresponse](https://user-images.githubusercontent.com/1561245/39925027-16a55e90-54f8-11e8-9c0c-e33139aec7bb.png)

As you can see there is some extra data that's returned that doesn't exist on the file object that's passed back to the done event; specifically the `key`.  If there is nothing that's exposed, is there a way I can bind something directly to the input to get that raw response?

**Comment by gabaum10** [comment]
Oh!  Indeed.  I see that now.  Weird I missed that.  Carry on.

**Comment by rikschennink** [comment]
@gabaum10 The server response should be a unique identifier so when the form is submitted it can be linked to the file on the server. But that's probably not always the case. I take it the property contains the entire response in your situation? But if it was just the `key` it would match right? Maybe some sort of filter method to select the right property from the response would make it match better?

**Comment by rikschennink** [comment]
A filter in FilePond, where it would pass the server response through the filter so you can select the property to use as file server identifier ( in your case `key`). You could write a custom processing method but that's a bit overkill if you only need to select a property, sometimes altering the server response is out of our control so this would make it a bit easier to use.

**Comment by gabaum10** [comment]
That sounds exactly like what we need here. :+1:

**Comment by gabaum10** [comment]
Great!  Thanks for being so responsive.

**Comment by rikschennink** [comment]
No problem @gabaum10! Let me know if you have any further questions.

**Comment by prevostc** [comment]
Please note that the typescript types are not up to date: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-filepond/index.d.ts
