### ISSUE TITLE
TypeError: cannot use 'in' operator to search for 'createObjectURL'

### ISSUE THREAD

**Issue by gitFrank** [pqina/filepond#412]
Hi, want test filepond for first time.
I use your test code from here (also from jquery adapter page tested). All scripts are loaded, but the console shows:
TypeError: cannot use 'in' operator to search for 'createObjectURL' ... (filepond.min.js:9:100499)

Seems only a problem for me, nobody else. What can be the reason?

(Win7, latest Firefox)

**Comment by rikschennink** [comment]
I'm not sure. It's likely related to this test:

```js
const hasCreateObjectURL = () => 'URL' in window && 'createObjectURL' in window.URL
```

Maybe `window.URL` is not available somehow?

**Comment by rikschennink** [comment]
Closed because no response.
