### ISSUE TITLE
FilePond IE11 instantiation issue

### ISSUE THREAD

**Issue by dalebarrie96** [pqina/filepond#413]
HI There,

I am having the below issue with filepond on IE11. 

"Unable to set property 'styleButtonRemoveItemPosition' of undefined or null reference" on line 10396 of filepond.js. The error is thrown every time I try to create a new FilePond object on ie11. I have included the required polyfills and can see in the network tab of the developer console that all resources are pulling through with the correct status and order.

```html

<head>
	<link rel="stylesheet" href="<c:url value='/scripts/filepond/filepond.css'/>">
		
	<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
<!-- 		<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.6.0/polyfill.min.js"></script> -->
		
	<script src="<c:url value='/scripts/filepond/filepond-polyfill.js'/>" type="text/javascript"></script>

	<script src="<c:url value='/scripts/filepond/filepond.js'/>" type="text/javascript"></script>
</head>

```

```js

$(document).ready(function(){	
	
	var inputElement = document.getElementById('${param.uploadName}${param.modelOrder}');
	var pond = FilePond.create( inputElement );
	
	pond.setOptions({
		allowMultiple: ${param.allowMultiple},
		allowRevert: allowRevert,
	    server: {
	    	process: {
	    		url: '${param.url}',
	    		ondata: function(fd){
	    			if(hasParams){
	    				for (key in JSONMap) {
		    			    if (JSONMap.hasOwnProperty(key)) {
		    			        fd.append(key, JSONMap[key]);
		    			    }
		    			}
	    			}
	             	return fd;
	             }
	    	},
	    	revert: {
	    		url: '${param.revertUrl}',
	    		method: 'POST'
	    	}
	    }
	});	
})
```

This setup is working as expected on both Chrome and Firefox. Do you have any idea what could be causing this? Any help on this would be greatly appreciated. I have attached screenshots of browser info, and the developer consoles network tab below.

![ie version](https://user-images.githubusercontent.com/17252667/69799154-a1923100-11ca-11ea-8255-46bb1226b4c1.PNG)

![filepond network tab](https://user-images.githubusercontent.com/17252667/69799112-8fb08e00-11ca-11ea-893f-2ed7a472f633.PNG)

**Comment by dalebarrie96** [comment]
Sorry about this, There was a meta tag in our decorator that was forcing ie users to compile in ie10.

**Comment by rikschennink** [comment]
No worries @dalebarrie96 :-)
