### ISSUE TITLE
No response while using onremovefile in Angular

### ISSUE THREAD

**Issue by shubhamsoni8769** [pqina/filepond#414]
Hello fellow developer!

🧠 If you have a question, please ask it on StackOverflow -> https://stackoverflow.com/questions/ask?tags=filepond

🐜 If you think you have found a bug, please use the template below to report it.

**The more details you provide, the more inclined others are to help you out and the faster the issue is resolved.**

If you're using one of the FilePond adapters for React, Vue, Angular or jQuery and think the issue might be related to the framework, submit the issue in the specific adapter repository.

Please format code snippets using triple backticks and set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

```js
const foo = 'bar';
```

### Summary
i am using onremovefile same as that of oninit as given in filePond document I.e 

<file-pond #myPond 

    [options]="pondOptions" 
    [files]="pondFiles"
    (oninit)="pondHandleInit()"
    (onremovefile ) = "pondRemoveFile()"
    (onaddfile)="pondHandleAddFile($event)">

</file-pond>

...

### How to reproduce

...

### Expected behaviour
i think, on canceling the loded image this function (i.e onremovefile ) should call. but that is not happning .
...

### Additional information

...

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
I don't know. it seems the code is malformed `(onremovefile ) = "pondRemoveFile()"` there's spaces in it, that could be the issue.

**Comment by shubhamsoni8769** [comment]
Hi,
i removed extra spaces and still method is not getting called.
here is full implementation.

// html file
<file-pond  #myPond
             [options]="pondOptions"
             (oninit)="pondHandleInit()"
(onremovefile ) = "pondRemoveFile()"
 (onaddfile)="pondHandleAddFile($event)">
             </file-pond>


//ts.file
pondRemoveFile(){
console.log(" pond file removed called()")
}

if there is other solution please provide me .
Thank You

**Comment by rikschennink** [comment]
@shubhamsoni8769 Please provide a test case on https://codesandbox.io

**Comment by pasevin** [comment]
You still have a lot of spaces: ```(onremovefile ) = "pondRemoveFile()"```

**Comment by rikschennink** [comment]
closed because no test case provided and code snippets still look malformed
