### ISSUE TITLE
Height of filepond--root not updating

### ISSUE THREAD

**Issue by qlow** [pqina/filepond#415]
### Summary
The "filepond--root" div's height doesn't get updated so the following elements are behind the filepond.

How it is:
![Bildschirmfoto 2019-12-01 um 11 40 47](https://user-images.githubusercontent.com/20094418/69912852-9db31880-142f-11ea-9304-3e922fc929a0.png)

How it should be:
![Bildschirmfoto 2019-12-01 um 11 41 30](https://user-images.githubusercontent.com/20094418/69912855-a1df3600-142f-11ea-827a-fc90b9792dc6.png)

### How to reproduce
Visit https://forms.neulia.de/onboarding/test 

or use this code:
```html
<head>
  <!-- add to document <head> -->
  <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
  <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">

  <style>
    #test {
      height: 100px;
      width: 100%;
      background: #eee;
      display: flex;
    }

    #test > h1 {
      margin: auto;
    }

    .filepond--drop-label {
      background: #696969;
      color: #fff;
    }
  </style>

</head>

<body>
  <!-- add before </body> -->
  <script src="https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.js"></script>
  <script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>

  <script src="https://unpkg.com/filepond/dist/filepond.js"></script>

<!--
The classic file input element we'll enhance
to a file pond, configured with attributes
-->
<input type="file"
    class="filepond"
    name="filepond"
    multiple
    data-max-file-size="3MB"
    data-max-files="3">

<div id="test">
  <h1>THIS SHOULD BE BELOW THE FILEPOND</h1>
</div>

<script>
  // Select the file input and use
  // create() to turn it into a pond
  FilePond.registerPlugin(FilePondPluginImageExifOrientation, FilePondPluginImagePreview);

  FilePond.create(
      document.querySelector('input')
  );

</script>

</body>

```

### Expected behaviour
Like on https://pqina.nl/filepond/#multi-file-demo the height of the filepond--root should be updated (when you inspect it, you see that the CSS "height" attribute of it gets modified"

**Comment by rikschennink** [comment]
Does your page have a doctype? `<!DOCTYPE html>`

**Comment by qlow** [comment]
thank you, never thought that this could be an issue at all.

**Comment by hijoem** [comment]
I wasted a few hours until I stumbled in this page.

I don't know why but my Laravel 8 views/layouts/app.blade.php didn't include this `<!DOCTYPE html>`  by default.

So basic.
So embarassing.

Well, thank you.

**Comment by tyrants666** [comment]
Doctype missing could be due to one of the following reasons explained here.
https://wordpress.org/support/topic/doctype-missing-one-some-pages/

**Comment by ruvilonix** [comment]
Found this answer after not being able to figure out why drag and drop wasn't working, and now it works, thanks. Maybe it should be included in the documentation.
