### ISSUE TITLE
[QUESTION] Blur tool on Doka?

### ISSUE THREAD

**Issue by replicat0r** [pqina/filepond#416]
First of all, thank you for all your amazing and hardwork on this project and Doka! It is one of the most intuitive and smooth image editor I have used. Please keep up the amazing work!

I love Doka! but my question is that is there  chance I can hook into the tool section and add a blur tool, or is there plans in the future to extend the editing toolset for doka?

thanks!

**Comment by rikschennink** [comment]
Hi, thank you! 

If you've purchased Doka you can request direct support or ask questions using the [support page](https://pqina.nl/doka/support/)

To answer your question, there are plans but I'm gathering user info first. What would you use the blur tool for?

**Comment by replicat0r** [comment]
Ah my use case if that if they published some sensitive information, they might want to blur it out before uploading the images.

**Comment by rikschennink** [comment]
Okay, so currently this is possible with the rectangle tool (simply place a square over some information), a redaction function is on the roadmap for a future release.
