### ISSUE TITLE
Image does not load properly after Markup on IE.

### ISSUE THREAD

**Issue by lvidrashchuk** [pqina/filepond#418]
Hi Rik!

### Summary
When editing an image using the "Markup" option and clicking on Done Filepond is not able to load the image properly.
...

### How to reproduce
https://pqina.nl/doka/ 
Scroll towards "Optimise Images Before They Hit Your Server" heading.

1. Drag & Drop your image or Browse;
2. Select "Markup"' and choose any of the following (square, circle, text or arrow);
3. Click Done;
4. Observe in Internet Explorer (IE) how image preview is displayed with black background.
...

### Expected behaviour
In Firefox and Chrome image after Markup is displayed correctly. 
...

### Additional information
In Console after Inspecting Elements "Script5007: Unable to get 'length' of undefined or null reference.
...

| Environment  | Version
|------------- | -----------
| OS           | Windows81 (Virtual Box 5.2.34)
| Device       | MacBook Pro
| Browser      | IE11

<img width="1308" alt="Inspect Elements" src="https://user-images.githubusercontent.com/58775139/70630843-2b5ae900-1c24-11ea-92e1-2dde00c32e1c.png">

![Markup on Filepond in IE](https://user-images.githubusercontent.com/58775139/70630864-31e96080-1c24-11ea-8e11-ded3caf7a3e2.png)

Thank you for looking into this in advance.

**Comment by rikschennink** [comment]
It's fixed in FilePond `4.8.1`, now updating the website. Thanks for reporting. 👍

**Comment by rikschennink** [comment]
I'll close this for now, let me know if it's not resolved.

**Comment by lvidrashchuk** [comment]
Hello Rik. Thank you very much for resolving this issue very quickly. Image uploads well now.
