### ISSUE TITLE
Failed to execute 'add' on 'DOMTokenList'

### ISSUE THREAD

**Issue by jenswittmann** [pqina/filepond#423]
### Summary

On empty CSS classes it produces an error.

> Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.

### How to reproduce

Set an empty class name on the input.

```
<input type="file" name="field_8" id="field_8" class="form-control form-control--file " value="" />
```

### Expected behaviour

Filepond shout be init.

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Device       | MacBook Pro
| Browser      | Chrome 79

**Comment by rikschennink** [comment]
Fixed in release `4.9.3` 👍
