### ISSUE TITLE
During "Crop" to a smaller size user can observe an appearance of a new icon.

### ISSUE THREAD

**Issue by lvidrashchuk** [pqina/filepond#430]
### Summary
When editing an image using "Crop" option user can observe an appearance of a new icon in Firefox and IE. 
...
### How to reproduce
https://pqina.nl/doka/;
Scroll towards "Optimise Images Before They Hit Your Server" heading;
1. Drag & Drop your image or Browse;
2. Start cropping the image to a smaller size and move the cropped image around;
Observe how a new icon appears on the screen.
...
### Expected behaviour
For better user experience no new icons appear on the screen after crop.
...
### Additional information
![Screenshot 2020-01-06 at 12 08 00](https://user-images.githubusercontent.com/58775139/71817301-4ed74f00-307d-11ea-964c-5a8c62efdac0.png)

<img width="1479" alt="Screenshot 2020-01-06 at 10 55 03" src="https://user-images.githubusercontent.com/58775139/71817307-526ad600-307d-11ea-97be-bd9fbf0280ba.png">

...
| Environment  | Version
|------------- | -----------
| OS           | Windows81 (Virtual Box 5.2.34)
| Device       | MacBook Pro 
| Browser      |  Firefox Quantum 65.0.1 / IE11

**Comment by rikschennink** [comment]
@lvidrashchuk This is the "keyboard interaction indicator" you can hide this by setting this style:

```css
.doka--image-gl:after { content: none; }
```

**Comment by rikschennink** [comment]
Will close as this is not related to FilePond.
