### ISSUE TITLE
loading 'local' files does not work when server url does contain queryParameters

### ISSUE THREAD

**Issue by pieterdegraeuwe** [pqina/filepond#432]
### Summary
First of all. This is a great library. Thanks for that.

Uploading files to the server (POST to the url, configured with the 'server' option) works ok.
However, loading 'local' files (added with 'files' option during the FilePond.create(). Didn't work. 
The server got the request, but did not get the requestParameter which would contain the serverId.
It took a while before I found the cause:
My sever url is kind of generated AND does contain already some parameters. (and thus also a '?').
It seems that filePond just adds '?load=&lt;serverId>' to the server property, while in this case, it should have added '&load=&lt;serverId>'.

### How to reproduce
Just use a server url with already a parameter in it.
...

### Expected behaviour
add the load query paramter with a '&' prefix instead of a '?' prefix when the server url does already contain a '?'

| WIndows Chrome | Version 4.9.3

**Comment by rikschennink** [comment]
Confirmed, will push a fix next week.

**Comment by rikschennink** [comment]
Fixed in version `4.9.4`
