### ISSUE TITLE
FilesizeBase support were you can set it to 1024 or 1000 to calculate the filesize.

### ISSUE THREAD

**Issue by prince272** [pqina/filepond#434]
Support FilesizeBase that is used to calculate the filesize. In which you can change this to 1024 if you would rather display kibibytes, mebibytes, etc...

**Comment by rikschennink** [comment]
I'm not sure where and why this is needed please elaborate

**Comment by prince272** [comment]
Windows 10 uses 1024. So I'll also like to follow that.

**Comment by rikschennink** [comment]
What values would you like to supply with 1024, chunk size is defined in bytes does this give issues

**Comment by prince272** [comment]
Take a look at this https://www.dropzonejs.com/#config-filesizeBase
It has what I just need.

**Comment by prince272** [comment]
So how do i change it to 1024

**Comment by rikschennink** [comment]
You’d have to edit the src files

**Comment by prince272** [comment]
how. I don't understand.

**Comment by Vang-z** [comment]
> how. I don't understand.

So now you've solved the problem?  This question has puzzled me for a long time.

**Comment by afsharmahmoodian** [comment]
> > how. I don't understand.
> 
> So now you've solved the problem? This question has puzzled me for a long time.

take a look at filepond.js . you will see this part of code : 
`// File size calculations, can set to 1024, this is only used for display, properties use file size base 1000
        fileSizeBase: [1024, Type.INT],`
you need to change fileSizeBase to 1024.

if you are using filepond.min.js , don't forget change it in filepond.min.js.
like this : 
`fileSizeBase:[1024,ge.INT]`

**Comment by rikschennink** [comment]
You can set `fileSizeBase` property to `1024` or `1000` depending on your needs.

```js
FilePond.create(
  document.querySelector('input'),
  {
    fileSizeBase: 1024
  }
);
```

**Comment by laurenskling** [comment]
Found this issue because my client reported Windows having file sizes in the UI that didn't match their expectations. Like mentioned above, this is because Windows calculates by 1024, not by 1000 like macOS. Meaning that a windows user uploading a (for them) 24.9mb (which is MiB) file will result in a error on max 25mb, because they are actually uploading 26.2mb
Setting the `fileSizeBase` helps. But then macOS (and Linux?) will fail. It doesn't really make sense to set it when it is OS depended what you might need. Shouldn't OS detection be a more fit solution?

**Comment by rikschennink** [comment]
@laurenskling I'm not confident making that decision for you, you could set the property yourself based on OS?

**Comment by laurenskling** [comment]
I probably could yes. Just very curious how people have been using this package for so long without ever noticing that Windows shows different filesizes than Filepond does 😅

**Comment by rikschennink** [comment]
@laurenskling I suspect it's just not _that_ important to the user?
