### ISSUE TITLE
Hangs on Firefox 52

### ISSUE THREAD

**Issue by edwh** [pqina/filepond#436]
### Summary

FilePond hangs in uploading state on Firefox 52

### How to reproduce

Use Firefox 52, either natively or via Browserstack.
Go to www.ilovefreegle.org
Click on Give
Enter a UK postcode e.g. PR3 2NX and click Next
Click Add Photos
Click the Browse button
Select a photo file

The entire browser locks at this point.

I haven't done a standalone demo because I think this is probably not related to my code - I see the same thing on https://codesandbox.io/s/github/KimGenius/React-file-pond/tree/master/?from-embed, for example.

### Expected behaviour

File is uploaded and process callback is triggered.  

This works on later versions of Firefox.

### Additional information

I've checked the return from supported(), which returns true.

![image](https://user-images.githubusercontent.com/56696/72893827-eb525000-3d11-11ea-97db-ea72839c95d2.png)

| Environment  | Version
|------------- | -----------
| OS           | Windows 
| Device       | BrowserStack W7 PC
| Browser      | Firefox 52

**Comment by rikschennink** [comment]
Thanks for reporting, not super concerned as Firefox 52 browser share is at 0.015% still, it should detect that this browser is not supported.

**Comment by edwh** [comment]
Yes, I agree it's a very low share browser.  We have a demographic with old kit (that's part of what we're about).  If I could show a message saying it wasn't supported because the browser was old, then they'd understand.

**Comment by rikschennink** [comment]
I just tested this on https://pqina.nl/filepond/ and can't confirm the issue. Revert + Upload works as intended.

![Screenshot 2020-01-28 at 13 18 15](https://user-images.githubusercontent.com/1132575/73263370-b726d580-41d0-11ea-83e8-9cd3949d8cec.png)

**Comment by edwh** [comment]
Which FF version was that? I just tried again using Browserstack FF52/W10, and Firefox still hangs for me on that demo.

**Comment by rikschennink** [comment]
@edwh Firefox 52 on Windows 10, not sure why it hangs when you test it. Happy to test again later this week.

**Comment by edwh** [comment]
Thanks. I don't think it's specific to Browserstack, as I had a report 
from a real end-user on an old PC.

------ Original Message ------

**Comment by rikschennink** [comment]
I retested:

![Screenshot 2020-02-03 at 08 44 34](https://user-images.githubusercontent.com/1132575/73634873-7f9daa80-4662-11ea-81bd-a335893575b9.png)

Result:

![Kapture 2020-02-03 at 8 49 12](https://user-images.githubusercontent.com/1132575/73634877-82989b00-4662-11ea-9c7c-d3d597f958e5.gif)

Maybe I'm doing something wrong?

**Comment by edwh** [comment]
Thanks for your patience.  What happens for you if you try the upload in 
the Demo section lower down?

------ Original Message ------

**Comment by rikschennink** [comment]
It only shows an issue when dropping an image. Seems to be the logic that generates the preview that is causing the issue.

**Comment by edwh** [comment]
Ah, progress.  I get it when browsing and selecting, but it might be the 
same problem.

------ Original Message ------

**Comment by rikschennink** [comment]
Fixed in new release of image preview plugin. Update to `4.6.2` 👍

**Comment by edwh** [comment]
Splendid.  Thanks - I know it's an old version, but it'll make one of my 
users feel surprised and grateful.

------ Original Message ------

**Comment by rikschennink** [comment]
Glad to hear that :-) Please close the issue if you can confirm it's fixed.

**Comment by edwh** [comment]
One quick question - how can I access the support() function via the Vue adaptor?  It uses it internally but doesn't seem to expose it remotely, though I may be wrong.

**Comment by rikschennink** [comment]
@edwh it doesn't currently expose it, a PR is welcome. If there's no `_pond` instance on the object it's not supported. (but this should be in vue-filepond, I believe there's an issue on the repo related to this already)

**Comment by edwh** [comment]
Ok, thanks.  That's unrelated to this one so I'll close it.  Thanks very much for your attention.

**Comment by edwh** [comment]
Did you mean 4.6.2?  That release doesn't seem to exist.  4.6.1 exists and is recent, but I just tried that using the _pond property, and that still exists on FF 52.

(Sorry to be a pain.)

**Comment by rikschennink** [comment]
It's this plugin that was updated: https://github.com/pqina/filepond-plugin-image-preview

**Comment by edwh** [comment]
Yes, I updated that plugin to 4.6.1, which seems to be the most recent - I assume 4.6.2 above was a typo.

 Then I tried to check if it was supported by testing the _pond property, which is the workaround suggested in https://github.com/pqina/vue-filepond/issues/136 as a way of dealing with the absence of supported().  

On FF52 that property still exists.  Am I doing the wrong thing (apart from, obviously, not providing a PR to expose the supported() method)?

**Comment by rikschennink** [comment]
Sorry yes, should be `4.6.1` indeed.

**Comment by rikschennink** [comment]
The Image Preview plugin has been updated in order to fix the issue so it should now render a preview on Firefox 52 without issues.

**Comment by edwh** [comment]
I'm sorry, I misunderstood.

When I test using 4.6.1 I still get the same hang, though.

(I'm getting a bit annoying at this point - shall I stop?)

**Comment by rikschennink** [comment]
No worries. That's weird, it worked in my test case, maybe test it in isolation (please note I haven't updated the FilePond product page yet).

I can't retest this for now.

**Comment by edwh** [comment]
I still see the same hang using the demo at https://pqina.nl/filepond/ .

I'll let you get on with something more important for a bit :-).

**Comment by rikschennink** [comment]
That's to be expected as it doesn't use the new version of the image preview plugin.

**Comment by edwh** [comment]
Ah, I see.  I still see the problem on my code using the updated preview plugin.

But as I say, this is getting to the point where it's a waste of your time.  Thanks, though.
