### ISSUE TITLE
Can't load remote url via files attribute in vue js

### ISSUE THREAD

**Issue by RjRana** [pqina/filepond#44]
```html
<file-pond
    allow-multiple="false"
    name="upload"
    ref="pond"
    drop-on-page="true"
    label-idle="Drop files here..."
    :files="uploadedFile[0].source"
    @addfile="onFilePicked()"
    @removefile="removeFile()"
    @init="handleFilePondInit"/>
```

```js
uploadedFile: [
    {
        source: this.getRemoteUrlforEditing,
        options: {
            type: 'remote'
        }
    }
]
```

`this.getRemoteUrlforEditing` computed property is giving me the remote URL. but filepond giving me 400 error everytime .. i have configured everything successfully.  but can't figure out this issue

**Comment by rikschennink** [comment]
@RjRana The `files` property expects an array, it looks like the `this.getRemoteUrlForEditing` is a reference to a function. Are you sure you shouldn't be running the function `this.getRemoteUrlForEditing()`?

**Comment by maverickpravin** [comment]
@RjRana any work around on this ?

**Comment by phiter** [comment]
@rikschennink `getRemoteUrlForEditing` being a computed property, it should not be called as a function. In Vue, it becomes a normal object property.

I'm getting the same error 400 issue and I don't know how to solve it.

**Comment by rikschennink** [comment]
@phiter If it's a URL the URL is passed as a string to FilePond. Updating the URL afterwards doesn't update it in FilePond, you'd have to pass a new "array" of values to the `:files` property.

**Comment by phiter** [comment]
@rikschennink I tried using  `.addFile` but I get "cannot load URL" error.
I had to use axios to fetch the image and convert it to blob to use addFile, then it worked, but now I have cors issues.

**Comment by christopher4lis** [comment]
Don't think this should be closed, even on the referenced issue, the problem isn't fully solved. Multiple people are having issues loading images from S3, even with CORS options set.

Is there any solution to this with an exact solution in the docs?
