### ISSUE TITLE
Animations choke upload performance; modifying animations increases performance but breaks uploading unpredictably

### ISSUE THREAD

**Issue by tobias7an** [pqina/filepond#441]
### Summary

We are using filepond and react-filepond in a webapp in which users occasionally need to upload hundreds of files at a time, and experience severe performance issues, characterized by the following patterns:
- CPU use maxes out from the point the files are added, and remains substantial the entire period, even during idle
- Browser framerate drops substantially and the page may become unresponsive
- Multiple users have reported chrome "aw, snap" crashes and script timeout warnings
- Several minutes can pass before the first batch of uploads (as specified using max concurrent) begins. Uploads complete quickly, after which filepond becomes unresponsive again. It can be a long wait, multiples of actual upload durations, before the next batch of uploads begins.

To diagnose the issue and increase performance, we have attempted several things:
- We added display: none to the root element, and add files via dropping onto the page. The browser framerate improves, but uploads still experience long pauses between network activity.
- We ran performance profiling in chrome devtools. A screenshot example is below. The animations processes, coupled with the large number of DOM nodes spawned, was found to be responsible. The deep orange boxes are the function requestTick and Tick. The red tags on them are performance warnings from the profiler. 

![Performance profiler](https://i.imgur.com/yrgonK8.jpg)

- We went into the dist JS file and manually removed all animation mixins. However, filepond items stopped loading. 
- We changed all "spring" animation mixins to "tween" with with duration of 1 for translate, transform and opacity styles. When we did this, performance greatly increases, FPS and responsiveness returns to normal, and there is minimal delay between network uploads. However, strange behaviour occurs that we have been unable to trace, hinting at the upload and render processes are dependent on the animation process:
-- Filepond items visually stop loading partway. Adding an interval timer function that forces filepond to refresh by modifying files will correct the visual appearance at the triggered intervals.
-- Uploading halts randomly and does not resume partway through the queue. This was a deal breaker in the attempted workarounds.

- In summary, a combination of display: none and duration: 1 animation mixins is the closest we get to the expected behaviour of continuous uploads with no long pauses between uploads. The solution of minimizing animations or disabling them seems very feasible. But the uploading queue itself breaks. If the cause of that can be identified and fixed, I can proposed a PR.

...

### How to reproduce

1. Add several hundred ~1mb pictures or files to filepond.
2. Add display:none to filepond--wrapper to isolate css/render-based factors.
3. Open Chrome devtools and run performance profiling. Note large gap between uploads consisting of animation scripting and high CPU usage.
4. Switch all animation mixins to {type: tween, duration: 1}, and run performance profile again for contrast. Observe for halt in upload process.

...

### Expected behaviour

- Uploads should be prioritized over animations. New uploads in the queue should immediately begin when the previous ones complete, instead of idling at high CPU while animation processes grind through updating properties on thousands of DOM objects. 
- Actual upload behaviour should not be coupled to view animations; modifying animations should not break uploading.
- The option to disable animations is a highly attractive option so filepond can be optimized for two major user groups:
-- Users uploading large numbers of files
-- Users on older or smaller devices with weaker CPUs

...

### Additional information

This issue is reported on the latest versions of filepond and filepond-react.

...

| Environment  | Version
| OS           | Users report this behaviour on Windows 10, Mac OS 10, and multiple flavours of Linux.
| Browser      | Users report this behaviour on latest versions of Chrome, Firefox, Edge and Safari.

**Comment by rikschennink** [comment]
Hi, at the moment FilePond is entirely driven with `requestAnimationFrame`, uploads are also bound to the draw loop (picking up the next upload can only be done when the view is redrawn). 

This is not ideal and might be the cause of the gaps you're seeing.

That said. With all the animation that is going, FilePond is simply not suitable for these huge amounts of files (in this case "several hundred 1mb pictures or files", not sure if you're also rendering previews?).

I will address this in a future version of FilePond, but for now this is not something that can be "fixed" easily. FilePond is great for smaller numbers of files, but if you need to upload 100s I'd consider either spreading them across multiple pages or using another library or using a custom upload solution.

**Comment by DavidRouyer** [comment]
@rikschennink It would be nice if we could toggle the animations on and off. I'm thinking of accessibility and low battery/low powered devices scenarios.

**Comment by rikschennink** [comment]
@DavidRouyer For sure, any input is welcome. I think the best approach would be swapping the spring / tween animation objects with objects that instantly jump to the target value.

I think this file would be the place to do that: https://github.com/pqina/filepond/blob/master/src/js/app/frame/utils/createAnimator.js

Both animators expose this API

```js
{
    interpolate,
    target: {
        // setter
        // getter
    },
    resting: {
        // getter
    },
    onupdate: value => {},
    oncomplete: value => {}
}
```

I think the biggest challenge is somehow getting the "should I animate" property to the `createAnimator` function.

**Comment by tobias7an** [comment]
@rikschennink Following your instructions, I've been testing out an implementation that replaces all animations with an animation object that, like you suggested, jumps to the target value. Performance increased tremendously. 

However, there remain a strange artifact I need help understanding:
- The processing of files to upload randomly pauses. Network traffic drops to zero. 
- Also randomly, at a variable amount of time after the pause, processing resumes.
- Also randomly, at a variable amount of files processed, the processing never resumes. 
- When processing is unexpectedly indefinitely halted, window.requestAnimationFrame(tick) is still firing every ~45ms interval. 
- After halting, calling this.pond.processFiles() has no effect.
- Adding additional files has no effect.
- I have not found a way to un-freeze processing besides completely reloading the page.

Any clues as to what might be causing processing to stop unexpectedly?

**Comment by tobias7an** [comment]
I couldn't find out what was causing the breaks in the upload queue, but I'd like to share a successful workaround for upload performance issues in my use case, specifically slow uploads in queues of 100s of files caused by long delays between each file upload process. The solution basically decouples the uploading processes from whatever cycle/timer Filepond was using to trigger uploads, and manages it in a separate queue.

My approach consists of a separate upload POST function, wrapped by the Bottleneck package (https://www.npmjs.com/package/bottleneck) for concurrency and flow control, provided to the filepond server prop as custom process function. I also set set maxParallelUploads to a very high number like 9999. The combination of this means that when an upload of hundreds of files is started, Filepond begins processing for all of them simultaneously, which Bottleneck manages and queues separately while Filepond itself carries on with its severely-overloaded animation tasks. The visual appearance suffers substantially, but the actual uploads can proceed independently at a faster rate, limited by CPU load rather than the internal animation/trigger cycle. (@rikschennink kudos for building in so much flexibility to the server API that highly customized workarounds such as this can be achieved!) 

Ideally, the CPU load can still be cut down drastically with the jump-to-target animation modification specified above in order to cater to low-performance/power devices, while the use of the alternative queuing avoids the random upload halts otherwise experienced as a side effect of modifying the animation. Just gotta figure out how to pass in that disableAnimation prop...

**Comment by rikschennink** [comment]
@tobias7an thanks for the detailed tests you're running. I currently don't have a lot of time to dig into this but here's some input: 

- The `requestAnimationFrame` is always active running, only stops running when the window loses focus, doesn't cost much CPU time to run (would be better if it paused, I believe there's an issue on this)
- I think the "random" things you mention might be related to the action loop freezing, if there's no more actions to run, FilePond will start idle-ing, dispatching a single action will then "boot" it up again. I usually call these "KICK" so `dispatch('KICK')`, not sure, but that might help.

This is all very experimental and impacts the inner workings of FilePond so I'm not surprised it doesn't work in one go. Also, you're still pushing a lot of files so not sure if that is related. I'd test with less files first.

**Comment by rikschennink** [comment]
Uploading in background should now be improved, changed require might also resolve some of the issues reported when animations are removed.

**Comment by snapey** [comment]
I was hoping to use this for uploading batches of very small (2K) XML files but the delays between uploads unfortunately makes this unworkable.

**Comment by rikschennink** [comment]
@snapey By default each file item will (if the upload takes shorter than 750 ms) "simulate" a longer upload so the user can actually see the upload happen (instilling trust the data is sent), instead of it instantly being done. While this works nicely for a couple files, it isn't perfect for lots of small files, I'll look into adding an option to disable this feature.

**Comment by rikschennink** [comment]
@snapey Just published version 4.27.0 which adds the `allowMinimumUploadDuration` option, set to `false` to disable perceived performance wait time. This will speed up uploading of files.

**Comment by rikschennink** [comment]
Closed because inactive.

**Comment by vesper8** [comment]
I'm also experiencing huge drops in performance when uploading just 4 files simultaneously.

Very interested in your approach @tobias7an, were you able to replace all animations by faster ones without forking the package? Any chance you could share your code.

I'm also going to try using `allowMinimumUploadDuration` to see if it helps.

I agree it should be simpler to disable or reduce animations.

**Comment by rikschennink** [comment]
@vesper8 I wonder if the drops in performance also happen in isolation, for example in a reproduction on https://codesandbox.io or that this is a result of two or more scripts running together and causing these slowdowns. I cannot reproduce this locally.
