### ISSUE TITLE
Disable onactivatefile callback when dragging/reordering

### ISSUE THREAD

**Issue by tomhorvat** [pqina/filepond#444]
Hi!

Thanks for the library!

Would it be possible to disable onactivatefile callback when dragging uploaded files to reorder?

I have onactivatefile callback to prompt for file metadata and that gets triggered on dragend.

![onactivatefile](https://user-images.githubusercontent.com/7021695/73955269-5f404b00-4903-11ea-9e12-05eaa0f0c234.gif)

**Comment by rikschennink** [comment]
@tomhorvat goon one, I'll see if I can fix this next week.

**Comment by tomhorvat** [comment]
Thanks!

**Comment by rikschennink** [comment]
@tomhorvat Should be fixed in `4.11.0`

**Comment by tomhorvat** [comment]
@rikschennink Fixed it! Thanks again!
