### ISSUE TITLE
Valid file type not dropped when dropValidation enabled

### ISSUE THREAD

**Issue by helmi-pts** [pqina/filepond#448]
Hi Rik,

**Summary**
I'm using dropValidation to avoid non valid files added to filepond input.

Based on documentation, only invalid files are not dropped. But in my case, if i drop multiple files with one being invalid, all the files will not dropped.

HTML
`<input type="file" class="filepond" name="filepond" accept="application/pdf,image/jpeg" multiple required>`

Script
`FilePond.registerPlugin(FilePondPluginFileValidateType);
	$('.filepond').filepond({
		dropValidation: true
	})`

| Environment  | Version
|------------- | -----------
| OS           | Windows 
| Browser      | Firefox 73

**Comment by rikschennink** [comment]
It'll validate the entire set of files, so if one file is invalid it'll discard the entire selection.

**Comment by rikschennink** [comment]
closed because inactive for 12 days

**Comment by asa108** [comment]
I wondered if there is a way to show a validation message when user uploads files that include the invalid file types?
