### ISSUE TITLE
Images overlapping and going out of the div boundaries. 

### ISSUE THREAD

**Issue by Whateverinc** [pqina/filepond#449]
For some reason when you drop more than 2 images the uploader background does not resize, and some images overlap. I am using the latest version of google chrome, on mac os. 

![Screen Shot 2020-02-17 at 12 13 18 AM](https://user-images.githubusercontent.com/8814394/74628189-993af980-511a-11ea-8039-78cbf401441b.png)

**Comment by rikschennink** [comment]
See note below the grid layout CSS example
https://pqina.nl/filepond/docs/patterns/api/style/#grid-layout
