### ISSUE TITLE
Browser Droping down on all devices when I uploading file(video) ~100mb and more

### ISSUE THREAD

**Issue by alexander-v-ysbm** [pqina/filepond#45]
Browser Droping down on all devices when I uploading file(video) ~100mb and more
maybe somebody can help

**Comment by rikschennink** [comment]
@alexander-v-ysbm I'm sorry but it's not clear to me what problem you're experiencing, please try to clarify. Additional information like error messages, code samples, browser names and versions are very helpful. The more effort you put in describing the issue the more willing people are to help you out.

**Comment by rikschennink** [comment]
@alexander-v-ysbm If this is about uploads of big files failing you could try this => https://github.com/pqina/filepond/issues/48

**Comment by alexander-v-ysbm** [comment]
@rikschennink Hi, sorry for long reply, for some reason when my users load files more that ±100mb browser freezing down(I have use it for upload videos on server) iPhone(safari) MacBook, Ubuntu(firefox), 
I have already resolve this problem using another uploader with chunk upload process, I saw that your uploader will be use it chunk upload at future 👍 . It will be interesting to use it in another project. 
Thx for your work!

**Comment by rikschennink** [comment]
@alexander-v-ysbm Thanks for the update! Glad to hear you've found a working solution. :-)

Hope to be able to add chunk uploading soon.
