### ISSUE TITLE
Changelog for plugins?

### ISSUE THREAD

**Issue by kylefox** [pqina/filepond#450]
I know there's a changelog for the `filepond` package, but I'm wondering how (if at all) that applies to the various Filepond plugins.

For example, in our app when I run `yarn outdated` I see this:

```
Package                            Current       Wanted        Latest
filepond                           4.9.3         4.11.0        4.11.0
filepond-plugin-image-preview      4.5.0         4.6.1         4.6.1
filepond-plugin-image-transform    3.5.1         3.7.1         3.7.1
```

[filepond/CHANGELOG.md](https://github.com/pqina/filepond/blob/master/CHANGELOG.md) lists the changes for the `filepond` package, but I'm not sure how to figure out what's changed in `filepond-plugin-image-preview` and `filepond-plugin-image-transform`. The plugin repositories do not have changelogs or release descriptions.

Is there something I'm missing? Or do you have a recommended approach for performing these upgrades?

Thanks!

**Comment by rikschennink** [comment]
You'd have to check the plugin commit history, plugins currently don't have an individual changelog. I understand that's not ideal but haven't gotten around to it.

**Comment by kylefox** [comment]
Understandable, just wanted to make sure I wasn't missing something 👍
