### ISSUE TITLE
Filepond behaves strangely in Chromium even though I have <!DOCTYPE html>

### ISSUE THREAD

**Issue by Evertt** [pqina/filepond#451]
The "strange" behavior is that it starts out having a weird height, and when I add files it never increases in height in order to show the added files.

But it acts normal in Safari, surprisingly enough.

I've seen that this question has been asked before a few times already and every time the answer seemed to be to put `<!DOCTYPE html>` at the top of the page. Well in my case that's already there, so now I don't know what the problem could be.

It does behave well in Chromium on the examples page on your website, so I'm definitely doing _something_ wrong...

### small update

I just experimented with _removing_ `<!DOCTYPE html>` and then it definitely behaves differently, but not much better or worse actually. It's still kinda the same, i.e. it's functional in Safari, but not really in Chromium.

**Comment by rikschennink** [comment]
Hi, please provide a publicly accessible test case, codesandbox.io is super useful for this.

**Comment by Evertt** [comment]
But on SO nobody responds to these questions. :-(
If you'd be willing to spend 5 minutes on it I'd be super grateful!
http://devign.nl/laf.htm

(I couldn't use CodeSandBox, because for some weird reason I can't minify my scripts at the moment.)
