### ISSUE TITLE
Drag'n'Drop reorder not working with Safari 10.1 MacOS

### ISSUE THREAD

**Issue by jwsinner** [pqina/filepond#452]
We've received a couple of complaints that reordering is not working on Safari 10.1 on MacOS. It was working relatively recently but for some reason it seems to have stopped. I've attached a basic project that I've confirmed works on Chrome and Firefox but not Safari. I'm at a loss for how to begin debugging the issue, especially since I'm working on a Windows machine. Any help would be greatly appreciated.

[filepond-test.zip](https://github.com/pqina/filepond/files/4257347/filepond-test.zip)

**Comment by rikschennink** [comment]
See https://github.com/pqina/filepond/blob/master/CHANGELOG.md#490

> Limited to browsers supporting Pointer events.
