### ISSUE TITLE
onaddfileprogress doesn't seem to work

### ISSUE THREAD

**Issue by avillarubia** [pqina/filepond#453]
Hello fellow developer!

### Summary
**onaddfileprogress** doesn't seem to work.

I am watching when the file is added and the animated circle starts running so the upload button must be disable that time. Until it the animation stops then that's the time the upload button is clickable for upload.

Good day I am using this on react.
...

### How to reproduce
```js
<Uploader
            onaddfileprogress={(file, progress) => {
                console.log(file, progress) // never print out any of the two
            }}
            ref={ref => pond = ref}
            file={files}
            allowFileSizeValidation={true}
            maxFileSize="50mb"
            instantUpload={false}
            name='items'
            allowMultiple={false}
            allowFilePoster={true}
            onupdatefiles={fileItems => setMetadata(fileItems)}
            oninit={handleInit}
            onprocessfile={(error, file) => {
                if (file && file.serverId)
                    dispatch(setFileProp({ filenameExt: file.serverId }))
            }}
            onprocessfileprogress={(file, progress) => {
                if (file && file.status)
                    dispatch(setFileProp({ isUploading: file.status === 3 }))
            }}
            labelIdle='Drag & Drop files or <span class="filepond--label-action">Browse</span>'
            server={`${apiBaseUrl}api/uploads/`}
        />
```

only onaddfileprogress is my concern
...

### Expected behaviour
I am expecting that it works like onprocessfileprogress, I guess it will updates in real-time until the animated circle stops.
...

### Additional Details
```js
    "react": "^16.12.0",
    "filepond": "^4.9.2",
    "filepond-plugin-file-encode": "^2.1.4",
    "filepond-plugin-file-poster": "^2.2.0",
    "filepond-plugin-file-validate-size": "^2.2.0",
    "filepond-plugin-file-validate-type": "^1.2.4",
    "filepond-plugin-image-exif-orientation": "^1.0.6",
    "filepond-plugin-image-preview": "^4.5.0",
    "filepond-plugin-image-resize": "^2.0.4",
```

| Environment  | Version
|------------- | -----------
| OS           | Windows 10 (64-bit)
| Device       | Desktop 
| Browser      | Google Chrome  79.0.3945.130 (Official Build) (64-bit)

**Comment by rikschennink** [comment]
`onaddfileprogress` should fire when loading URLs, it doesn't file when loading file objects

**Comment by avillarubia** [comment]
@rikschennink I see and thank you for fast response
