### ISSUE TITLE
Initial Files Are Uploaded Again

### ISSUE THREAD

**Issue by clikader** [pqina/filepond#455]
### Summary

Hi! I am currently building a form where users can enter information and upload related files. When the user opens an existing form record, I am setting initial `files` so that all previously uploaded files will be shown and files can be reordered, however loading initial files will make filepond upload them again so if the user refreshes the page or modify the form multiple times we end up having many duplicated files on the server. 

Was this intended or is there a way to disable this feature?

### Info about the app
Filepond version:  `4.11.0`
Web framework: `Django 3.0` (unrelated to the question but that's why my JS code looks a bit different)

### Filepond Config

```javascript
FilePond.setOptions({
    files: [
        {% for file in userFiles reversed %}
            {
                source: '{{ file }}'
            },
        {% endfor %}
    ],
    acceptedFileTypes: [
        'application/pdf',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'image/tiff',
        'image/png',
    ],
    name: 'file',
    server: {
        headers: {
            'X-CSRFToken': getCookieValue('csrftoken')
        },
        process: {
            url: '/api/upload/',
            method: 'POST'
        },
        revert: null,
        fetch: null,
        load: null,
        restore: null,
        remove: null,
        patch: null,
    },
    labelIdle: 'Drag & Drop pdf/doc/tif files or <span class="filepond--label-action">Browse</span>',
    required: true,
    allowMultiple: true,
    allowReorder: true,
    dropOnPage: true,
    dropOnElement: false,
    onactivatefile: (file => previewAttachment(file))
});
```

where `userFiles` is a list of urls such as
```python
userFiles = [
    '/media/files/20200131/beb779a7187d438f/check_list.pdf',
    '/media/files/20200131/1sdf6fghw2d1g6bd/task_list.pdf'
]
```

Thank you!

**Comment by rikschennink** [comment]
You need to set the type of the files as well.

```js
const pond = FilePond.create({
    files: [
        {
            // the server file reference
            source: '12345',

            // set type to local to indicate an already uploaded file
            options: {
                type: 'local'
            }
        }
    ]
});
```

https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

**Comment by clikader** [comment]
Hi @rikschennink Thanks for your reply! I have tried all three acceptable `types` for `options` but none of them worked. Please see the image for error. I have a function assigned to `onactivatefile` so that when I click on the uploaded file, another tab will be opened to preview it. When I am using the local type, I can still preview the image even it gives me the error, so I am pretty sure it's not the source issue.

![image](https://user-images.githubusercontent.com/5997214/75695412-a0601c80-5c6f-11ea-9d85-6052220c3b3c.png)

Thanks!

**Comment by rikschennink** [comment]
It looks like you've not configured the `server.load` or `server.restore`end points so FilePond can't load the file data.

I'll close this issue as it's most likely a configuration issue.
