### ISSUE TITLE
[Concern] Transferring questions to stackoverflow

### ISSUE THREAD

**Issue by avillarubia2** [pqina/filepond#456]
Good day @rikschennink 

Recently I was able to post questions here and the answers are like instant. But now, when you want questions to be raised in stackoverflow as I observe the answer is not that fast. I was posting like 2 days ago in stackoverflow but until now no questions arrive compare posting questions here in github can be answered quickly.

My suggestion is I guess it is better to post question in stackoverflow and we can post also here in github by just providing a link from stackoverflow question. In this way the answer is faster than the current way.

What do you think @rikschennink ?

**Comment by rikschennink** [comment]
To keep things organized the GitHub repository issues page is for bug reports/feature requests separate from your specific implementation. 

While I’m sure it’s handy if you receive quick support, the support you receive is free of charge and therefor can take some time.

I monitor both GH and SO for entries related to FilePond. If the issue/question is well formed, shows effort (and features a test case) I usually reply within a workday.
