### ISSUE TITLE
Can't click and browse when stylePanelLayout set to compact

### ISSUE THREAD

**Issue by kyle-mccarthy** [pqina/filepond#459]
### Summary

When the stylePanelLayout setting is set to compact, the user cannot click to browse for files. The default, integrated and circle setting values work as expected. 

It looks like this is due to `filepond--list-scroller` class having a 100% height and a higher z-index value than the `filepond--drop-label` class. When using the integrated option, the height for `filepond--list-scroller` is also 100%, [but the z-index is set to be higher (set to 7)](https://github.com/pqina/filepond/blob/master/src/css/modifiers.scss#L26).

### How to reproduce

Repo: https://github.com/kyle-mccarthy/filepond-compact-bug
Live: https://filepond-compact-bug.kmccarthy.now.sh/

### Expected behaviour

Clicking the label should open the file browser.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS 
| Browser      | Chrome

**Comment by rikschennink** [comment]
Should be fixed in v4.12.1
