### ISSUE TITLE
AngularJS Component

### ISSUE THREAD

**Issue by johnnyasantoss** [pqina/filepond#46]
Hey! Just for letting you know that I made a AngularJS Component for FilePond (inspired by the other Angular Component) :)
I still need to do some tests, so there might be errors :)
If you are interested you can check it out [here](https://github.com/johnnyasantoss/angularjs-filepond).

**Comment by rikschennink** [comment]
@johnnyasantoss Waw! Thanks so much! 

I don't have a lot of experience with Angular but will surely take a look this week.

**Comment by rikschennink** [comment]
By the way, if you've got some ideas on how to best set up the [other angular adapter](https://github.com/pqina/angular-filepond/issues/1), I'm all ears! :-)

**Comment by johnnyasantoss** [comment]
I'm not much familiarized with Angular and it's AOT compilation system, so I think that I might not be a really good help hehe :sweat_smile: but I would like keep helping with the AngularJS adapter :)

**Comment by rikschennink** [comment]
@johnnyasantoss No worries! 😊 Keep being awesome! I'll close this issue and add a link to your repository to the readme.
