### ISSUE TITLE
How to save image with PHP?

### ISSUE THREAD

**Issue by vgavrilovikj** [pqina/filepond#461]
I have included the javascript in my project and FilePond works great on the FrontEnd, as you can see below:
![image](https://user-images.githubusercontent.com/29601489/76217870-84322180-6213-11ea-9f65-38e70442f08a.png)
 Here is the code in my HTML:
<input type="file" class="filepond" name="filepond[]" data-max-file-size="2MB" data-max-files="1" required>

When I submit the form this is what I get for filepond:
![image](https://user-images.githubusercontent.com/29601489/76218010-bc396480-6213-11ea-9a20-2362dcc2408e.png)

Now, how can I save the image to a folder, let's say: C:/temp/?

I know that I have to decode because the data is base64 encoded, here is my PHP so far, with decoded format:
$filepond = $_POST["filepond"];
$json_decoded = json_decode($filepond[0], true);
var_dump($json_decoded);

and this is what I get from the decoded format:
![image](https://user-images.githubusercontent.com/29601489/76218176-09b5d180-6214-11ea-91a7-fd20dae5f293.png)

Could you please tell me what should I do next in order to save the image in a folder and in a MySql DB? Thank you very much!

**Comment by rikschennink** [comment]
👉 https://github.com/pqina/filepond-server-php

**Comment by vgavrilovikj** [comment]
Dear,

I am aware of the link you sent me but there is not a single good guide on how to use it!!! That it why I opened the question.. So, can you please explain me? Thank you in advance.

Yours Sincerely,
Viktor

**Comment by rikschennink** [comment]
@vgavrilovikj As stated in the issue template, please ask questions on SO:

> 🧠 If you have a question, please ask it on StackOverflow -> https://stackoverflow.com/questions/ask?tags=filepond
