### ISSUE TITLE
[typescript] onload function has no response param

### ISSUE THREAD

**Issue by nicolasrhc** [pqina/filepond#462]
I am using filepond with react and typescript.
I want to configure the server to be able to capture the file id in the onload function, but the function does not receive any parameters.

In the official documentation it says that it is the place where I have to do it, and the function is called with the parameter
![documentacion](https://user-images.githubusercontent.com/15108965/76327686-96cb5a00-62ea-11ea-9633-ede497644b95.PNG)
![codigo](https://user-images.githubusercontent.com/15108965/76327705-9b900e00-62ea-11ea-8956-d76ec851ed29.PNG)

But I can't use it since my function doesn't receive parameters, although it says that it is the function that I have to use
![visual](https://user-images.githubusercontent.com/15108965/76327923-eca00200-62ea-11ea-9406-959c253f4dd6.PNG)

| Environment  | Version
|------------- | -----------
| OS           | Windows 
| Browser      | Chrome

**Comment by rikschennink** [comment]
Feel free to submit a PR to add the parameter

**Comment by rikschennink** [comment]
Has been added by PR
