### ISSUE TITLE
Upload empty folders (Folder Object)

### ISSUE THREAD

**Issue by EthosData** [pqina/filepond#463]
We have integrate FilePound in our web application to use it for our drag&drop upload feature. 

It is working great after you added the relative path for the files (issue #443). However we are having problems when uploading empty folders (this is something that in our use case will need).

I know the plugin does not have any Folder object, but do you know if it would be reasonable to add? with this, the plugin will be 100% useful for content drag&drop upload to be used by web applications; so users can upload folders structures.

It would be great a great help!

David.

**Comment by rikschennink** [comment]
Hi, I'm not sure, happy to accept a PR, or suggestions on how we could do this.

**Comment by EthosData** [comment]
Thanks Rik.

Maybe another approach for this to explain better what we are looking for:

The plugin return the files with their metadata and relative path so, for example, if we drop a folder structure like this:

FOLDER_A/SUBFOLDER_A/File_a.txt
FOLDER_A/File_b.txt
FOLDER_B/File_c.txt

In our application we can recreate the folder structure and upload the files in their folders.

However if we try to drop a folder structure that has any empty folder like this:

FOLDER_A/SUBFOLDER_A/File_a.txt
FOLDER_A/SUBFOLDER_B/
FOLDER_A/File_b.txt
FOLDER_B/File_c.txt

Our application will not know anything about SUBFOLDER_B because it is not sent by the plugin.

Looking at the plugin, one idea could be is if there is a way for the plugin to capture and send the relative path even if the object file is empty (no file). By this way, in the example above, our application will get a relative path without object file and we will know this is an empty folder to create. 

We were checking the code where we could modify this and return the relative path of empty items (like in the code below), but we are not sure where to look at.

```
var getItemByQuery = function getItemByQuery(items, query) {
  // just return first index
  if (isEmpty(query)) {
    return items[0] || null;
  }
  // query is index
  if (isInt(query)) {
    return items[query] || null;
  }
  // if query is item, get the id
  if (typeof query === 'object') {
    query = query.id;
  }
  // assume query is a string and return item by id
  return (
    items.find(function(item) {
      return item.id === query;
    }) || null
  );
};
```

**Comment by rikschennink** [comment]
It's this method: https://github.com/pqina/filepond/blob/master/src/js/app/utils/requestDataTransferItems.js#L93

I think the only approach is to extract all the file items (items that can be uploaded), this already happens, and at the same time build a separate directory tree and send that to the server as file metadata. Still that would mean the tree is attached to each file, which would also be kind of strange.

**Comment by JaimeBtab** [comment]
Actually what we wanted to achieve is reading the empty folders and pass it to plugin and server to create internally the structure in our application. Would we have to manage the folder item as file item and pass it to plugin as an empty file or something?

FOLDER_A/SUBFOLDER_B/  -> empty folder

**Comment by rikschennink** [comment]
Will close for now, if more devs want to upload empty folders I’ll reopen

**Comment by kevinexxas** [comment]
We also need this feature... 

This is the only thing filepond is missing currently ...

**Comment by rikschennink** [comment]
@kevinexxas happy to accept code suggestions, please don't create additional tickets.

**Comment by savaseso** [comment]
+1 also need this feature

**Comment by bolivar-amancio** [comment]
+1 also need this feature

**Comment by rikschennink** [comment]
adding this in v5 https://twitter.com/rikschennink/status/1541689231159984130?s=20&t=EAejkjIb9Ppki6R-pPW8Fg

**Comment by avillegasfdz** [comment]
Hi! We are very excited about this and other v5 features. Do you have any updates on the planned release date? Thank you!

**Comment by rikschennink** [comment]
I do not, it's ongoing.

**Comment by butera-simone** [comment]
+1 looking for a way to do this right now
