### ISSUE TITLE
UI halt when moving to different browser tab

### ISSUE THREAD

**Issue by EthosData** [pqina/filepond#467]
Hello!

I have notice that while uploading via the plugin, if I go to another tab and then come back after some time, the upload stopped the moment I went to another tag and resume as soon as I went back.

I can see this issue was happening in the past looking at closed ticket #239.

I am using I am using the last version 4.11.0 of plugin and it is happening in Chrome and Edge.

Does anyone also see this? maybe after a recent change, the issue is happening again?

Thanks.

**Comment by rikschennink** [comment]
Hi, thanks for reporting, please use the closed issue. Will reopen if confirmed.

Latest is 4.13
