### ISSUE TITLE
Custom chunks upload

### ISSUE THREAD

**Issue by Lori0107** [pqina/filepond#468]
### Summary
Hi Everyone,

I'm using Filepond with VueJS and Ruby on Rails to create a video uploader, I'm using chunks to upload it. I would like to make my chunks upload "resumable".
So, I have 2 questions:

Is it possible to send additional custom parameters on the initial POST which initialize the chunks upload (for instance: send the Filename), and not only the [Upload-Length] parameter ?

From my Server-side, instead of sending back a plain text response only with the ID Filepath, can I send a JSON response like : { id: my_id, UploadOffset: value ( default 0 ) } ?
Like so, Filepond can use the UploadOffset params to start the upload of my file according to the UploadOffset value.

Here is my Filepond component configuration:

```
import vueFilePond, { setOptions } from 'vue-filepond';
setOptions({
  chunkUploads: true,
  chunkForce: true,
  server: {
    url: "/uploads",
    headers: {
      'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content'),
    },
    process: {
      method: 'POST',
    },
  }
});
const FilePond = vueFilePond();
```

Do not hesitate to tell me if something is not clear, thanks in advance for your help :)

Lori

**Comment by rikschennink** [comment]
Duplicate of https://github.com/pqina/vue-filepond/issues/140
