### ISSUE TITLE
allowReorder does not change DOM order

### ISSUE THREAD

**Issue by vjanssens** [pqina/filepond#469]
### Summary
When setting `allowReorder: true` and after drag/dropping, the order of images in the filepond instance are visually changed by using CSS transforms instead of actually changing the order of the DOM elements. When you try to process the form after it has been submitted using a PHP back-end, the files enter the application in the order of the DOM elements (as is usual with regular HTML forms). Unfortunately, this makes it impossible to know in which order the user intended to upload the images.

### How to reproduce

1. Create a filepond instance with `allowReorder: true`
1. Upload two files
1. Re-order the files by moving the bottom file above the first file
1. Check with devtools the order of the DOM elements. The image that was dragged above the first image is still second in the DOM.

### Expected behaviour

I expected the DOM order to be changed after re-ordering the images. When processing the files in the back-end, order of images can be deduced by the hidden input fields were send to the back-end.

**Comment by vjanssens** [comment]
I just found #465, which resolves this issue. Closing this ticket.

**Comment by jacintofleta** [comment]
Hello, I'm having the same issue, I followed #465 but I can't get how to solve this. Could you show me your solution? Thank you.

**Comment by vjanssens** [comment]
Update of filepond solved this issue. Try to reorder the images _before_ submitting the form, as #505 is still a bug.
