### ISSUE TITLE
Same name for thumb and original

### ISSUE THREAD

**Issue by fundup** [pqina/filepond#470]
I tried to process an upload with original file and thumbs (using imageTransformVariants) but it seems that filenames are all the same on my request. 
So on my server I can't retrieve the differents files (only the first one).
![Capture du 2020-03-20 17-13-39](https://user-images.githubusercontent.com/4673348/77183174-38626080-6ace-11ea-8453-b125732fdaee.png)

**Comment by rikschennink** [comment]
Article on transform variants:
https://dev.to/pqina/generating-image-thumbnails-in-the-browser-using-javascript-and-filepond-10b8

Docs:
https://pqina.nl/filepond/docs/patterns/plugins/image-transform/#using-transform-variants

>  The name of each file will be prefixed with the name of the transform variant.

The field will be the same name, the name of the each file will be different.

If you want to change the field name you will have to set up a custom processing method:
https://pqina.nl/filepond/docs/patterns/api/server/#advanced
