### ISSUE TITLE
Multiple upload only uploads 2 files

### ISSUE THREAD

**Issue by avillarubia** [pqina/filepond#472]
**Stay Home, Keep Safe Everyone.**

Summary
Multiple uploads only upload 2 files and save to static folder and the rests are the loading animation never stops. Both client and server allow only a maximum of 5 files.
...

### How to reproduce
Below is my sample code the uses React

```js
import React from 'react'
import { FilePond, registerPlugin } from 'react-filepond'
import FilePondPluginFileEncode from 'filepond-plugin-file-encode'
import FilePondPluginImagePreview from 'filepond-plugin-image-preview'
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type'
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size'
import FilePondPluginFilePoster from 'filepond-plugin-file-poster'

import 'filepond/dist/filepond.min.css'
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css'
import 'filepond-plugin-file-poster/dist/filepond-plugin-file-poster.css'

registerPlugin(FilePondPluginImagePreview, FilePondPluginFileEncode, FilePondPluginFileValidateType, FilePondPluginFileValidateSize, FilePondPluginFilePoster)

const { REACT_APP_API_BASE_URL, REACT_APP_API_PORT } = process.env
const apiBase = `${REACT_APP_API_BASE_URL}:${REACT_APP_API_PORT}`

const Uploader = () => {
    return <>
        <FilePond
            allowFileSizeValidation={true}
            name='files'
            maxFiles={5}
            allowMultiple={true}
            allowFilePoster={true}
            labelIdle='Drag & Drop files or <span class="filepond--label-action">Browse</span>'
            server={`${apiBase}/api/uploads/`} />
    </>
}

export default Uploader
```

in my server is...
```js

const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, uploadPath)
    },
    filename: function (req, file, cb) {
        const id = shortid.generate()
        cb(null, `${id}_${file.originalname}`)
    }
})

const mb = 50
const limits = {
    fileSize: mb * 1024 * 1024
}

const upload = multer({ storage, limits }).array('files', 5)

router.post('/', upload, (req, res) => { //TODO: auth before upload...
    console.log('uploading...')
})
```
...

### Expected behaviour
Should upload 5 files.
...

### Additional information
- I tested random files. For every batch to drop down will only pick 2 files and the rest still loading.
- Each files are not 50 mb above. Just dummy images and files were tested.
- Multer doesn't show errors. 
- I ask to multer community but someone says not a problem with multer. Here is the link https://github.com/expressjs/multer/issues/866
- shortId is only a generator of name
...

| Environment  | Version
|------------- | -----------
| OS           |  Windows 10 64bit
| Browser      | Chrome Version 80.0.3987.149 (Official Build) (64-bit)
|react           | 16.8.6
|react-filepond           | 7.0.1
|filepond           | 4.13.0
|filepond-plugin-file-encode           | 2.1.5
|filepond-plugin-file-poster           | 2.2.0
|filepond-plugin-file-validate-size           | 2.2.1
|filepond-plugin-file-validate-type           | 1.2.5
|filepond-plugin-image-preview           | 4.6.1
|multer | 1.4.2

**Comment by rikschennink** [comment]
Can you try unregistering the `FilePondPluginFileEncode` plugin.

**Comment by avillarubia** [comment]
@rikschennink still same :(

**Comment by rikschennink** [comment]
@avillarubia Then I honestly don't know, if you create a public test case I can take a look.

**Comment by avillarubia** [comment]
@rikschennink it is now solved, I remove node_modules and reinstall and update but not for this concern. 

Thank you for your time

**Comment by Shadowsm29** [comment]
I had the same issue and I solved it by setting **maxParallelUploads** attribute to a sufficiently high number. I played with this number a little bit and if I don't set the attribute at all, the upload stops after the second file is uploaded. Maybe 2 is a hidden default? If I set a low number, 3 for example, the upload is stopped after the third file is uploaded. So it looks like the next batch of parallel uploads is not started.

**Comment by gmw-web** [comment]
We had the exact same issue, and @Shadowsm29 's solution worked for us too. 
Perhaps @rikschennink can shed some light on why this is the case?

**Comment by rikschennink** [comment]
@gmw-web default is 2 but should then pick up next file, if that doesn't happen it would be helpful if you can supply a public test case

**Comment by gmw-web** [comment]
Tried to create a sandbox, but I can't replicate the issue a.t.m.. I will take a better look when I have a bit more time.

**Comment by McGern** [comment]
Ended up here for exactly the same reason, but worked out what I was doing wrong, so leaving a note in case someone else (or me in the future) has this issue.

I'm using react-filepond (not the problem) and the component wouldn't upload anything after 2 files, whether opening 3 at once or adding them one at a time. The process wasn't hitting the console log either for the 3rd+ files. The first 2 files were uploaded, but what I didn't notice was that the "complete" indicator didn't correctly change to the "X" for undo.

My issue was that I was using a custom server process function, but never called the "load" method on successful upload.

server={{
  process: async (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
  
    // do your uploading method
   uploadFile(file).then((id) => {
   
     **load("finished");**
   
   });
  
  }
