### ISSUE TITLE
externally set file value results in a 'gray' status

### ISSUE THREAD

**Issue by chapkovski** [pqina/filepond#473]
I know it's  most likely not a bug, but still:
for some of my fields that use filepond I sometimes set their values outside of FilePond component, by setting its value using 'options' (as it is described in documentation).
The value I set is for instance:

```
"options": {
      "type": "local",
      "file": {
        "name": "ph_version.xlsx",
        "size": 404370,
        "type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      }
```

It works fine, with one caveat:
those files that are 'uploaded' by setting the filepond value externally are gray.
Like that:

![Screen Shot 2020-03-30 at 10 53 52 AM](https://user-images.githubusercontent.com/5639776/77927444-3b4f1500-7275-11ea-99b3-acaee84626b8.png)

While if the same file is uploaded directly via FilePond it looks like that:
![Screen Shot 2020-03-30 at 10 58 02 AM](https://user-images.githubusercontent.com/5639776/77927601-689bc300-7275-11ea-92bf-fc3278d68b5f.png)
Even if the values of a field in both cases are the same.

Can something be done so they both look the same (green) in both scenarios?

Versions:
```
 "filepond": "^4.12.0",
 "react-filepond": "^7.0.1",
```

**Comment by rikschennink** [comment]
Does setting type to "limbo" make a difference.

**Comment by chapkovski** [comment]
'limbo' works!

**Comment by ryanzzeng** [comment]
@chapkovski does limbo works? i think limbo will set a different request ?
