### ISSUE TITLE
Sorting on plugin content

### ISSUE THREAD

**Issue by EthosData** [pqina/filepond#474]
Hello!

One question: which is the order that the plugin takes to generate the upload list when dropping the content? Is it aleatory, as it comes from the user desktop (drop) or is there any logic (alphabetical, natural, order, etc.)? 

This will be important to know in case we need to handle the sorting of the files once they are uploaded.

David.

**Comment by rikschennink** [comment]
It's defined by the OS, I'm not sure if it's the same everywhere to be honest. Maybe you can use the sort method.

**Comment by EthosData** [comment]
Yes, that will work. Thanks!
