### ISSUE TITLE
Issue with destroy when used with Svelte

### ISSUE THREAD

**Issue by Nico-L** [pqina/filepond#477]
Hi, I am trying to use filepond with Svelte and I have an issue when destroy components

### Summary

I started with a simple component. I made a Svelte REPL to show :
https://svelte.dev/repl/0f3d60c1bd084cac962cb2df3f70846e?version=3.20.1
If you click on the checked box, the following error is thrown
```
Error: Uncaught (in promise): Cannot read property 'removeChild' of null
```
and the component becomes unresponsive

### How to reproduce

See the REPL

### Expected behaviour

There seem to have some interaction between both code beyond my skill level, maybe would you have an idea on how to fix that in my own component

Thanks,
Nicolas

**Comment by rikschennink** [comment]
FilePond uses the `input` file element, so Svelte can't find it when FilePond has moved it around. Wrapping it in a div solves the issue.

```
<div>
  <input type="file" bind:this={inputElement}>	
</div>
```

You don't have to pass the element to the FilePond `destroy` method. You can just call `pond.destroy()`.

**Comment by Nico-L** [comment]
Hi @rikschennink 

That is a fast answer! And a simple solution, sorry not to have try this.

Thank you. I'm glad I found filepond.

**Comment by rikschennink** [comment]
@Nico-L No worries 👍😊
