### ISSUE TITLE
Problem in populating initial files from remote URLs on Safari browser

### ISSUE THREAD

**Issue by Asad4429** [pqina/filepond#482]
### Summary
I'm populating initial files from remote urls in filepond. It's working fine on all browsers excepts Safari. During debug I noticed that load method is not get called due to which image gets failed in Safari. I'm using it in React along with react-filepond.
...

### How to reproduce
Populate initial file in Safari. Load method will not call.
...

### Expected behaviour
Initial image should set as in other browsers.
...

| Environment  | Version
|------------- | -----------
| OS           | MacOS Catalina
| Browser      | Safari Version 13.0.5 (15608.5.11)

**Comment by rikschennink** [comment]
Please supply a public test case on codesandbox.io

**Comment by Asad4429** [comment]
@rikschennink here is the test case link. Problem occurs in Safari browser, Working fine in Chrome and Firefox 
https://codesandbox.io/s/github/Asad4429/testproj?file=/src/App.tsx

**Comment by rikschennink** [comment]
on chrome and firefox it doesn't load either. It's just that Safari seems to cancel the request sooner.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dummyserver/photo-of-red-rose.jpg. (Reason: CORS request did not succeed).
```

**Comment by Asad4429** [comment]
It's dummy url just to test the call of load method
I put some logs in load method of serverConfig. load method is not get called in Safari but works well in chrome

**Comment by Asad4429** [comment]
@rikschennink can you please check console logs in Safari and Chrome? It didn't event print logs which I put in load method before server request in Safari.

**Comment by Asad4429** [comment]
@rikschennink I updated test case Can you please check it now?
https://codesandbox.io/s/github/Asad4429/testproj?file=/src/App.tsx

Output On Safari
<img width="549" alt="Screenshot 2020-04-23 at 4 30 56 PM" src="https://user-images.githubusercontent.com/14857273/80094651-0ede9e00-8580-11ea-8ca5-16045f66af29.png">

On chrome
<img width="553" alt="Screenshot 2020-04-23 at 4 31 04 PM" src="https://user-images.githubusercontent.com/14857273/80094662-156d1580-8580-11ea-8dba-63dea76f5c21.png">

**Comment by rikschennink** [comment]
It works as it should in this sandbox?

https://codesandbox.io/s/vanilla-filepond-2oltb?file=/src/index.js

**Comment by Asad4429** [comment]
yes

**Comment by Asad4429** [comment]
> It works as it should in this sandbox?
> 
> https://codesandbox.io/s/vanilla-filepond-2oltb?file=/src/index.js

yes

**Comment by Asad4429** [comment]
> Then maybe there's something wrong with your implementation? Not sure. Happy to investigate further if you have more information or if more devs report issues.

I copied same example code snippets which was given in react-filepond repo, So there should not be any issue with implementation. But dependencies and configuration of this test case is different. I think **some compatibility issues with filepond and safari comes when TypeScript/babel/webpack is being used** in react's project, but not sure.

**Comment by rikschennink** [comment]
@Asad4429 I've set up a React test case for your convenience: https://codesandbox.io/s/filepond-react-server-load-method-test-iwqq5?file=/src/App.js
