### ISSUE TITLE
Problem in setting initial files [Safari]

### ISSUE THREAD

**Issue by Asad4429** [pqina/filepond#483]
### Summary

I'm setting initial files in filepond. It's working fine on all browsers excepts Safari. I am using react-filepond.

Output on Safari:
<img width="549" alt="Screenshot 2020-04-23 at 4 30 56 PM" src="https://user-images.githubusercontent.com/14857273/80097465-c83f7280-8584-11ea-9480-0ae1f930f46c.png">

Output on Chrome
<img width="553" alt="Screenshot 2020-04-23 at 4 31 04 PM" src="https://user-images.githubusercontent.com/14857273/80097488-d097ad80-8584-11ea-8390-37c7bc746c83.png">

Related issue #482.
...

### How to reproduce
Here is test case. Just open it in Safari browser.
https://codesandbox.io/s/github/Asad4429/testproj?file=/src/App.tsx
...

### Expected behaviour
Should work file on Safari as it's working on chrome and firefox.
...

| Environment  | Version
|------------- | -----------
| OS           | MacOS 
| Browser      | Safari 11.1.1

**Comment by rikschennink** [comment]
There's already an issue on this, have some patience.
