### ISSUE TITLE
FilePond.AddFile() doesn't set the correct file name in the UI

### ISSUE THREAD

**Issue by starwarskidfan** [pqina/filepond#484]
### Summary
After calling the the FilePond.AddFile method and supplying it with a local file, after loading it the file name in the UI is still the serverId

### How to reproduce
```
this.myPond.addFile(
{
          // the server file reference
          source: '12341234',

          // set type to local to indicate an already uploaded file
          options: {
              type: 'local',
          }
      }
})
```
### Expected behaviour

The UI should be using the FileName

### Additional information
```
this.myPond.addFile({}).then(x => {console.log(x.filename)})
```
This logs the correct file name but the UI is not updated.

**Comment by starwarskidfan** [comment]
Here are my response headers

access-control-allow-origin: https://something.com
access-control-expose-headers: Content-Disposition, Content-Length, X-Content-Transfer-Id
cache-control: no-cache
content-disposition: inline; filename=SourceTreeSetup-3.3.8.exe; filename*=utf-8''SourceTreeSetup-3.3.8.exe
content-length: 25567520
content-type: application/octet-stream
date: Mon, 27 Apr 2020 17:37:34 GMT
expires: -1
pragma: no-cache
server: Microsoft-IIS/10.0
status: 200
x-aspnet-version: 4.0.30319
x-powered-by: ASP.NET

**Comment by rikschennink** [comment]
Please use the `files` property to set initial files:
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

**Comment by starwarskidfan** [comment]
I am not setting initial files. Does the AddFile method not work.

**Comment by rikschennink** [comment]
@starwarskidfan no, you should use `files`, `addFile` is for adding new files

**Comment by rikschennink** [comment]
Closed because inactive
