### ISSUE TITLE
add file to the Filepond by using data-files inside <input> returns empty array

### ISSUE THREAD

**Issue by omiderfanmaneshit** [pqina/filepond#485]
I am going to use PHP MVC and Filepond together and pass the default file URL to the Filepond inside HTML. I don't want to request again to the server and get the URL of my file using addFile() to load it to the pond object. 
So, I use data-files inside <input> and pass the URL but the file array is empty. 

```html
     <input id="input-file"
                           type="file"
                           style="min-height: 25em;"
                           class="filepond"
                           data-files="['http://url/a.pdf']"
                           name="filepond">

```

```javascript

let initFileUploadInput = function () {

    // avatar = $('#input-avatar');
    $.fn.filepond.registerPlugin(
        FilePondPluginFileValidateType,
        FilePondPluginFileValidateSize
    );

    $(':input[type="submit"]').prop('disabled', true);


    pond = FilePond.create(
        document.querySelector('input[id="input-file"]'));


    console.log(pond.files,pond.name)
};

```

the result of ```console.log(pond.files,pond.name)``` is ```[] "filepond" ```

link this question in stack :

https://stackoverflow.com/questions/61411939/add-file-to-the-filepond-by-using-data-files-inside-input-returns-empty-array

**Comment by rikschennink** [comment]
Please see: https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

You need to use a `<fieldset>` instead of the data attribute.
