### ISSUE TITLE
I've stuck on a problem within a week "Laravel validation with Filepond Plugin"

### ISSUE THREAD

**Issue by z-flash** [pqina/filepond#486]
@rikschennink 
When I try to `dd($request->all());` it will display JSON type data like this

`array:3 [▼
  "_token" => "mt9BLJMyr3i8NdpmqTl22k2DJsF0Bd0D4E6VR5r3"
  "phone" => "31 231 23 12"
  "file" => array:2 [▼
    0 => "{"id":"1r8cqszse","name":"travel.jpg","type":"image/jpeg","size":334996,"metadata":{},"data":"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODw ▶"
    1 => "{"id":"50v9mvf7y","name":"b.jpg","type":"image/jpeg","size":30436,"metadata":{},"data":"/9j/4AAQSkZJRgABAQAASABIAAD/2wBDAAYEBAUEBAYFBQUGBgYHCQ4JCQgICRINDQoOFRIW ▶"
  ]
]`
I wanna Validate this data via Laravel Controller how can I do it ?

Here's my Store Function 

![Screenshot (20)](https://user-images.githubusercontent.com/44101838/80307725-56656400-87e4-11ea-8b2e-12edd4229fb7.png)

**Comment by rikschennink** [comment]
This is not a FilePond issue. You can view the [FilePond PHP server repo](https://github.com/pqina/filepond-server-php) for how it parses the request.
