### ISSUE TITLE
Svelte Doka 6.9.0 with filepond - cropping/editing of image failing

### ISSUE THREAD

**Issue by JohnRSim** [pqina/filepond#488]
```js
//svelte
import { onDestroy, onMount } from 'svelte';

//libs
import {default as FilePond} from 'filepond';
import { create, DokaModal, toURL } from '@libs/svelte-doka';

let result = null;
let src = null;

onMount(async () => {
	console.info('[EditProfile][Mount]');
	//const FilePondPluginImagePreview = await import('filepond-plugin-image-preview');
	//const FilePondPluginImageExifOrientation = await import('filepond-plugin-image-exif-orientation');
	//const FilePondPluginFileEncode  = await import('filepond-plugin-file-encode');
	//const FilePondPluginFileValidateSize = await import('filepond-plugin-file-validate-size');
	const FilePondPluginImageEdit = await import('filepond-plugin-image-edit');

	FilePond.registerPlugin(
		//FilePondPluginImagePreview.default,
		//FilePondPluginImageExifOrientation.default,
		//FilePondPluginFileValidateSize.default,
		FilePondPluginImageEdit.default,
		//FilePondPluginFileEncode.default,
	);

	pond = FilePond.create();

	pond.setOptions({
		allowDrop: false,
		allowReplace: false,
		instantUpload: false,
		//onpreparefile: handleConfirm,

		// default crop aspect ratio
		//imageCropAspectRatio: 1,

		// resize to width of 200
		//imageResizeTargetWidth: 200,

		// open editor on image drop
		imageEditInstantEdit: true,

		// configure Doka
		imageEditEditor: create({

			// Doka.js options here ...
			utils:'crop, filter, color',
			//src,
			cropAspectRatio:'1',
			cropMask:mask,
			onconfirm:handleConfirm,
			//oncancel:handleCancel,
			//onclose:handleClose
		}),
	});
});


const handleConfirm = (conf, output) => {
	console.log('Confirm edit!', output);
	const file = output.file;
	
	// encode the file using the FileReader API
	const reader = new FileReader();
	reader.onloadend = () => {

		// use a regex to remove data url part
		const base64String = reader.result
			.replace('data:', '')
			.replace(/^.+,/, '');
		
		// log to console
		console.log(base64String) // logs wL2dvYWwgbW9yZ...
		src = `data:${file.type};base64,${base64String}`;
	};
	reader.readAsDataURL(file);
	
	result = toURL(output.file);
}
```
```html
<style>
#profileAvatarWrapper {
    height: 120px;
    width: 120px;
    border-radius: 120px;
}
</style>
<div id="profileAvatar" on:click="{() => { pond.browse(); }}">
    <img src="{src}" alt="" />
</div>
```

### Summary

handleConfirm method that returns the file;
- returns the original preparsed image that was selected through filepond.

If I use the same approach with just Doka and not filepond the response is the edited file.

### How to reproduce

example code above

### Expected behaviour

Doka onconfirm to return edited file and not original.

### Additional information

Also tried to use onpreparefile method.

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Device       | android
| Browser      | chrome  84.0.4131.0

**Comment by JohnRSim** [comment]
**onclick - pond.browse();**
<img width="270" alt="filepond selected image" src="https://user-images.githubusercontent.com/364208/80709876-0210fb80-8ae6-11ea-9439-b565c925f2a2.PNG">

**Edit image with Doka Plugin**
<img width="270" alt="filepond editimage doka" src="https://user-images.githubusercontent.com/364208/80709885-04735580-8ae6-11ea-8cda-db8e5bc72392.PNG">

**Image returned as original image**
<img width="269" alt="filepond after doka edit response" src="https://user-images.githubusercontent.com/364208/80709888-06d5af80-8ae6-11ea-8441-bba43d614158.PNG">

**Comment by rikschennink** [comment]
It doesn't look like you've registered the FilePond image transform plugin? It is needed to do the image transformations.

**Comment by JohnRSim** [comment]
```js
const FilePondPluginImageEdit = await import('filepond-plugin-image-edit');
		const FilePondPluginImageTransform = await import('filepond-plugin-image-transform');

		FilePond.registerPlugin(
			//FilePondPluginImagePreview.default,
			//FilePondPluginImageExifOrientation.default,
			//FilePondPluginFileValidateSize.default,
			FilePondPluginImageEdit.default,
			FilePondPluginImageTransform.default,
			//FilePondPluginFileEncode.default,
		);
```
hmm I added the above but still the same - also added all the pond callback hooks to see if there were any errors but all seemed fine.

**Comment by JohnRSim** [comment]
Also appear to be having issues with the cropping starts off as rectangle not square.

Added FilePondPluginImageCrop plugin and also set the following but no luck..
- when I select the corner of the croper it flips to a square.

```js

			// default crop aspect ratio
			allowImageCrop:true,
			imageCropAspectRatio: '1:1',
			// resize to width of 200
			//imageResizeTargetWidth: 200,

			// open editor on image drop
			imageEditInstantEdit: true,

			// configure Doka
			imageEditEditor: create({

				// Doka.js options here ...
				utils:'crop, filter, color',
				//src,
				cropAspectRatio:'1',
				cropAspectRatioOptions: [
					{
						label: 'Square',
						value: 1
					},
				],
				cropMask:mask,
				onconfirm:handleConfirm,
				oncancel:handleCancel,
				onclose:handleClose
			}),
```

**Comment by JohnRSim** [comment]
https://github.com/pqina/filepond-docs/blob/master/content/patterns/plugins/image-edit.md

Also added the FilePondPluginImagePreview but no change

**Comment by rikschennink** [comment]
Can you try the included FilePond "integration" example? Run it outside Svelte, add the `onpreparefile` callback to the FilePond config below, test if it works. Then compare with Svelte implementation.

```js
onpreparefile: (item, output) => {
    const img = new Image();
    img.src = URL.createObjectURL(output);
    document.body.appendChild(img);
}
```

**Comment by JohnRSim** [comment]
yes let me try it..

Also I can create a base sapper/svelte project if you want to see the issue 
- wont include doka lib you can add that.

**Comment by JohnRSim** [comment]
That works let me match with my config and see if I can find the issue

**Comment by JohnRSim** [comment]
Ok disabled instantUpload as this prevented onpreparefile from triggering.
Also disabled the onconfirm in doka
```js
//instantUpload: false,
//onconfirm:handleConfirm,
```
used onpreparefile - all working as expected now in svelte :)
Still issues with the crop appearing initially as a rectangle but will raise a new issue. 

@rikschennink thanks for your help 👍
