### ISSUE TITLE
Doka 6.9.0 with filepond - cropAspectRatio full size not square

### ISSUE THREAD

**Issue by JohnRSim** [pqina/filepond#489]
I'm using filepond / Doka to allow users to select their profile picture.

However after selecting their picture and initialising Doka the crop mask initially shows as the full image size / rectangle until the mask is selected and then it autofixes and recorrects / resize to the correct aspect ratio of a square. 

Looking at the DemoProfile.svelte code this initalises with the profile image and croper mask as a square correctly.

```js
const mask = (root, setInnerHTML) => {
            setInnerHTML(root, `
                <mask id="my-mask">
                    <rect x="0" y="0" width="100%" height="100%" fill="white"/>
                    <circle cx="50%" cy="50%" r="50%" fill="black"/>
                </mask>
                <rect fill="rgba(255,255,255,.3125)" x="0" y="0" width="100%" height="100%" mask="url(#my-mask)"/>
                <circle cx="50%" cy="50%" r="50%" fill="transparent" stroke-width="1" stroke="#fff"/>
            `);
        };

FilePond.registerPlugin(
            //FilePondPluginImageExifOrientation,
            FilePondPluginImagePreview,
            //FilePondPluginImageResize,
            FilePondPluginImageEdit,
            FilePondPluginImageTransform,
            FilePondPluginImageCrop,
        );

let pond = FilePond.create();

pond.setOptions({
    allowImageCrop:true,
    imageCropAspectRatio: 1,
    // open editor on image drop
    imageEditInstantEdit: true,

    // configure Doka
    imageEditEditor: Doka.create({

        // Doka.js options here ...
        utils:'crop, filter, color',
        //src,
        cropAspectRatio:'1',
        cropAspectRatioOptions: [
            {
                label: 'Square',
                value: 1
            },
        ],
        crop: {
            aspectRatio: 1,
            center: {
                x: 0.5378,
                y: 0.355
            }
        },
        cropMask:mask,
    })
});


document.querySelector('button').addEventListener('click', () => {
    pond.browse();
});
```

### Summary

Works standalone with Doka; 
however when included with filepond shows cropper as fullscreen of image.

### How to reproduce

use code above

### Expected behaviour

Cropper to display as a square.

### Additional information

tried '1:1' as aspect ratio 

| Environment  | Version
|------------- | -----------
| OS           | Windows 
| Device       | android
| Browser      | chrome 84

**Comment by JohnRSim** [comment]
**On initialise of Doka via filepond - full screen cropper**
<img width="270" alt="filepond_doka_init" src="https://user-images.githubusercontent.com/364208/80729696-896b6880-8b00-11ea-9bfe-cb70abb97454.PNG">

**Select Cropper - cropper resizes to square**
<img width="270" alt="filepond_doka_cropperSelected" src="https://user-images.githubusercontent.com/364208/80729704-8bcdc280-8b00-11ea-9b7d-f53cef537c7c.PNG">

**Example of DemoProfile.svelte initialised**
<img width="269" alt="doka_example" src="https://user-images.githubusercontent.com/364208/80729709-8d978600-8b00-11ea-9229-6f8253bd649d.PNG">

**Comment by rikschennink** [comment]
I think you have to remove the `crop` and `cropAspectRatio` properties from Doka.

When using Doka with FilePond, FilePond is in charge, Doka offers the means to edit the image but FilePond should provide the data. This means you have to set the `crop` property to the file item metadata. Same with the `imageCropAspectRatio`.

By the way, `utils` should be an array, `['crop', 'filter', 'color']`.

**Comment by rikschennink** [comment]
I think also the FilePond `imageCropAspectRatio` needs to be in "human readable format" so '1:1'.

Will close because inactive.
