### ISSUE TITLE
Stale files when replacing an already-uploaded temporary file

### ISSUE THREAD

**Issue by enisdenjo** [pqina/filepond#49]
First of all, FilePond is **very awesome and slick**, superb job!

Anyhow, I'll go right to the point. Lets say you have a FilePond instance which **allows only 1 file**. You drag-and-drop the file and it is immediatly uploaded as a tmp file on the server. Now you realised that its the wrong file, the natural behaviour would be to **just drag another file over that one**, FilePond behaves accordingly: it removes the previous one and replaces it with the newly-dragged one.

But when the user does so, no `revert` method is called for the previous file. This means that the server will have a lot of **stale** files!

It would be great, if the `revert` method is called in this case so that the server can clean the tmp directory!

Kind regards,
Denis

**Comment by rikschennink** [comment]
Hi @enisdenjo, Thanks for giving FilePond a go!

Good point, it should call `revert`, I've added it to my todo list.

About the temp files. I think it's wise to set up a server script that periodically clears the temp upload folder ( for instance of files older than a day ) as users could also simply close the browser window.

**Comment by enisdenjo** [comment]
Hey @rikschennink,

thanks for the quick reply! Of course we'll have a cleanup method which removes stale temporary files. The reason behind the issue is that our use case is that EVERY uploaded file will come with a `payload` which will hold all relevant information for processing the said file. In this case we need to be carefull in what we delete from the tmp file, and this feature would help a lot!

**Comment by rikschennink** [comment]
@enisdenjo Aha, got it! :-)

Just published version `1.5.4` which should fix the issue.

**Comment by enisdenjo** [comment]
Amazing, I can confirm that it works! 😄

**Comment by rikschennink** [comment]
Thanks for confirming 👍

**Comment by rikschennink** [comment]
@enisdenjo Just uploaded version `1.6.2`, found an issue with restored temporary files not being removed when replaced. Should be good now.
