### ISSUE TITLE
Process hangs during upload when trying to calculate file size

### ISSUE THREAD

**Issue by chintanp** [pqina/filepond#490]
### Summary

I have been using filepond on my website successfully for several days and recently iPhone users have been reporting an error. 

![image0](https://user-images.githubusercontent.com/752869/81145040-465b2c00-8f2a-11ea-862e-fe843cd121e6.png)

Filepond just stays stuck at this screen with message "Waiting for size".

The code I use is as below:

```js
FilePond.registerPlugin(

    // previews dropped images
    FilePondPluginImagePreview,
    // corrects mobile image orientation
    FilePondPluginImageExifOrientation,
    // encodes the file as base64 data
    // FilePondPluginFileEncode,
    // validates the size of the file
    FilePondPluginFileValidateSize,
    FilePondPluginFileValidateType, // validate type
    FilePondPluginImageResize,
    FilePondPluginImageTransform
);

// Select the file input and use create() to turn it into a pondd
FilePond.create(
    document.querySelector('input[type="file"]'), {
    acceptedFileTypes: ['image/*'],
    allowImageExifOrientation: true,
    imageCropAspectRatio: '1:1',
    imageResizeTargetWidth: 300,
    imageResizeTargetHeight: 300,
    imageResizeUpscale: false,
    imageResizeMode: 'cover',
    instantUpload: true,
    imageTransformOutputQuality: 85,
    // allowFileEncode: false,
    server: {
        process: {
            url: './upload',
            onload: (response) => {
                console.log("file successfully uploaded with id: " + response)
                imageId = JSON.parse(response)[0];
...
```

I do not have an iPhone so I am not able to reproduce the error. I will post more info as I receive. Everything works fine and dandy on my Android and iPad.

| Environment  | Version
|------------- | -----------
| OS           | iOS 13.3.1
| Device       |  iPhone 11 Pro Max
| Browser      | Safari & Chrome

**Comment by rikschennink** [comment]
Is this with latest versions of all plugins?

**Comment by chintanp** [comment]
Yes, directly from the NPM cdn.

As a check, the validate size demos and demos on filepond site work fine on
the iPhone in question.

Any other test I can perform on my side to debug the issue?

**Comment by rikschennink** [comment]
Will run some tests

**Comment by chintanp** [comment]
@rikschennink I have a few results from someone with an iPhone, the folder (https://drive.google.com/drive/folders/1MnLbXUBwH69DrbYhRmhqDoQ5PMn81I0t?usp=sharing) has images labeled as work_ and nowork_ for images that worked and did not. Hopefully, Google drive did not mess up the image exif data.

**Comment by chintanp** [comment]
@rikschennink so some success in getting to the root of the error. I was able to recreate the problem in my Android (10.3.1) Firefox Beta (75.0.0-beta-6), and connecting it to my desktop firefox for remote debugging, I see the following error in the console. 

![image](https://user-images.githubusercontent.com/752869/81356118-4f144500-9085-11ea-8847-66691177d7a7.png)

And the timing since the error appeared matches the update to the filepond-plugin-image-resize . 

What is interesting is, this does not happen for all images and all browsers. In a later nightly build of firefox (77.0a1), it worked fine. In the meantime, I will try to go back to the previous version of the plugin and update with my findings.

**Comment by rikschennink** [comment]
@chintanp Thanks so much for the detailed test reports, this really helped a lot in quickly solving this. I just pushed 2.0.6 which should fix this.

**Comment by chintanp** [comment]
Works on my Android now. Thanks for the quick fix. I am tempted to version lock the library and plugins though. I am new to JS dev, so not sure what the best practices are for this. 

If someone can test on iPhone and finds that the issue persists, then they can re-open.

**Comment by rikschennink** [comment]
Glad to hear it works 👍

I would advise to always version lock.
