### ISSUE TITLE
multiple uploads using the same name

### ISSUE THREAD

**Issue by lekoala** [pqina/filepond#50]
Hello,

I'm trying to use the multiple uploads feature, but it seems that the hidden fields created to store the temporary id use all the same name (and not the array notation, like `filepond[]`).

Therefore, when I post the form, only one id gets through.

In your examples on the website, there is no mention of any other setting

```html
<input type="file" 
    class="filepond"
    name="filepond" 
    multiple 
    data-max-file-size="3MB"
    data-max-files="3">
```

I'm currently using multiple attribute (although I use `multiple="multiple"` but I don't expect it to work differently) and also using `allowMultiple` option.

Any help is appreciated!

**Comment by rikschennink** [comment]
Hi @lekoala! If you change the `name` of the `input` to `filepond[]` FilePond will copy that name to the hidden input fields.

**Comment by lekoala** [comment]
I just tried on jsfiddle, it works indeed as you said so there must be something wrong in my setup. I'll have a look tomorrow to see what's wrong.

**Comment by rikschennink** [comment]
Alright, will await your response.

**Comment by lekoala** [comment]
ok, it was because I was using the name option to set the name of the field when uploading the file. It's still a bit annoying though because it means that the behaviour is not the same when having single or multiple uploads : the endpoint will get passed an array of files or a single file. But at least its working now :-)

Maybe the docs deserved to be updated so that it's clearly specified that when using multiple attribute, the name should include [] in it?

**Comment by rikschennink** [comment]
I'm not sure I understand what you mean with:

> I was using the name option to set the name of the field when uploading the file

But I'm glad it's working.

[The docs are on GitHub](https://github.com/pqina/filepond-docs) as well, so if you have suggestions for improvement, pull requests are very welcome.

**Comment by lekoala** [comment]
it means i was doing something like

`<input class="filepond" type="file" name="Files[]" multiple="multiple" id="InputFiles">`

and then doing this

`$('.filepond').filepond({allowMultiple: true, name: 'Files'})`

When done like that, it's Files that will be used for hidden fields, not Files[]. I was using the "name" option to make sure that it was sent properly to the server.

With Files as key, you get a regular array (['name' => 'some name', ...] and with Files you get a more complex array (['name'] => [ 0 => 'some name']).
