### ISSUE TITLE
minFiles option support

### ISSUE THREAD

**Issue by vommuan** [pqina/filepond#503]
I develop a [module for Yii Framework](https://github.com/nowmovesoft/yii-filepond) to easy connect FilePond in project.

Yii contain option [minFiles](https://www.yiiframework.com/doc/api/2.0/yii-validators-filevalidator#$minFiles-detail) in FileValidator. I want to integrate Yii validators to FilePond. So, it will be better to use FilePond validation abilities instead of provided by Yii.

That's why I need this option. Option means the following: "The minimum file count the given attribute can hold. Defaults to 0. Higher value means at least that number of files should be uploaded".

Alternate way is to write custom code based on jQuery (available out of the box in Yii).

**Comment by rikschennink** [comment]
While I can see use cases for this, it's also "easy" to determine this using the FilePond API, so will close for now.

**Comment by vommuan** [comment]
Ok. Can you suggest, what API calls I should use for that?

**Comment by rikschennink** [comment]
You can use `getFiles` to see how many files are in the list currently

**Comment by vommuan** [comment]
Thank you.
