### ISSUE TITLE
Remove file in filepond client-side without triggering revert function

### ISSUE THREAD

**Issue by yovichi** [pqina/filepond#504]
Hi, first of all, thanks for this wonderful tool for file upload.

I've just noticed that there was an update on the latest version 4.13.6 related to revert function. I used to have 4.13.4 installed in my apps but when I ran npm install yesterday, filepond's removeFile function now triggers revert function which basically triggers file removal in the server. My system requirement prior this update was to remove a file from filepond area in 5 second count to clear the filepond area and give space for new uploads, and not to totally revert the file upload. Are there any workaround for this in the current update or some other way to remove the uploaded file in filepond area without triggering revert function?

Thanks in advance! Any suggestions or help will be greatly appreciated.

**Comment by rikschennink** [comment]
I'm not sure I understand the use case, but if the files should not be removed, maybe add mock files?

**Comment by yovichi** [comment]
I'm not sure if adding a mock file will work as an alternative, but here's my code for you to clearly visualize what I want to achieve.
In 'pondOptions' I have this defined 

`
revert: (objectParam, load, error) => {
          var params = JSON.parse(objectParam);
          // Func to delete the file from the server
}
`

then I also have this function to perform some logic once file is successfully uploaded. After 5 seconds, we should be able to remove the file in filepond area and add the uploaded files in a list view. Within the 5 second mark, we allow reverting of file upload transaction, otherwise the file will be transferred from filepond area to the list view. 

`
onprocessfile(event: any) {
    setTimeout(() => {
      event.pond.removeFile();
    }, 5000);
}
`

This feature works nicely prior the updates from 4.13.4 but not in the latest release. I was thinking if there are other things I can do to remove a file from filepond area once successfully uploaded without deleting it from the server.

**Comment by rikschennink** [comment]
Okay, now I understand, hmm might be better to revert the change and add a parameter to the API method. I’m going to give it some though.

**Comment by rikschennink** [comment]
Published `4.13.7` should restore functionality to normal.

To trigger revert you can now pass `{ revert: true }` to the `removeFile` method.

**Comment by yovichi** [comment]
Thanks @rikschennink. I really appreciate your help. :) Very nice work.
