### ISSUE TITLE
Fetching cloudinary file triggers a process call

### ISSUE THREAD

**Issue by emery** [pqina/filepond#514]
Hello,

After fetching already uploaded files from Cloudinary, the custom server process function is called, uploading the file again on the cloud.

- Here is my fetch function:
`    fetch: (source, load, error, progress, abort, headers) => {
      var myRequest = new Request(source);
      fetch(myRequest).then(function(response) {
        response.blob().then(function(myBlob) {
          progress(true, 0, 1024);          
          load(myBlob);                
        });
      });             
    },`
- My process function is exactly the one provided here https://gist.github.com/rikschennink/7f1896f6b52e4730e24156fdec2525e6

- I use vue-filepond-5.1.3 like this, no event handler.
`          <file-pond
            name="pictures"
            ref="pond"
            allow-multiple="true"
            accepted-file-types="image/jpeg, image/png"
            :files="pictures"
          />`
- File data to fetch:
`      pictures:[{
        source:"http://res.cloudinary.com/.../image/upload/.../gtuw2ylunpi8rqagizfj.jpg",
        options: {}
      }]`
- Running on Ubuntu / Chrome 79

Am I missing something?
Thanks a lot for your help.
Marc

**Comment by rikschennink** [comment]
You haven’t set a file type see server docs, in this case probably “local” if it’s a temp upload it should be “limbo”
