### ISSUE TITLE
Expose "file-status" view for plugins

### ISSUE THREAD

**Issue by enisdenjo** [pqina/filepond#52]
Hello again!

I am currently implementing a custom filepond plugin which will handle some specific steps and requirements for us. I have managed to make one by reading through the filepond, and some plugins, source code.

During this process I realised that I needed a **filter** which will hook to the "file-status" view, but the `const fileStatus = createView(...)` does not have a `didCreateView` defined.

I've already made a local fork containing the fix, but I want to be up-to-date with new FilePond releases! So I am hereby asking if you could add the `didCreateView` to the "file-status" view?

Best regards,
Denis

**Comment by rikschennink** [comment]
Hi Denis! That is awesome!

Do note that I've currently not documented the plugin API as it might still change in the future. I'll see if I can add the didCreateView to the file status view as well. 

What kind of plugin are you building if I may ask?

**Comment by enisdenjo** [comment]
Hey Rik,

I figured that its because of that, I'll just re-write it again once you change the API. 😄 

Anyway, for us, when you upload a document file it goes through 2 processing steps. **1st** one is the upload (FilePonds "processing"); and the **2nd** one is our own processing of the said document. This 2nd step is rather similar to the FilePond "processing" step where you see the progress, you are able to abort it, retry on errors and all that good stuff.

So the plugin itself essentially initiates the 2nd step; displays the progress (retrieved through WebSocket); allows aborting and retrying; and after having finished the processing, it removes the item/file from the FilePond list.

**Comment by rikschennink** [comment]
Thanks for clarifying Denis! Amazing that you've managed to set this up with a plugin. I'll see if I can add the `createView` method somewhere this week.

**Comment by enisdenjo** [comment]
Any updates regarding this?

**Comment by rikschennink** [comment]
Sorry Denis, unfortunately, I haven't gotten around to it yet.

**Comment by enisdenjo** [comment]
No problem! Anyway, I made the changes in a new branch (locally) but I can't push it here so that I create a PR. Everything is in place, it just needs to be reviewed by you. 😄 

Can you give me access to create a new **branch** at this repo? I would understand if you say "no", just asking.

**Comment by enisdenjo** [comment]
No problem! I made a PR, so you just need to review/test it. 😄

**Comment by rikschennink** [comment]
Just published version `1.7.2` it adds the `didCreateView` filter for file status. 🙂

**Comment by enisdenjo** [comment]
Superb! Thanks a lot. 😁
