### ISSUE TITLE
MS Outlook .msg file not uploading properly

### ISSUE THREAD

**Issue by bmalin92** [pqina/filepond#520]
This has been posted elsewhere, but I have yet to see any solution or response for a full resolution. The "application/vnd.ms-outlook" filetype with the ".msg" extension can't be properly uploaded right now with FilePond as far as I can see.

The lack of proper support means when clicking Browse to select a file to upload, the .msg files will always be grayed out. The only workaround is to drag the .msg file into the upload section and run the following code:
```jsx
<FilePond
    ref={ref => (this.pond = ref)}
    files={null}
    allowMultiple={true}
    allowRevert={false}
    maxFiles={5}
    allowFileSizeValidation
    maxFileSize={'5MB'}
    // allowFileTypeValidation
    allowFileEncode
    acceptedFileTypes={[
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/msword',
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-excel',
        'application/vnd.ms-outlook'
    ]}
    fileValidateTypeDetectType={(source, type) =>
        new Promise((resolve, reject) => {
            if (source.name.includes('msg')) {
                type = 'application/vnd.ms-outlook';
                resolve(type);
            }
        })
    }
    fileValidateTypeLabelExpectedTypesMap={{
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
            '.docx',
        'application/msword': '.doc',
        'application/pdf': '.pdf',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
            '.xlsx',
        'application/vnd.ms-excel': '.xls',
        'application/vnd.ms-outlook': '.msg"'
    }}
    labelIdle={
        '<span class="filepond--label-action">Browse</span><br>Files must be under 5MB each and in one of the following formats: .doc, .docx, .xls, .xlsx, .pdf, .msg'
    }
    server={{
        url: this.state.baseUrl,
        process: {
            url: '[OMITTED FOR CODE SNIPPET]',
            method: 'POST',
            headers: {
                [OMITTED FOR CODE SNIPPET]
            },
            onload: res => {
                [OMITTED FOR CODE SNIPPET];
            }
        }
    }}
/>
```

This allows me to upload the .msg file but all the metadata is lost, and the title of the file won't show up when it's added to the list of files.

The most I've seen is people saying "use fileValidateTypeDetectType" but none of those posts have provided an explanation on how to use that to solve all of these issues. (I've used it in some capacity, but it's not a fix for everything.)

**Comment by rikschennink** [comment]
Just published version `4.16.0`, it should address this issue.

> Add `allowSyncAcceptAttribute`, set to `false` to prevent FilePond from setting the file input field `accept` attribute to the value of the `acceptedFileTypes`.

If the `accept` attribute isn't set to the same value you can select all files and validation happens inside FilePond.

**Comment by bmalin92** [comment]
Thanks for the update! This allows me to add the file through the Browse capabilities. Unfortunately uploading .msg files still prevents the data on the .msg from appearing on the item once uploaded. Basically, any other file I upload, the title of the file will appear as the title in the uploaded item. The .msg will just be blank. Am I not writing this correctly?
 ```
fileValidateTypeDetectType={(source, type) =>
    new Promise((resolve, reject) => {
        if (source.name.includes('msg')) {
            type = 'application/vnd.ms-outlook';
            resolve(type);
        }
    })
}
```

**Comment by rikschennink** [comment]
That snippet looks okay.

But I'm not sure what you mean with this:

> Unfortunately uploading .msg files still prevents the data on the .msg from appearing on the item once uploaded.

Is the file empty after upload?

It does how the correct name, if that's what you mean?

![Screenshot 2020-06-11 at 09 19 04](https://user-images.githubusercontent.com/1132575/84356664-ce38f380-abc4-11ea-8cd5-11cae0a8a23b.png)

**Comment by bmalin92** [comment]
When testing this elsewhere, we found that it worked correctly, and we determined there was a server-side issue causing the empty file after upload on the other page.

Do you happen to know why .msg files seem to have issues being accepted file types? We're happy we can upload them now, but we're also hoping someday we won't need to set `allowSyncAcceptAttribute` to false.

**Comment by rikschennink** [comment]
See: https://pqina.nl/filepond/docs/patterns/plugins/file-validate-type/#custom-type-detection

It's probably that the system uses a different type and so setting the type synced to the `accept` attribute doesn't match the system type and the files cannot be selected. If you can find out what type the system uses it might work.
