### ISSUE TITLE
onreorderfiles fires too many events

### ISSUE THREAD

**Issue by Silbad** [pqina/filepond#521]
Hello,

**Describe the bug**
onreorderfiles fires too many events, so if you want call an ajax request, you have too many calls

**To Reproduce**
Drag image.

**Expected behavior**
Fire event when you drop the image, not when you drag.
Or add a drop event ?

**Additional context**
Test with jQuery

Thanks ^^

**Comment by rikschennink** [comment]
It currently should fire an event when the index changes. Does it fire events when it stays the same?

**Comment by Silbad** [comment]
If I drag & drop an image, I have 11 events (test with two images)

**Comment by rikschennink** [comment]
Fixed in 4.17.1, event now also receives `origin` and `target` properties which contain indexes
https://github.com/pqina/filepond/releases/tag/4.17.1

**Comment by Silbad** [comment]
At the top ! Thanks for the reactivity ^^
