### ISSUE TITLE
Reorder with a mix of new files and initial files not work very well

### ISSUE THREAD

**Issue by Silbad** [pqina/filepond#522]
Hello

**Describe the bug**
When you have initial files and new files uploaded, the reorder by drag & drop not work very well. I test with 1 initial file and two new files. The drag & drop don't want sometimes.

**Expected behavior**
Drag & drop new files and inital files works like just new files uploaled

Thanks :)

**Comment by rikschennink** [comment]
I can't reproduce this. Please provide a concise test case.

**Comment by rikschennink** [comment]
Should be fixed in `4.18.0`
