### ISSUE TITLE
ReplaceOnClick

### ISSUE THREAD

**Issue by dataconnectnl** [pqina/filepond#523]
enhancement:

There is allready this function: allowReplace. However that is only for D&D. the idea is to click on the upload or poster to replace it with a click instead of D&D. if enabled dont show the remove button or optional.

'ReplaceOnClick'

It only requires one touch or click instead of first touch/click the remove button.

**Comment by rikschennink** [comment]
I don't feel this is a thing that should be in core, I think you can implement this yourself with `onactivatefile` ?

Will close for now.

**Comment by rosnaib11** [comment]
On your filepond instance add method `:onactivatefile="activateFile"`

then call the browse method

```
   activateFile(file) {
      this.$refs.pond.browse()
    },
```
