### ISSUE TITLE
Wrong type declaration

### ISSUE THREAD

**Issue by Kurbezz** [pqina/filepond#527]
Wrong type declaration of FilePond.addfFile options argument when add file without load.

addFile: (source: ActualFileObject | Blob | string, options?: { index: number }) => Promise<File>;

Options argument same as [this comment](https://github.com/pqina/filepond/issues/33#issuecomment-398480072).

**Comment by rikschennink** [comment]
Feel free to submit a PR

**Comment by Kurbezz** [comment]
#528
