### ISSUE TITLE
FilePondOptionProps missing fileRenameFunction

### ISSUE THREAD

**Issue by smithbrianscott** [pqina/filepond#529]
I updated filepond to the latest version (4.18.0) and I am now getting an error with filepond-plugin-file-rename. It looks as though the previous version I was using (3.3.0) didn't have an interface for "FilePond.setOptions" and now in version 4.18.0 the interface is FilePondOptionProps which doesn't have any a property for fileRenameFunction. According to this documentation the way it is written is correct. 

https://pqina.nl/filepond/docs/patterns/plugins/file-rename/

![image](https://user-images.githubusercontent.com/19986009/85756231-9fe70800-b6dc-11ea-81d6-ec94612af604.png)

![image](https://user-images.githubusercontent.com/19986009/85757131-403d2c80-b6dd-11ea-99d3-7c7861d5c414.png)

**Comment by rikschennink** [comment]
Can you try adding the below as a `types.d.ts` file:

```ts
declare module "filepond-plugin-file-rename" {
    const FilePondPluginFileRename: FilePondPluginFileRenameProps;
    export interface FilePondPluginFileRenameProps {

        /** Enable or disable renaming */
        allowFileRename?: boolean;

        /** Renames files */
        fileRenameFunction?: any;
    }
    export default FilePondPluginFileRename;
}
```

I've set `any` to the `fileRenameFunction` for testing purposes

**Comment by smithbrianscott** [comment]
That works, thank you!
