### ISSUE TITLE
Changing file name of uploaded files

### ISSUE THREAD

**Issue by mattwriley** [pqina/filepond#53]
I'm new to FilePond - and GitHub - so if this isn't the proper channel to ask for help, please let me know what is.  :-)

I want to change the name of files uploaded through FilePond. I've figured out how to manipulate this with the php boilerplate files you have provided. However, I want to be able to pass a php variable from the page FilePond is on to the Item.class.php file to add to the file name but I can't get a variable to go through so it can be used in the class.

I was wondering if there was an easier way to handle file naming through the setOptions/configuration of FilePond instead. If there is, I can't figure it out from the docs, so that's why I'm asking for your help.

Specifically, the page I am using FilePond on has an ID number for the project, stored in a php variable. I'd like any files uploaded through FilePond to be renamed using this ID (say, "12345"), so I can easily associate them with the project later on. So, when uploading my_file.jpg, I'd like it to change to 12345-my_file.jpg when stored on the server.

Thanks for making a cool product and putting it out there!
Matt

**Comment by rikschennink** [comment]
Hi Matt, excellent first post!

If you're uploading the files async then you could add the file id when posting the form. You can then modify the submit.php file and loop over the `$items` array after the temp files have been loaded. The `Item` class has a `rename()`, `getFilename()` and `getName()` function which you can use to rename the file.

**Comment by mattwriley** [comment]
Thanks for the quick response. I really appreciate it.

I've spent some time messing around with it again tonight based on your suggestions. I think I'm closer but I'm still struggling to figure out what I need to change to make it work.

In the submit.php file, I've got a loop going over the $items array, prepending the ID to each item. This ID comes from a hidden $POST value I added to the form.

```
...
// Get submitted field data items, pass input field name along
$items = FilePond\RequestHandler::loadFilesByField('filepond');

function prepend_ticket($x) {
    $ticket = $_POST['ticket'] . '_';
    return($ticket . $x);
}
$items = array_map("prepend_ticket",$items);

// Items will always be an array as multiple files could be submitted
FilePond\RequestHandler::save($items, 'uploads');
```
If I do a var_dump on $items at the end of the last line, I get the ID I want prepended to the item but the item being returned is the name of the temp folder being generated during the initial upload/drop of the file, rather than the file name.

`array(1) { [0]=> string(32) "myID#_9ce44f05523308b03b454b84c0432535" }`

I can't figure out how to use the rename function in the Item class to actually rename the files after hitting the submit button. I feel like I'm close but just don't know enough about PHP to put the right pieces in the right places. Any further help you can offer would be greatly appreciated!  :-)

-Matt

PS- It would be awesome to somehow offer some sort of file renaming (prepending, appending or complete rename) as part of the setOptions when configuring the FilePond script on the page. I don't know if that's possible or not, but if there is a way to have the file renamed right from the user dropping it on a FilePond instance that would save having to muck about with PHP, making this much more approachable for us mere mortals. :-)

**Comment by rikschennink** [comment]
No problem Matt!

A file rename plugin is on the roadmap but I am currently not working on it so it's still some time away.

I had to update the PHP boilerplate to make this work correctly, indeed the `$items` were id's instead of actual Item instances.

After getting the latest files, this should work:

```php

// Get submitted field data items, pass input field name along
$items = FilePond\RequestHandler::loadFilesByField('filepond');

foreach($items as $item) {
    $item->rename('foo_' . $item->getNameWithoutExtension());
}

// Items will always be an array as multiple files could be submitted
FilePond\RequestHandler::save($items, 'uploads');
```

**Comment by rikschennink** [comment]
Hi! Just published the [File Rename plugin](https://github.com/pqina/filepond-plugin-file-rename) to rename files on the client, I would still advice to prepend id's on the server but who knows, it might be useful.

**Comment by rikschennink** [comment]
For demo purposes, the default path is currently relative to the API location, as that makes it visually clear where the files end up. You can override the location either in code or by setting the static property.

I've updated the file-rename plugin docs with a quick example:
https://pqina.nl/filepond/docs/patterns/plugins/file-rename/#usage

**Comment by rikschennink** [comment]
Will close this for now as the original issue has been resolved.
