### ISSUE TITLE
FilePond cannot properly upload large file (> 2mb)

### ISSUE THREAD

**Issue by Codth** [pqina/filepond#530]
When I upload a file that is larger than around 2mb, I found that the data I got from the server side is not complete.  (May be because the file is too large for url to take from client to server ? ) Since I realize the problem, I started to use file-upload middleware, such as Multer or Express-fileupload to upload a large file through FilePond. However, It does not work. Therefore, I want to know is there a way or any configurations allow me to upload a large file successfully?

**Comment by rikschennink** [comment]
Closed because doesn't follow issue template.

Please note that uploads above 2MB can be done without issue, this is most likely a server configuration issue.
