### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by mpavey0** [pqina/filepond#54]
Clicking on https://pqina.nl/filepond gives me a 503 response and this screen:

![image](https://user-images.githubusercontent.com/12401696/40849232-5adcb07a-658f-11e8-9780-2d483ef59d8e.png)

**Comment by matthieubellon** [comment]
This is where you realize that without documentation any code is worthless.

**Comment by rikschennink** [comment]
Thanks for reporting, should be back up again.
