### ISSUE TITLE
Any method to add clickable link to label?

### ISSUE THREAD

**Issue by zhaoxin** [pqina/filepond#540]
Hi,

Thanks for this awesome project.

I want to add a clickable link to labelFileProcessingComplete for my users take some action on succeed uploading.
e.g. "Upload succeed. <a href='/view_data'>Go to view data</a>"
But it seems that the HTML is escaped in the label.
Any method or planned feature for this?

Regards.

**Comment by rikschennink** [comment]
No feature planned for this, I'd advise to hide FilePond or show the message above the drop area instead of in the file itself where space is limited.

**Comment by zhaoxin** [comment]
> No feature planned for this, I'd advise to hide FilePond or show the message above the drop area instead of in the file itself where space is limited.

Got it. Thanks.
