### ISSUE TITLE
filepond.supported not working as expected

### ISSUE THREAD

**Issue by philipca** [pqina/filepond#541]
The following code:

```js
if(!FilePond.supported()){
    window.location = window.location.origin + "/not-supported.php";
};
```

does NOT result in the user being taken to the file "not-supported.php"
when the page is opened in Safari 7 or 8, or in Android 5.

**Comment by rikschennink** [comment]
Need more details on which which Android 5 browser is used.

Detection of Safari 7 / 8 is improved in release 4.19, will close for now.
