### ISSUE TITLE
Filepond preview but don't upload feature

### ISSUE THREAD

**Issue by serendipity1004** [pqina/filepond#542]
This is a great library to upload images and files (post request). However, it would be even better if we can use it for patches. Say for example, right now, if we programmatically trigger addFile it will upload the file to the server. However, I think it would be useful if we can just provide the preview of already uploaded file and do not process the upload. This way, users can view the files already uploaded and also add images to the list.

**Comment by rikschennink** [comment]
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

**Comment by fansheng0594** [comment]
"filepond": "^4.30.4"
https://pqina.nl/filepond/docs/api/exports/#setoptions

`instantUpload: false`
