### ISSUE TITLE
Pass object to `load` in a custom `server.process` callback

### ISSUE THREAD

**Issue by LostKobrakai** [pqina/filepond#547]
**Describe the bug**
The input parameter type for `load` within a `server.process` callback allows for objects or strings:
https://github.com/pqina/filepond/blob/d1dd6dbfb6259d51c77bf07a9f1e0d33c1d90777/types/index.d.ts#L136

When I supply an object the hidden input does not have a proper value though, but it's set to `undefined`.

**Expected behavior**
Supplying an object does work.

**Information about your project:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 11)
FF 79

- Your operating system: (e.x. MacOS 10, Ubuntu Linux 19.10, Windows 10, etc)
Mac OS Catalina

- FilePond version (Please check you can reproduce the issue with the latest release!)
4.19.2

**Additional context**
<img width="484" alt="Screenshot 2020-07-29 16 25 33" src="https://user-images.githubusercontent.com/2489835/88812552-2305ed00-d1b8-11ea-8ac9-558d1e07f9ae.png">
<img width="893" alt="Screenshot 2020-07-29 16 29 46" src="https://user-images.githubusercontent.com/2489835/88813039-bb03d680-d1b8-11ea-8d91-1e6b152b4008.png">

**Comment by rikschennink** [comment]
I believe the object should have a `body` property like so. 

```js
{
    body: /* file identifier here */,
}
```

I'd advise to return a string instead. The object format is used internally.

**Comment by LostKobrakai** [comment]
Ok, I've just serialized the object to json for now, so I'll just keep doing so.

**Comment by rikschennink** [comment]
@LostKobrakai Just make sure each object serialisation results in a unique string.

**Comment by LostKobrakai** [comment]
The object includes the unique path. I just need to also send back the original filename, as it might not be part of the path and the upload alone doesn't store it elsewhere.
