### ISSUE TITLE
File size validation (maximum file size feature) does not trigger at all. (see pics)

### ISSUE THREAD

**Issue by Danscap** [pqina/filepond#550]
Filepond: latest version (4.19)

react 16.8.0

**Relevant images of the problem:**

Imports and registering the plugins:

![image](https://user-images.githubusercontent.com/34867523/89804121-bec12280-db01-11ea-8366-225ec6780bed.png)

The filepond component... relevant areas:

![image](https://user-images.githubusercontent.com/34867523/89804247-e6b08600-db01-11ea-8e64-4f72134599ec.png)

How it is called in parent component:

![image](https://user-images.githubusercontent.com/34867523/89804386-1cee0580-db02-11ea-900a-78a6aa20b241.png)

Filepond in action:

![image](https://user-images.githubusercontent.com/34867523/89804525-4c9d0d80-db02-11ea-90b5-9425a0181b61.png)

As you can see, the custom message I triggered when the max total file size of the pond is exceeded does not display, and there is nothing stopping users from uploading beyond 2MB which is the size I set for the maximum.

Please advise, I believe this is a bug.

**Comment by Danscap** [comment]
I am so sorry I had typos in my code, please ignore. I closed as soon as I realized my error.

**Comment by rikschennink** [comment]
@Danscap no worries :-) 👍
