### ISSUE TITLE
error using "beforeAddFile"

### ISSUE THREAD

**Issue by royer-r-arevalo** [pqina/filepond#551]
Hello

I'm trying to change the maxFiles property based on the selected file.

Example

by default set the maxFiles property to 5, in case the file being loaded is zip, the maxFiles property must change to 1.

to do this use the "beforeAddFile" event, which allows me to evaluate the file before it is loaded into the component and thus change the property.

but this event throws me the following error:

![image](https://user-images.githubusercontent.com/69604497/90067420-15269080-dcbd-11ea-864e-59dcfc0e3bcf.png)

what has me more confused is that on some occasions this error is not shown and works perfectly.

some idea of how you can fix it or maybe another idea of how you can change the maxFiles property depending on the files that are selected.

this is my code

![image](https://user-images.githubusercontent.com/69604497/90067726-8403e980-dcbd-11ea-9332-b785b6b6e697.png)

**Comment by rikschennink** [comment]
Updating the property while files are being added will probably not work. I'd advise reading out the current files and then returning false if it's one file and it's a zip.

**Comment by rikschennink** [comment]
closed because inactive for 8 days.
