### ISSUE TITLE
Removing files loaded from the server, does not fire any events 

### ISSUE THREAD

**Issue by adars47** [pqina/filepond#552]
**Describe the bug**
When i press the remove button, the image is removed from the UI, but no event gets fired or request gets send. This only happens for files loaded using file param during initalization. ( for files already uploaded in the server) 

**Logs**
Nothing gets logged and no error is posted in the console.

**To Reproduce**
Create an files array, and pass it as the option during initialization, implementation is below
after initialzation and sucessful loading of image, press the remove button on the image.

**Expected behavior**
An error, or a request being sent to the server.

**Information about your project:**
Chrome 84.0.4147.105
Windows with WSL 2 running ubuntu 18
Filepond Version 4.19.2

**Additional context**

This is how i am initalizing it. When i press the remove button, the image is removed from the UI, but no event gets fired or request gets send, i have looked all over the docs but couldn't find anything relevant

```
FilePond.setOptions({
    acceptedFileTypes: ['image/*'],
    allowMultiple: true,
    allowFileEncode: true,
    name: "images",
    server: {
        url: post_url,
        process: {
                url: '',
                method: 'POST',
                headers: {
                    'X-CSRF-TOKEN': '1UDR3e0DeoRU4HT4LtwPpVDyo8zvck5JnuFLMbKj'
                },
                withCredentials: false,
            },
        revert: {
            url: '',
            method: 'POST',
            headers: {
                'X-CSRF-TOKEN': '1UDR3e0DeoRU4HT4LtwPpVDyo8zvck5JnuFLMbKj',
                '-method':'delete'
            },
            withCredentials: false
        },
        load: (source, load, error, progress, abort, headers) => {
            var myRequest = new Request(source);
            fetch(myRequest).then(function(response) {
              response.blob().then(function(myBlob) {
                load(myBlob)
              });
            });         
        },
    }
});

const inputElement = document.querySelector('#images');

const pond = FilePond.create( inputElement ,{
    files: [
                {
            source: 'http://fds.test/storage/food_item/1/3/jjq0T49dtUnfMPQJ0TI7GpU8Uy6wDbawSjbzWqBP.jpeg',
            options:{
                type: "local"
            }
        },
        ]
});
```

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.

**Comment by rikschennink** [comment]
You need to implement the `server.remove` property, see: 
https://pqina.nl/filepond/docs/patterns/api/server/#remove

> The remove end point is used to remove local files located on the server. This end point is not enabled by default and can only be set to a custom function.
