### ISSUE TITLE
Headers update are not reflected in FilePond PATCH calls.

### ISSUE THREAD

**Issue by osnodegeoffrey** [pqina/filepond#553]
**Describe the bug**
My case is when I have huge file upload chunked. I have my JWT token in the headers but it expires during the upload. 
My solution does update the token in the Vuex store and, as far as I can tell, it seems to get updated in the FilePond component (using Vue chrome extension) under props -> server -> patch -> headers. However the XHR calls are still using the outdated token and I get an HTTP 401.

**Logs**
Getting HTTP 401

**To Reproduce**
Not easy to reproduce but here are the basics from the code is:
```
<FilePond :server="serverOptions" :chunkUploads="true"/>
...
computed: {
  ...mapState({
    token: state => state.access_token
  }),
  serverOptions () {
    process: {
      url: './process/',
      headers: {
        Authorization: 'Bearer ' + this.token,
        'x-access-token': this.token
      }
    }
  }
}
```

**Expected behavior**
Update of the headers should be seen in FilePond XHR call

**Information about your project:**
MacOS 10, Chrome 84, Filepond 4.19.2, Vue-FilePond 6.0.2, Vue 2.6.11

**Additional context**
I'm not sure if it is a problem in FilePond itself or in Vue-FilePond (or in my code). It seems like, if I try to continue the upload (retry), it actually works.

**Comment by rikschennink** [comment]
Not sure if this will fix this specific issue but you can set the server `headers` property to a function, in which case FilePond will call this function before each request to get the headers.

You will have to supply these chunk props yourself. `chunk` has a reference to the `file` so that should be possible.

```
'Content-Type': 'application/offset+octet-stream',
'Upload-Offset': chunk.offset,
'Upload-Length': file.size,
'Upload-Name': file.name
```

See FilePond inner logic below:
```js
const headers = typeof chunkServer.headers === 'function' ? chunkServer.headers(chunk) : {
            ...chunkServer.headers,
            'Content-Type': 'application/offset+octet-stream',
            'Upload-Offset': chunk.offset,
            'Upload-Length': file.size,
            'Upload-Name': file.name
};

const request = chunk.request = sendRequest(ondata(chunk.data), requestUrl, {
            ...chunkServer,
            headers
});
```

So something like this should work:

```js
FilePond.setOptions({
    server: {
        process: {
            // other props
            headers: function(chunk) {
                return {
                    // headers
                }
            },
        },
    },
})
```

**Comment by osnodegeoffrey** [comment]
Thanks Rik.
I checked it out and it works. 

A couple of notes though:
- I believe it should be in the patch part of the configuration
- If anyone else comes across this, you would need to add the headers created for you in the default inner logic

Here is my sample from my Vue file using Vuex store:
```javascript
serverOptions: {
  // other props
  patch: {
    headers: function (chunk) {
      return {
        Authorization: 'Bearer ' + store.access_token,
        'Content-Type': 'application/offset+octet-stream',
        'Upload-Offset': chunk.offset,
        'Upload-Length': chunk.file.size,
        'Upload-Name': chunk.file.name
      }
    }
  }
}
```
This works even if it is set in the `data` element (not needed to have it in `computed`

Dank U vel (I guess)

**Comment by rikschennink** [comment]
Thanks, I've updated the code snippet accordingly

> Dank U vel (I guess)

👍 💯
