### ISSUE TITLE
allowRevert: false doesn't remove the X button when initial files are loaded.

### ISSUE THREAD

**Issue by ziming** [pqina/filepond#554]
**Describe the bug**

My filepond component load the already uploaded files as seen in the screenshot below. The 3 files you see there are previously uploaded before I navigate back to the upload page.

https://share.getcloudapp.com/nOukv2O8

As you can see the X button is there allowing people to click it to have the file disappear from the filepond component. When the page refresh, the files come back since I don't allow delete of uploaded files. Which is the right behaviour but the X button shouldn't be there in the 1st place since I set allowRevert: false to the Filepond component

**Logs**
There are no logs, this is entirely visual

**To Reproduce**

```javascript
FilePond.create(inputElement, {
        labelIdle: 'Upload Here',
        acceptedFileTypes: 'application/pdf',
        allowRevert: false,
        server: {} // removed for sensitivity
        // other items like server and such
}
```

A brief look at 1 of the items in the files array

```javascript
'files': [
            {
                source: '12345',
                options: {
                    type: 'local',
                    file: {
                        name: 'abc.pdf',
                        size: '20000',
                        type: 'application/pdf',
                    },
                }
            },
        ],
```

**Expected behavior**
There shouldn't ben an X when allowRevert is false

It also feel a bit weird that the uploaded files appears as black instead of green but I guess you guys probably have a good reason for it.

**Stacktraces**
None

**Information about your project:**

All browsers

All OS

 "filepond": "^4.19.2"

None!

**Comment by ziming** [comment]
Edited!

**Comment by rikschennink** [comment]
@ziming you can now disable the remove button by setting `allowRemove` to `false`

**Comment by rikschennink** [comment]
Closed because inactive
