### ISSUE TITLE
Reverting multiple files removes from server only first one

### ISSUE THREAD

**Issue by micrac** [pqina/filepond#555]
When trying to revert multiple files (by calling pond.removeFiles()) that were added to filepond on client side only first one is removed from the server. Also, only first one is removed from UI.
I checked that files appear correctly on server side and filedpond collects appropriate fileServerIds from the server.

My observation: inside the method removeFiles(), when removeFile() is called, the file argument has appropriate serverId. Then, when being passed to store.dispatch in removeFile(), the second argument does NOT contain serverId any more (Object.assign({}, options, { query: query})). Finally, when being dispatched (dispatch() function, actionHandlers[type](data)), in methdod getItemByQueryFromState() the query is always undefined (probably for this reason the first file is used for revert function, since the first entry does not disapear before the whole revert process finishes, it is always used for reverting). 

This problem appears always.

I would expect that the method removeFiles() removes all files from the server.

I am using:
Chrome 84.0.4147.135
Windows 10
Angular 8.3
FilePond 4.19.2

**Comment by rikschennink** [comment]
Thanks for reporting, will look into this ASAP.

**Comment by rikschennink** [comment]
Should be fixed in `4.20.0` please confirm

**Comment by rikschennink** [comment]
Closed because inactive
