### ISSUE TITLE
Add support HTML for "capture" attribute in file input field

### ISSUE THREAD

**Issue by Eric24** [pqina/filepond#560]
On phones or tablets that have still cameras, it is possible to automatically select camera input when doing a conventional HTML file upload, but including the "capture" attribute (with a value of "user" or "environment", but even "true" works on all platforms we've tested). If the device does not have a still camera (like a laptop) or the platform doesn't support the "capture" attribute, then it's ignored and will behave in whatever the default is for the device (like showing the file browser).

I would like to see the option of setting the "capture" attribute as part of the filepond config (i.e. set it to the value of "user", "environment", etc.) and have filepond include the attribute (when defined) in the HTML file input field used when a user clicks on the filepond field. Filepond itself doesn't need to care what the value is and wouldn't need to do anything else except add it to the HTML file input field.

This will allow the developer to automatically select the camera(s) on phones/tablets, if they wish to "force" the user to take a new photo at that time, rather than be able to select a photo from their gallery.

**Comment by rikschennink** [comment]
It should be possible to set the `captureMethod` prop. Does it not work?

**Comment by Eric24** [comment]
Ah, maybe so. I didn't see that prop. Is it supported in version 4.12?

**Comment by rikschennink** [comment]
It should be

**Comment by rikschennink** [comment]
will close for now

**Comment by Abhi0725** [comment]
@rikschennink I have added `captureMethod: "camera",` in "options during FilePond.create()". But the browser on laptop always opens file browser. Isn't camera option supported?

**Comment by rikschennink** [comment]
@Abhi0725 

see this comment in the code

```js
    // Allow media capture when value is set
    captureMethod: [null, Type.STRING],
    // - "camera", "microphone" or "camcorder",
    // - Does not work with multiple on apple devices
    // - If set, acceptedFileTypes must be made to match with media wildcard "image/*", "audio/*" or "video/*"
```

**Comment by Abhi0725** [comment]
@rikschennink Yes tried that but it works on mobile device only.

**Comment by rikschennink** [comment]
@Abhi0725 Then it's likely the browser on your laptop doesn't support selecting the camera.

Alternatively you can use WebRTC to capture a photo and then send the resulting file to FilePond.
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos
