### ISSUE TITLE
CORS errors using GCP's cloud storage

### ISSUE THREAD

**Issue by secmin** [pqina/filepond#564]
Chrome: the latest
Framework: vue(nuxt.js)
File Pound The Latest

I use vuetify in my design framework, but it displays fine even if you use a direct link to cloudStorage.
When I put an image link to filepond for initial display, I get a CORS error.
I'm having trouble recovering even after setting up cloudStorage's CORS.
Why do I get a CORS error only when displaying with filepond?

**Comment by rikschennink** [comment]
Image data is resized and presented in a <canvas> element so CORS needs to be configured on the remove server.

Please, next time when you submit an issue, follow the issue template (it's the text in the issue text area). 👍
