### ISSUE TITLE
multiple fields - Identify instances index ?

### ISSUE THREAD

**Issue by laurent-d** [pqina/filepond#57]
Hi !
Is there way to get the index of field, for example to get some info about dom parent when we have multiple instances ? (i didn't found it on documentation)
Or we have to create all instances separately ?

**Comment by rikschennink** [comment]
The `FilePond.create` method returns an array of instances. Each instance has an `element` property which you can use to identify it on the page. If you need a FilePond instance bound to a certain DOM element you can use the `FilePond.find(certainDOMElement)` method and it will return the instance bound to the passed element.
