### ISSUE TITLE
Waiting for size, similar to #490

### ISSUE THREAD

**Issue by fisketavlingnu** [pqina/filepond#575]
**Describe the bug**
I have been using filepond on my website successfully for quite a while. But now I can see that on at least android and chrome it get stuck with  "waiting for size". 

It is not for all images.  But I have a specific image that creates the problem.

My code:
```html
</div>
  <script src="https://unpkg.com/filepond-plugin-file-metadata/dist/filepond-plugin-file-metadata.js"></script>          
  <script src='https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.min.js'></script>
  <script src='https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js'></script>
  <script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>
  <script src='https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.min.js'></script>
  <script src="https://unpkg.com/filepond-plugin-image-crop/dist/filepond-plugin-image-crop.js"></script>
  <script src="https://unpkg.com/filepond-plugin-image-resize/dist/filepond-plugin-image-resize.js"></script>
  <script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>
  <script src='https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.js'></script>
  <script src='https://unpkg.com/filepond/dist/filepond.min.js'></script>
<script>
            
  // register desired plugins...
  FilePond.registerPlugin(
// encodes the file as base64 data...
   FilePondPluginFileEncode,
// validates the size of the file...
   FilePondPluginFileValidateSize,
   
   // validates the file type...
   FilePondPluginFileValidateType,
// corrects mobile image orientation...
   FilePondPluginImageExifOrientation,
   
   // calculates & dds cropping info based on the input image dimensions and the set crop ratio
   FilePondPluginImageCrop,
   
   //  calculates & adds resize information
   FilePondPluginImageResize,
   
   // applies the image modifications supplied by the Image crop and Image resize plugins before the image is uploaded
   FilePondPluginImageTransform,
// previews dropped images...
   FilePondPluginImagePreview,
// Add water mark
   FilePondPluginFileMetadata




  );
// Select the file input and use create() to turn it into a pond
  FilePond.create( document.querySelector('.filepond'), { 
    labelIdle:'<span class="filepond--label-action">Klicka här</span>',
   allowMultiple: true,
   allowFileEncode: true,
   maxFiles:2,
   required: true,
   maxParallelUploads:2,
   instantUpload:true,
   acceptedFileTypes: ['image/*'],
   imageResizeTargetWidth: 800,
//   imageCropAspectRatio: '1:1',
   imageResizeUpscale:false,
   imageTransformOutputStripImageHead: false,
   imageTransformOutputQuality: 60,
   imageTransformOutputMimeType: 'image/jpeg',
   imageTransformVariants: {
        'resized_': transforms => {
            transforms.resize.size.width = 800;
            return transforms;
        }
   } ,
   FileMetadataObject: {
        'markup': [
            [
                'rect', {
                    left: 0,
                    right: 0,
                    bottom: 0,
                    height: '60px',
                    backgroundColor: 'rgba(0,0,0,0)'
                },
            ],
            [
                'image', {
                    right: '10px',
                    bottom: '10px',
                    width: '128px',
                    height: '34px',
                    src: 'https://fisketavling.nu/images/mylogos/watermark_ver1.png',
                    fit: 'contain'
                }
            ]
        ]
    }
  }
  );

```

**Logs**
Browser Console:
`
Uncaught (in promise) TypeError: Cannot read property 'size' of undefined
    at resized_ (registrera-fangst-team?cid=472&team_name=Robusto&pos=59.4813446,18.234440199999998&browser=Chrome&bversion=85.0.4183.121&os=Windows&acc=1756:434)
    at filepond-plugin-image-transform.js:3661
    at filepond-plugin-image-transform.js:3772
    at new Promise (<anonymous>)
    at filepond-plugin-image-transform.js:3771
    at filepond-plugin-image-transform.js:3926
    at Array.map (<anonymous>)
    at filepond-plugin-image-transform.js:3925
`
**To Reproduce**

This is the file that causing the problem

![0733d68a-e0d9-4d48-b507-e416d6551590](https://user-images.githubusercontent.com/53155624/94448294-059ad280-01ab-11eb-9b42-4294f714a81b.jpg)

I can make it possible to run on our site https://fisketavling.nu
(Just contact me for more information)

**Expected behavior**
Image resized and displayed.

**Stacktraces**
None

**Information about your project:**
- Your browser and the version: Chrome Version 85.0.4183.121 (Officiell version) (64 bitar)

- Your operating system: Windows 10 /Android

- FilePond version (Please check you can reproduce the issue with the latest release!)
Using unpkg.com = latest

**Additional context**
Used for downloading images of fish from mobile phones during competition.

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.

**Comment by fisketavlingnu** [comment]
Updated according to template

**Comment by fisketavlingnu** [comment]
Hmm, my example image was smaller so I changed 
   imageResizeUpscale:false to
   imageResizeUpscale:true,

**Comment by rikschennink** [comment]
Can you try the solution offered in this thread:
https://github.com/pqina/filepond-plugin-image-transform/issues/21

**Comment by fisketavlingnu** [comment]
This problem arises when the image is to small.   In my case < 800 px. By changing
imageResizeUpscale:false
 to
imageResizeUpscale:true,
The problem disappeared and it worked.

But I guess that the correct behaviour would be not resize the image if width in uploaded picture was to small.

**Comment by rikschennink** [comment]
will close because this seems to be resolved? unclear.
