### ISSUE TITLE
File size calculation configurable as binary or decimal

### ISSUE THREAD

**Issue by jmhellman** [pqina/filepond#576]
**Is your feature request related to a problem? Please describe.**
A few questions from customers have arisen regarding the difference between what a user sees for file size information in Windows vs what is displayed as the size of file when chosen for upload. The disparity increases as the file size increases -- for example a file Windows reports as an 8.61 GB file (9,255,155,634 bytes) displays in the interface as a 9.26 GB file. 

**Describe the solution you'd like**
I can see an argument for wanting to use a base 10 calculation instead of the binary divide-by-1024 calculation. I propose a configuration to File Pond (and in my case the React implementation) that will allow a developer to choose what type of calculation to apply. This would impact behavior for the displayed file info, as well as the file size validation plugin.

**Describe alternatives you've considered**
We've talked about adjusting our file size restriction to accommodate the disparity to help prevent a user from trying to upload too large of a file and then getting confused, however the root question of the difference between the OS and what we display won't go away.

**Additional context**
![file upload disparity](https://user-images.githubusercontent.com/29870168/94485842-24e23180-01a4-11eb-9b79-fff4bd27a0b8.png)

**Comment by rikschennink** [comment]
Will add new prop to configure this at the start of next week.

**Comment by rikschennink** [comment]
Now available in `4.21.0` 👍
