### ISSUE TITLE
issue with Huawei mobile phone

### ISSUE THREAD

**Issue by yguerdat** [pqina/filepond#577]
**Describe the bug**
It's actually not possible to use the plugin filepond on a Huawei P20 Pro and on this mobile phone only. I get an error every time I try to upload a file on this mobile phone but it's working fine on any other Android or iOS phone. We are actually working with the version 4.11.0 but we can reproduce the bug on the last version of the plugin.

**Logs**
Here is a sample of the error message : https://usersnappublic.s3.amazonaws.com/2020-09-15/15-12/403c5441-cb8a-4eae-82ab-69689930a37c.png 

**Information about your project:**
- Your browser and the version: Android 10 - Chrome 85.0.4183.120 / 85.0.4183.127
- Your operating system: Huawei P20 Pro CLT-L29
- FilePond version : 4.11.0

**Additional context**
OS of the mobile phone is in french

**Comment by rikschennink** [comment]
Can you reproduce the issue on https://pqina.nl/filepond

**Comment by yguerdat** [comment]
Yeah I confirm you that I can reproduce the issue on the URL you give me.

**Comment by rikschennink** [comment]
Tried to test this on BrowserStack but I can't find the device.

**Comment by rikschennink** [comment]
Any errors in the developer console?

**Comment by rikschennink** [comment]
Closed because inactive.
