### ISSUE TITLE
Hook beforeDropFile is not working

### ISSUE THREAD

**Issue by tzsk-rw** [pqina/filepond#579]
I have the issue detailed in the `filepond-vue` repository. Please read that first: https://github.com/pqina/vue-filepond/issues/176

I'm creating this one as well, cause I looked into the Vue component file in that package as well, and there is nothing that is happening differently for `beforeAddFile`. Then still the `beforeAddFile` is working and `beforeDropFile` is not. 

Which got me thinking that, it might be some kind of issue with the source repository as well.

Here is the example again for quick reference: https://jsfiddle.net/9vb3cf75/

**Comment by rikschennink** [comment]
Please don't double post. I've moved your other issue here.
