### ISSUE TITLE
Upload files directly to S3 with server signing using Laravel

### ISSUE THREAD

**Issue by simioluwatomi** [pqina/filepond#58]
For brevity sake, I won't be including steps on how to create a S3 bucket, set up of CORS configuration and how to setup the aws sdk in your laravel project. If you want to do that, kindly visit this [link](https://cwhite.me/avoiding-the-burden-of-file-uploads/)

**Code updated to reflect @rikschennink's comment**

```js
    FilePond.registerPlugin(
        FilePondPluginFileValidateSize,
        FilePondPluginFileValidateType
    );
    // create a FilePond instance at the input element location
    const pond = new FilePond.create(document.querySelector("#filepond"), {
        maxFiles: 1,
        allowPaste: false,
        maxFileSize: "3MB",
        acceptedFileTypes: ['image/png', 'image/jpeg'],
        server: {
            timeout: 99999999,            
            process: function (fieldName, file, metadata, load, error, progress, abort) {
                var filepondRequest = new XMLHttpRequest();
                var filepondFormData = new FormData();
                fetch("/audio/signed", {
                    headers: {
                        "Content-Type": "application/json",
                        "Accept": "application/json",
                        "X-Requested-With": "XMLHttpRequest",
                        "X-CSRF-Token": $('input[name="_token"]').val()
                    },
                    method: "post",
                    credentials: "same-origin",
                    body: JSON.stringify({
                       fileName: metadata.fileInfo.filenameWithoutExtension,
                       fileExtension: metadata.fileInfo.fileExtension
                    })
                })
                    .then(function (response) {
                        return response.json();
                    })
                    .then(function (json) {
                        file.additionalData = json.additionalData;
                        // append the FormData() in the order below. Changing the order
                        // would result in 403 bad request error response from S3.
                        // No other fields are needed apart from these ones. Appending extra
                        // fields to the formData would also result in error responses from S3.
                        for (var field in file.additionalData) {
                            filepondFormData.append(field, file.additionalData[field]);
                        }
                        filepondFormData.append("file", file);
                        filepondRequest.upload.onprogress = function (e) {
                            progress(e.lengthComputable, e.loaded, e.total);
                        };
                        filepondRequest.open("POST", json.attributes.action);
                        filepondRequest.send(filepondFormData);
                        load(`${ file.additionalData.key }`);
                    });                
                progress(true, 0, file.size);
                return {
                    abort: (function () {
                        filepondRequest.abort();
                        abort();
                    });
                };
            }
        }
    });
    pond.on("addfile", function (error, file) {
        if (error) {
            return;
        }
         // Set file metadata here in order to retrieve it in the custom process function
         // file attributes like fileExtension and filenameWithoutExtension
         // are not availabe in the file object in the custom process function
        file.setMetadata('fileInfo', {
            filenameWithoutExtension: file.filenameWithoutExtension,
            fileExtension: file.fileExtension
        });
    });
```

@rikschennink 
The arguments of the `progress` callback in the custom `progress` function are not clear enough. `Computable` is a boolean; what are `curent` and `total`? Should `current` always be set to 0? Should `total` always be 1024 or set to the size of the file being uploaded? I ask because when `total` is set to 1024 or `file.size`, the upload progress is always miscalculated so upload progress always reaches 100% before file upload is actually complete.

Now to the Laravel code. Below is the `Controller` that contains the `signed` method which is called when the `audio/signed` route is hit.

```php
<?php

namespace App\Http\Controllers\Web;

use Aws\S3\S3Client;
use Aws\S3\PostObjectV4;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class AudioController extends Controller
{
    protected $client;

    public function __construct(S3Client $client)
    {
        $this->client = $client;
    }

    /**
     * Generate a presigned upload request.
     *
     * @param $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function signed(Request $request)
    {
        $options = [
            ['bucket' => config('services.s3.bucket')],
            ['starts-with', '$key', env('AUDIO_PATH')]
        ];

       // Rename the file before being uploaded
        $filename = md5($request->fileName . microtime()) . '.'. $request->fileExtension;
        $postObject = new PostObjectV4(
            $this->client,
            config('services.s3.bucket'),
            ['key' => env('AUDIO_PATH') . $filename,],
            $options,
            '+1 minute'
        );

        $this->formInputs = $postObject->getFormInputs();
        return response()->json([
            'attributes' => $postObject->getFormAttributes(),
            'additionalData' => $postObject->getFormInputs()
        ]);
    }
}
```

Finally, the documentation needs to be clearer. I found some callback names unintuitive. The custom `process`, `revert`, and `fetch` functions have an `error` callback. I was expecting them to have a `success` callback but it is named `load`.

**Comment by rikschennink** [comment]
Thanks for the example!

> For some weird reason the file object here is different from the one in the onaddfile callback. Therefore file attributes like fileExtension, filename, filenameWithoutExtension return null here

The `file` param of the `process` method contains the native file object, access to the file item is restricted inside the process method. You could then set properties or run functions that would contradict or interfere with the current processing of the file.

> The arguments of the progress callback in the custom progress function are not clear enough.

This is similar to the values exposed by the `onprogress` event of the `XMLHttpRequest` object. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress

You can pass the total file size to `total` and use the `progress` event to update the currently loaded size. FilePond will then show the progress. Calling `progress(false)` will automatically switch the loading indicator to infinite mode.

> Also, for some weird reason, the load callback takes only strings as a parameter. In this particular case, uniqueFileId should be file.additionalData.key as S3 sends responses only in headers. The only way that can be supplied to the load callback is

Pass it like this, it currently accepts either a string ( id ) or an object. So the key is probably a number and the code doesn't facilitate those.

```js
load(`${ file.additionalData.key }`);
```

> Finally, the documentation needs to be clearer. I found some callback names unintuitive. The custom process, revert, and fetch functions have an error callback. I was expecting them to have a success callback but it is named load.

It's named `load` because that's what it's called when using `XMLHttpRequest`.
https://developer.mozilla.org/en-US/docs/Web/Events/load

I appreciate the feedback and will try to improve the docs, but there's only so much hours in a day so any ideas and improvements are welcome. The docs are open source as well so you can easily make improvements: https://github.com/pqina/filepond-docs

-------

Please note that your current setup doesn't work when uploading multiple files because the XMLHttpRequest object is created outside of the pond instance. It's a single object used by every process call, it's better to instantiate it ( and the FormData object ) inside the process method.

If you need the `filenameWithoutExtension` and `fileExtension` values inside the process method you can use the `setMetadata` method and add them to the file object inside the `"addfile"` callback. They are then available in the `metadata` parameter.

```js
pond.on('addfile', function (error, file) {
    if (error) {
        return;
    }
    file.setMetadata('info', {
        filenameWithoutExtension: file.filenameWithoutExtension,
        fileExtension: file.fileExtension
    });
});
```

These changes should make the code functional for multi-file upload mode.

**Comment by simioluwatomi** [comment]
@rikschennink Thanks for your comment. I have made changes to the code to reflect your suggestions 

> You can pass the total file size to total and use the progress event to update the currently loaded size. FilePond will then show the progress.

Could you provide an example of how to do this? My javascript skills are not at ninja level yet.

> Please note that your current setup doesn't work when uploading multiple files because the XMLHttpRequest object is created outside of the pond instance. It's a single object used by every process call, it's better to instantiate it ( and the FormData object ) inside the process method.

Spot on. I noticed that if I revert a successful upload then perform another upload, the second file does not get uploaded. Your suggestion fixes that.

I will definitely take a look at the docs and fix some typos.

**Comment by rikschennink** [comment]
> Could you provide an example of how to do this? My javascript skills are not at ninja level yet.

Adding this before `filepondRequest.open`should work:

```js
filepondRequest.upload.onprogress = e => {
    progress(e.lengthComputable, e.loaded, e.total);
}
```

**Comment by simioluwatomi** [comment]
> Adding this before filepondRequest.open should work:

```
filepondRequest.upload.onprogress = e => {
    progress(e.lengthComputable, e.loaded, e.total);
}
```
Unfortunately, this
- makes it impossible to cancel any uploads in progress
- file preview turns green (indicating upload is complete) just before upload starts, then reverts to the default grey color when upload starts. When uploading progress gets to 100%, file progress doesn't change to `Upload complete`;

>     // Can call the error method if something is wrong, should exit after
    error('oh my goodness');

Could you please provide a sample implementation?

Thank you!

**Comment by rikschennink** [comment]
You're calling `load` immediately without waiting for the upload to finish. Also there's stray `progress` after the `fetch` closes, that needs to be removed.

![screen shot 2018-06-15 at 09 23 42](https://user-images.githubusercontent.com/1132575/41455741-818e560c-707e-11e8-839b-49b7a65dbbf6.png)

Add this before the `filepondRequest.send()`

```
filepondRequest.onload = function () {
    load(`${ file.additionalData.key }`);
};
```

More information on the XMLHttpRequest object.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget/onload

**Comment by simioluwatomi** [comment]
Thank you for your patience, really appreciate. I am also working on the docs to make them extremely easy to understand for novices like me. Would send a PR soon!!!

**Comment by rikschennink** [comment]
No problem! PR's on the docs are very much appreciated! Thanks in advance :-)

**Comment by Kendysond** [comment]
Hi @simioluwatomi , please would you mind sharing the final code you use that worked for s3 presigned uploads?

**Comment by simioluwatomi** [comment]
@Kendysond the code is what you have as my first post in the issue which I clearly indicated has been amended to reflect all comments in the issue. So I believe the code up there works

**Comment by vesper8** [comment]
@simioluwatomi Thanks a lot for sharing the amended code. I'm trying to achieve the very same thing.

Can you confirm if your shared code works for uploading multiple files at the same time?

One thing I am a bit confused about is regarding the entire flow.

Right now you make a call to the back-end to get the signed-urls, then use those to upload files to S3 directly

But then what? I would imagine that once the files are done uploading to S3 a response is sent back to Filepond, and then you take that response and send it back to your back-end so that your back-end can log the upload file entries in a database so it knows which files are available for that user?

I'm using laravel-medialibrary, and all uploads need to be stored in my back-end (not the files themselves but records of them). Perhaps in your use-case you didn't need to do that and once the file is uploaded to S3 then the job is done and over?

**Comment by simioluwatomi** [comment]
@vesper8 this project was so long ago.

But if I remember correctly, AWS S3 sends responses and the things you'd need were in the response headers (that might have changed).

Yes, the code works as at when it was written. I'd suggest you take a stab at it, upload a small file to S3, then check the response S3 sends back (do not ignore the response headers).

I'd try poking through my laptop to see if I can come across the project. If I do, I'd update with S3 responses (as at the time the code was written)

**Comment by vesper8** [comment]
Many thanks for the response @simioluwatomi : )

It was a while ago but still super relevant and with a rather glaring absence of good guides on how to do this common thing so your post is very useful indeed.

I did also find https://cwhite.me/blog/avoiding-the-burden-of-file-uploads which speaks of the same things, I wonder if he used your info as a basis for his.. or perhaps vice-versa

I will be taking a stab at it in a few hours.. but if you do find more useful bits to add as you mentioned I would appreciate you posting them! I'm sure it will be useful to me and to future users trying to achieve the same

**Comment by majortom64** [comment]
@vesper8 Did you ever get it working? I think my use case is similar to yours. I want to upload the files, and then send the metadata (actual filename, original file path, _etc._) to my backend once (either as part of the process to get the pre-signed URL or after the upload completes).

**Comment by vesper8** [comment]
@majortom64 I did get it working.. it wasn't easy.. took a lot of trial and error.. and I'm still not 100% happy with the solution, it just seems slow sometimes, it appears to be AWS itself that can be slow at times. Also had to deal with some race conditions related to thumbnail creation. Overall I'm not overjoyed with Filepond here.. all its animations cause the experience to feel sluggish and lacking polish unfortunately.

**Comment by rikschennink** [comment]
@vesper8 Sorry to hear that. Are you uploading in the `server.process` hook or have you opted for a different solution.

**Comment by majortom64** [comment]
@vesper8 Would you be willing to post your code (or share it with me privately)? It would help me a lot.

**Comment by vesper8** [comment]
Hey @majortom64 and @rikschennink 

Sorry for the long reply, been a bit crazy during the holidays, I intended to reply though : )

I guess this means I use the `server.process` ? Sorry, a bit unsure here.

I really would like to optimize this in the future because right now uploading 4 images at the same time results in a lot of jankiness and it seems related to the animations. I don't have time to dive deep right now but I will come back to this later with an upload video of what I'm getting. I'm using your Pintura editor as well in the process, pretty much exclusively for its crop feature, and this might be one of the causes for the slowness I'm experiencing.

But if you do spot something odd in the code below I'd love to hear about it.

---------

I hesitated to share my code because it feels a bit messy. But it does work so here you go so hopefully it can help you solve your problem.

The following `serverOptions` basically fetches a pre-signed url from the backend (I use Laravel, and will also share that controller method below), then adds that data to a form request and uploads directly to S3.

```
      serverOptions: {
        url: `${this.$api}/api/v1/profile/images`,

        timeout: 99999999,

        headers: {
          Authorization: `Bearer ${this.$auth.token()}`,
        },

        process: (fieldName, file, metadata, load, error, progress, abort) => {
          const self = this;

          const filepondRequest = new XMLHttpRequest();
          const filepondFormData = new FormData();

          Bus.$emit('loading', true, 'uploading file', 60000);

          this.$http
            .post(`${this.$api}/api/v1/profile/images/signed`, {
              fileName: metadata.fileInfo.filenameWithoutExtension,
              fileExtension: metadata.fileInfo.fileExtension,
            })
            .then((response) => {
              file.additionalData = response.data.additionalData;

              for (const field in file.additionalData) {
                filepondFormData.append(field, file.additionalData[field]);
              }

              filepondFormData.append('file', file);

              filepondRequest.upload.onprogress = function (e) {
                progress(e.lengthComputable, e.loaded, e.total);
              };

              filepondRequest.open('POST', response.data.attributes.action);

              filepondRequest.onload = function () {
                load(`${file.additionalData.key}`);
              };

              filepondRequest.onreadystatechange = function () {
                console.log('filepond-server-s3.process.onreadystatechange.readyState', this.readyState);
                console.log('filepond-server-s3.process.onreadystatechange.status', this.status);
                console.log('filepond-server-s3.process.onreadystatechange.responseText', this.responseText);
              };

              filepondRequest.send(filepondFormData);
            });
          return {
            abort() {
              filepondRequest.abort();
              abort();
            },
          };
        },
        load: (source, load, error, progress, abort, headers) => {
          const url = source;
          const myRequest = new Request(url);

          fetch(myRequest).then((response) => {
            response.blob().then((myBlob) => {
              load(myBlob);
            });
          });
        },
        remove: (source, load, error, progress, abort, headers) => {
          this.$http
            .delete(`${this.$api}/api/v1/profile/images`, {
              params: {
                route: this.$route.name,
                source,
              },
            })
            .then((response) => {
              if (response.data === 'deleted') {
                load();
              } else {
                error();
              }

              this.updateFileCount();
            });

          return true;
        },
      },
```

And the PHP controller method for returning the pre-signed urls:

```
    /**
     * @Post("/api/v1/profile/images/signed")
     */
    public function signedUrls(Request $request)
    {
        $s3Client = \Storage::disk('media')->getDriver()->getAdapter()->getClient();

        $photoPath = 'user-data/photos-tmp/';

        $options = [
            ['bucket' => config('services.s3.bucket')],
            ['starts-with', '$key', $photoPath],
        ];

        // Rename the file before being uploaded
        $filename = md5($request->fileName.microtime()).'.'.$request->fileExtension;

        $postObject = new \Aws\S3\PostObjectV4(
            $s3Client,
            config('services.s3.bucket'),
            ['key' => $photoPath.$filename],
            $options,
            '+1 minute'
        );

        $this->formInputs = $postObject->getFormInputs();

        $return = [
            'attributes' => $postObject->getFormAttributes(),
            'additionalData' => $postObject->getFormInputs(),
        ];

        return response()->json($return);
    }
```

Hope it helps

**Comment by rikschennink** [comment]
@vesper8 thanks for posting! I've taken the liberty to format and color the code snippets a tiny bit.

This might definitely have to do with Pintura and the FilePond File Poster plugin. I've recently improved performance quite a bit, see: https://pqina.nl/pintura/changelog/#8.19.2

> Improve performance of FilePond Image Editor plugin, image posters are now generated faster and processing of images is queued allowing for FilePond to stay responsive. Requires updating the FilePond Image Poster plugin. 

I suspect updating will solve the issues. If not, please reach out using the support form on the customer portal, happy to investigate.

**Comment by majortom64** [comment]
@vesper8 Thanks for posting your code. Adding a few comments would make it easier for people who are not using PHP to generate the pre-signed URLs would be great. An example:

```javascript
filepondRequest.open("POST", response.data.attributes.action); //response.data.attibutes.action is the pre-signed URL.
```

My other question is based on this comment:

```javascript
file.additionalData = json.additionalData;
                        // append the FormData() in the order below. Changing the order
                        // would result in 403 bad request error response from S3.
                        // No other fields are needed apart from these ones. Appending extra
                        // fields to the formData would also result in error responses from S3.
                        for (var field in file.additionalData) {
                            filepondFormData.append(field, file.additionalData[field]);
                        }

                        filepondFormData.append("file", file);

                        ```
Are the fields required to be in the right order or does that refer to the adding of the file to the `FormData` object?
Does the PHP `getFormInputs` always return the fields in the right order?

I am not sure it matters, as it does not seem I can set advanced server options on the Vue-FilePond component (my attempt:

```javascript
        <FilePond
          ref="ctPond"
          name="ctUploads"
          label-idle="Drop your documents and/or directories here!"
          allow-multiple="true"
          instant-upload="false"
          server="{
                url:
                      'https://beitshemesh-local.weinzweig.com:22070/api/files/getSignedPostWasabi',
          
                    timeout: 99999999,
          
                    headers: {
                      Authorization: 'Bearer ' + userAccessToken
                    },
          
                    process: (
                      fieldName,
                      file,
                      metadata,
                      load,
                      error,
                      progress,
                      abort
                    ) => {
                      const self = this
          
                      const filepondRequest = new XMLHttpRequest()
                      const filepondFormData = new FormData()
          
                      Bus.$emit('loading', true, 'uploading file', 60000)
          
                      axios({
                        method: 'POST',
                        url:
                          'https://beitshemesh-local.weinzweig.com:22070/api/files/getSignedPostWasabi',
                        headers: {
                          Authorization: 'Bearer ' + userAccessToken,
                          'Content-Type': 'application/json; charset=utf-8'
                        },
                       ... (etc.)
                       "
          :files="ctFiles"
          @updatefiles="handleUpdateFiles"
          @init="handleFilePondInit"
        />
        ```
        Does not seem to work.)

**Comment by vesper8** [comment]
@majortom64 I don't think I can help you more than this. As you can see, the code I shared above, which is 100% working for me, is in large part built from the code that was shared in the original post of this thread. I adapted the Laravel part to use a more up-to-date AWS PHP implementation, that's about all I've changed.

I know that AWS is very strict when using signed urls, so it seems like order matters and things like making sure you don't add more parameters also matters. As for that comment in question, that is copied from the first post in this issue. I did not write that comment. As far as I can tell, the original issue shared a working implementation, but as is often the case, it may need small tweaks for it to work in your specific case.

**Comment by rikschennink** [comment]
@majortom64 When using Vue I'd advise to set your server options in `data` and then use `v-bind`

```vue
<template>
    <div id="app">
        <file-pond
            name="test"
            ref="pond"
            class-name="my-pond"
            label-idle="Drop files here..."
            allow-multiple="true"
            accepted-file-types="image/jpeg, image/png"
            v-bind:server="myServer"
            v-bind:files="myFiles"
            v-on:init="handleFilePondInit"
        />
    </div>
</template>

<script>
    // Import FilePond
    import vueFilePond from 'vue-filepond';

    // Import plugins
    import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.esm.js';
    import FilePondPluginImagePreview from 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.esm.js';

    // Import styles
    import 'filepond/dist/filepond.min.css';
    import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css';

    // Create FilePond component
    const FilePond = vueFilePond(FilePondPluginFileValidateType, FilePondPluginImagePreview);

    export default {
        name: 'app',
        data: function () {
            return {
                 myFiles: ['index.html'],
                 myServer: {
                     /* server options here */
                 }
            };
        },
        methods: {
            handleFilePondInit: function () {
                console.log('FilePond has initialized');

                // example of instance method call on pond reference
                this.$refs.pond.getFiles();
            },
        },
        components: {
            FilePond,
        },
    };
</script>

```

**Comment by KrunchMuffin** [comment]
Is this still the defacto for S3 in 2023?

**Comment by simioluwatomi** [comment]
Update... I just reimplemented this same feature in a few hours using the code I posted about 5 years ago...

So yeah; it works

**Comment by clementmas** [comment]
@rikschennink I'm glad to see you're making good progress on FilePond v5. It's an amazing library!

It would be great to get better support and an official guide for uploading files directly to S3 buckets (and R2, B2, etc.). It looks like the new architecture might help.

**Comment by rikschennink** [comment]
@clementmas I definitely have adding these as extensions on the todo list for when FilePond v5 is out of beta, creating them should be fairly straightforward using the `createStoreExtension` factory.
