### ISSUE TITLE
Hook :before-drop-file is not working

### ISSUE THREAD

**Issue by tzsk-rw** [pqina/filepond#582]
**My code:**
```vue
<Filepond ref="pond" :before-drop-file="beforeDrop" :before-add-file="beforeAdd" :allow-multiple="true" />

// Methods
methods: {
  beforeDrop(file) {
    console.log(file);
    return true;
  },
  beforeAdd(file) {
    console.log(file);
    return !file._relativePath; // Don't add files inside a folder.
  },
}
```

Now, the problem here is, the `beforeAdd` method in my component is firing successfully but not the `beforeDrop`.

### Here is the example for your reference: https://jsfiddle.net/9vb3cf75/

I've tried multiple things like,

```vue
this.$refs.pond._pond.on('beforeDropFile', this.beforeDrop)

<Filepond @beforeDropFile="beforeDrop" :before-add-file="beforeAdd" :allow-multiple="true" />
```

I know that the `.on` is used to listen for the events. But it was worth a try. Also the `@` is for events as well.

**Additional context**

I have a scenario where I want to zip the files in a folder before it is being processed by Filepond. I am successfully being able to do that with `:before-add-file` as of now, but there is a huge performance hit. 

What filepond is doing is, trying to add all of the files first then remove the files based on the return type of the `beforeAdd` method.

So, it shows a huge list of files (1000 files inside a folder) with extreme slowness. Then removes them and when I dynamically drop the zip with `this.$refs.pond.addFile(zip)` it all comes back to normal without any lag.

**Solution**

I was hoping I could tap into the before drop hook and snatch those thousands of files inside the folder before Filepond tries to render them in the DOM and take a lot of memory in doing so. Which could be a huge performance win for my app.

**Comment by rikschennink** [comment]
Is this resolved with the PR?

**Comment by tzsk-rw** [comment]
Yes
