### ISSUE TITLE
URL components  with special characters as & are not encoded.

### ISSUE THREAD

**Issue by nicolaferrara82** [pqina/filepond#587]
**Describe the bug**
I have an issue uploading files with "&" character in url component name, if I process  encodeURIComponent() on the folder name it will also be processed after with encodeUri().

**To Reproduce**
```javascript
FilePond.setOptions({
    allowRevert: false,
    server: {
        url: 'upload?folder='+encodeURIComponent('r&b'),
        process: {
            headers: {
                'X-CSRF-TOKEN': document.getElementsByName("csrf-token")[0].content,
                'X-Requested-With': 'XMLHttpRequest'
            },
            onerror: error => {
                console.log('error', error);
            return error;
            }
        },
    }
```

**Expected behavior**
`upload?folder=r&b` become `upload?folder=r%2526b` instead of `upload?folder=r%26b`

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.

**Comment by nicolaferrara82** [comment]
Solved editing my script appending url component in the formData.

```javascript
FilePond.setOptions({
    allowRevert: false,
    server: {
        url: 'upload',
        process: {
            headers: {
                'X-CSRF-TOKEN': document.getElementsByName("csrf-token")[0].content,
                'X-Requested-With': 'XMLHttpRequest'
            },
            ondata: (formData) => {
                formData.append('folder', 'r&b');
                return formData;
            },
            onerror: error => {
                console.log('error', error);
            return error;
            }
        },
    },
```
