### ISSUE TITLE
Pasting files when focused on another input

### ISSUE THREAD

**Issue by last-partizan** [pqina/filepond#588]
**Is your feature request related to a problem? Please describe.**

https://github.com/pqina/filepond/commit/1a10367bd00ebd38d9ed3ce7898689fab4865e22#diff-13202d0d98680aa2d5c1ee46b009e4ff596b345aa99264cf4cfdd4356d3927d4

This commit removed ability to paste files outside of `.filepond--root`, we're used it with vue with template like this:

```vue
<textarea />
<file-pond />
```

And now pasting files works only with unfocused textarea, this is unexpected behaviour.

**Describe the solution you'd like**
Provide a way to allow pasting from textarea, maybe using class like `filepond--paste` for textarea/inputs or for some shared parent container.

**Describe alternatives you've considered**
For now i fixed it by patching filepond to check not only filepond--root, but also `filepond--paste` class on element.

**Comment by last-partizan** [comment]
I can create PR if you're interested. This is small change.

Or maybe there is some other way to connect filepond to textarea?

**Comment by last-partizan** [comment]
For now i can use in my own code class "filepond--root" on textarea, but i don't think it's a good idea.

**Comment by rikschennink** [comment]
You can handle paste event on the textarea and then pass the file to FilePond.
