### ISSUE TITLE
Image label

### ISSUE THREAD

**Issue by haribabu500** [pqina/filepond#59]
Is it possible for us to add custom label like tags in uploaded preview.

Any information would be really helpful 
Thank you

**Comment by rikschennink** [comment]
I'm not sure what you mean, can you elaborate?

**Comment by haribabu500** [comment]
After successful upload of image, we can view uploaded image with the name of an image file, can we append some text to file name after it?
or is it possible to add some additional text as a label in the preview?

**Comment by rikschennink** [comment]
You can use the [file-rename plugin](https://pqina.nl/filepond/docs/patterns/plugins/file-rename/) to alter the filename.

If you want to add additional data to the upload, you can use the `setMetadata` method on the [file item](https://pqina.nl/filepond/docs/patterns/api/file/#methods).

**Comment by haribabu500** [comment]
can you please elaborate rikschennink,
my code is as folllows:
Initialize
             

```
<script src='https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.min.js'></script>
<script src='https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js'></script>
<script src='https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.min.js'></script>
<script src='https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.js'></script>
<script src="https://unpkg.com/filepond-plugin-file-rename/dist/filepond-plugin-file-rename.js"></script>
<script src='https://unpkg.com/filepond/dist/filepond.min.js'></script>
 FilePond.registerPlugin(                        
                        FilePondPluginFileEncode,                       
                        FilePondPluginFileValidateSize,
                        FilePondPluginImageExifOrientation,
                        FilePondPluginImagePreview,                   
               ); 
                  FilePond.setOptions({
                        fileRenameFunction: (file) => {
                            return `myname{file.extension}`;
                        }
                    })
```
 Creating of filepond instance is as follows:
                 `const pond2= FilePond.create(
                        document.querySelector('#floorplan_image'),{
                            allowImagePreview:true,
                            allowFileRename:true                      
                        }
                      );`

I am not able to change file name in image preview..
![screen shot 2018-06-12 at 8 11 43 pm](https://user-images.githubusercontent.com/6425207/41296589-010baf8c-6e7d-11e8-9b6d-3868b8ce4f41.png)

**Comment by rikschennink** [comment]
I think you forgot to add `FilePondPluginFileRename` to the `registerPlugin` call.
