### ISSUE TITLE
Options order does matter, but it's not documented (setting initial files can seem broken)

### ISSUE THREAD

**Issue by liarco** [pqina/filepond#594]
I was trying to [set some initial files](https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files) passing them to the `.setOptions(...)` function, but I was always getting a 400 error with no HTTP request or any other activity from the inspector.
Then I created [this example on CodePen](https://codepen.io/Liarco/pen/ZEOBxje?editors=1111) and I found out that setting the files later (with `.addFiles(...)`) was working as expected (passing the exact same files array).

So I looked at the [source code](https://github.com/pqina/filepond/blob/b7bff12ec419ea626137f30c98ecbb357d5fa2be/src/js/app/actions.js#L990) and, if I'm not mistaken, `.setOptions(...)` loops through the options and runs actions at the same time... so if I set `files` before `server` it will break.

This is behavior is not documented and the `files` option is also listed on top of everything so it can be misleading: https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#server-configuration

If you take my example on CodePen and move the `files` key **after** `server` the code will run fine even without clicking the button.

Wouldn't it be better to force a key order before looping or to document this behavior explicitly?

Thank you for your time.

---

I add the code from my CodePen example for future reference since I won't keep it forever:

**Assets from CDN:**
- https://unpkg.com/filepond/dist/filepond.css
- https://unpkg.com/filepond/dist/filepond.js

**Html:**
```html
<input type="file"><button>Run pond.addFiles(...)</button>
```

**JS:**
```ts
const inputElement = document.querySelector('input[type="file"]');
const pond = FilePond.create(inputElement);

const files = [{
  source: 'https://picsum.photos/200/300',
  
  options: {
    type: 'local',
  },
}];

pond.setOptions({
  files: files,
  server: {
    process: (fieldName, file, metadata, load, error, progress, abort) => {
      console.log('process', file.name);
      load(file);
    },
    load: (source, load, error, progress, abort, headers) => {
      console.log('load', source);
    },
  },
});

document.querySelector('button').addEventListener('click', () => {
  console.log('button clicked');
  pond.addFiles(files);
})
```

**Comment by rikschennink** [comment]
Thanks for the detailed description @liarco, agree that it would be better if the order was fixed.

**Comment by liarco** [comment]
Thank you @rikschennink, I'm quite busy these days, but I can try open a PR so that you can save some time.
