### ISSUE TITLE
Automatic upload retry

### ISSUE THREAD

**Issue by Herz3h** [pqina/filepond#599]
**Is your feature request related to a problem? Please describe.**
When uploading many files, sometimes there are errors with some files which cause failed upload

**Describe the solution you'd like**
It would be nice to have some kind of automatic upload retry. Like specify number of maximum retries before giving up and letting user retry manually if so he wishes.

**Describe alternatives you've considered**
Thought about using:

```javascript
onerror: (error, file, status) => 
{
// pond.retry(file)
},
```

But there is no retry method :/

**Comment by rikschennink** [comment]
You can call `processFile` or `processFiles`, I believe the later will retry processing files that errored

**Comment by Herz3h** [comment]
Thank you !

For future visitors, here is how I've done it:

```javascript
const MAX_TRIES = 3;
let failedUploads = {};
const pond = FilePond.create(inputElement);
pond.setOptions({
            onprocessfile: 	(error, file) =>
            {
                if(Object.keys(this.failedUploads).includes(file.id))
                {
                    delete this.failedUploads[file.id];
                }
            },
            onerror: (error, file, status) =>
            {
                if(Object.keys(this.failedUploads).includes(file.id))
                {
                    this.failedUploads[file.id]++;
                }
                else
                {
                    this.failedUploads[file.id] = 0;
                }

                if(this.failedUploads[file.id] >= MAX_TRIES)
                    return;

                pond.processFile(file.id);
            },
});
```
