### ISSUE TITLE
Unable to upload files on multiple input with preloaded files

### ISSUE THREAD

**Issue by aitorllj93** [pqina/filepond#60]
Hi, I'm trying to use the allowMultiple feature but I'm unable to make it work properly.

When there's no files on start it works fine, but when I initialize the input with already uploaded files with this config:

options:
```js
{
  allowMultiple: true,
  server: {
    process: myProcessHandler,
    revert: myRevertHandler,
    restore: myRestoreHandler,
    load: myLoadHandler
  }
}
```

files:
```js
[
  {
    source: 'myfile.pdf',
    options: {
      type: 'local'
    }
  }
]
```

And try to add another file, the process event isn't triggered and file doesn't get uploaded.

I'm currently using filepond v1.7.1 and ngx-filepond

Thanks for your time

**Comment by rikschennink** [comment]
Is the `myfile.pdf` file correctly loaded via the server `load` endpoint?

**Comment by aitorllj93** [comment]
Hi,

yes, the preloaded files get loaded correctly (or at least I think so). I can even remove them.
Here is the events log:
![preload-attachments](https://user-images.githubusercontent.com/5903438/41409932-2e3967f4-6fd8-11e8-9db4-149afb1bdcda.png)

When I try to upload another file I get this events:
![upload-another](https://user-images.githubusercontent.com/5903438/41410006-656e237c-6fd8-11e8-8172-88fda09a7e71.png)

While when there is no preloaded files the output is something like this:
![upload-first](https://user-images.githubusercontent.com/5903438/41410085-96fcfbde-6fd8-11e8-8356-62a76d5aaf69.png)

The process never starts when there are some preloaded files

**Comment by rikschennink** [comment]
@aitorllj93 I'm not sure what's going on. I just tested with 5 local files, adding a new file correctly runs the `process` method. Do you have a public test case?

**Comment by rikschennink** [comment]
Will close for now.

**Comment by Carmezim** [comment]
I'm also having trouble uploading multiple files on Vue with `allow-multiple` set to `true`.

**Comment by rikschennink** [comment]
@Carmezim That's so weird.

Some questions:
- Does renaming to `allowMultiple` do anything?
- Are you using Vue-CLI?
- Can you create a public test case?
- Does it only happen when setting the `files` array?

**Comment by rikschennink** [comment]
@Carmezim I've just uploaded a new version of FilePond which will probably fix the issue in Vue
