### ISSUE TITLE
Error message when drag and dropped files aren't able to be uploaded

### ISSUE THREAD

**Issue by eacan7** [pqina/filepond#609]
**Is your feature request related to a problem? Please describe.**
No message or indication of an error is being displayed when the amount of files being dragged and dropped is greater than the max file count. Currently nothing displays, this may be confusing to a user.

**Describe the solution you'd like**
A customizable error message when a drag and dropped file cannot be upload because it exceeded the maximum allow file count. It should also take the amount of files that have already been uploaded into account in the calculation.

**Describe alternatives you've considered**
Tried using the beforeDropFile prop but if I upload more than the allowed max it never makes it to beforeDropFile.

**Additional context**
Looks like you're already planning on adding this feature?
![dragAndDrop](https://user-images.githubusercontent.com/69166774/98868595-01163a80-2436-11eb-87f5-0217c3607189.png)

Thanks!

**Comment by rikschennink** [comment]
https://github.com/pqina/filepond/issues/137

**Comment by jpozogm** [comment]
you can use `onwarning={(error) => console.error(error.body)} `as a filepondProperty
