### ISSUE TITLE
addFile() Encoding Encoded URL Parameters

### ISSUE THREAD

**Issue by CameronSumpter** [pqina/filepond#610]
**Describe the Bug**
When using `addFile()`, FilePond changes querystring parameters inconsistently before retrieval.

**To Reproduce**
Pass a URL containing an already-encoded character.

For example, calling:
`filepond.addFile('https://pqina.nl/filepond/docs/images/logo.svg?x=y%2Cz');`

Will result in it attempting to fetch:
`https://pqina.nl/filepond/docs/images/logo.svg?x=y%252Cz`

**Expected Behavior**
FilePond should either not modify the URL, or it should do so in a predictable manner. For example, FilePond does not convert commas to `%2C` when passed unencoded (i.e. `logo.svg?x=y,z`), so it does encode `%` while ignoring `,`.

In my case, the remote server validates the request based on a hash of the querystring, so it needs to be submitted with proper encoding, whether that occurs before or after being passed to FilePond.

**Metadata**
- **Browser:** Chrome 86.0.4240.198
- **OS:** macOS Catalina 10.15.7
- **FilePond Version:** 4.23.1

**Comment by rikschennink** [comment]
Thanks for reporting @CameronSumpter 

FilePond runs `encodeURI` on the URLs of the requests it makes.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

Haven't had any issues with this before. Maybe you can set up a custom `load` method to circumvent the encode call?

**Comment by rikschennink** [comment]
will close because inactive
