### ISSUE TITLE
Filepond ignoring crop aspect ratio when imageEditInstantEdit is true

### ISSUE THREAD

**Issue by michael-ciavattone** [pqina/filepond#614]
Describe the Bug
When imageEditInstantEdit is set to true, the imageCropAspectRatio does not work and is being ignored at first. Once the user starts to resize it automatically goes to the imageCropAspectRatio set. However, if changing imageEditInstantEdit to false and then manually selecting to edit the file, it will use the correct aspect ratio.

To Reproduce
Create a new FilePond instance, set imageEditInstantEdit to true and define a imageCropAspectRatio. Also make sure to use Doka as the image editor.

Expected Behavior
When the image gets opened in the editor on select, it should already be set to the proper imageCropAspectRatio defined in the FilePond object.

Metadata
Browser: Chrome 86.0.4240.193
OS: Windows 10 Enterprise Version 1809
FilePond Version: 4.23.1

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.

**Comment by michael-ciavattone** [comment]
Sorry for the incorrect format, I believe it is correct now.

**Comment by rikschennink** [comment]
Can you try setting `imageCropAspectRatio` as a numeric value?

**Comment by michael-ciavattone** [comment]
Still doesn't seem to change anything. Here is my code for reference. I have tried changing the value to a numeric value, a string and even 1/1 but nothing works on render of doka. As soon as I just click on one of the four corners to resize, it automatically resizes the crop area to the 500 x 500 that I set but only when I go to make any modifications and never on load.

` var pond = FilePond.create(document.querySelector('.filepond'), {
            allowImageCrop: true,
            imageCropAspectRatio: '1:1',
            imageResizeTargetWidth: 500,
            imageResizeTargetHeight: 500,  
            imageEditInstantEdit: true,
            allowProcess: false,
            allowDrop: false,
            styleButtonProcessItemPosition: 'left',
            styleLoadIndicatorPosition: 'left',
            styleProgressIndicatorPosition: 'left',
            itemInsertLocation: 'after',
            checkValidity: true,
            // configure Doka
            imageEditEditor: Doka.create({
                _EXCLUDE_TRANSFORM_IMAGE: true,
                onconfirm: function (output, item) {
                    pond.processFile(item);
                },
                cropAllowInstructionZoom: true,
                utils: ['crop', 'color', 'markup']
            }),
            allowMultiple: false,
            maxFileSize: '26MB',
            instantUpload: true
        });`

**Comment by michael-ciavattone** [comment]
Still doesn't seem to change anything. Here is my code for reference. I have tried changing the value to a numeric value, a string and even 1/1 but nothing works on render of Doka. As soon as I just click on one of the four corners to resize, it automatically resizes the crop area to the 500 x 500 that I set but only when I go to make any modifications and never on load.

```
var pond = FilePond.create(document.querySelector('.filepond'), {  
            allowImageCrop: true,  
            imageCropAspectRatio: '1:1',
            imageResizeTargetWidth: 500,
            imageResizeTargetHeight: 500,  
            imageEditInstantEdit: true,
            allowProcess: false,
            allowDrop: false,
            styleButtonProcessItemPosition: 'left',
            styleLoadIndicatorPosition: 'left',
            styleProgressIndicatorPosition: 'left',
            itemInsertLocation: 'after',
            checkValidity: true,
            // configure Doka
            imageEditEditor: Doka.create({
                _EXCLUDE_TRANSFORM_IMAGE: true,
                onconfirm: function (output, item) {
                    pond.processFile(item);
                },
                cropAllowInstructionZoom: true,
                utils: ['crop', 'color', 'markup']
            }),
            allowMultiple: false,
            maxFileSize: '26MB',
            instantUpload: true
        });
```

**Comment by rikschennink** [comment]
`_EXCLUDE_TRANSFORM_IMAGE: true,` this won't work, you need conditional compilation to do that.

`onconfirm` is handled automatically so can be removed as well.

`allowImageCrop` is `true` by default.

Have you registered the required plugins?

```js
FilePond.registerPlugin(
  FilePondPluginImageExifOrientation,
  FilePondPluginImagePreview,
  FilePondPluginImageCrop,
  FilePondPluginImageResize,
  FilePondPluginImageTransform,
  FilePondPluginImageEdit
);
```

**Comment by michael-ciavattone** [comment]
I was missing the FilePondPluginImageResize plugin but I just added it and made the changes you suggested above and still behaving the same way. Below is the updated code:

```
FilePond.registerPlugin(
            FilePondPluginFileEncode,
            FilePondPluginFileValidateSize,
            FilePondPluginImageExifOrientation,
            FilePondPluginImagePreview,
            FilePondPluginImageEdit,
            FilePondPluginFileValidateType,
            FilePondPluginFilePoster,
            FilePondPluginImageTransform,
            FilePondPluginImageCrop,
            FilePondPluginImageValidateSize,
            FilePondPluginImageResize
        );

var pond = FilePond.create(document.querySelector('.filepond'), {  
            imageCropAspectRatio: '1:1',
            imageResizeTargetWidth: 500,
            imageResizeTargetHeight: 500,  
            imageEditInstantEdit: true,
            allowProcess: false,
            allowDrop: false,
            styleButtonProcessItemPosition: 'left',
            styleLoadIndicatorPosition: 'left',
            styleProgressIndicatorPosition: 'left',
            itemInsertLocation: 'after',
            checkValidity: true,
            // configure Doka
            imageEditEditor: Doka.create({
                cropAllowInstructionZoom: true,
                utils: ['crop', 'color', 'markup']
            }),
            allowMultiple: false,
            maxFileSize: '26MB',
            instantUpload: true
        });
```

**Comment by rikschennink** [comment]
Can you match the order of the plugins.

**Comment by michael-ciavattone** [comment]
Ya that worked. Seems to be dependent on the order the plugins are loaded. Thank you so much for your help!
