### ISSUE TITLE
Compress a folder to a zip file before uploading it

### ISSUE THREAD

**Issue by YotYot** [pqina/filepond#615]
When a user uploads a folder, it could potentially contain a very long list of files.

My suggestion is to allow the compression of a directory to a zip file and upload the zip file alone.

Thanks!

**Comment by rikschennink** [comment]
This plugin should do the trick: https://github.com/tzsk/filepond-plugin-zipper

**Comment by YotYot** [comment]
Thanks! I Will look into it
