### ISSUE TITLE
Should not call server.load when using filepond-plugin-file-poster

### ISSUE THREAD

**Issue by virtualize** [pqina/filepond#618]
**Describe the bug**

Displaying poster images for local files with filepond-plugin-file-poster works well.
But FilePond is still calling the server.load url to make a requests to server. The server response is obviously ignored, as its using the URL set in the file's `options.metadata.poster` to display the image.

If we omit `server.load`, the default URL is used.
Setting `server: { load: null}` displays the Error 400 (Can't load URL) inside FilePond.

**Logs**

No console error is displayed.
We can see a XHR call to https://8h2xx.csb.app/?load=night.jpg
We can see call to image https://uploads.codesandbox.io/uploads/user/ac40d4d5-08e1-4213-a5df-964ca39355c3/5yA2-night.jpg

**To Reproduce**

Reproducer: https://codesandbox.io/s/vanilla-filepond-forked-9b0c9

**Expected behavior**

FilePond should not call the server.load as no load URL is given (or set to null) it is not necessary because the preview image is loaded from poster.
Or FilePond should provide a way to disable the server.load call.

**Stacktraces**

No trace required.

**Information about your project:**

- Your browser and the version: Tested in latest Chrome, Firefox and Safari
- Your operating system: MacOS 10.14
- FilePond version: latest, 4.23.1

**Additional context**

No context. But I big thank you for this great toolset!

**Comment by rikschennink** [comment]
I think you can provide mock file info to prevent this.

```js
const pond = FilePond.create({
    files: [
        {
            // the server file reference
            source: '12345',

            // set type to local to indicate an already uploaded file
            options: {
                type: 'local',

                // mock file information
                file: {
                    name: 'my-file.png',
                    size: 3001025,
                    type: 'image/png'
                }
            }
        }
    ]
});
```

https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

**Comment by virtualize** [comment]
Thanks for your fast reply. 
I've tried your suggestion, but it does not make any difference, server.load still gets called.

**Comment by rikschennink** [comment]
```js
create(inputElement, {
  allowMultiple: true,
  server: {
    process: "./",
    load: (src, load) => {
      console.log("test");
      load();
    }
  },
  files: [
    {
      source: "night.jpg",
      options: {
        type: "local",
        file: {
          name: "my-file.png",
          size: 3001025,
          type: "image/png"
        },
        metadata: {
          poster: "./night.jpg"
        }
      }
    }
  ]
});
```

this doesn't log "test"

**Comment by virtualize** [comment]
I'm sorry, you're right. I had the file key under root. Moved it into options now and everything works as expected.
Will make an appointment with my optometrist... :)
