### ISSUE TITLE
How set "allowRemove" separately for each file?

### ISSUE THREAD

**Issue by vjik** [pqina/filepond#619]
Something similar to:

```js
{
	source: file.id,
        allowRemove: false,
	options: {
		type: 'local',
		file: {
			name: file.name,
			size: file.size,
		},
	},
}
```

**Comment by rikschennink** [comment]
That's not possible, maybe you can hide the button using the `onaddfile` callback

sorry for the insane delay on this response

**Comment by rikschennink** [comment]
Will close because the issue doesn't conform to the issue template.
