### ISSUE TITLE
Filename not visible with option styleButtonRemoveItemPosition: 'right' for local files

### ISSUE THREAD

**Issue by virtualize** [pqina/filepond#620]
**Describe the bug**

When using the option `styleButtonRemoveItemPosition: 'right'` as described in the documentation, the labels for file name and size are not visible anymore on local files. The labels seem to be pushed to the right outside the `filepond--item`

I fixed it temporarily like this
```
.filepond--file-info {
  margin-right: 2em;
  transform: translate3d(0px, 0px, 0px) !important;
}
```

**To Reproduce**

https://codesandbox.io/s/vanilla-filepond-forked-jhx52?file=/src/index.js
Try to uncomment the styles in index.html there

**Expected behavior**

File labels should be visible and displayed inside `filepond--item` div

**Information about your project:**

- Your browser and the version: latest Chrome, Firefox, Safari 
- Your operating system: MacOS 10.14
- FilePond version: latest 4.23.1

**Context**

It is also mentioned here, although the issue is already closed: https://github.com/pqina/filepond/issues/366#issuecomment-708156604

**Comment by rikschennink** [comment]
Should be fixed in https://github.com/pqina/filepond/releases/tag/4.25.2

Please close when confirmed.

**Comment by virtualize** [comment]
Yep. It's fixed now. Thanks.
