### ISSUE TITLE
whether it controllable to only upload the slice that haven't been uploaded

### ISSUE THREAD

**Issue by food-billboard** [pqina/filepond#621]
I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this.

As I known. When an error happen as the the user adding file and uploading. The `filepond` can send `head` request to make the server response to the `Upload-Offset` respons headers. and control the next  chunk that are to uploaded. 

**But if it possible to return to the `Upload-Offset` response header to control the next upload chunk during a correct uploading(in other word.in the `patch` request)** 

The backend koa server code like this:
```js
router.patch('/upload', async(ctx) => {
  ctx.set('Upload-Offset', 10000) //next chunk offset
})
```
and then `filepond` can deal this response

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.

**Comment by rikschennink** [comment]
closed because no additional info supplied within 5 days
