### ISSUE TITLE
filepond--drop-label CSS Transition blurred on Chrome 87

### ISSUE THREAD

**Issue by kirikintha** [pqina/filepond#625]
**Describe the bug**

On Chrome 87 on OSX Catalina with a React 16 and bootstrap 4, I noticed that when the animation for removing a file completes, the text is blurred after the transform completes. I am not using the React Component, just loading it into my home page to check it out.

**To Reproduce**

https://pqina.nl/filepond/docs/patterns/installation/ - I was following the basic setup with a file input as described.

1. FilePond renders well and looks awesome!

![Screen Shot 2020-12-15 at 5 18 30 PM](https://user-images.githubusercontent.com/274575/102289007-e6cef100-3efa-11eb-8bca-0e0bd71ef494.png)

2. Browse For A File

![Screen Shot 2020-12-15 at 5 19 02 PM](https://user-images.githubusercontent.com/274575/102289049-fcdcb180-3efa-11eb-835e-e1587f35c032.png)

3. Remove File

![Screen Shot 2020-12-15 at 5 19 14 PM](https://user-images.githubusercontent.com/274575/102289074-09f9a080-3efb-11eb-9faa-692cc236e6bb.png)

4. Transition Completes, Text Blurry

![Screen Shot 2020-12-15 at 5 19 25 PM](https://user-images.githubusercontent.com/274575/102289107-1a118000-3efb-11eb-9179-b5325763dc80.png)

**Expected behavior**

Text remains sharp after transition

**Information about your project:**

- Your browser and the version: Version 87.0.4280.88 (Official Build) (x86_64)
- Your operating system: OSX Catalina 10.15.7
- FilePond version: 4.25.1

**Additional context**

I did look at the CSS, and from what I am seeing is that will-change: transform,opacity is causing my specific issue. 

if I update: filepond--drop-label 

```
.filepond--drip-blob,
.filepond--drop-label {
  will-change: auto;
}
```

The affect goes away on my version of chrome. So sorry that I can't give a repro for this easily.

**Comment by rikschennink** [comment]
Hey, thanks for the detailed issue! Is it possible one of the FilePond parent containers is transformed as well and maybe positioned at a non rounded pixel?

**Comment by kirikintha** [comment]
@rikschennink  - Thanks for responding! I've tried this on a number of pages with the same result, so I am guessing this is at my base app layer. I'm using lazy routing and a lot of fluid layout, so it would not surprise me that things are getting in the way.

I am going to close this, but is a good reference for anyone else who may be experiencing the same issue.

**Comment by stunaz** [comment]
@kirikintha @rikschennink I have the same issue, texts and images are blurred.
can you please point out what could be the issue?

**Comment by shimisnow** [comment]
I have the same issue, but only on browsers based on Chromium, it appears. Tested in my project and in the [example page](https://pqina.nl/filepond/) on pqina.

Your operating system: Windows 10.0.19043 Build 19043
FilePond version: 4.28.2

**The blur occurs in:**

- Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)
- Edge Version 93.0.961.47 (Official build) (64-bit)

**The blur do not occurs in:**

- Firefox 91.0.2

Disabling the animation works:

```css
.filepond--drop-label {
  will-change: unset;
}
```

**Comment by rikschennink** [comment]
@shimisnow thanks for sharing your solution 🙏
