### ISSUE TITLE
Image preview issue

### ISSUE THREAD

**Issue by zoulhisham** [pqina/filepond#626]
After i've upload an image, the preview shows black background. The upload is complete with no error, but the image does not load properly.
(Safari is working fine but chrome, IE not working properly)
![example](https://user-images.githubusercontent.com/45656005/102315418-163f3580-3faf-11eb-8eb7-29d91e8a8b70.PNG)

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.

**Comment by rikschennink** [comment]
Closed because template not filled in
