### ISSUE TITLE
Documentation extremely slow

### ISSUE THREAD

**Issue by mneuhaus** [pqina/filepond#63]
Hey, thanks for creating such an awesome fileupload library!

is there any chance, that you move the Documentation to github or somehwere else?
Currently the Documentation takes 15s to respond, which is a bit annoying, if you want to look up something :joy:

**Comment by rikschennink** [comment]
Hi!

The docs GH repository is available here:
https://github.com/pqina/filepond-docs

The docs website is super fast from where I'm viewing it, it's a static site and I've set it up behind Cloudflare so it should serve it fairly quickly around the world. I'm no expert so maybe I missed something. Is it possible that this is a connection issue?

**Comment by mneuhaus** [comment]
ok, pretty weird, seems like my provider is doing some shitty stuff :/

This really looks quite ok:
![](http://img.mia3.com//?i=ZGuCq9SIXHA5AJq3.png)

but with my provider it's more like this: 
![](http://img.mia3.com//?i=Y0GRnX0s6Wlkcv69.png)

my connection speed itself isn't the culprit either: 

![](http://img.mia3.com//?i=ib4e7QUgcUun6jxP.png)

so, this does not seem to be something you can fix, so i'll close this, sorry for bothering :)

**Comment by rikschennink** [comment]
Hm strange, thanks for sharing. I might be able to improve the time to first byte ( which is a bit high ) but other than that it should be quite fast.
