### ISSUE TITLE
Data workflow should not rely on the return from event callbacks

### ISSUE THREAD

**Issue by Yahasana** [pqina/filepond#633]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I forget return data from `onload`, `ondata` or `onerror`. filepond run in tricky mode.

**Describe the solution you'd like**
see pr #631

**Describe alternatives you've considered**
`onxxx` should only do something and void return.

**Comment by rikschennink** [comment]
Closed, agree that this would be a nice fix, still not sure if I can merge without causing backwards compatibility issues, let's continue in PR.
