### ISSUE TITLE
Safari (and probably IOS) files are sent with zero length

### ISSUE THREAD

**Issue by phelbas** [pqina/filepond#635]
On Safari  13.1.3 (OSX Catalina), uploaded files are currently sent with zero length
This appears to be a Safari/IOS problem. I am unsure when the issue appeared, or when/if it has been fixed in Safari/IOS.

The problem, I think, is use of formData().append of a File object. The uploaded multi-part form does not include the contents of each file so on the server side, the files created are zero length.

The only way I could fix it was to convert each file to a Blob, then append the Blob, but the method to convert a file object to a Blob is async, using FileReader(), so createFileProcessorFunction does not return the request anymore. This worked for me but probably is not the patch to make.

I think this is a new problem introduced by Apple at some point because twitter (for example) will currently not accept uploaded images on tweets on my OSX browser - giving a generic error message - unless you "edit" them in-browser first, which I suspect achieves the same workaround.

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.

Please also try to reproduce this on the [product page](https://pqina.nl/filepond/).

**Comment by phelbas** [comment]
Is there a product page demo where one can test that the image is actually uploaded to a server without truncation?

**Comment by rikschennink** [comment]
It's unclear to me what you mean.

**Comment by phelbas** [comment]
You said "please try to reproduce this on the product page" however I unless there is something I am missing, there is no way to see what the server received after upload of a file. With this particular issue the browser and FilePond reports all is ok.

So I guess I'd have to adapt the product page example in codepen to post to postman echo test or something like that, then submit that example, as demonstrating the issue.

**Comment by rikschennink** [comment]
Because of privacy concerns there's no page to see the actual upload.

If you create a public test case with actual upload I'm happy to take a closer look.

**Comment by phelbas** [comment]
Sorry for the delay. Here you go.  

Minimal filepond at  ... http://139.180.163.144:8080/test.html it uploads with POST to same server.

When I inspect network POST using OSX Safari 13.1.3 dev tools:

<img width="703" alt="Screen Shot 2021-01-06 at 9 20 15 am" src="https://user-images.githubusercontent.com/67846089/103706208-98e07100-5000-11eb-929a-c1fc2610c158.png">

It doesn't actually matter what the server POST end-point is if the browser does not actually send the file contents.

**Comment by phelbas** [comment]
(Safari 13.1.3 is actually the last version of Safari for OSX Catalina which I imagine is still the most common OSX in active use. It may also be the Safari code in iOS 13.x and have the same issue)

 after this, there is Big Sur and Safari 14.0, 14.0.1 and 14.02, and IOS 14

**Comment by phelbas** [comment]
I was on a wild goose chase, sorry. The zero length file problem on the back-end looks to have been a weird issue with my dev setup :( closing.
