### ISSUE TITLE
nsimageTransformVariants resize issue: Uncaught (in promise) TypeError: Cannot set property 'size' of undefined

### ISSUE THREAD

**Issue by misisol** [pqina/filepond#636]
**Describe the bug**

I found an issue when imageResizeUpscale = false, smaller images (smaller than imageResizeTargetWidth or imageResizeTargetHeight) don't have access to the resize transform in imageTransformVariants,

`const pond = FilePond.create(document.querySelector('input'), {
      imageResizeTargetWidth: 1280,
      imageResizeTargetHeight: 1280,
      imageResizeMode: 'contain',
      imageResizeUpscale: false,
      imageTransformOutputQuality: 80,

      imageTransformVariants: {
        'm_': transforms => {
          // errors here on any image that is less than the 1280x1280 defined above, since it doesn't have to resize the image.
          transforms.resize.size.width = 640;
          transforms.resize.size.height = 640;
          return transforms;
        }
     }
  });`

**Logs**
`Uncaught (in promise) TypeError: Cannot read property 'size' of undefined
    at thumb_medium_`

**To Reproduce**

 Create a new Filepond instance as mentioned above and upload a photo below 1280x1280 size;

**Expected behavior**

It should not throw an error.

**Information about your project:**

It happens on All browsers including Chrome, Firefox, and Safari.

**Comment by rikschennink** [comment]
See: https://github.com/pqina/filepond-plugin-image-transform/issues/21
