### ISSUE TITLE
Option for setting a label text missing?

### ISSUE THREAD

**Issue by cajsamra** [pqina/filepond#641]
I am having trouble finding the label text option for the case where the user hits the upload button, but has not selected a file yet.  A message pops up in a small frame with the words “Please select one or more files.”  I need to translate that label into other languages.  Please advise.  I’ve attached a screen shot of what I am talking about.

![Screen Shot 2021-01-22 at 10 39 08 AM](https://user-images.githubusercontent.com/30735556/105531382-13b2b880-5c9e-11eb-8189-b9ebbac13541.png)

**Comment by cajsamra** [comment]
Sorry, but I now understand what is happening.  it is the browser that is putting out that message, not FilePond  Sorry for the bother.

**Comment by rikschennink** [comment]
Hi, yes this is native HTML functionality, thanks for the update. I'll close the issue.
