### ISSUE TITLE
Filepond uploader disappears after deleting image

### ISSUE THREAD

**Issue by autresrhumbs** [pqina/filepond#642]
Hello,

I have an issue I couldn't solve so far.
When I delete an image that is first in a row, the whole Filepond uploader disappears.
If I have a look at source code, everything seems to be hided behind something but cannot figure out what it could be.

What am I doing wrong here?!

https://user-images.githubusercontent.com/39381278/105557165-d4bb4c00-5d0b-11eb-82df-bf55e49541a7.mov

Thanks for your help.

Bruno.

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. Please leave a comment after you've updated the issue.
