### ISSUE TITLE
sponsorship - throw some money at rikschennink

### ISSUE THREAD

**Issue by fratzinger** [pqina/filepond#644]
Hey @rikschennink,

I just want to say that I love the filepond ecosystem with it's beautiful plugins! I also contributed code here and there, so it fulfills my needs even more. You merged it quite fast! Really good Open Source work!

I would like to give something back, even if it's not that much! How about a monthly sponsorship? I believe there would be more guys like me willing to throw money at you! Do you have some sort of github sponsorship / open collective / buy me a coffee? A monthly 5$ subscription would be nice for me!

**Comment by rikschennink** [comment]
Hi @fratzinger, thanks so much for the kind words, and thanks for contributing! 

I've experimented with Patreon sponsorship links in the past but it didn't really "take off", I've just re-enabled it with the more casual donation platform "buy me a coffee". :)

🙏 https://www.buymeacoffee.com/rikschennink

**Comment by fratzinger** [comment]
5 on me.

Maybe you should consider github sponsorship some day. It surely would not "take off", but I see a slow shift in voluntary financial support. Github sponsorship is a good way of call to action. Just my two cents.

Enjoy your coffee! ;)

**Comment by rikschennink** [comment]
Thanks @fratzinger! and thanks for the gh sponsorship suggestion, will definitely look into it
