### ISSUE TITLE
Set files metadata through FilePond.create

### ISSUE THREAD

**Issue by enisdenjo** [pqina/filepond#65]
Hey its me again! 😄 

I have another enhancement request. All files which go through my FilePond implementation have a `payload` which is essentially the file `metadata`. This `metadata` lives alongside the file ALWAYS and it provides some extra information which changes the way the file is displayed.

It would be really nice if I could set the `metadata` of the file through the instance creation with `FilePond.create(...)`. Currently there is the `files` option holding an array of objects in the format:
```json
{ "source": "server-unique-id", "options": { "type": "'limbo' | 'local' | 'input'" } }
```

Maybe pass something like this:
```json
{ "source": "server-unique-id", "options": { "type": "'limbo' | 'local' | 'input'", "metadata": { "some": "object" } } }
```

Which would create the `File` and set its `metadata` immediately.

What do you think?

Kind regards,
Denis

**Comment by rikschennink** [comment]
Thanks for the suggestion, I'm currently working on issue #33, this is something I'll add immediately as it's indeed vital for building continuous client/server experience.

**Comment by enisdenjo** [comment]
Sweet! You know it. 😄 

As I am digging deeper in filepond, I also realised that I would find `file-info` view very helpful.

Can you maybe do the same thing you did with the `file-status` but for `file-info` for the next release? (I wan't to display addition information next to the filename).

**Comment by rikschennink** [comment]
Just published version `1.8.0`, secretly added the `createView` filter in file-info. Now updating docs and plugins.

Release info:
https://twitter.com/rikschennink/status/1009036630307540993

**Comment by enisdenjo** [comment]
Wow, you are amazing! Thanks. 😄

**Comment by rikschennink** [comment]
My pleasure!

**Comment by enisdenjo** [comment]
I can confirm that both: setting `metadata` and the exposed `file-info` work nice.
