### ISSUE TITLE
changing of revert icon not working 

### ISSUE THREAD

**Issue by ReymarEnteria** [pqina/filepond#652]
Hi,

I just want to raise an issue on changing revert icon from "Cross Icon" to "Trash Icon".
I am using vue-filepond v4.25.1 .

here's the screenshot of my code.
![image](https://user-images.githubusercontent.com/44773797/106729668-b6791880-6648-11eb-8ff8-6bad08feba21.png)

here's the actual result
![image](https://user-images.githubusercontent.com/44773797/106729873-ede7c500-6648-11eb-9fbf-fb678bf32a9c.png)

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. Please leave a comment after you've updated the issue.
