### ISSUE TITLE
Error "Error in parsing value for 'contain'. Declaration dropped." in Firefox

### ISSUE THREAD

**Issue by andreasklostermaier** [pqina/filepond#658]
**Describe the bug**

Loading a page in Firefox (85.0.1), with filepond active, produces the error
"Error in parsing value for ‘contain’.  Declaration dropped. filepond.css:936:24"
The error message seem to not affect the correct performance of FilePond (therefore low prio).

**Logs**

```
Error in parsing value for ‘contain’.  Declaration dropped. filepond.css:936:24
Übereinstimmende Elemente mit Selektor: .filepond--root

NodeList(1)
​
0: <div class="filepond--root filepond filepond--hopper" data-style-button-remove-item-position="left" data-style-button-process-item-position="right" data-style-load-indicator-position="right" data-style-progress-indicator-position="right" data-style-button-remove-item-align="false" style="height: 103px;">
​
length: 1
​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }

```

**To Reproduce**

The error message only shows up in Firefox (cannot see it in Brave/Vivaldi).
The error message only shows up, if a manual install of "filepond.css" was performed (Version: FilePond 4.25.1).
Loading "filepond.css" from the CDN does NOT produce the error message.

**Expected behavior**

No error message should be produced by "filepond.css"

**Stacktraces**

The affected lines in "filepond.css" are:

.filepond--root {
  /* layout*/
  box-sizing: border-box;
  position: relative;
  margin-bottom: 1em;
  /* base font size for whole component */
  font-size: 1rem;
  /* base line height */
  line-height: normal;
  /* up uses default system font family */
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica,
    Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
  /* will increase font weight a bit on Safari */
  font-weight: 450;
  text-align: left;
  text-rendering: optimizeLegibility;
  direction: ltr;
  contain: layout style size;
}

**Information about your project:**

- Firefox 85.0.1
- Ubuntu Linux 20.10
- FilePond version 4.25.1

**Comment by rikschennink** [comment]
Tried to reproduce this on pqina.nl/filepond and in a local test project, the error does not show up.

Please create a public test case.
