### ISSUE TITLE
File not renamed on restore as of 1.7.4

### ISSUE THREAD

**Issue by enisdenjo** [pqina/filepond#66]
Hey,

I have found a bug. When restoring a temporary uploaded file, the filename is not updated using the `Content-Disposition` header. The item filename stays at the unique server ID.

This bug appears in version `1.7.4`, downgrading to `1.7.3` solves the issue.

**Comment by rikschennink** [comment]
Can you post the header?

**Comment by enisdenjo** [comment]
Restore header: `content-disposition: inline; filename=invoice_sample.pdf`

**Comment by enisdenjo** [comment]
I see your change, it should be: `content-disposition: inline; filename="invoice_sample.pdf"` _notice the quotes_. Right?

**Comment by rikschennink** [comment]
Yes, as far as I can tell it should have quotes. More information on the Content-Disposition header:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by enisdenjo** [comment]
My fault.

Everything (from 1.8.0) is working great again!

**Comment by rikschennink** [comment]
Fantastic :-) Thanks for the update.

**Comment by enisdenjo** [comment]
I used your server reference to build my server, so that might be the case. 😅

**Comment by rikschennink** [comment]
Hah :) Wooops 🙃

**Comment by sjclemmy** [comment]
Hi there,
Really great library you've made!
I've just come across this same issue with a laravel integration and just wanted to contribute to the discussion.

When using the Storage facade in Laravel **double quotes are not provided for the filename field** on the content-disposition header and I think that is correct.

So Laravel returns:
`content-disposition: inline; filename=test.png` and FilePond doesn't replace the name.

However if I force Laravel to send `content-disposition: inline; filename="test.png"` then FilePond replaces the name correctly. 

Based on the RFC for content-disposition I think it should support both instances.

If you look at the RFC it mentions that it must be a string but doesn't say the string must be delimited by double quotes and also **gives a specific example of only delimiting with quotes when there is a space in the filename**. Please see section 5 of the RFC: 
https://tools.ietf.org/html/rfc6266#section-5.

I'm using version 3.2.1 and using the Vue wrapper (4.0.0).

**Comment by rikschennink** [comment]
Thanks, will see if I can adjust it so it works without quotes as well

**Comment by rikschennink** [comment]
Should be fixed in `3.3.3`, please confirm.
