### ISSUE TITLE
allowMultiple does not set default filepond[] name

### ISSUE THREAD

**Issue by bartek5186** [pqina/filepond#662]
**Describe the bug**

Normal setting without "name" parameter dont generate multiple field name. 
allowMultiple: true, dont generate name for multiple.
I must set name to "filepond[]" to get multiple ids from post, because before all have the same name "filepond"

![image](https://user-images.githubusercontent.com/4134966/108724819-0bac9980-7526-11eb-83a8-02fafe501157.png)

(Browser: Opera)

**Comment by rikschennink** [comment]
Yes name needs to be set manually.

**Comment by axi** [comment]
For anyone like me searching a solution and ending here, here is what worked for me:
```html
<input name="mediaList[]" id="uploader-media">
```

```javascript
$('#uploader-media').filepond({
        allowMultiple: true,
        // name: 'mediaList[]',  <= doesn't work 
});
```
