### ISSUE TITLE
Add lastModified property on File Object

### ISSUE THREAD

**Issue by adarshmadrecha** [pqina/filepond#673]
**Is your feature request related to a problem? Please describe.**
The [file object ](https://developer.mozilla.org/en-US/docs/Web/API/File) has `lastModified` read-only property provides the last modified date of the file.
(Reference: https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified)

**Describe the solution you'd like**
`processFile` method return `File` Object (Ref: [filepond/api/file](https://pqina.nl/filepond/docs/patterns/api/file/)).
It will be good to have access to `lastModified` property on this `File` Object.

**Describe alternatives you've considered**
None

**Additional context**
It can help with checking if the user is uploading a very old file, if newer file is required by business application.

**Comment by rikschennink** [comment]
The `file` property is a reference to the file object which contains the `lastModified` property.

**Comment by adarshmadrecha** [comment]
@rikschennink My bad, I was not clear on the which `file` object I am referring to.
Have updated my original post. Request you to reopen.

The `file` object which `processFile` get does not contain `lastModified` property.

The console log of `file` looks like this.
FYI, the `lastModifiedTime` is always current time. (May be because I am using Transform Plugin)
![image](https://user-images.githubusercontent.com/11911938/111074992-bacc0780-850b-11eb-8d64-af4c8f86a8b7.png)

**Comment by rikschennink** [comment]
@adarshmadrecha it's probably a blob because of applied transformations. You could store the original date in file metadata when the file is first added?
