### ISSUE TITLE
Error state does not show on "stylePanelLayout": "integrated" or "circle"

### ISSUE THREAD

**Issue by Zwimber** [pqina/filepond#674]
**Describe the bug**

In the documentation  the following is listed:

stylePanelLayout | null | Set a different layout render mode. Can be either 'integrated', 'compact', and/or 'circle'. Compact mode will remove padding, integrated mode is used to render FilePond as part of a bigger element. Circle mode adjusts the item position offsets so buttons and progress indicators don’t fall outside of the circular shape.

However when using 'integrated', 'compact' or 'circle' the otherwise nicely looking errors are no longer shown.

```js
// Works nicely
pondOptions = {
  labelIdle: `Drag & Drop your picture or <span class="filepond--label-action">Browse</span>`,
  imagePreviewHeight: 170,
  imageCropAspectRatio: '1:1',
  imageResizeTargetWidth: 200,
  imageResizeTargetHeight: 200,
  server: './',
 
  // Size validation
  allowImageValidateSize: true,
  maxFileSize: '10mb',
  imageValidateSizeMinWidth: 128,
  imageValidateSizeMaxWidth: 8192,
  imageValidateSizeMinHeight: 128,
  imageValidateSizeMaxHeight: 8192,
}

// Error is not shown
pondOptions = {
  labelIdle: `Drag & Drop your picture or <span class="filepond--label-action">Browse</span>`,
  imagePreviewHeight: 170,
  imageCropAspectRatio: '1:1',
  imageResizeTargetWidth: 200,
  imageResizeTargetHeight: 200,
  stylePanelLayout: 'compact circle',
  styleLoadIndicatorPosition: 'center bottom',
  styleProgressIndicatorPosition: 'right bottom',
  styleButtonRemoveItemPosition: 'left bottom',
  styleButtonProcessItemPosition: 'right bottom',
  server: './',
  
  // Size validation
  allowImageValidateSize: true,
  maxFileSize: '10mb',
  imageValidateSizeMinWidth: 128,
  imageValidateSizeMaxWidth: 8192,
  imageValidateSizeMinHeight: 128,
  imageValidateSizeMaxHeight: 8192,
}
```

# Nice and readable error
<img width="194" alt="Screenshot 2021-03-14 at 12 36 03" src="https://user-images.githubusercontent.com/6017921/111067024-5df82f00-84c2-11eb-910d-d114cf297c29.png">

# Not even a red color
<img width="224" alt="Screenshot 2021-03-14 at 12 36 24" src="https://user-images.githubusercontent.com/6017921/111067025-5f295c00-84c2-11eb-8c2a-f9d0706bcc8d.png">

Please note that some other errors (such as file could not upload will display the red color).

**Comment by rikschennink** [comment]
I advise to capture the error with the error handler and render an error below the field or prevent dropping invalid items entirely by setting `dropValidation` to `true`.

**Comment by rikschennink** [comment]
Closed because inactive.

**Comment by rosnaib11** [comment]
+1
