### ISSUE TITLE
Filepond not save updated file from doka

### ISSUE THREAD

**Issue by Sector911** [pqina/filepond#678]
Hello! I try updated my file from Doka, but when sending files to the server, the base64 file remains the same as it was. The preview of the image changes, but the image itself is not when it is sent.

```
import {
    // editor
    openEditor,
    processImage,
    createDefaultImageReader,
    createDefaultImageWriter,
    imageOrienter,
    locale_en_gb,
    legacyDataToImageState,
    // plugins
    setPlugins,
    plugin_crop,
    plugin_crop_defaults,
    plugin_crop_locale_en_gb,
    plugin_finetune,
    plugin_finetune_defaults,
    plugin_finetune_locale_en_gb,
    plugin_filter,
    plugin_filter_defaults,
    plugin_filter_locale_en_gb,
    plugin_decorate,
    plugin_decorate_defaults,
    plugin_decorate_locale_en_gb,
    component_shape_editor_locale_en_gb,
} from '/assets/uploader/doka/doka.js';
setPlugins(plugin_crop, plugin_finetune, plugin_filter, plugin_decorate);
FilePond.registerPlugin(
    FilePondPluginFileValidateType,
    FilePondPluginImageEditor,
    FilePondPluginFilePoster,
    FilePondPluginImageCrop,
    FilePondPluginFileMetadata,
    FilePondPluginImageTransform,
    FilePondPluginFileEncode
);

FilePond.setOptions({
    allowMultiple: true,
    allowReorder: true,
    onconfirm: (output) => {
        console.log(output);
    },
    onpreparefile: (file, output) => {
        console.log(file, output, 'file')
    },
    imageTransformImageFilter: (item) =>
        new Promise((resolve) => {
            resolve(false);
        }),
    onpreparefile: (fileItem, res) => {
        console.log(res);
    },
    // Added this ----------------------------------------
    onreorderfiles(files, origin, target) {
    }
});

pondImg = FilePond.create(document.querySelector('#filepond-imgs'), {
    imageEditor: {
        // map legacy data objects to new imageState objects
        legacyDataToImageState: legacyDataToImageState,

        // used to create the editor, receives editor configuration, should return an editor instance
        createEditor: openEditor,

        // Required, used for reading the image data
        imageReader: [createDefaultImageReader],

        // optionally. can leave out when not generating a preview thumbnail and/or output image
        imageWriter: [createDefaultImageWriter],

        // used to generate poster images, runs an editor in the background
        imageProcessor: processImage,

        // editor options
        editorOptions: {
            imageOrienter: imageOrienter,
            ...plugin_crop_defaults,
            ...plugin_finetune_defaults,
            ...plugin_filter_defaults,
            ...plugin_decorate_defaults,
            locale: {
                ...locale_en_gb,
                ...plugin_crop_locale_en_gb,
                ...plugin_finetune_locale_en_gb,
                ...plugin_filter_locale_en_gb,
                ...plugin_decorate_locale_en_gb,
            },
        },
    },
    filePosterMaxHeight: 100
});

```

And code sending on click my button:

```
let filesImg = pondImg.getFiles();
let formData = new FormData();
formData.append('object_id', response.object_id);
$.each(pondImg.getFiles(), function (i, file) {
        formData.append('X', file.file);
         formData.append('X['+i+']', file.getFileEncodeBase64String());
 })
$.ajax({
     url: "/file_upload",
    method: "POST",
    data: formData,
    cache: false,
    processData: false,
    contentType: false
 }).done((response_files) => {
     console.log(response_files);
});
```

On server all time i get the same string base64. Please help me.

**Comment by Sector911** [comment]
For example
![image](https://user-images.githubusercontent.com/41770950/111935375-118aa000-8b0f-11eb-8b2c-9658ff8852ec.png)
when sending, these files are the same, although I edited one of them in doka

**Comment by rikschennink** [comment]
Hi, please see these instructions for using Doka Image Editor with FilePond:
https://pqina.nl/doka/docs/v7/getting-started/installation/filepond/

You don’t need the imageTransform and imageCrop plugins.

**Comment by Sector911** [comment]
I delete plugins, but this not work.
```
import {
    // editor
    openEditor,
    processImage,
    createDefaultImageReader,
    createDefaultImageWriter,
    imageOrienter,
    locale_en_gb,
    legacyDataToImageState,

    // plugins
    setPlugins,
    plugin_finetune,
    plugin_finetune_defaults,
    plugin_finetune_locale_en_gb,
    plugin_filter,
    plugin_filter_defaults,
    plugin_filter_locale_en_gb,
    plugin_decorate,
    plugin_decorate_defaults,
    plugin_decorate_locale_en_gb
} from '/assets/uploader/doka/doka.js';
import ru_RU from '/assets/uploader/filepond/locale/ru-ru.js';

setPlugins(plugin_finetune, plugin_filter, plugin_decorate);

FilePond.registerPlugin(
    FilePondPluginFileValidateType,
    FilePondPluginImageEditor,
    FilePondPluginFilePoster,
    FilePondPluginFileMetadata,
    FilePondPluginFileEncode
);

FilePond.setOptions({
    allowMultiple: true,
    allowReorder: true
});

//Изображения
pondImg = FilePond.create(document.querySelector('#filepond-imgs'), {
    imageEditor: {
        // map legacy data objects to new imageState objects
        legacyDataToImageState: legacyDataToImageState,

        // used to create the editor, receives editor configuration, should return an editor instance
        createEditor: openEditor,

        // Required, used for reading the image data
        imageReader: [createDefaultImageReader],

        // optionally. can leave out when not generating a preview thumbnail and/or output image
        imageWriter: [createDefaultImageWriter],

        // used to generate poster images, runs an editor in the background
        imageProcessor: processImage,

        // editor options
        editorOptions: {
            imageOrienter: imageOrienter,
            ...plugin_finetune_defaults,
            ...plugin_filter_defaults,
            ...plugin_decorate_defaults,
            locale: {
                ...locale_en_gb,
                ...plugin_finetune_locale_en_gb,
                ...plugin_filter_locale_en_gb,
                ...plugin_decorate_locale_en_gb,
            },
        },
    },
    filePosterMaxHeight: 100
});
```

Files remain unchanged when transferred to the server. Both base64 string and just $ _FILES
In Doka:
![image](https://user-images.githubusercontent.com/41770950/111978470-a6ad8900-8b4f-11eb-8b63-9bd3aac4f916.png)

In server:
![image](https://user-images.githubusercontent.com/41770950/111978528-b6c56880-8b4f-11eb-8e38-9e082033c8e4.png)

**Comment by rikschennink** [comment]
The data will be uploaded as a base64 string wrapped in an object, it looks like this:

```js
{
    "id": "b56kpu6u9",
    "name": "encoded-file.png",
    "type": "image/png",
    "size": 123456,
    "metadata": {
        "resize": {
            "mode": "force",
            "size": {
                "width": 200,
                "height": 200
            }
        },
        "crop": {
            "rect": {
                "x": 0.19234,
                "y": 0,
                "width": 1,
                "height": 0.61213
            },
            "aspectRatio": 1
        }
    },
    "data": "iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAA..."
}
```

You'll have to get the `data` property and then turn it back into a file.

I just tested with the following logic and it does set the hidden field property correctly. Can you confirm the JSON string arrives on the server?

```js
// this will wait a couple seconds and then read out the first hidden filepond data field
FilePond.create(node, {
  onaddfile: () => {
                    setTimeout(() => {
                        const field = document.querySelector(
                            'input[name="filepond"][type="hidden"]'
                        );
                        const fieldValue = JSON.parse(field.value);
                        const dataURL = `data:image/jpeg;base64,${fieldValue.data}`;
                        const image = new Image();
                        image.src = dataURL;
                        document.body.appendChild(image);
                    }, 2000);
                },
})
```

**Comment by Sector911** [comment]
Apparently we did not understand each other a little)

A task:
1. Add objects to the Filepond
2. Edit them in doka.js
3. By clicking on the button, save them on the server

I have code on native JS:

```
let filesImg = pondImg.getFiles();
// I use FormData() and pondImg.getFiles()
let formData = new FormData();
$.each(pondImg.getFiles(), function (i, file) {
         //Why in this place getFileEncodeBase64String() return old base64 string? But 
         formData.append('x', file.getFileEncodeBase64String());
 })
```

**And new example:**

**First image**
![image](https://user-images.githubusercontent.com/41770950/112093350-fc804080-8be4-11eb-8b13-03e3fe181cde.png)

In console chrome:
![image](https://user-images.githubusercontent.com/41770950/112093392-099d2f80-8be5-11eb-904e-2c59ac51732d.png)

**Second image**
![image](https://user-images.githubusercontent.com/41770950/112093462-289bc180-8be5-11eb-8917-ce830d17e2f8.png)

In console chrome:
![image](https://user-images.githubusercontent.com/41770950/112093488-35b8b080-8be5-11eb-9c55-c47045d44964.png)

**Base64 are the same lines!**

---------------------------------------
And I found an error while adding the png file
![image](https://user-images.githubusercontent.com/41770950/112093588-6c8ec680-8be5-11eb-823d-84fe47a5647a.png)
![image](https://user-images.githubusercontent.com/41770950/112093654-93e59380-8be5-11eb-9679-6da2d2cb735c.png)

**Comment by Sector911** [comment]
I dont have this error with JPG format. Only with PNG.

**Comment by rikschennink** [comment]
@Sector911 if you update Doka to the latest version that should be resolved.

**Comment by rikschennink** [comment]
@Sector911 

When does this run?

```
let filesImg = pondImg.getFiles();
// I use FormData() and pondImg.getFiles()
let formData = new FormData();
$.each(pondImg.getFiles(), function (i, file) {
         formData.append('x', file.getFileEncodeBase64String());
 })
```

**Comment by Sector911** [comment]
I call this code by clicking on the "Save all images" my custom button.
 ```
let filesImg = pondImg.getFiles();
// I use FormData() and pondImg.getFiles()
let formData = new FormData();
$.each(pondImg.getFiles(), function (i, file) {
         formData.append('x', file.getFileEncodeBase64String());
 })
$.ajax({
      url: "/file_upload",
      method: "POST",
      data: formData,
      cache: false,
      processData: false,
      contentType: false
}).done((response_files) => {
         console.log('Ok');
     } 
 });
```
----------------------------
Thanks for the update. I do not have time to update, because you release updates very often. Many thanks.

**Comment by rikschennink** [comment]
If I run this code it correctly shows the output image in the browser, is that not the case?

```js
const fileItems = pond.getFiles();

fileItems.forEach((item) => {
    const dataURL = item.getFileEncodeDataURL();

    // preview the output image
    const image = new Image();
    image.src = dataURL;
    document.body.appendChild(image);
});
```

I think that would be a good place to start to see if the image data is correct.

**Comment by Sector911** [comment]
Yes, when i load img in filepond and update this in doka - i see correct preview images:
![image](https://user-images.githubusercontent.com/41770950/112242119-ef238e80-8c96-11eb-8a71-72cbdde8b6a5.png)

But i try this code:
```
const fileItems = pond.getFiles();

fileItems.forEach((item) => {
    const dataURL = item.getFileEncodeDataURL();

    // preview the output image
    const image = new Image();
    image.src = dataURL;
    document.body.appendChild(image);
});
```
I see this:
![image](https://user-images.githubusercontent.com/41770950/112242043-ce5b3900-8c96-11eb-92f3-e4857061c9dd.png)

**Comment by Sector911** [comment]
I think that sources image not update from doka. But i dont understand reason.

**Comment by rikschennink** [comment]
@Sector911 the original file isn't updated, it's still there, only the encoded output is updated. You can also catch the encoded files in the `onpreparefile` callback.

Can you send me a support request via the PQINA customer portal, I'll send you a working demo project tomorrow morning 👍

**Comment by rikschennink** [comment]
@Sector911 I'm awaiting your support ticket 👍

**Comment by Sector911** [comment]
Hello!
I updated the library to a newer version and it worked. Base64 began to assemble correctly. Thanks for the help

**Comment by robitinku** [comment]
hi i face same problem ,and i use pintura.js and my codding exactly same,need solution

**Comment by rikschennink** [comment]
@robitinku make sure the file encode plugin is registered with FilePond.

**Comment by robitinku** [comment]
<script type="module">
 import {
        openEditor,
        processImage,
        createDefaultImageReader,
        createDefaultImageWriter,
        createDefaultImageOrienter,
        legacyDataToImageState,
        getEditorDefaults,
		
    } from './assets/pintura.js';
  
    FilePond.registerPlugin(
        FilePondPluginFileValidateType,
        FilePondPluginImageEditor,
        FilePondPluginFilePoster,
        FilePondPluginFileMetadata,
		//FilePondPluginImagePreview,
		FilePondPluginFileEncode
		
    );



    FilePond.setOptions({
        maxFileSize: '10MB',
        server: {
            url: 'images/',
            process: {
                onload: function (response) {
                    // if (response.status === 'success') {
                        checkValidation();
                        $('#arrange_button_container').show('slow');
                    // }
                },
            },
            revert: {
                url: 'revert',
                onload: function (x) {

                    // X - empty, why????
                    console.log(x)

                },
            },
            load: {
                url: 'images/',
            },
        }, 
		

        onreorderfiles(files, origin, target)
		{
		currentPosition.length=0;
			
		//sessionStorage.setItem('fileList', files);
		
		}
             
    });
  
  pond2 = FilePond.create(document.querySelector('input.filepond2'), {
       allowReorder: true,
        allowDrop: true,
        instantUpload: false,
		allowFileEncode:true,
        filePosterMaxHeight: 256,
        styleLoadIndicatorPosition: 'left right',
        styleProgressIndicatorPosition: 'right bottom',
        styleButtonRemoveItemPosition: 'left bottom',
        styleButtonProcessItemPosition: 'right bottom',
        fileMetadataObject: {
            
            upload_type: 'listing',
            default_image: 0
        },
		legacyDataToImageState: legacyDataToImageState,
	     imageEditor: {
            
            createEditor: openEditor,
            imageReader: [
                createDefaultImageReader,
                {
                    // createDefaultImageReader options here
                },
            ],
             imageEditInstantEdit: true,
            imageWriter: [
                createDefaultImageWriter,
                {
                    targetSize: {
                        width: 800,
                        height: 500,
                    },
                    allowImageCrop: true
                },
            ],

            // Used to poster and output images, runs an invisible "headless" editor instance.
            imageProcessor: processImage,

            // Pintura Image Editor options
            editorOptions: {
                // Pass the editor default configuration options
                ...getEditorDefaults(),

                // This will set a square crop aspect ratio
                 
            },
        }
			
		 
	
		 
    });
</script>
<script>
see my code, where wrong

**Comment by robitinku** [comment]
and submit button

$("#btnsend").click(function(e){
  e.preventDefault();
//
  var form_data = new FormData();
  pondFiles = pond2.getFiles();


  for (var i = 0; i < pondFiles.length; i++) {
            form_data.append('file[]', pondFiles[i].file);
        }
		
		//form_data.append("order",currentPosition);
	

   $.ajax({url:'<?php echo base_url().'index.php/Image/upload';?>',
					 type:'POST',
					data:form_data,
					//dataType: 'JSON',
	                async: false,
				   contentType: false,
                   cache: false,
                   processData: false,
					success:function(result){
							alert(result);
	  
						}});
 
						

});

**Comment by rikschennink** [comment]
Please format the code.

**Comment by robitinku** [comment]
which part

**Comment by robitinku** [comment]
<!DOCTYPE html>
<html>
<head>
<base href=".">

<link rel="stylesheet" href="http://localhost:8012/imageorder/assets/jquery.fileupload.css" >

<link href="http://localhost:8012/imageorder/assets/bootstrap.min.css" rel="stylesheet">

<link href="http://localhost:8012/imageorder/assets/pintura.css" rel="stylesheet">
<link href="http://localhost:8012/imageorder/assets/filepond.css" rel="stylesheet" type="text/css" />
<link href="http://localhost:8012/imageorder/assets/filepond-plugin-file-poster.css" rel="stylesheet" type="text/css"/>

<style>
#listing_photos_container{
	width:80% !important;
}

.row
{
	width:1000px !important;
}

ul.filepond--list{display:flex; background-color:#FF0000 !important;}
.filepond--item{width:32.5%;}

.filepond--action-process-item{
    visibility:hidden;
}

</style

</head>
<body style="position: center;margin-left:10%;margin-top:5%;" >
<div class="row"  >

                                            <div class="col-md-12" id="listing_photos_container">
                                                
                                                <input type="file" class="filepond2" name="uploadFile" id="listing_photos" multiple="multiple" />

                                            </div>
											</div>
                 <div >                
               
				<button
                      style="background-color: #3f5ea1; border: none;"
                      class="btn btn btn-primary ml-auto js-btn-next w-25 text-uppercase"
                      type="button"
                      title="Next"
					  id="btnsend"
                    >
                      Save Order
                    </button>
					</div>
					 

</body>
</html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>

<script src="http://localhost:8012/imageorder/assets/filepond-plugin-file-poster.js"></script>
<script src="http://localhost:8012/imageorder/assets/filepond-plugin-file-validate-type.js"></script>
<script src="http://localhost:8012/imageorder/assets/filepond-plugin-file-metadata.js"></script>
<script src="http://localhost:8012/imageorder/assets/FilePondPluginImageEditor.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"></script>
<script src="https://unpkg.com/filepond/dist/filepond.js"></script>


<script type="module">
 import {
        openEditor,
        processImage,
        createDefaultImageReader,
        createDefaultImageWriter,
        createDefaultImageOrienter,
        legacyDataToImageState,
        getEditorDefaults,
		
    } from './assets/pintura.js';
  
    FilePond.registerPlugin(
        FilePondPluginFileValidateType,
        FilePondPluginImageEditor,
        FilePondPluginFilePoster,
        FilePondPluginFileMetadata,
		//FilePondPluginImagePreview,
		FilePondPluginFileEncode,
		
    );

 pond2 = FilePond.create(document.querySelector('input.filepond2'), {
       allowReorder: true,
        allowDrop: true,
        instantUpload: false,
		allowFileEncode:true,
        filePosterMaxHeight: 256,
        styleLoadIndicatorPosition: 'left right',
        styleProgressIndicatorPosition: 'right bottom',
        styleButtonRemoveItemPosition: 'left bottom',
        styleButtonProcessItemPosition: 'right bottom',
        fileMetadataObject: {
            
            upload_type: 'listing',
            default_image: 0
        },
		legacyDataToImageState: legacyDataToImageState,
	     imageEditor: {
            
            createEditor: openEditor,
            imageReader: [
                createDefaultImageReader,
                {
                    // createDefaultImageReader options here
                },
            ],
             imageEditInstantEdit: true,
            imageWriter: [
                createDefaultImageWriter,
                {
                    targetSize: {
                        width: 800,
                        height: 500,
                    },
                    allowImageCrop: true
                },
            ],

         
            imageProcessor: processImage,

            
            editorOptions: {
             
                ...getEditorDefaults(),
 
            },
			
        }
			
		 
    });
</script>


<script>
var pond2;
$(document).ready(function(){
$("#btnsend").click(function(e){
  e.preventDefault();

  var form_data = new FormData();
  pondFiles = pond2.getFiles();


  for (var i = 0; i < pondFiles.length; i++) {
            form_data.append('file[]', pondFiles[i].file);
        }
		
   $.ajax({url:'http://localhost:8012/imageorder/index.php/Image/upload',
					 type:'POST',
					data:form_data,
					//dataType: 'JSON',
	                async: false,
				   contentType: false,
                   cache: false,
                   processData: false,
					success:function(result){
							alert(result);
	  
						}});
 
});

});

</script>

**Comment by robitinku** [comment]
import {
        openEditor,
        processImage,
        createDefaultImageReader,
        createDefaultImageWriter,
        createDefaultImageOrienter,
        legacyDataToImageState,
        getEditorDefaults,
		
    } from './assets/pintura.js';
  
    FilePond.registerPlugin(
        FilePondPluginFileValidateType,
        FilePondPluginImageEditor,
        FilePondPluginFilePoster,
        FilePondPluginFileMetadata,
		//FilePondPluginImagePreview,
		FilePondPluginFileEncode,
		
    );

 pond2 = FilePond.create(document.querySelector('input.filepond2'), {
       allowReorder: true,
        allowDrop: true,
        instantUpload: false,
		allowFileEncode:true,
        filePosterMaxHeight: 256,
        styleLoadIndicatorPosition: 'left right',
        styleProgressIndicatorPosition: 'right bottom',
        styleButtonRemoveItemPosition: 'left bottom',
        styleButtonProcessItemPosition: 'right bottom',
        fileMetadataObject: {
            
            upload_type: 'listing',
            default_image: 0
        },
		legacyDataToImageState: legacyDataToImageState,
	     imageEditor: {
            
            createEditor: openEditor,
            imageReader: [
                createDefaultImageReader,
                {
                    // createDefaultImageReader options here
                },
            ],
             imageEditInstantEdit: true,
            imageWriter: [
                createDefaultImageWriter,
                {
                    targetSize: {
                        width: 800,
                        height: 500,
                    },
                    allowImageCrop: true
                },
            ],

         
            imageProcessor: processImage,

            
            editorOptions: {
             
                ...getEditorDefaults(),
 
            },
			
        }
		
    });

**Comment by robitinku** [comment]
$(document).ready(function(){
$("#btnsend").click(function(e){
  e.preventDefault();

  var form_data = new FormData();
  pondFiles = pond2.getFiles();


  for (var i = 0; i < pondFiles.length; i++) {
            form_data.append('file[]', pondFiles[i].file);
        }
		
   $.ajax({url:'<?php echo base_url().'index.php/Image/upload';?>',
					 type:'POST',
					data:form_data,
					//dataType: 'JSON',
	                async: false,
				   contentType: false,
                   cache: false,
                   processData: false,
					success:function(result){
							alert(result);
	  
						}});
});

});

**Comment by robitinku** [comment]
[image view.txt](https://github.com/pqina/filepond/files/8213584/image.view.txt)

**Comment by gonzaguerini** [comment]
> I delete plugins, but this not work.
> 
> ```js
> import {
>     // editor
>     openEditor,
>     processImage,
>     createDefaultImageReader,
>     createDefaultImageWriter,
>     imageOrienter,
>     locale_en_gb,
>     legacyDataToImageState,
> 
>     // plugins
>     setPlugins,
>     plugin_finetune,
>     plugin_finetune_defaults,
>     plugin_finetune_locale_en_gb,
>     plugin_filter,
>     plugin_filter_defaults,
>     plugin_filter_locale_en_gb,
>     plugin_decorate,
>     plugin_decorate_defaults,
>     plugin_decorate_locale_en_gb
> } from '/assets/uploader/doka/doka.js';
> import ru_RU from '/assets/uploader/filepond/locale/ru-ru.js';
> 
> setPlugins(plugin_finetune, plugin_filter, plugin_decorate);
> 
> FilePond.registerPlugin(
>     FilePondPluginFileValidateType,
>     FilePondPluginImageEditor,
>     FilePondPluginFilePoster,
>     FilePondPluginFileMetadata,
>     FilePondPluginFileEncode
> );
> 
> FilePond.setOptions({
>     allowMultiple: true,
>     allowReorder: true
> });
> 
> //Изображения
> pondImg = FilePond.create(document.querySelector('#filepond-imgs'), {
>     imageEditor: {
>         // map legacy data objects to new imageState objects
>         legacyDataToImageState: legacyDataToImageState,
> 
>         // used to create the editor, receives editor configuration, should return an editor instance
>         createEditor: openEditor,
> 
>         // Required, used for reading the image data
>         imageReader: [createDefaultImageReader],
> 
>         // optionally. can leave out when not generating a preview thumbnail and/or output image
>         imageWriter: [createDefaultImageWriter],
> 
>         // used to generate poster images, runs an editor in the background
>         imageProcessor: processImage,
> 
>         // editor options
>         editorOptions: {
>             imageOrienter: imageOrienter,
>             ...plugin_finetune_defaults,
>             ...plugin_filter_defaults,
>             ...plugin_decorate_defaults,
>             locale: {
>                 ...locale_en_gb,
>                 ...plugin_finetune_locale_en_gb,
>                 ...plugin_filter_locale_en_gb,
>                 ...plugin_decorate_locale_en_gb,
>             },
>         },
>     },
>     filePosterMaxHeight: 100
> });
> ```
> 
> Files remain unchanged when transferred to the server. Both base64 string and just $ _FILES In Doka: ![image](https://user-images.githubusercontent.com/41770950/111978470-a6ad8900-8b4f-11eb-8b63-9bd3aac4f916.png)
> 
> In server: ![image](https://user-images.githubusercontent.com/41770950/111978528-b6c56880-8b4f-11eb-8e38-9e082033c8e4.png)

I know it's late, but to upload the file with the changes you must include the filepond-plugin-image-transform plugin (https://pqina.nl/filepond/docs/api/plugins/image-transform/)
It also took me a while to figure it out. And in the docs it says perfectly that this plugin is required too
