### ISSUE TITLE
Get instance from dom element

### ISSUE THREAD

**Issue by bilalmalkoc** [pqina/filepond#680]
Is there any way to get instance from dom element?
`<div class="filepond--root my-custom-uploader-1">...</div>`

**Comment by rikschennink** [comment]
`find` → https://pqina.nl/filepond/docs/patterns/api/filepond-object/#methods

**Comment by bilalmalkoc** [comment]
Hello. Thank you for your quick response. Can you write a simple example please? It is not clear for me. Maybe like this?

`document.querySelector( '.my-custom-uploader-1' ).FilePond.getFile();`

**Comment by rikschennink** [comment]
`FilePond.find(document.querySelector(“.my-class-name”));`

**Comment by bilalmalkoc** [comment]
OK. Thank you so much.
