### ISSUE TITLE
Accepting Functions on Dropping of file

### ISSUE THREAD

**Issue by imabp** [pqina/filepond#685]
**Problem**
For my use case, we need a function to be called, when a file is dropped in the file pond, which does the necessary handling and uploading the file. Our constraint is, we are not going to have any backend.

**Solution**
If there is a prop like, onDrop={handler} will definitely solve my problem. 

**Describe alternatives you've considered**
The alternative I considered, was creating a quick express server and uploading the file there.

**Comment by rikschennink** [comment]
Hi you can use the `server.process` end point to upload or send files to other storage locations.
