### ISSUE TITLE
Odd behaviour or maybe I am using it wrongly

### ISSUE THREAD

**Issue by viotopo** [pqina/filepond#688]
I am using filepond to upload pictures for real estate listings. 

When I create new listings everything works fine, I upload everything to Amazon S3 internally and no complaints. The odd situation arises when I allow the user to modify the listing, obviously, I have to show all the images previously uploaded and I am doing it this way:

`<fieldset class="filepond" id="file"
              files="fieldset">
        <ul>
            @foreach($images as $asset)
                <li>
                    <label>
                        <input value="{{ $asset }}" data-type="local" checked type="checkbox" style="display:none;">
                    </label>
                </li>
            @endforeach
        </ul>`

What filepond is doing is like uploading everything again, you can read the uploading and takes ages. That's not normal because the main thing I need is to show the images inside the filepond container and that should be something straightforward, I need to have the X button to allow the user to delete the picture and all the functionality rearranging pictures, etc. 

This is code in js: (I know is a bit messy but works, for some reason wasn't showing the fading background behind the text, it was loading the image but not showing, the behaviour, as I said, was odd and for sure it's my fault.

`load: (source, load, error, progress, abort, headers) => {
                    // This is the AWS S3 URL https://bucket...../image.jpg
                    let fetchURL = getURL('get-file')+'/'+elemFile.getAttribute('identifier')+'/';

                    fetch(fetchURL + source)
                        .then(response => response.blob())
                        .then(blob => {
                            load(blob)
                            var uri = URL.createObjectURL(blob);
                            var img = new Image();

                            // I had to do this code in order to show to show the image, the image was there but hidden.
                            let elemText = Array.from(document.querySelectorAll('span')).find(el => el.textContent === source);
                            let panel = elemText.parentElement.parentElement.parentElement.parentElement.querySelectorAll('.filepond--panel')[0];
                            img.src = uri;
                            img.setAttribute("style", "position:absolute; top: 0; border-radius: 8px;");

                            [].forEach.call(panel.querySelectorAll('.filepond--item-panel'), function(div) {
                                div.setAttribute("style", "display: none !important;");
                            });
                            // I had to do this code to position the background underneath the text.
                            const newDiv = document.createElement("div");
                            newDiv.setAttribute("style", "z-index: 1; width:100%; position:absolute; top: 0; border-radius: 8px; height: 50px; background-image: linear-gradient(rgba(0,0,0,0.25), rgba(0,0,0,0));");
                            panel.appendChild(newDiv);
                            panel.appendChild(img);

                        });
                }`

Can anyone help me with this issue, absolutely lost with this issue. I want filepond loads the image from the URL showing the text and background and keep the functionality on the X button to delete the picture.

Million thanks

**Comment by rikschennink** [comment]
Why not use the image preview plugin?

**Comment by viotopo** [comment]
Thank you, I will have a look :)

**Comment by rikschennink** [comment]
Closed because inactive.
