### ISSUE TITLE
FilePond performance degrades for every file item

### ISSUE THREAD

**Issue by enisdenjo** [pqina/filepond#69]
Hey hey,

this is another **enhancement** request. Essentially using FilePond on an average device and uploading 15+ items immediately causes a heavy frame drop! We can either: have a property `enableAnimations` which would disable the animations completely; disable the animations automatically when received N+ items; or virtualize the items.

The first 2 options are self-explanatory, but regarding the virtualization we can approach it from various sides. The one that I would use is `IntersectionObserver` (https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). Essentially we would wrap every item with the `IntersectionObserver` (of course to a single instance of `IntersectionObserver` to maintain the performance) and render only when its in the screen, otherwise hide it. Its often not a good approach to wrap EVERY item with an `IntersectionObserver`, but from my personal experience as soon as you are NOT wrapping more than 200 items on a single instance you're good to go. Also you can recycle the `IntersectionObserver` by removing (un-observing) it from the item once its rendered/displayed.

On the other hand we can also hack this currently by setting the `maxFiles` prop to a desired pool size. But to be honest, for me the `maxFiles` logic is not good when `maxFiles > 10`. Why? Well FilePond **SILENTLY** omits files once it reached the `maxFiles` threshold. This would cause **huge** confusion with users which drag and drop `maxFiles + (20+)` files as they magically disappear and the user might not even know that they were NOT uploaded. Of course except for those users which will scroll and manually check the state of 30+ files (which is like 2% of the average internet consumer).

Best,
Denis

**Comment by rikschennink** [comment]
Hi Denis,

Some questions as FilePond already heavily optimizes for render performance.

- What device specifically are you testing on?
- Does the problem occur on a blank page ( to make sure no other script is interfering )? 
- Does the problem occur without any plugins loaded? 
- On which browsers did you test this?
- And is the problem the same on all browsers?

**Comment by enisdenjo** [comment]
Hey @rikschennink,

So I just stress tested your own FilePond instance on https://pqina.nl/filepond/. And I saw a different result! The problem causing the performance bottleneck is in MY custom plugin or the implementation, I must've missed some re-flow causing JS calls... Sorry again, I'll report back soon once I find out what is causing the problem exactly.

You can close this issue!

My bad! 😭

**Comment by rikschennink** [comment]
No problem @enisdenjo, be careful to do DOM reads in a read function and writes in a write function. It's a bit finicky but results in very smooth performance.

**Comment by pkat** [comment]
Hi @rikschennink,

I have a scenario in which a user would be dropping a folder with potentially hundreds of files. I'm using the React adaptor and i'm seeing frames drop and a performance lag in rendering when adding the 100+ files.

Additionally I have some validation logic that reads the first few bytes of each file, which can get JS heavy, further compounding the lag. Of course this quantity of files and validation is not ideal, but is a requirement for what i'm working on.

1) Is there an option to disable the transform animation on the `filepond--item` when adding items or any way around the transform animations?
2) Or is there any option to display the files as a group?
3) On a slight unrelated question, is there an ability to queue uploads or limit the number of concurrent uploads?

Thanks,
Prashant

**Comment by rikschennink** [comment]
@pkat It's simply not built to animate 100's of files. Even without that if you'd start doing CPU heavy operations on 100's of files things would start to slow down.

I'm looking into grouping multiple files (folders or sets of dropped files).

Queueing uploads is on my high priority todo list so should be available soon.

**Comment by pkat** [comment]
@rikschennink I understand. Thanks for the response and the update on grouping and queuing uploads!

**Comment by drone1** [comment]
I've actually got an issue where filepond.js is eating up 5-10ms per frame on a page that does not even have a filepond component loaded. The CSS, however, is present, and "Animation Frame Fired" seems to be causing a hit on performance. Will investigate further.

**Comment by rikschennink** [comment]
@drone1 That sounds like a lot for a simple `requestAnimationFrame` loop that doesn't do anything, do you have a public test case for this?

**Comment by drone1** [comment]
@rikschennink Yeah I agree. Are you 100% sure it isn't doing anything at all? 

I do not have a test case for you. I can tell you I'm on macOS Mojava, 10.14.5 (18F132), MacBook Pro (15-inch, 2018). 

Filepond stuff that I've got in the project:

├── filepond@4.4.7
├── filepond-plugin-file-validate-size@2.1.3
├── filepond-plugin-image-exif-orientation@1.0.6
├── filepond-plugin-image-preview@4.1.1

The only actual bit of my code that was being run, with regard to FilePond, however, was this:

```import * as FilePond from 'filepond'```

I had plugins conditionally imported, in code that was not running. So yeah, literally this one line, plus the SASS imports for ``filepond`` and ``filepond-plugin-image-preview``

So yeah, I don't have a JSfiddle for you. I'm guessing you've looked and do not see this behavior though?

**Comment by rikschennink** [comment]
This is with 6x CPU slowdown on Macbook Pro Mid 2014 on https://pqina.nl/filepond/

![Screenshot 2019-06-20 at 19 02 16](https://user-images.githubusercontent.com/1132575/59867249-ffa22900-938d-11e9-80ff-6fe3e9759034.png)

**Comment by drone1** [comment]
Is this a screenshot of Filepond included but doing nothing (ie no Filepond
instances on the page)?

If so, isn't 1.31ms high for doing nothing, when there are only ~17ms
budgeted per frame?

I will try to repro when I find some time.

**Comment by rikschennink** [comment]
@drone1 you can test it isolated on this page: https://j71ps.codesandbox.io/

It's high if it was on a high-end laptop without CPU slowdown BUT I'm testing on an average 2014 MacBook Pro with CPU slowdown @ 6x so I'd say 1.31ms is very reasonable. Without the slowdown it takes 0.16ms to run. Again I know this is not ideal.
