### ISSUE TITLE
server.remove callback not called for local files edited with image editors.

### ISSUE THREAD

**Issue by Rampin97** [pqina/filepond#690]
**Describe the bug**

server.remove callback not called for local files edited with [Doka Image Editor](https://pqina.nl/doka/) or other third party image editors.

The remove callback is called together with revert callback only when I delete the edited image. If you never delete the edited image, the server is not aware that the original is removed and the final result is 2 images in the server (the edited one and the original).

This does not happen if the file is uploaded in the same session (`file.origin === FileOrigin.INPUT`)

**To Reproduce**

[CodeSandbox](https://codesandbox.io/s/filepond-editor-plugin-bug-ei26q?file=/src/index.js)

**Expected behavior**

server.remove callback called for the original image after the user confirm his changes in the editor.

**Information about your project:**

Tested with 
- Chrome 90 - Windows 10 and Ubuntu 20.10
- Firefox 87 - Ubuntu 20.10
- Filepond 4.27.0
- filepond-plugin-image-preview 4.6.6
- filepond-plugin-image-edit 1.6.3
- this issue appear with Doka 7.8.0 and its plugin for FilePond too

**Additional context**

I attached a video that reproduce the problem

https://user-images.githubusercontent.com/9613211/115115322-2898a280-9f94-11eb-9d87-41ea74ec16b0.mp4

**Comment by rikschennink** [comment]
@Rampin97 Thanks for reporting, I reproduced the issue, will look into this as soon as possible.

**Comment by rikschennink** [comment]
Should be fixed in https://github.com/pqina/filepond/releases/tag/4.28.2

**Comment by Rampin97** [comment]
I confirm that it's now fixed. Thank you :-)
