### ISSUE TITLE
Synchronous upload?

### ISSUE THREAD

**Issue by ddsky** [pqina/filepond#692]
The website states filepond supports synchronous and asynchronous upload. I can't find how to "turn on" synchronous upload. I don't want to implement the more complex processing logic on my server so I was wondering what setting I have to use to just send the entire binary file to my server just like with a normal form submit?

**Comment by rikschennink** [comment]
You can use the file encode plugin to upload synchronously, this would require changes to to the server so it can turn the base64 strings back into file objects.

See the article below for more information:
https://pqina.nl/blog/the-trouble-with-editing-and-uploading-files-in-the-browser/
