### ISSUE TITLE
allowMultiple with maxFiles forces the upload of the maximum number of files, no less

### ISSUE THREAD

**Issue by funkyfennec** [pqina/filepond#694]
**Describe the bug**

Having the properties maxFiles and allowMultiple together forces the upload of exactly the number of maxFiles specified, no less.

Is there a way to allow the upload of a maxFiles: 0 to n, with allowMultiple: true. That way the user can choose not to upload anything but if they do, they can upload up to n files with one browse or drop?

Thanks.

P.S: I read the documentation on both these properties and there was not a link between them. i.e: maxFiles will not work without allowMultiple OR having both forces the behaviour described above.

**To Reproduce**

Instantiate a FilePond object with the properties: maxFiles: {somenumber} AND allowMultiple: true .

**Expected behavior**

The ability to multi select up to {somenumber} of files or zero and not be forced to select exactly {somenumber}

**Comment by rikschennink** [comment]
Do you mean when the max number of files is exceeded the component goes in error state?

**Comment by funkyfennec** [comment]
Hi thanks for your answer. I'm not sure if this is a bug or something I'm missing but this is I want to achieve. I want a user to be able to upload 0 or n number of files and be able to multiselect them (not having to browse for each one).

If I set the properties {**maxFiles: n**} AND {**allowMultiple: true**}. If forces the user to select exactly **n** files. They cannot submit a form with 0 upload.

**The weird part is:**
On this sandbox, it works [here](https://codesandbox.io/s/confident-pare-t4m40?file=/src/index.js) however locally It will not let me submit unless I have the number of files specified in the maxFiles or set allowMultiple to false.

I've tried loading the scripts with defer and directly in the html like in the sandbox.
I fail to see what exactly is going on

**Comment by rikschennink** [comment]
The sandbox was missing a doctype, so that caused some weird rendering.

Some ideas to find the issue:
- test if you haven't set required attribute on the input
- remove everything except what you see in the sandbox
- only load filepond core

Updated version:
https://codesandbox.io/s/great-firefly-okzdh?file=/index.html

(I will close the issue because this is not related to FilePond)
