### ISSUE TITLE
Progress percentage is "NaN"

### ISSUE THREAD

**Issue by rowhel95** [pqina/filepond#695]
On v4.27.0 with allowMinimumUploadDuration: false when uploading the progress percentage is "NaN".

![image](https://user-images.githubusercontent.com/17615589/116519364-b13b0b00-a8d1-11eb-87cd-cff844597f6d.png)

Browser: latest Edge

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. 

**Please leave a comment after you've updated the issue.**

**Comment by rikschennink** [comment]
Fixed in v4.27.1
