### ISSUE TITLE
Layout bug file poster plugin

### ISSUE THREAD

**Issue by rowhel95** [pqina/filepond#696]
On version v4.27.0 and file poster plugin v2.4.2 this happens:

![image](https://user-images.githubusercontent.com/17615589/116520203-b187d600-a8d2-11eb-80fd-8976040f2779.png)

Browser: latest edge

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. 

**Please leave a comment after you've updated the issue.**

**Comment by rikschennink** [comment]
Firefox and Safari both render this correctly, it seems this is a chromium bug.

**Comment by rikschennink** [comment]
Fixed in `2.4.3` still a chrome bug probably.

`<canvas>` wouldn't scale properly with `width: 100%` unless setting `aspect-ratio` to `auto`.
