### ISSUE TITLE
Able to select main file or thumbnail of the multiple uploaded files

### ISSUE THREAD

**Issue by YashsviG** [pqina/filepond#698]
An star can be used to mark a file as main file or an image uploaded as thumbnail and a filled star could represent if the file is selected as the main.

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. 

**Please leave a comment after you've updated the issue.**
