### ISSUE TITLE
Wrong MIME type transferred when using CDN ?

### ISSUE THREAD

**Issue by FaycalBorsali** [pqina/filepond#699]
**Describe the bug**
Importing the `css` files via CDN comes with wrong MIME type.

**Logs**
The browser console gives :
`Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://unpkg.com/filepond/dist/filepond.css".`

**To Reproduce**
Follow the instruction from the [docs](https://pqina.nl/filepond/docs/patterns/installation/#from-a-cdn)

**Expected behavior**
Just importing the css without any warning or error

**Information about your project:**

- Browser: `Chrome Version 89.0.4389.82 (Official Build) (64-bit)`
- Operating system: `Ubuntu 20.04`
- FilePond version `// Doesn't apply`

**Additional context**
The project is laravel-based.
I am adding this line `<link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet" />` to the head in a template blade file upon which all files are based (other stylesheets are imported via CDN within the same head tag and there is no problem with them)
The filepond styles apply correctly

**Comment by rikschennink** [comment]
I don't control the CDN. Not sure why this happens so if you have any suggestions I'm happy to hear them.

Will close as it's unrelated to FilePond itself.

**Comment by FaycalBorsali** [comment]
I fixed it by specifying the version in the `href` so it became :

`<link href="https://unpkg.com/filepond@4.27.1/dist/filepond.css" rel="stylesheet" />`

This has its limitation (need to manually upgrade) but I think it would be nice if this was mentioned in the docs

Thank you anyway
