### ISSUE TITLE
Canvas toBlob quality option

### ISSUE THREAD

**Issue by kasparek** [pqina/filepond#7]
FilePondPluginImageTransform

image.toBlob(resolve, options.type, **options.quality**);

Canvas toBlob function accepts values for quality parameter between **0-1**

so if the parameter imageTransformOutputQuality specified by docs between 0-100 is used directly images are always encoded 100% quality

So either use imageTransformOutputQuality: **0.6**, or change to image.toBlob(resolve, options.type, **options.quality/100**);

**Comment by rikschennink** [comment]
You're absolutely right, it takes a value between 0 and 100, should be divided by hundred before being applied. Thanks for reporting @kasparek! Will fix this on Monday.

**Comment by rikschennink** [comment]
@kasparek Just published version 1.0.1 to npm and [GitHub](https://github.com/pqina/filepond-plugin-image-transform).
