### ISSUE TITLE
when adding a blob, blob name is ignored and current date used as name instead

### ISSUE THREAD

**Issue by kevduggan** [pqina/filepond#70]
I am added a Blob using the addFile function. the name of the file then gets set to the current date.
<img width="468" alt="screen shot 2018-06-22 at 11 09 48" src="https://user-images.githubusercontent.com/3285939/41771368-d24fc074-760c-11e8-8032-5fd2d504229e.png">

there doesn't appear to be any way of over-ridding this behaviour (I am using the blob method in IE11 as adding a File object not working). Is there a way to set the filename after the upload (i've tried using setMetadata on the returned File but it had no effect)

debugging you can see that the blob has a name
<img width="847" alt="screen shot 2018-06-22 at 11 07 48" src="https://user-images.githubusercontent.com/3285939/41771340-ae01d78e-760c-11e8-81b6-6968aa4990ad.png">

**Comment by rikschennink** [comment]
FilePond tests if it's an instance of `File` or `Blob`, you can turn a Blob into a file using the following method:

```js
var file = new File([myBlob], 'name.extension');
```

This might not work on older browsers, I'll see if I can adjust the logic so it tests for `name` and only sets the `name` and `lastModifiedDate` automatically if they're missing.

**Comment by rikschennink** [comment]
Just published version 1.8.1, should work now. Please confirm.

**Comment by kevduggan** [comment]
works like a dream @rikschennink. Thanks a million!

**Comment by rikschennink** [comment]
@kevduggan Fabulous! Thanks for confirming. :-)
