### ISSUE TITLE
Plugin for custom functionalities

### ISSUE THREAD

**Issue by BuchholzTim** [pqina/filepond#700]
**Is your feature request related to a problem? Please describe.**
A few days ago I opened and closed this issue #697 . I have to hash each file and do some validation stuff before actually uploading it. I could now overwrite the whole `process`-function, as you mentioned. But this seems somewhat over-the-top, as the current functionality of `process` is fine, I just need to do something in-before.

So I tried looking if I could make it somehow work without changing `process`.

I discovered, that I can somewhat abuse the [Type-Validation-Plugin](https://github.com/pqina/filepond-plugin-file-validate-type) . It has the option to present a custom function via `fileValidateTypeDetectType`, which allows basically what I asked for. Evaluate something based on the file and then `resolve` or `reject` the promise. 

**Describe the solution you'd like**
My solution does work, but I don't like it in terms of understandable and clean code. Importing the Type-Validation-Plugin for another reason than validating types is misleading. 

A relatively easy solution would be to write a new plugin with most of the obligations and functionality of the Type-Validation-Plugin stripped. Currently I have to provide all Mime-Types, which I want to allow, since leaving the Array of accepted Types empty leads to rejection of every file.

So a plugin which can be given a promise-based function that executes on `'LOAD_FILE'` would be a really clean solution I think.

**Additional context**
I implemented it myself based on the mentioned plugin. I'm sure the code is optimizable and perhaps only listening on `'LOAD_FILE'` is an issue, but perhaps you could take a look and if you think it's worthwhile adopt it as a plugin-idea 😄 

```js
const plugin = ({ addFilter, utils }) => {
  // get quick reference to Type utils
  const {
    Type,
    isString,
    replaceInString,
    guesstimateMimeType,
    getExtensionFromFilename,
    getFilenameFromURL,
  } = utils;

  const validateFile = (file, customPreloadFunction) =>
    new Promise((resolve, reject) => {
      customPreloadFunction(file)
        .then(() => {
          resolve();
        })
        .catch(reject);
    });

  // called for each file that is loaded
  // right before it is set to the item state
  // should return a promise
  addFilter(
    'LOAD_FILE',
    (file, { query }) =>
      new Promise((resolve, reject) => {
        // custom type detector method
        const customPreloadFunction = query('GET_PRE_LOAD_FUNCTION');
        const errorMessageBig = query('GET_ERROR_MESSAGE_BIG');
        const errorMessageSmall = query('GET_ERROR_MESSAGE_SMALL');

        // If function is not provided exit
        if (!customPreloadFunction) {
          return resolve(file);
        }

        const validationResult = validateFile(file, customPreloadFunction);

        const handleRejection = () => {
          const answer = {
            status: {
              main: errorMessageBig,
              sub: errorMessageSmall,
            },
          };

          reject(answer);
        };

        // has returned immidiately
        if (typeof validationResult === 'boolean') {
          if (!validationResult) {
            return handleRejection();
          }
          return resolve(file);
        }

        // is promise
        validationResult
          .then(() => {
            resolve(file);
          })
          .catch(handleRejection);
      }),
  );

  // expose plugin
  return {
    // default options
    options: {
      // Custom function to detect type of file
      preLoadFunction: [null, Type.FUNCTION],
      errorMessageBig: ['Big Error-Label', Type.STRING],
      errorMessageSmall: ['Small Error-Label', Type.STRING],
    },
  };
};

// fire pluginloaded event if running in browser, this allows registering the plugin when using async script tags
const isBrowser =
  typeof window !== 'undefined' && typeof window.document !== 'undefined';
if (isBrowser) {
  document.dispatchEvent(
    new CustomEvent('FilePond:pluginloaded', { detail: plugin }),
  );
}

export default plugin;
```

**Comment by rikschennink** [comment]
Hey, that's exactly what the `addFilter` function is for, to allow creation of custom plugins. So if it works 👍
