### ISSUE TITLE
 9:315 Uncaught ReferenceError: FilePond is not defined

### ISSUE THREAD

**Issue by CleoCTech** [pqina/filepond#701]
I'm using Laravel, where I installed Filepond with CDN 

It was working pretty well with images uploading, and then it's just stoped with no code touch.  

**Logs**

![image](https://user-images.githubusercontent.com/45172768/117609702-24157300-b169-11eb-8ef7-455f68512d21.png)

HTML
`<div class="custom-file">`
      ` <input type="file" id="test">`
 ` </div>`

Script
`<script>`
    `const inputElement = document.querySelector('input[id="test"]');`
    `const pond = FilePond.create( inputElement );`
   ` FilePond.setOptions({`
        `server:{`
            `url: '/upload',`
           ` headers: {`
                `'X-CSRF-TOKEN': '{{ csrf_token() }}'`
           ` }`
      `  }`
    `});`
`</script>`

Kindly help.

**Comment by rikschennink** [comment]
I do not manage the CDN so if it doesn't return FilePond you might get errors. I'll close this issue as it's not related to FilePond itself.
