### ISSUE TITLE
Problems after updating Bootstrap to v.5

### ISSUE THREAD

**Issue by gboscolo** [pqina/filepond#706]
Hi there, i'm facing some style after updating Bootstrap to the latest release (5.0.1)
here's the actual appearance, it seems to be over-sized:

![image](https://user-images.githubusercontent.com/26042341/118638940-a93b0080-b7d7-11eb-8364-9d0a806e5b0a.png)

Is it planned to update stylesheet to be compliant with the new bs release? I wanna avoid to overwrite your stylesheet to achieve the same look!

Many thanks 
Gianluca

**Comment by rikschennink** [comment]
Haven't gotten around this yet, can you create a public test case on codesandbox.io? Project with FilePond and Bootstrap 5, that would help speed this up.

**Comment by rikschennink** [comment]
Ran a quick test here but seems to be okay?
https://codesandbox.io/s/filepond-bootstrap-5-test-pjm98?file=/src/index.js
