### ISSUE TITLE
Looking for rotate option

### ISSUE THREAD

**Issue by riktamnandi** [pqina/filepond#711]
**### Looking for photo rotate feature. How i could do this using filepond plugin?**

**Comment by rikschennink** [comment]
That’s what https://pqina.nl/doka/ is for.

**Comment by riktamnandi** [comment]
> That’s what https://pqina.nl/doka/ is for.

Thank you Rik.

But can I use DOKA in my existing code? Or I have to replace my upload code from beginning?

**Comment by rikschennink** [comment]
The upload code stays the same.

See https://pqina.nl/doka/docs/v7/getting-started/installation/filepond/

**Comment by riktamnandi** [comment]
> The upload code stays the same.

Thank you.

How much it would cost?

**Comment by rikschennink** [comment]
See https://pqina.nl/pricing/

**Comment by rikschennink** [comment]
(fixed URL typo)

**Comment by rikschennink** [comment]
Will close the issue because it doesn’t fit the issue template and I think it’s been answered.
