### ISSUE TITLE
unable to determine when multiple uploads are done processing

### ISSUE THREAD

**Issue by vesper8** [pqina/filepond#715]
**Describe the bug**

I am using vue-filepond and I can't figure out how to determine when multiple files are finished uploading. I read the documentation and and I see that a onProcessFiles event has been added for exactly this. However nothing I do is triggering this event when using vue-filepond

I already use `@processfile="onProcessFile"` which works fine

I have tried setting `@processfiles="onProcessFiles"` but this never gets called

Alternatively if there was a way to get the number of still-processing files inside of `onProcessFile` then I could know whether `onProcessFile` is being called for the last time. I need to call an event after ALL files are finished uploading.

**Expected behavior**

I expect to be able to determine when filepond is completely finished processing all files in the event that multiple files are queued at once

**Information about your project:**

```
Chrome 90
MacOS Big Sur
filepond@4.27.2
├─ vue-filepond@6.0.3
```

Many thanks

**Comment by rikschennink** [comment]
Replied to other issue
https://github.com/pqina/vue-filepond/issues/27#issuecomment-850204897
