### ISSUE TITLE
Canvasrenderingcontext2d getimagedata out of memory

### ISSUE THREAD

**Issue by misisol** [pqina/filepond#716]
**Describe the bug**

While transforming the image, apporach this error in console Chrome browser : 
```
Reason : Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
Error Stack : RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
```
[filepond-all.min.js.zip](https://github.com/pqina/filepond/files/6602329/filepond-all.min.js.zip)

I've merged the modules I wanted in a file named filepond-all.min.js which has been attached and have this stack log error too which will help :
```
 at n.canvasMemoryLimit (/filepond-all.min.js:35:19694)
    at /filepond-all.min.js:35:19743
```

**Comment by rikschennink** [comment]
Please provide an example on Codesandbox, you can fork this repo: https://codesandbox.io/s/restless-frost-9998c

Will close for now.
