### ISSUE TITLE
Upload empty folders

### ISSUE THREAD

**Issue by kevinexxas** [pqina/filepond#718]
Hi 

We're not able to upload empty folders. 

We are able to upload file structures but filepond ignores empty folders. Is there a way that we can upload empty folders too? 

It would be good could have a callback for empty folders. That would be awesome. 

Somebody in the past already requested that. But the ticket was closed due to low demand. 
https://github.com/pqina/filepond/issues/463

Is there a chance that we can upload empty folders with froala? I've tried everything but failed unfortunately

**Comment by rikschennink** [comment]
No duplicate tickets please. Keep it in #463
