### ISSUE TITLE
Restore frontend + server example potential bug?

### ISSUE THREAD

**Issue by AndreasElia** [pqina/filepond#720]
I'm working on adding "restore" functionality to a Laravel project, but ran into an issue where filepond always displays "upload complete" for chunked files.

As you can see from the below code, I return the file and header as expected via the filepond documentation.

```php
public function restore(Request $request, string $id)
{
    $disk = config('filepond.temporary_files_disk', 'local');
    $path = config('filepond.temporary_files_path', 'filepond').DIRECTORY_SEPARATOR.$id;

    $mime = Storage::disk($disk)->mimeType($path);
    $file = Storage::disk($disk)->get($path);

    return Response::make($file, 200, [
        'Content-Type' => $mime,
        'Content-Disposition' => 'inline; filename="'.$id.'"',
    ]);
}
```

Routes (overwritten):

```php
// Filepond
Route::prefix('filepond')->group(function () {
    Route::patch('/', [FilepondController::class, 'chunk'])->name('filepond.chunk');
    Route::post('/process/{video}', [FilepondController::class, 'upload'])->name('filepond.upload');
    Route::delete('/process/{video}', [FilepondController::class, 'delete'])->name('filepond.delete');
    Route::get('/restore/{id}', [FilepondController::class, 'restore'])->name('filepond.restore');
});
```

Frontend JS:

```js
FilePond.setOptions({
    chunkUploads: true,
    server: {
        url: '/filepond',
        process: '/process/{{ $video->id }}',
        revert: '/process/{{ $video->id }}',
        restore: '/restore/',
        headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}',
        }
    },
});

const inputElement = document.querySelector('.filepond');
const pond = FilePond.create(inputElement, {
    files: [
        {
            source: '9K3Z9t0DSEU4tfFI', // example chunk id
            options: {
                type: 'limbo',
            },
        },
    ],
});
```

Visiting the page with filepond integrated then displays:

![image](https://user-images.githubusercontent.com/5033092/121609463-d2a02280-ca4b-11eb-991e-316a04321d4b.png)

But I'd expect it to continue the upload which was interrupted.

Any suggestions would be greatly appreciated.

**Comment by rikschennink** [comment]
Which version of FilePond?

**Comment by trevsewell** [comment]
filepond version is 4.28.1

**Comment by AndreasElia** [comment]
Correct, what Trev said.

**Comment by rikschennink** [comment]
@AndreasElia Why close?

**Comment by AndreasElia** [comment]
@rikschennink It turns out "restore" doesn't work how I thought it did, so in turn, this isn't a bug as far as I'm aware?

From my understanding, restore only restores already uploaded files. I assumed when creating this that restore would restore a partially uploaded file in order for the user to continue the upload (e.g. if the upload got to 70% and the user refreshed, it would restore the file for the user to continue the final 30%).

Feel free to correct me if I'm wrong.

**Comment by rikschennink** [comment]
@AndreasElia you're correct. I believe it currently doesn't do that.
