### ISSUE TITLE
Hopper does not receive hopperState changes in IE

### ISSUE THREAD

**Issue by zolotyx** [pqina/filepond#724]
**Describe the bug**

The following code from src/js/app/utils/createHopper.js 

```
 const api = {
        updateHopperState: () => {
            if (lastState !== currentState) {
                scope.dataset.hopperState = currentState;
                lastState = currentState;
            }
        },
```

Uses  `scope.dataset.hopperState = currentState;`. It works everywhere except IE. The attribute changes, but the browser can not identify DOM changes, and any CSS that uses the `[data-hopper-state]` attribute will not work

**To Reproduce**

Add any CSS that will highlight the hopper when you drag the file over the filepond using `[data-hopper-state]` attribute.
It will not work in IE

**Expected behavior**

The solution could be just `scope.setAttribute('data-hopper-state', currentState);` instead

**Comment by rikschennink** [comment]
Which version of IE?

**Comment by rikschennink** [comment]
Closed because inactive.
