### ISSUE TITLE
Support restore HEAD metadata

### ISSUE THREAD

**Issue by PinkDuck** [pqina/filepond#727]
I'd like to be able to set method:"HEAD" on restore options to be able to restore limbo/server-temp files without downloading hundreds of megabytes of previously uploaded binary content before final form submission. Though if I try this though the source ID is shown instead of filename, despite response content-disposition header. If the standard "GET" method and response body then filename is displayed.

e.g. HEAD http://localhost:8080/API?restore=2

HTTP/1.1 200 OK
Content-Length: 123456
Content-Type: application/zip
Expires: -1
Content-Disposition: inline; filename="my-file.zip"
X-Content-Transfer-Id: 2
Date: Mon, 28 Jun 2021 11:46:50 GMT

Shows as "2" with 123 kB in an green upload complete row.

Additionally, providing a mock file interface within the create() set-up function files array still results in a server call to resolve by way of full download, defeating the point of the mock object.

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. 

**Please leave a comment after you've updated the issue.**

**Comment by PinkDuck** [comment]
Fine, see https://github.com/pqina/filepond/issues/731
