### ISSUE TITLE
Image preview not visible in demo

### ISSUE THREAD

**Issue by tacman** [pqina/filepond#729]
Even running in the sandbox from the plugin page link, the image preview is outside the viewport.

![image](https://user-images.githubusercontent.com/619585/123958303-e1a73000-d97a-11eb-8471-bf566a9f8270.png)

It seems like it should be going in where the gray box is.

Screenshot is from Chrome, happens on firefox too.

code is the demo code:

```javascript
mport { create, registerPlugin } from 'filepond';
import 'filepond/dist/filepond.css';

// Import the Image Preview plugin
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';

// Register the plugin with FilePond
registerPlugin(FilePondPluginImagePreview);

// Get a file input reference
const input = document.querySelector('input[type="file"]');

// Create a FilePond instance
create(input);
```

https://codesandbox.io/s/dwvt4

**Comment by rikschennink** [comment]
You need to load image preview css.
