### ISSUE TITLE
Broken allow-multiple in versions 1.8.2 and above

### ISSUE THREAD

**Issue by Crisis2010** [pqina/filepond#73]
Hello! Today I updated filepond to version 1.8.3 and encountered a problem. Allow-multiple parametr does not work any more
I teseted all versions from 1.8.0 to 1.8.5 (newest at this time) and problem starts from 1.8.2

I also use vue-filepond 2.1.3, maybe problem is there...

But, also i have problem with css styles, the back of the plugin panel is very narrow and does not change at all when adding files
![2018-06-28_14-48-39](https://user-images.githubusercontent.com/24792724/42032483-5d9ba3d0-7ae2-11e8-8e1c-8cd4d5ebaa9c.png)
![2018-06-28_14-49-42](https://user-images.githubusercontent.com/24792724/42032524-8259445c-7ae2-11e8-9691-879e8b08403a.png)

**Comment by rikschennink** [comment]
What was the previous version you were running?

**Comment by Crisis2010** [comment]
I started using your plugin about a couple of days ago, so version was 1.8.0 or 1.8.1, don't remember
And multiple files was ok, but problem with styles was from the beginning

**Comment by rikschennink** [comment]
Might be a collision with other styles, do you have a public test case?

I'm looking into the other problem, it seems the changes to option inheritance in version 1.8.2 somehow impact the Vue adapter.

**Comment by Crisis2010** [comment]
No, these is no collapse with other styles, looks like it cannot hook container with background, because there is no style="height: 81px" etc, like in demo

Probably

**Comment by rikschennink** [comment]
The `allowMultiple` problem is now fixed in version `1.8.5` of FilePond. I just published version `2.1.5` of the Vue adapter so installing that should resolve the problem.

Concerning the style issue. Do you experience the same problem in a clean HTML page without any other scripts or styles?

**Comment by rikschennink** [comment]
The only thing I can think of is that it overwrites a global variable or JavaScript feature that FilePond relies on. I can only test this if I can view the generated source, better yet, look at a public test case.

**Comment by rikschennink** [comment]
Will close the issue as the original problem has been resolved and we're now looking into interactions between Laracast and FilePond.
