### ISSUE TITLE
input attribute "name" is removed after adding files

### ISSUE THREAD

**Issue by kiennguyen1101** [pqina/filepond#742]
**Describe the bug**

The original attribute "name" of input is removed after adding files (drag&drop, click&browse)

**Logs**
Before adding files, the (demo) input is:
```<input class="filepond--browser" type="file" id="filepond--browser-bewmmd2uf" name="filepond" aria-controls="filepond--assistant-bewmmd2uf" aria-labelledby="filepond--drop-label-bewmmd2uf" multiple="">```html

After adding files, the (demo) input becomes this:
```<input class="filepond--browser" type="file" id="filepond--browser-6wphyduqr" aria-controls="filepond--assistant-6wphyduqr" aria-labelledby="filepond--drop-label-6wphyduqr" multiple="">```html

**To Reproduce**
- Go to demo: https://codepen.io/rikschennink/pen/WXavEx
- Drag&drop file or click and browse
- Check input "name" attribute is missing

**Expected behavior**

input attribute "name" should be as of configuration.

**Comment by rikschennink** [comment]
FilePond doesn't store the files in that input element, it's only there to "take-in" files. If the name would be set on that element there would be double form data entries in the POST.
