### ISSUE TITLE
Style example in the docs breaks the height

### ISSUE THREAD

**Issue by redfellow** [pqina/filepond#746]
When adding a width for the `.filepond--item`, the height of `.filepond--root` is mis-calculated.

```css
.filepond--item {
    width: calc(50% - 0.5em);
}
```` 

![image](https://user-images.githubusercontent.com/1110164/127463872-23ff67b7-48e3-414f-9d06-8b632c25c73f.png)

Init options:

```js
FilePond.registerPlugin(
  FilePondPluginImagePreview,
  FilePondPluginImageResize,
  FilePondPluginImageTransform,
  FilePondPluginImageExifOrientation,
  FilePondPluginMediaPreview
);

FilePond.create({
  dropOnElement: false,
  dropOnPage: true,
  allowMultiple: true,
  maxFiles: 250,
  imagePreviewHeight: 200,
  maxParallelUploads: 3,
  credits: "",
  name: "filepond-test",
});
```

I would expect the root container to contain all the rows, instead of being too low, thus making the content overlap with other elements on the page. 

Tested with Chrome and Firefox.

I suspect that without the previews, it would function correctly, so I hope there's a way to trigger re-calculation.

Edit: I did additional testing, and found that the culprit is a video file. Without video previews, the issue does not happen.

**Comment by redfellow** [comment]
Tested my theory, and indeed it's the previews/plugins causing the issue. 
![image](https://user-images.githubusercontent.com/1110164/127464797-2e3a679c-bb3f-441b-aa21-c665eabde6d1.png)

**Comment by rikschennink** [comment]
See comment below the styles https://pqina.nl/filepond/docs/api/style/

Make sure that each item is the same height. FilePond currently calculates the height of the first item in the list and then uses that as the base height for each item. You can set the item height using `styleItemPanelAspectRatio`, `imageCropAspectRatio`, or by setting a fixed `imagePreviewHeight`.

In this case you need to set `styleItemPanelAspectRatio`

**Comment by redfellow** [comment]
Thanks, I only tested one of those documented variables (imagePreviewHeight). Will test the others now.

**Comment by redfellow** [comment]
I originally tested with `styleItemPanelAspectRatio: "16:9"` which did not work. 

![image](https://user-images.githubusercontent.com/1110164/127629699-d0e2d4b6-ff56-435c-8bc7-2306dd295b64.png)

..but setting `styleItemPanelAspectRatio: "0.5625"` does work. Docs said I could use the human readable format, but it appears there's a bug with it perhaps.

![image](https://user-images.githubusercontent.com/1110164/127629797-efec4187-7b7f-496d-acc4-ef003580b86f.png)

This issue is now resolved.

**Comment by redfellow** [comment]
For anyone ending up here, I was able to make the setting dynamic by using the events.

```js
	const MEDIA = new RegExp(/^(gif|png|jpg|jpeg|mp4)$/i);
	component.pond.oninitfile = function(file) {
		if (MEDIA.test(file.fileExtension) === true) {
			component.pond.setOptions({"styleItemPanelAspectRatio" : "0.5625"});
		}
	};
