### ISSUE TITLE
Mocking files without making any server requests

### ISSUE THREAD

**Issue by davidli3100** [pqina/filepond#747]
I've read through quite a few issues and the docs, so hopefully someone can clarify this further.

My goal is to be able to mock/show previously uploaded files in the filepond instance without actually having a server defined in the Filepond instance as the files are hosted on Airtable. This is currently causing issues when the files are formatted like so:

```
{
  source: upload.url,
    options: {
      type: 'local',
      file: {
        name: upload.filename,
        size: upload.size,
        type: upload.type,
        airtableUrl: upload.url,
      },
    },
}
```

Is there any way around this other than just giving filepond the file URLs. That does seem to work but it could potentially load hundreds of megabytes of data on page load.

**Comment by rikschennink** [comment]
Just tested but it works perfectly fine here:
https://codesandbox.io/s/filepond-mock-file-4dost?file=/src/index.js

Will close for now as issue doesn't adhere to issue template (see template when you click on new issue).
