### ISSUE TITLE
Aborted and retried upload: progess cannot be set to 100%

### ISSUE THREAD

**Issue by redfellow** [pqina/filepond#748]
I've overridden the server variable like so:

```js
server: {
	process: component.processFile
}
```
I'm storing the processfile functions variables to an object during processfile, so that in my custom uploaders XHR onprogress callback I can update the progress.

```js
component.processFile = function(fieldName, file, metadata, load, error, progress, abort, transfer, options) {
....
	component.fileMethods[metadata.fileID] = {
		progress: progress,
		load: load,
		abort: abort,
		error: error,
		transfer: transfer,
		options: options,
	};
};
```
```js
xhr.upload.onprogress = function (e) {
	if (defined(parameters.fileMethods)) {
		var percentage = Math.ceil(e.loaded / e.total * 100);
		parameters.fileMethods.progress(100, percentage, 100);
	}
};

xhr.onload = function (e) {
	if (xhr.status === 404) console.error("stato.service XHR 404: not found", e);
	else {
		if (defined(parameters.fileMethods)) {
			parameters.fileMethods.progress(100, 100, 100);
			parameters.fileMethods.load();
		}
		
		resolve(JSON.parse(xhr.responseText).service.response);
	}
};
```

It's been workin pretty well. I've now started testing by throwing custom errors during the XHR upload (or before that), which then calls the `error` method, and then I `process` the file again to get it to loading state, but after I've done that, the progress percentage gets broken. Even if I manually call `...progress(100,100,100)`, The percentage will never go to 100%, it gets stuck to a random value, like 87%, 99% etc, and calling `load()` does nothing.

I'm thinking that to work around this, I'll just use `abort` and re-add the file, but it would be better if I could just "retry" so to speak.

It would be a bit difficult to make an external test case for this, but I can try.

Edit: If I don't retry by pressing `filepond--action-retry-item-processing` button, I'm able to keep manipulating the item with the events as expected. So maybe I'll just overwrite the event in that button.

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. 

**Please leave a comment after you've updated the issue.**


Note that the progress function doesn't take three numeric arguments. It should be `true`, `loaded`, `total` → `progress( true, 50, 100)` for 50% complete.
