### ISSUE TITLE
When imageEditInstantEdit is true, Filepond hangs at waiting for size

### ISSUE THREAD

**Issue by jphilung** [pqina/filepond#752]
**Description of the bug**
On the latest CDN version of Filepond and the plugins (Image Preview, Image Edit), when imageEditInstantEdit is true and after uploading an image, Filepond opens the editor correctly, but hangs at "Loading" and shows "Waiting for size" even though the confirm and cancel callbacks are called.

When the property is set to false, everything functions properly.

**To Reproduce**

https://codesandbox.io/s/vanilla-filepond-forked-2kx9t?file=/src/index.js:1106-1126

**Expected behavior**

When the editor is confirmed or cancelled, the file preview should function and the following upload should ensue.

**Comment by rikschennink** [comment]
Confirmed the issue, looking into it.

**Comment by rikschennink** [comment]
The sandbox is not running the latest versions. But, you should also run onclose when the editor is closed, see: 
https://codesandbox.io/s/vanilla-filepond-forked-pkocx?file=/src/index.js

**Comment by jphilung** [comment]
Ok that works, but if I try to edit again the photo, an error is thrown:
this.onclose is not a function

This is caused by the following lines which are called on onconfirm

```
          if (!handleEditorResponse) return;
          editor.onclose = function() {
            handleEditorResponse(false);
            editor.onclose = null;
          };
```

**Comment by rikschennink** [comment]
That's because I believe normally the editor instance is renewed each time an editor is created.

**Comment by damienmutt** [comment]
This issue still happens, I'm using _Filepond_ with _Cropperjs_ and _Filepond_ hangs whatever I do (_onconfirm, oncancel, onclose_...). It's really frustrating as everything works setting `imageEditInstantEdit: false`.
