### ISSUE TITLE
Processing of upload is delayed starting by approx 1.6s

### ISSUE THREAD

**Issue by leeovery** [pqina/filepond#753]
Hi,

**EDIT:** I _think_ I'm having an issue with the perceived progress. However as I was writing this it occurred to me it may not be to do with the fake process but some other cause. The underlying issue here is the delay before the processing of the upload begins.

The upload of the file doesn't start until AFTER the perceived progress has finished. I like the idea of the perceived progress but Im guessing it was meant to run concurrently with the real upload, not sequentially causing a delay before the real upload even starts its work?

So to try to work around this issue, I dived into the source a bit and found the prop `allowMinimumUploadDuration`. I set this to false, but the perceived progress delay is still occurring.

**To Reproduce**

Open up the console in the following sandbox and drop a file into the dropzone. You'll notice it takes approx 1second before the console shows the text triggered from the `server.process` option. I would expect this to trigger instantly, while the fake process is running.

https://codesandbox.io/s/vanilla-filepond-forked-16lsf?file=/src/index.js

**Expected behavior**

I would personally expect that the perceived fake progress begins at the moment the upload starts, and then the upload progress runs for whichever takes longest; the real upload or the fake.

Additionally, I expected the prop `allowMinimumUploadDuration` to completely disable the fake progress.

**Information about your project:**

- Tested in chrome and the sandbox above
- MacOS Big Sur
- Tested with vue-file-pond 6.0.3. Also tested in sandbox with vanilla latest filepond without plugins with same result

Thank you
Lee

**Comment by rikschennink** [comment]
The upload is slightly delayed because FilePond waits for the file animation to finish, uploading during the animation will cause the animation to stutter, therefor it waits for the "spring animation" to settle before start. I suspect this is what you're seeing?

**Comment by leeovery** [comment]
I wondered that too but ~1.6s seems on the long side for the animation to end.

Looks like the animation has finished well before the upload begins. If you watch the console log on the codesandbox, you can see the animation has ended quite a while before the processing begins.

I also tested starting the file processing manually, and that triggered the exact same delay, even though the file was comfortably sitting in the pond for a while before I processed.

**Comment by rikschennink** [comment]
I'll take a look as soon as possible probably gonna be end of month

**Comment by leeovery** [comment]
Cool beans, thanks mate 👍🏼

**Comment by rikschennink** [comment]
Yeah this is because it's waiting for the spring animations to rest, if it doesn't animations will stutter. If you drop more files at once it'll wait till all files are at rest.

Only way around this would be preventing animations which unfortunately is currently not possible.

**Comment by leeovery** [comment]
Ok thank you for looking.

I wouldn't want to disable the animations. You've done a beautiful job of building it. I can feel the love and attention to detail that went into those animations, and the code itself :)

Having said that, 1.6s is on the long side though so anything we can do to shorten that would be awesome.

Ill close for now though.

Thanks again!
Lee

**Comment by vesper8** [comment]
Any progress on this? Can we not speed up animations at least?
