### ISSUE TITLE
3D file types validation issues

### ISSUE THREAD

**Issue by gengns** [pqina/filepond#754]
I'm having trouble validating 3D file types using the [File Type Validation plugin](https://pqina.nl/filepond/docs/api/plugins/file-validate-type/).
If I try to upload a [GLB](https://docs.fileformat.com/3d/glb/) file format ([model/gltf-binary](https://www.iana.org/assignments/media-types/media-types.xhtml#model) as MIME type) 

```svelte
<FilePond bind:this={pond} acceptedFileTypes=['model/gltf-binary']/>
```
I get the following error:
![issue](https://user-images.githubusercontent.com/13253926/129940389-fe8ce1ab-9560-4a41-9ca7-402c04b7e3c5.png)
 

**According to the docs `acceptedFileTypes` property accepts mime types** but it looks like these 3D types ([basic for three.js](https://threejs.org/docs/#manual/en/introduction/Loading-3D-models)) are not supported, at least after using the [codepen](https://codepen.io/rikschennink/pen/NzRvbj) of the [Github repo ](https://github.com/pqina/filepond-plugin-file-validate-type)to detect the mime type.

**Comment by rikschennink** [comment]
It means the browser doesn't support it / doesn't recognise the file mime type.

You can manually detect the type using this function: https://pqina.nl/filepond/docs/api/plugins/file-validate-type/#custom-type-detection

**Comment by gengns** [comment]
Thank you Rik, I can resolve the Promise directly for supported types like images, videos and audios, and then manually detection for some 3D model types. Awesome plugin.
