### ISSUE TITLE
Cannot select multiple images when using Samsung Web Browser + Photo App on android

### ISSUE THREAD

**Issue by jakejackson1** [pqina/filepond#759]
**Describe the bug**

If you use the [Samsung Internet Browser](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en_AU&gl=US) with a FilePond that allows multi-file uploads, all files but the first that are selected get ignored when selecting images [through the Photo app](https://play.google.com/store/apps/details?id=com.google.android.apps.photos&hl=en_AU&gl=US). 

**Logs**

Nothing present in the console.

**To Reproduce**

Replicatable with https://codesandbox.io/s/vanilla-filepond-2oltb

1. Using the Samsung Web Browser select the "Browse" button on FilePond
2. Choose the "Files" action
3. Under the "Browse Files in other apps" section select "Photos"
4. Choose a folder, select multiple images in that folder and press "Done"

**Expected behavior**

All selected images should show up in FilePond and not just the first image.

**Information about your project:**

- On Android 11 tested on Google Pixel 5 and Samsung Galaxy S20 Ultra phones
- FilePond version: 4.29

**Additional context**

Notes: multi-select works if you choose photos from the Recent Files list when you first choose the "Files" action.

**Comment by rikschennink** [comment]
Does it work with a basic file input element? `<input type="file" multiple/>`

**Comment by jakejackson1** [comment]
@rikschennink just tested this out and only 1 file is selected when using a basic file input element, so this is a problem in the browser itself and not a filepond issue. Thanks for the help debugging!
