### ISSUE TITLE
Add base64 file error

### ISSUE THREAD

**Issue by keha94** [pqina/filepond#76]
Using the addFile method on the filepond instance to add a base64 image is returning an error.
`getDateString is not defined`

Looked into the filepond.js code - and found `var getDateString$1 = function getDateString()`

But at line 3473 `data[0] = source.name || getDateString();` - the reference here does not have the '$1' in the function name - which I believe is causing the undefined error.

I am using latest 1.8.5 version of filepond.

**Comment by rikschennink** [comment]
Thanks for the detailed error report, will look into this later today!

**Comment by keha94** [comment]
Thanks for the prompt fix, however I'm actually using vue-filepond which is currently dependent on `1.8.5`.

Any chance you can update the filepond dependency to latest on that?

**Comment by rikschennink** [comment]
Done!
