### ISSUE TITLE
FilePond: if allowBrowse is true then a file open dialog is always displayed when the onactivatefile event is fired

### ISSUE THREAD

**Issue by vilhjalmur** [pqina/filepond#764]
I am using the onactivatefile event to open a file when the user clicks it. But I cannot prevent the file open dialog from being displayed also, without setting allowBrowse to false.

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. 

**Please leave a comment after you've updated the issue.**
