### ISSUE TITLE
Problem with positioning files grid

### ISSUE THREAD

**Issue by morawcik** [pqina/filepond#765]
When I load page grid starts positioning but it stops in middle and all grids (mostly those in center which are still not positioning) shakes. Sometimes after a while (1-2s) its end with proper positioning but sometimes its just "shakes" without ending.
I tested it on almost every modern browser (updated) at MacOS Big Sur.

![Screenshot](https://user-images.githubusercontent.com/4557530/135832850-f89f54fa-8e60-477a-b365-b8a3dfdd023f.png)

https://user-images.githubusercontent.com/4557530/135834255-320b8bfd-8ffd-4845-b3a2-5adeacd060b9.mp4

**Comment by rikschennink** [comment]
Appreciate the video, but please fill in the issue template (see text area contents when clicking NEW ISSUE) and supply a public test case.

---

We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. 

**Please leave a comment after you've updated the issue.**
