### ISSUE TITLE
incompatible with Spring Framwork's RequestParam

### ISSUE THREAD

**Issue by ZandreeTresvalles** [pqina/filepond#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Description
Also having this issue. I'm using spring boot's @RequestParam Multipartfile to get the file, this needs the name attribute,
specifically in the form-data.
what is the name attribute in POST-form?
### Postman
the name attribute is image in RequestParam
![image](https://user-images.githubusercontent.com/20995639/137793035-7f52aaee-cef9-43dc-957f-b9553d9edd1f.png)

### in HTML
```
<input name="image" form="upload" type="file" accept="image/png, image/jpeg" required/>
```
### Error Message
![image](https://user-images.githubusercontent.com/20995639/137788100-1971e831-357c-4fd8-9bed-5c89eccd073c.png)

### Reproduction

It is related to this issue.
[Issue](https://github.com/pqina/filepond/issues/742#issue-950623981)

### Environment

```markdown
- Broser:Chrome
```

**Comment by rikschennink** [comment]
Maybe change `name` to `filepond`?

This does look like a configuration issue, and not a FilePond bug, so will close for now.
