### ISSUE TITLE
 button Close does not close modal of DOKA Image editor

### ISSUE THREAD

**Issue by vovizottoni** [pqina/filepond#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

When I upload an image using Filepond + DOKA , and this image has a size smaller than the minimum size, a modal with the following error message is displayed: "Minimum image size is 556 x 436" and a close button.

When I click on the close button, the message described above is replaced by the message "Waiting for image" and the modal is not closed.

how do i make the close button work?

versions: Filepond (4.27.1) , Doka Image Editor (7.14.0)

### Reproduction

Upload an image with a size smaller than the minimum resolution allowed (  imageCropMinSize / resizeMinSize  ) and then click the close button

### Environment

```markdown
- Browser: Google Chrome Versão 94.0.4606.81 (Versão oficial)
- Windows 10
```

**Comment by rikschennink** [comment]
Hi, Please update to the latest version of the editor, if you have an active subscription you can submit this as a support ticket on the PQINA customer portal.

Note that you did _not_ update FilePond to the latest version which is 4.30.3
