### ISSUE TITLE
Using filepond with web sockets

### ISSUE THREAD

**Issue by papamauro** [pqina/filepond#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Is it possible to use Web Sockets with filepond? Is there any working example code to use?

### Describe the solution you'd like

I'd like the possibility to switch beetween Fetch and [Web Socket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API?retiredLocale=it)

### Describe alternatives you've considered

Using the Web Socket API without filepond

**Comment by rikschennink** [comment]
You can customise every end point FilePond uses to load and upload files so you're free to use whatever web tech you like, see:
https://pqina.nl/filepond/docs/api/server/#advanced
