### ISSUE TITLE
[Feature] Redirect to a url after upload has completed

### ISSUE THREAD

**Issue by h4k1m0u** [pqina/filepond#780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Apologies in advance if this feature already exists (I didn't find anything that matches it though in the docs or among the issues).

When I try to redirect inside my nodejs/express server's route after the upload has been done using `res.redirect()`, the redirect doesn't work and the page is rendered inside the response of the xhr request.

### Describe the solution you'd like

Add an option in `FilePond.create()` to allow to redirect after the upload finishes.

### Describe alternatives you've considered

I know I can listen for "on-upload-done" event using `FilePond:processfile` event, but that won't allow me to pass some of the data I had produced in my route to the view.

**Comment by rikschennink** [comment]
This is something you have to solve outside of FilePond. FilePond's request is asynchronous so you're redirecting the XHR request, that doesn't work. I advise to return the file id and use the processfile event for the redirect.
