### ISSUE TITLE
[Bug] Unexpected ")" in CSS

### ISSUE THREAD

**Issue by jere-co** [pqina/filepond#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I'm migrating a project to `ESBuild` and since got the following error: 

```
[WARNING] Unexpected ")"
node_modules/pintura/pintura.css:7:7749:
7 │ ...}.PinturaRoot>.PinturaNav:empty(){display:none!important}.Pintur...
```

The relevant CSS is: 
```
.PinturaRoot>.PinturaNav:empty(){display:none!important}
```

The `:empty()` is probably not valid CSS, so maybe ditch the `()`

### Reproduction

Try including Pintura with `ESBuild`. 

### Environment

```markdown
- Device: iMac
- OS: macOS Monterey 12.0.1
- Browser: Latest Google Chrome
```

**Comment by rikschennink** [comment]
Hi, just pushed Pintura 8.16.8 which removes this invalid selector. I'll close the issue because this isn't related to FilePond.
