### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ishanjainsf** [pqina/filepond#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Fetching the images are working fine from the s3 bucket, but I ain't able to preview the images

### Reproduction

<FilePond
style = {{marginTop:'10px'}}
files={files}
allowMultiple={true}
allowReorder={true}
onupdatefiles={setFiles}
imagePreviewHeight = "125px"
server={{
           load: (source, load, error, progress, abort, headers) => {
           var myRequest = new Request(source);
           fetch(myRequest).then(function(response) {
           response.blob().then(function(myBlob) {
           load(myBlob);
           });
         });
        },
     process: null
  }}
labelIdle='Drag & Drop your files or <span class="filepond--label-action">Browse</span>'
/>`
`

### Environment

```markdown
- Device: HP Probook
- OS:
- Browser: Google
```

**Comment by rikschennink** [comment]
Hi, you have to properly configure CORS, see this article:
https://pqina.nl/pintura/docs/v8/faq/resolve-cors-errors/

**Comment by ishanjainsf** [comment]
![Screenshot from 2021-12-14 12-46-39](https://user-images.githubusercontent.com/88362775/145950948-7ec383e2-184f-438f-af2c-4db944515fc7.png)


This is what i am getting. I am not sure if its a CORS error.

**Comment by rikschennink** [comment]
You can check the developer console to see if a CORS error is thrown. Additionally I'd advise to to check the content-type of the response. It's suspicious that every file is 2KB.

**Comment by ishanjainsf** [comment]
`server={{
        load: (source, load, error, progress, abort, headers) => {
        headers('*');
        var myRequest = new Request(source);
        console.log("request : ", myRequest)
        fetch(myRequest).then(function(response) {
            response.blob().then(function(myBlob) {
                load(myBlob);
            });
          });
        },
        process: null
      }}
`


I removed this server config. 
After this I am able to see preview of just  images, but still not getting the rest. 

![Screenshot from 2021-12-14 13-23-43](https://user-images.githubusercontent.com/88362775/145956052-f1df559f-95cc-4847-8f03-f01d2f3b9c4b.png)
