### ISSUE TITLE
Typescript index.d.ts file missing fields [Bug] 

### ISSUE THREAD

**Issue by jestervine** [pqina/filepond#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I am working on an Angular project that will use FilePond. The issue that I am having is coming from the filepond source code, not ngx-filepond. 

The issue is that certain I want to use are not defined in index.d.ts so I have to resort to declaring a property as any instead of using a typesafe declaration.

Example:
![image](https://user-images.githubusercontent.com/69054904/146413554-fc1b8921-7cd9-4a90-81c0-b2d0cfdaea9c.png)

In the source code it is missing the transfer and option parameters:
![image](https://user-images.githubusercontent.com/69054904/146413733-8e43b0f4-8db9-4dfb-8640-471ccaa58df7.png)

This is confusing since the documentation has these two parameters used for chunking.
![image](https://user-images.githubusercontent.com/69054904/146414062-e101c5b2-3075-47b3-8859-72b7f42abe53.png)

Also in the documentation it talks about using patch. There is not a function for the Patch type in index.d.ts but I can use it (without compile error) if I declare my server object as type any. 

### Reproduction

This is a simple example. This would just demonstrate that it breaks unless you declare your variable as type any.

1. Create a new Angular project (or I imagine any project that uses typescript).
2. Install filepond, and ngx-filepond. 
3. Make sure you setup your Module correctly with the necessary imports.
4. In your app component import FilePondServerConfigProps from filepond.
5. Write something like this:

//This will throw an error because transfer and options is not defined in in ProcessServerConfigFunction. Remove them and it works. Change FilePondServerConfigProps to any and it works. 

 var pondServerExample: FilePondServerConfigProps = {
        server: {
          url: '/api/Example/',
          process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
            //do some stuff
          }
        }
      }

### Environment

```markdown
- Device: Laptop.
- OS: Windows 10.
- Browser: Doesn't matter. Fails compile unless you work around it.
```

**Comment by rikschennink** [comment]
Hi, thanks for reporting, happy to accept a PR on the types.
