### ISSUE TITLE
upload not storing id; can't delete w/ id

### ISSUE THREAD

**Issue by sandro-pasquali** [pqina/filepond#79]
### Summary
`<hidden>` field not being populated with uniqid returned from server on upload

### How to reproduce
See implementation below

### Expected behaviour
after upload `<hidden>` field has value="uniqid"

### Additional information
Express server, using multer.

| Environment  | Version
|------------- | -----------
| OS           | MacOS High Sierra
| Browser      | Chrome latest

Hi, using the following config:

```js
            server: {
                url: './main',
                process: {
                    url: '/upload',
                    method: 'POST',
                    withCredentials: false,
                    headers: headers: {Authorization:...}
                },
                revert: {
                    url: `/media`,
                    method: 'DELETE',
                    withCredentials: false,
                    headers: {Authorization:...}
                }
            }
```

Upload works great, returning a sha1 hash as text/plain on upload. The `<hidden>` field is not being updated with this hash. 

Is there maybe an example (node.js) that shows upload and revoke behaviors?

**Comment by rikschennink** [comment]
Hi, I just tested on my local environment to be sure but it seems to store the server response just fine. If the above is how you've configured the server it should function correctly. Can you see the server response and the returned unique id in your chrome dev tools network tab?

**Comment by balabis** [comment]
Hello, sorry for bringing up this old question.
I am facing this exact issue. The config is almost exactly the same, just without `withCredentials`.
For testing this out I am returning a simple text/plain string from the server and nothing else. 
I can see the response in the chrome dev tools network tab. `Preview` shows only the string and in the `Headers` sections I can see `Content-Type: text/plain;charset=UTF-8`.
Have been trying to figure out what exactly is a problem here for a while now but without any luck.

**Comment by rikschennink** [comment]
If you have a public test case I'm happy to take a look (away for a couple of days so won't be this week).

**Comment by balabis** [comment]
I do not, but this is the code I'm with at the moment:

```
<FilePond ref={pond}
    name={"file"}
    imagePreviewMaxHeight={400}
    allowMultiple={10}
    onprocessfile={(er, file) => {console.log("done", file)}}
    server={
        {
             url: "http://localhost:8080",
             process: {
                 url: "/process",
                 method: "POST",
                 onload: onResponse,
                 headers: {Authorization: "..."}
             },
             revert: "/revert"
       }
    }
>
</FilePond>
```
Response Header:
```
Access-Control-Allow-Origin: *
Content-Length: 21
Content-Type: text/plain;charset=UTF-8
Date: Mon, 04 Mar 2019 16:14:57 GMT
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
```

And this is just a simple string returned from the server:
```
13gfhj32uygr34343r4g5
```

**Comment by rikschennink** [comment]
Does `onResponse` return the file server id to FilePond?

**Comment by balabis** [comment]
Oh god.. :))
My `onResponse` method just logged the response to console and did not return anything. Now I made it return the response and the hidden value is exactly the string `onResponse` returned.
Thank you for the right question :)
