### ISSUE TITLE
Issue on Android Device When Choosing File from Google Drive [Bug] 

### ISSUE THREAD

**Issue by nicolaspilot** [pqina/filepond#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Hi,
I'm testing filepond from an Android 11 Device - Chrome 96.
For some reason the profile picture demo (https://pqina.nl/filepond/#profile-picture-demo) does not work when browsing file from Google Drive. (Browse \ Open from \ Drive \ ...)

But the first demo (upload anything from anywhere) works fine when choosing the same file from Google Drive
So I suspect that is issue comes from the Preview Plugin or the Resize Plugin. (FilePondPluginImagePreview / FilePondPluginImageResize)

Unfortunately, I can't get the exact error message from my phone.

### Reproduction

- Open chrome 96 on an android device
- Go To https://pqina.nl/filepond/#profile-picture-demo
- Click on Browse
- Click on Browse again
- Open from : choose Drive (your google account)
- Choose My Drive
- Pick an image 

### Environment

```markdown
- Device: OnePlus Nord N10 5G
- OS: Android 11
- Browser: Chrome 96
```

**Comment by rikschennink** [comment]
I suspect this is related to CORS settings. The second demo wants to read source image data, which might be blocked by CORS settings of google drive.

Will close because this is related to server configuration.
