### ISSUE TITLE
[Bug] Not able to validate a file by checking mime-type and extension 

### ISSUE THREAD

**Issue by harunoz** [pqina/filepond#793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Hello in my code I defined the accepted mime types and accepted extensions. After, I created an example malicious file called  example.js and renamed as example.js.pdf. The code check the extension and mime type and declined the my example file. However, I was able to upload my file.

### Reproduction

  const pond = FilePond.create( inputElement,
  {

      // set allowed file types with mime types
      acceptedFileTypes: [
        'application/pdf',
        'application/doc',
        'application/x-iwork-pages-sffpages'
    ],

    fileValidateTypeLabelExpectedTypesMap: {
        'application/pdf': '.pdf',
        'application/doc': '.doc',
        'application/x-iwork-pages-sffpages': '.pages'
    }

 } );

### Environment

```markdown
- Device: Macbook Pro M1
- OS: macOS Monterey
- Browser: Chrome
```

**Comment by rikschennink** [comment]
The validation is a browser technology, the mimeType used is the type detected by the browser. You can override this with the `fileValidateTypeDetectType` hook.
https://pqina.nl/filepond/docs/api/plugins/file-validate-type/#custom-type-detection

Note that even when doing a deep file inspection in that hook it's not secure as the scripts run on the client it's easy for malicious actors to adjust how your scripts validate files. 

**Always validate files on the server**
