### ISSUE TITLE
Simple extension filter example (for File type validation plugin)

### ISSUE THREAD

**Issue by burak1000** [pqina/filepond#796]
Firstly Thank you so much for this great library.
There is no bug
Only i need to explain how to simply validate files just with extension. because i spent couple of hours for this.
I readed a hundred times the documents and other issues but it's not written anywhere how we return with promise ?

what is the promise man?  we are the copy-and-paste programmers :)  

we will return via  " resolve('.'+source.name.split('.').pop());  "  complete example following

```html
<head> 
<script src="/plugins/filepond/filepond-plugin-file-validate-type.js"></script> //this plugin must be added

</head> 



<script>
FilePond.registerPlugin(FilePondPluginFileValidateType); //!! this line must be here

var muploader = FilePond.create(document.querySelector('.input'), {
    acceptedFileTypes: ['.stl'],
    fileValidateTypeDetectType: (source, type) =>
        new Promise((resolve, reject) => {
           resolve('.'+source.name.split('.').pop());  //!!!WRITE HERE it's will just check your extension!!!
        }),
});
</script>
```

There is no bug it's just a simple example

**Comment by rikschennink** [comment]
`acceptedFileTypes` should be an array of mime types not extensions, so `image/jpeg` instead of `.jpg`

Now your `fileValidateTypeDetectType` should resolve with a mime type.

```js
(source, type) => new Promise(resolve) => {
  // type is the mime type the browser has detected
  // source is the source file

  // if source is a jpeg image file, resolve with JPEG mime type
  resolve('image/jpeg')
}
```
