### ISSUE TITLE
[Bug] Warning Message not displayed when selecting more than maxFiles 

### ISSUE THREAD

**Issue by nicolas-cusan** [pqina/filepond#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

When selecting more images than allowed in `maxFiles` the system dialog is closed and no warning message (or any other feedback) is displayed. When trying the plugin on the [project page](https://pqina.nl/filepond/#multi-file-demo) the message is displayed as expected.

### Reproduction

1. Go to this link https://codepen.io/cus/pen/NWaEewX
2. Use the upload field and select more than three files
3. No warning is displayed

### Environment

```markdown
- Device: Macbook Pro (2019)
- OS: macOS
- Browser: Brave, Firefox
```

**Comment by rikschennink** [comment]
https://github.com/pqina/filepond/issues/137

**Comment by nicolas-cusan** [comment]
Sorry for misfiling. So in the demo here:  https://pqina.nl/filepond/#multi-file-demo  you are using a callback as suggested in #137. Jus curious. Thank you for the great library!

**Comment by rikschennink** [comment]
@nicolas-cusan exactly, it's this piece of code

```js
var pondDemoMultiple = ponds[1];
var pondMultipleTimeout;
pondDemoMultiple.onwarning = function() {
    var container = pondDemoMultiple.element.parentNode;
    var error = container.querySelector('p.filepond--warning');
    if (!error) {
        error = document.createElement('p');
        error.className = 'filepond--warning';
        error.textContent = 'The maximum number of files is 3';
        container.appendChild(error);
    }
    requestAnimationFrame(function() {
        error.dataset.state = 'visible';
    });
    clearTimeout(pondMultipleTimeout);
    pondMultipleTimeout = setTimeout(function() {
        error.dataset.state = 'hidden';
    }, 5000);
};
pondDemoMultiple.onaddfile = function() {
    clearTimeout(pondMultipleTimeout);
    var container = pondDemoMultiple.element.parentNode;
    var error = container.querySelector('p.filepond--warning');
    if (error) {
        error.dataset.state = 'hidden';
    }
};


```

**Comment by nicolas-cusan** [comment]
Perfect, thank you for getting back to me!
