### ISSUE TITLE
[Bug] Random onremovefile calls

### ISSUE THREAD

**Issue by thebrucecgit** [pqina/filepond#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

When I try to upload a file, the callback `onremovefile` is called when it shouldn't be. I am using `react-fiilepond` and I'm trying to make filepond a controlled input. 

### Reproduction

https://codesandbox.io/s/filepond-debug-jfhkh?file=/src/App.js

Upload any file

Then you'll see in the console that `onprocessfile` callback is called (as it should be) but also `onremovefile` is called (even though it shouldn't be)

### Environment

```markdown
- Device: Custom PC
- OS: Linux Ubuntu 20.04.3 
- Browser: Chromium 97
```

**Comment by rikschennink** [comment]
I don't know if this is possible, it's definitely not designed to be possible. 

What I do know is that the file will be in "limbo" state when processed, and you're forcing it to "local" state when setting files. So that I think triggers the removal of the file.

**Comment by thebrucecgit** [comment]
Right that clears things up. I know how to get it to work in the way I need it to now. Thanks
