### ISSUE TITLE
Jquery event handler not run.

### ISSUE THREAD

**Issue by aminkt** [pqina/filepond#8]
I'm trying use more than one filepond in page.
I registered one process event and want know wich one are already changed but all filepond triggered.

**Comment by aminkt** [comment]
I tried jquery interface to select one element and register for that just but not working.

**Comment by rikschennink** [comment]
Hi! Please post a code snippet, it's very difficult to debug without knowing how it's setup.

**Comment by rikschennink** [comment]
Will close for now.

**Comment by lytvynenko** [comment]
Having same issue with react wrapper. The "onprocessfile" event hasn't been fired after successful upload to the server. See example here: https://codesandbox.io/s/x2zw6jzj24.

**Comment by rikschennink** [comment]
The `onprocessfile` event was not defined on the global options object. If you download the latest version of FilePond it should now work correctly.
