### ISSUE TITLE
Multiple upload with encoding only posts one file

### ISSUE THREAD

**Issue by KevinCocquyt39** [pqina/filepond#80]
### Summary

It seems only 1 file is uploaded after using the encode-plugin, whilst I selected 2 files.

### How to reproduce

```html
<input type="file" class="filepond" name="filepond" multiple>

<script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"></script>
<script src="https://unpkg.com/filepond/dist/filepond.js"></script>
<script>
    FilePond.registerPlugin(
        // encodes files as base64 (needed for regular form post)
        FilePondPluginFileEncode
    );

    const inputElement = document.querySelector('.filepond');
    const pond = FilePond.create(inputElement, {
        allowMultiple: true,
        allowFileEncode: true,
        name: "filePond"
    });
</script>
```

### Expected behaviour

The JSON string that was posted only contains an object with 1 file in there. I would expect a JSON array notation with 2 files.

### Additional information

Processing the JSON string is done using .NET MVC. I receive the posted data as a string and use the Newtonsoft.Json library to deserialize the string into a POCO class.

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Browser      | Chrome 67

**Comment by rikschennink** [comment]
Does setting the name to `"filepond[]"` fix this?

**Comment by KevinCocquyt39** [comment]
Hi. Thanks for the quick reply. I tried that, using a closed issue as inspiration, but I've got the same result unfortunately. The input element looks like this...

```
<input type="file" class="filepond" name="filepond[]" multiple>
```

But after the post, it only shows 1 file and the hidden field contains the following after the upload of the 2 files (also, logically, containing the 1 json object).

```
<input type="hidden" name="filepond[]" value="{&quot;id&quot;:&quot;a0ol7j4ls&quot;,&quot;name&quot;:&quot;FILENAME&quot;,&quot;type&quot;:&quot;text/html&quot;,&quot;size&quot;:1791,&quot;metadata&quot;:{},&quot;data&quot;:&quot;BASE64NOTATION&quot;}">
```

**Comment by rikschennink** [comment]
Alright thanks, will look into this further tomorrow morning

**Comment by rikschennink** [comment]
I've just run a quick test, it seems to work on my local development environment where I test against a scotch box PHP server.

FilePond creates two hidden inputs, one for each file, each with the name of the original input element `"filepond[]"`, values are set correctly, see below with two small text files.

![screen shot 2018-07-13 at 08 49 06](https://user-images.githubusercontent.com/1132575/42676876-14ee6052-867a-11e8-8389-c88ba3ec3fc3.png)

Then when pressing the submit button and inspecting the post request I can see both fields being sent:

![screen shot 2018-07-13 at 08 50 12](https://user-images.githubusercontent.com/1132575/42676896-2cae4cd4-867a-11e8-8156-1c2e6139137f.png)

PHP is able to pick this up and successfully receives the files.

Could this be a problem with .Net not being able to handle fields with same name? I did a quick google search but it seems to be able to handle it when using the right methods:
https://stackoverflow.com/questions/437955/submitting-form-elements-with-the-same-name

**Comment by KevinCocquyt39** [comment]
You're completely correct. I must have missed the second hidden field (thinking it would have been a JSON array instead of 2 separate objects). Passing those to .NET is easy as the receiving model contains a List<string> property, meaning both objects will be passed to the server where I can use the JSON library to deserialize the objects into a dto and continue from there.

Sorry for wasting your time and thanks again for the extra information, providing this library and I'll be using it for my future projects.

**Comment by rikschennink** [comment]
No problem @KevinCocquyt39, glad to hear it's working and good to know that this setup is easy to link to .Net as well.

**Comment by joshmanhuwa** [comment]
Sorry guys but i am also experiencing the same issue as the other gentleman, i am not getting an encoded string, i am in laravel

**Comment by doubleprincez** [comment]
I'm having the same issues too and it works on my local host. I was able to upload three images but the live server only stores one image

**Comment by moizmasood10** [comment]
Any update on this?
