### ISSUE TITLE
[Bug] Drag and Drop Folders on React File Pond

### ISSUE THREAD

**Issue by aknight023** [pqina/filepond#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I was reading the docs on `Filter files from dropped folders` on the FilePond Features Tab https://pqina.nl/filepond/#features. But when you drop a folder onto the file pond it freezes and crashes your browser.

### Reproduction

Drag and Drop a Folder onto the Multiple File Upload example
 https://pqina.nl/filepond/#examples
Your Brower will freeze and you will have to Force Quit out of Chrome

### Environment

```markdown
- Device: MacBook Pro (16-inch, 2019)
- OS: MacOs Big Slur 11.6.2 (20G314)
- Browser: Google Chrome Version 97.0.4692.99 (Official Build) (x86_64)
```

**Comment by rikschennink** [comment]
Just tested this, on Chrome / macOS Big Sur, it works without issues?

Will close for now.
