### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TSalu** [pqina/filepond#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Hello, I am unable to validate .asice files which are digitally signed files. 

The mime type of .asice file is **application/vnd.etsi.asic-e+zip**

### Reproduction

I Installed the latest version of Filepond by using the CDN method.

Example of something that I tried: 

```
  <script>
            document.addEventListener('DOMContentLoaded', function() {
                
                FilePond.registerPlugin(FilePondPluginFileValidateType);

                const inputElement = document.querySelector('input[type="file"]');
                const pond = FilePond.create(inputElement);

                FilePond.setOptions({
                    allowFileTypeValidation: true,
                    acceptedFileTypes: ["application/vnd.etsi.asic-s+zip/*"],
                    server: {
                        url: '/upload',
                        headers: {
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        }
                    }
                });


            });

        </script>
```

I also tried setting the accepted file type like this: 
acceptedFileTypes: [".asice"]

When I did that then the Browse Explorer window only showed me .asice files(as it should) but when I clicked upload then I got this error: 
![image](https://user-images.githubusercontent.com/22459445/153412751-605fb1ff-6e56-4201-8df4-f047d0afb4e6.png)

### Environment

```markdown
- Device: PC
- OS: Win 11
- Browser: Chrome (latest)
```

**Comment by rikschennink** [comment]
https://pqina.nl/filepond/docs/api/plugins/file-validate-type/#custom-type-detection
