### ISSUE TITLE
acceptedFileTypes file selection mask doesn't respect fileValidateTypeDetectType

### ISSUE THREAD

**Issue by SilverBull** [pqina/filepond#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I don't know if it's a bug or intended behavior.
When I open the file selection mask to browse, the file type is blocked among those selected in the acceptedFileTypes array.
The problem arises from the need to load a file that does not have a defined mime type, that is an xbrl, which some systems recognize as an xml (it is in fact an xml) but having a different extension it is rejected by the selection mask. If I select all and load the file, the logic implemented through the fileValidateTypeDetectType function allows loading correctly.

Is there a way to force the file selection mask to accept the xbrl extension?

### Reproduction

https://codesandbox.io/s/tender-lucy-bv2nu?file=/src/index.js

use the browse link to open the file manager upload mask

try to find an xbrl file (you can just rename an xml for the purpose of the test).

If you switch to all files the file appears and you can upload it correctly 

![image](https://user-images.githubusercontent.com/12399837/153899739-344a681b-1219-4f2a-a9d4-2545469614ac.png)

### Environment

```markdown
- Device: Irrilevant (Xps 9560)
- OS: Irrilevant (manjaro 21.2.3)
- Browser:Edge, Firefox. Desktop variants
```

**Comment by rikschennink** [comment]
Will close for now as this is most likely a browser thing. Best to try with a basic file input and see if you get the same result.
