### ISSUE TITLE
[Feature] Verbose Debug mode?

### ISSUE THREAD

**Issue by vesper8** [pqina/filepond#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I'm having such a terrible time troubleshooting this. I'm using your Pqina editor along with this package inside a Vue/Cordova setup. ~75% of my users have issues with uploading files, especially when they attempt to upload multiple files at once. I so wish there was a way to force them to upload only a single file at a time.

In the meantime, is there a way to enable a debug mode of sorts that will be verbose and spit out warnings/errors whenever it encounters any kind of issue?

I've added lots of logging myself but I can't seem to pinpoint the source of the issues.. I suspect some kind of race condition or buffering/chunking issue.. but it's so hard to get to the bottom of it.

A debug mode would be helpful.

Otherwise, are you by any chance available for one-on-one support? We'll pay of course. At this point I have spent 30+ hours trying to get this to work perfectly and I'm starting to run out of ideas and getting a bit desperate.

### Describe the solution you'd like

---

### Describe alternatives you've considered

---

**Comment by rikschennink** [comment]
You could set `maxParallelUploads` to `1` but maybe that's not what you mean?

Additionally if you are only uploading one file I'd stay away from FilePond and use the included <pintura-input> element. It's a lot more lightweight and Pintura can handle file uploads as well.
https://pqina.nl/pintura/docs/v8/getting-started/installation/pintura-input/

If that doesn't work, please reach out using the support form on the customer portal, happy to discuss this but it's better to do that outside GitHub.

Will close this for now as the feature request is intertwined with other issues. If needed I'll clean this up later.

**Comment by rikschennink** [comment]
Glad to hear that.

I'm not aware of any attribute on the file input element that allows you to limit the amount of files you select, the only thing you can do is hint at the file types the user can select, but that isn't supported on every OS.
