### ISSUE TITLE
Have hidden input with empty state when no files added.

### ISSUE THREAD

**Issue by kylefox** [pqina/filepond#81]
Is there a way to directly modify the hidden input?

Here's my use case:

Our FilePond is part of an AJAX form that saves other data (ex: title, body, image_id). The user can upload an image and pressed "Save", which will submit the data `image_id="1234"`.

However, if they now remove (i.e. _revert_) that file, the hidden `image_id` input is removed from the DOM. If "Save" is pressed, there is no value for `image_id`. Our server expects `image_id=""` to be submitted, so I need a way to keep the hidden input in the DOM but set the value to an empty string `""`.

Is this possible? Or, alternatively, is there a better way to _always_ have the hidden input present (and simply be empty if there is no file present?)

**Comment by rikschennink** [comment]
I think it would be better to add the element outside of the FilePond root element, just to be on the safe side. 

Added this to my todo list as well as it should indeed have an empty state.

**Comment by pfp-ph** [comment]
What's the status on this one? I'm facing the same problem. Also, i'd really like to add some additional information, like the file extension.

**Comment by rikschennink** [comment]
You can add additional info using the `file.setMetadata` method.
https://pqina.nl/filepond/docs/patterns/api/file/#methods

Will see if I can pick this up soon.

**Comment by rikschennink** [comment]
Added in version `4.3.0`
