### ISSUE TITLE
[Feature] Ability to set a "main image"

### ISSUE THREAD

**Issue by oldcastlehq** [pqina/filepond#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

No that I know.

### Describe the solution you'd like

Hi,

It would be very handy if we could set a "main image" from the preview of the images that we just uploaded.

For example. Let's say that we have a product_new page, where we use it to create the product page in our CRUD. In the images section, we can select multiples images to be uploaded. During the preview, it would be nice if we could select/tag one image to be the "main image" of the product. This is a common setup in ecommerce websites. You have the main product image and the rest are used for carousel or gallery. You could add a hover on the image, and on the left/right top corner a label/button/icon saying "set main image" or something like that. It would be like a radio element. You can only set one main image. Now, I just don't know how you could upload/submit them to the server. Maybe the main image can create a hidden input for it?

I hope I made it clear.

Cheers.

### Describe alternatives you've considered

I cannot think of any now.

**Comment by rikschennink** [comment]
You can use `onactivefile` to track clicks on files and use file metadata to store information about files, both of those should help implement this.

**Comment by oldcastlehq** [comment]
Thanks.
