### ISSUE TITLE
[Feature] Modify file before filepond. e.g compress file before filepond add it

### ISSUE THREAD

**Issue by aneesdev** [pqina/filepond#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hi @rikschennink 

First of all, thank you so much for the great package. Always appreciate the hard work that you have put into it.

Is there a way I can like before filepond starts adding a file I take the file and do something with it e.g compress it and give that compress File object to filepond etc.

### Describe the solution you'd like

None

### Describe alternatives you've considered

i tried the before add file hook but still filepond upload the original File object

```javascript
beforeAddFile(item) {
      console.log('beforeAddFile', item);
      // before adding a file we compress the image using compressorjs by fengyuanchen library
      // and then we return the compressed image to filepond
      return new Promise((resolve, reject) => {
        // we check if the file is an image
        if(item.file.type.includes('image'))
        {
            new Compressor(item.file, {
            maxWidth: 2500,
            quality: 0.6,
            resize: 'cover',

            // The compression process is asynchronous,
            // which means you have to access the `result` in the `success` hook function.
            success(result) {
                // we return the compressed image to filepond
                console.log('compressed image', result);
                // item.file = result;
                resolve(result);
                
            },
            error(err) {
              console.log(err.message);
              return;
            },
          });
        } else {
          // if the file is not an image we resolve the promise with the file src
          resolve(item.file);
        }
      });
```

**Comment by rikschennink** [comment]
Thanks! This can be with a plugin, I'd advise to look in to a couple plugins and see how you can intercept a file (for example the file encode plugin). [I believe the original image edit plugin ](https://github.com/pqina/filepond-plugin-file-encode/blob/master/src/js/index.js)

**Comment by aneesdev** [comment]
> Thanks! This can be with a plugin, I'd advise to look in to a couple plugins and see how you can intercept a file (for example the file encode plugin). https://github.com/pqina/filepond-plugin-file-encode/blob/master/src/js/index.js

thanks for the reply.. i checked the code but I still can't wrap my around it.. can I use the addFilter in my filepond? what which filter I need to intercept it?

**Comment by aneesdev** [comment]
@rikschennink is there any guide on how to write filepond plugins?

**Comment by rikschennink** [comment]
@aneesdev at the moment there is not, your best bet is to look at existing plugins.

**Comment by bilalmalkoc** [comment]
Hello. Did you find any solution to handle/compress image before adding to FilePond?

**Comment by june07** [comment]
https://github.com/june07/filepond-plugin-zip
