### ISSUE TITLE
[Bug] setting allowProcess from JS does not work

### ISSUE THREAD

**Issue by nadorator** [pqina/filepond#813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

`this.$refs.pond.allowProcess = false;
        console.log(this.$refs.pond);`

result: allowProcess still true. 

I want to add files to preview on first load of my vue page but I do not want to upload them becase they are already uploaded. I am using the component to decide if I revert last upload to make a new one before uploading again.  It also break the vue router navigation because each time I go back to the page using the filepond then the same picture is upload again and again. 

I have added a value in localStorage to bypass the upload by changing the allowProcess value only when needed but is has no effect on the instance. 

### Reproduction

``this.$refs.pond.allowProcess = false;
        console.log(this.$refs.pond);``

### Environment

```markdown
- Device: PC
- OS: Windows 11
- Browser: Chrome on windows 11.
```

**Comment by rikschennink** [comment]
When setting initial files you should use the files prop.
https://pqina.nl/filepond/docs/api/instance/properties/#files

Not all filepond props are reactive so setting `allowProcess` to false after initialisation doesn't work.
