### ISSUE TITLE
[Bug] acceptedFileTypes for video not working - React

### ISSUE THREAD

**Issue by krajcikondra** [pqina/filepond#815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I have following filePond

```
<FilePond
    acceptedFileTypes={['video/mp4']}
   ...
/>
```

When I upload .mpg video no error is throw and video is successfully uploaded.

### Reproduction

```
<FilePond
    acceptedFileTypes={['video/mp4']}
   ...
/>
```

### Environment

```markdown
- Device: Dell Latitude
- OS: Linux MX 11
- Browser: Chrome 97
```

**Comment by rikschennink** [comment]
Some types aren't correctly recognised by the browser, you can use the hook below to work around that:
https://pqina.nl/filepond/docs/api/plugins/file-validate-type/#custom-type-detection
