### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [pqina/filepond#817]
Hey there!

I belong to an open source security research community, and a member (@harunoz) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by rikschennink** [comment]
Hi, you can temporarily use this contact form, busy adding one to pqina root site as well which I'll add to `SECURITY.md`

**Comment by JamieSlome** [comment]
@rikschennink - thanks for your response! 👍 

I have sent a message via your contact form, but for reference, you can also find the report [here](https://huntr.dev/bounties/f73502a2-d560-40fb-acf3-8f8f8dac4ca9/).

**Comment by rikschennink** [comment]
I've already discussed this issue a couple weeks ago. In short, when you handle uploaded files, always validate file content on the server.
