### ISSUE TITLE
[Bug] Filepond doesn't work with Cloudflare Images

### ISSUE THREAD

**Issue by fergusmeiklejohn** [pqina/filepond#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Filepond doesn't work with Cloudflare images. If I use a simple form it works great, uploads successfully, but if I use filepond the upload fails.
```
// A simple form works
      <form action={uploadURL} method="post" encType="multipart/form-data">
        <input type="file" id="myFile" name="file" />
        <DefaultButton type="submit">Upload Image</DefaultButton>
      </form>
```

It's difficult to know where this bug is, but I'm hoping that you'll know what the difference might be from the server's POV between filepond and a simple form

### Reproduction

I've created a reproduction but it's pretty simple stuff, the server endpoint at Cloudflare returns a 400.  This is using their Direct Creator Upload feature which enables uploading from the client. Each upload URL is unique and only valid for a short time. It's a paid service ($5) So if you don't have an account want to reproduce let me know and I'll hit their API for a URL you can use. 

thanks

https://codesandbox.io/s/floral-sea-w98i74?file=/src/index.js

### Environment

```markdown
- Device: M1 Macbook Air
- OS: OSX 12.3
- Browser: Firefox 98.0.1
```

**Comment by rikschennink** [comment]
It could be this happens because FilePond sends both the file and the file metadata in the same post, you can try to use a custom process method shown below:
https://pqina.nl/filepond/docs/api/server/#process-1

Replacing `'url-to-api'` should do the trick.

If that doesn't work you can also try removing the `server` property and setting `storeAsFile` to `true`

I will close this for now as there is nothing really special about how FilePond posts file (apart from what I described in the first paragraph) so if it doesn't work with the other two options I suspect it's some configuration option in Cloudeflare.

**Comment by fergusmeiklejohn** [comment]
Thanks! There is a mismatch in the types that causes problems with the React component. The type of Process is:
```
type ProcessServerConfigFunction = (
  /** The name of the input field. */
  fieldName: string,
  /** The actual file object to send. */
  file: any,
  metadata: { [key: string]: any },
  /**
   * Should call the load method when done and pass the returned server file id.
   * This server file id is then used later on when reverting or restoring a file
   * so that your server knows which file to return without exposing that info
   * to the client.
   */
  load: (p: string | { [key: string]: any }) => void,
  /** Call if something goes wrong, will exit after. */
  error: (errorText: string) => void,
  /**
   * Should call the progress method to update the progress to 100% before calling load().
   * Setting computable to false switches the loading indicator to infinite mode.
   */
  progress: ProgressServerConfigFunction,
  /** Let FilePond know the request has been cancelled. */
  abort: () => void
) => void;
```
But the example includes `transfer` and `options` which throws a TS error: `(fieldName, file, metadata, load, error, progress, abort, transfer, options)`

**Comment by rikschennink** [comment]
Thanks for sharing your solution @fergusmeiklejohn
