### ISSUE TITLE
Support for IE11?

### ISSUE THREAD

**Issue by KevinCocquyt39** [pqina/filepond#82]
### Summary

There is no support in IE11 for the file uploader. Are there any plans for support or would it need a polyfill or a suggested fix/fork/pull request?

### How to reproduce

When loading the page with FilePond, a javascript error occurs... "Object doesn't support this action".

### Additional information

It has to do with IE not knowing the method "document.dispatchEvent()".

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Browser      | Internet Explorer 11

**Comment by rikschennink** [comment]
Hi! Adding the [FilePond Polyfill](https://github.com/pqina/filepond-polyfill) files should fix the issue

**Comment by KevinCocquyt39** [comment]
As I was driving home, I thought to myself, I should have RTFM a little bit better before opening a new issue. Browser support is idd mentioned in the docs and I should have seen it. Thanks again for your patience and making the README even better.

Maybe something to mention... For IE, there is no support for Promises which made me also add a polyfill like es6-promise (https://github.com/stefanpenner/es6-promise, the auto version). Might be useful for future users?

**Comment by rikschennink** [comment]
Haha, no worries @KevinCocquyt39, and good idea to mention Promises as well!

**Comment by KevinCocquyt39** [comment]
Hi. Here I am again... I implemented filepond in a production website using unpkg.com without an explicit version number. As my client was testing the functionality today, he couldn't get it to work in IE11. As I had a look at the history of this project, there were (since my implementation) 2 major releases for filepond and for those, it seems the IE11 support is lacking, even when using the polyfill (I also tried v2 via unpkg but with the same unresponsive behavior (IE11 freezes with the message "waiting for size")). I have set v1.8.8 now in my unpkg-url making it work again on all browsers but I wanted to let you know about the issue.

**Comment by rikschennink** [comment]
Hi @KevinCocquyt39, a number of IE11 bugs have been fixed in the past days so it should now function, I'll re-test it as soon as possible.

I would advise to always lock version number to major version.

**Comment by KevinCocquyt39** [comment]
First time I ever used unpkg to serve libraries and learning it the hard way. Thanks for the quick response!

**Comment by rikschennink** [comment]
@KevinCocquyt39 Can you try adding this babel polyfill:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
```

**Comment by KevinCocquyt39** [comment]
I'll try asap and get back to you.

**Comment by KevinCocquyt39** [comment]
No such luck but I'm actually not using Babel, just plain MVC with built-in bundling and referring to script in the old-school way (non-modules). These are the references I currently am testing with (not using explicit version numbers with unpkg)...

<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.auto.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
<script src="https://unpkg.com/filepond-polyfill/dist/filepond-polyfill.min.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.min.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js"></script>
<script src="https://unpkg.com/filepond/dist/filepond.min.js"></script>

It's getting quite crazy with all those polyfills nowadays :)

**Comment by rikschennink** [comment]
Hm, any info on the specific error IE11 is throwing?

**Comment by KevinCocquyt39** [comment]
That's the weird thing. It is stuck on 'waiting for size' but the console window doesn't give any indication on what the reason is. With the issues I had in the past, at least it gave a warning like 'Promises not supported' but now it's all just a blank.

**Comment by rikschennink** [comment]
I'm looking into it.

**Comment by rikschennink** [comment]
Just published version `3.1.5` which resolves a problem with web workers on IE11 and Edge, it's possibly related to this issue.

**Comment by rikschennink** [comment]
I've updated the [FilePond PHP Boilerplate](https://github.com/pqina/filepond-boilerplate-php/blob/master/public/index.html) and made sure it functions correctly on IE11.

**Comment by KevinCocquyt39** [comment]
I was able to test the new version in my project and it works in IE (not needing the extra babel polyfill). Thanks!

**Comment by BMCwebdev** [comment]
For people who end up here searching for an answer to this problem, I solved it by using the following:
[https://www.npmjs.com/package/custom-event-polyfill]
