### ISSUE TITLE
[Security issues] XSS 

### ISSUE THREAD

**Issue by therealsphinx** [pqina/filepond#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

**File:** https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js

The application is vulnerable to DOM-based cross-site scripting. Data is read from window.location.href and passed to the 'innerHTML' property of a DOM element. DOM-based vulnerabilities arise when a client-side script reads data from a controllable part of the DOM (for example, the URL) and processes this data in an unsafe way. DOM-based cross-site scripting arises when a script writes controllable data into the HTML document in an unsafe way. An attacker may be able to use the vulnerability to construct a URL that, if visited by another application user, will cause JavaScript code supplied by the attacker to execute within the user's browser in the context of that user's session with the application. The attacker-supplied code can perform a wide variety of actions, such as stealing the victim's session token or login credentials, performing arbitrary actions on the victim's behalf, and logging their keystrokes.

### Reproduction

var url = window.location.href.replace(window.location.hash, '');
mask = mask.replace(/url\(\#/g, 'url(' + url + '#');
root.element.innerHTML = mask.replace(/__UID__/g, SVGMaskUniqueId);

### Environment

```markdown
...
```

**Comment by rikschennink** [comment]
How do you suggest we fix this?

**Comment by rikschennink** [comment]
fixed in 4.6.11
