### ISSUE TITLE
[Bug] Uploaded Files Disappear when changing the values of other v-model

### ISSUE THREAD

**Issue by eskiesirius** [pqina/filepond#824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

When updating other fields, the uploaded file disappears

### Reproduction

https://codesandbox.io/s/distracted-snow-kuksq0?file=/src/App.vue

### Environment

```markdown
- Device: PC
- OS: Windows 10
- Browser: Chrome
```

**Comment by rikschennink** [comment]
Can you try it like this `:files="documents"` instead of `:files="[…documents]"`

**Comment by eskiesirius** [comment]
yeah i changed it to [..documents] and added updatefiles event.. thank you
