### ISSUE TITLE
[Bug] Not able to download the file using keyboard, accessibility issue. 

### ISSUE THREAD

**Issue by tomchi89** [pqina/filepond#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Hi,

I have noticed that there is no way to download uploaded files using a keyboard. I would assume that will be a core feature for the accessibility part of the plugin but the user can't access a button or link that will allow downloading the file. 

I've been looking at the HTML layout and there is no download button being hidden either. 

Because the plugin is advertised as accessible by keyboard I believe this is a bug and should be addressed as soon as possible. 

### Reproduction

You can easily test this issue on your homepage. Upload the files to one of the demo example and try to use keyboard to download uploaded file. You will be able to remove it, edit, re upload but not download. 

### Environment

```markdown
- Device: Macbook Pro
- OS: Mac OS
- Browser: Chrome, Edge (chrome), Safari, probably all of them
```

**Comment by rikschennink** [comment]
Downloading files is not part of FilePond, there is no download button, so I don't see how this is an accessibility issue.

If you want to add a download button you can use this plugin, it's offered by a third party so I can't promise if it is accessible.
https://github.com/nielsboogaard/filepond-plugin-get-file
