### ISSUE TITLE
[Bug] Upload Files open up camera on iOS

### ISSUE THREAD

**Issue by iambryansanders** [pqina/filepond#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Whenever you click open your files on iOS devices, it opens the camera. You can't open files. 

It should open to files in the iOS browser

<img width="959" alt="image" src="https://user-images.githubusercontent.com/5375223/167502948-6f99a663-b121-4518-ae39-f13cae7450c2.png">

### Reproduction

Create a basic Vue3 install, add file-pond, set accepted file type to 'application/pdf,application/msword,
  application/vnd.openxmlformats-officedocument.wordprocessingml.document'. It will default open a camera. 

### Environment

```markdown
- Device: iPad, iPhone
- OS: all
- Browser: safari
```

**Comment by rikschennink** [comment]
This is probably basic file input behaviour, will close for now, you can try to reproduce with a normal file input and setting the `accept` and `capture` attributes.

**Comment by iambryansanders** [comment]
What should they be set to?

**Comment by rikschennink** [comment]
https://stackoverflow.com/questions/21523544/html-file-input-control-with-capture-and-accept-attributes-works-wrong
