### ISSUE TITLE
Locale options?

### ISSUE THREAD

**Issue by ronaldohoch** [pqina/filepond#84]
Hello! Thank you for this AWESOME plugin, I have a question:

![image](https://user-images.githubusercontent.com/2287371/42883017-c2e38eb8-8a70-11e8-914e-9691d0746150.png)
![image](https://user-images.githubusercontent.com/2287371/42883102-fec37dda-8a70-11e8-8883-1a8edf5ea3a7.png)

How can I change this labels, can you provide a Locale object to us?

**Comment by rikschennink** [comment]
See the [labels](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#labels) entry in the docs for translation and customization options.
