### ISSUE TITLE
[Bug] Unable to replace the selected file by dragging when maxFiles is set and allowMultiple is false

### ISSUE THREAD

**Issue by iadcode** [pqina/filepond#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

It's not possible to replace the selected file by dragging when allowReplace is enabled and maxFiles has a value of one.

### Reproduction

Given the following [code](https://codesandbox.io/s/empty-cherry-8gnmro):
```
import "filepond/dist/filepond.min.css";
import { create } from "filepond";

const inputElement = document.querySelector('input[type="file"]');

create(inputElement, {
  allowMultiple: false,
  allowReplace: true,
  maxFiles: 1
});
```
1. Select a file
2. Try to replace the selected file by dragging a new file

### Environment

```markdown
Not browser specific, but tested on:
- Device: PC
- OS: Window 10
- Browser: Firefox 100.0.2, Chrome 101.0.4951.67 (Official Build) (64-bit)
```

**Comment by rikschennink** [comment]
Does it work when not setting `maxFiles`?
