### ISSUE TITLE
Filepond ignores server config

### ISSUE THREAD

**Issue by floriansemm** [pqina/filepond#85]
We are using Filepond together with Symfony4. When a image was uploaded and the form was submitted with an error, then filepond ignores the server config. Filepond tries to call the default `restore` endpoint, which does not exists in our application and is not configured (see below). 

```javascript
    FilePond.registerPlugin(
        FilePondPluginFileEncode,
        FilePondPluginFileValidateType,
        FilePondPluginImageExifOrientation,
        FilePondPluginImagePreview,
        FilePondPluginImageCrop,
        FilePondPluginImageResize,
        FilePondPluginImageTransform
    );

    const inputElement = document.querySelector('.js-product-images');
    FilePond.create(
        inputElement,
        {
            name: 'product[images][]',
            allowMultiple: true,
            allowRevert: false,
            server: '/uploads/',
            labelIdle: 'Drag & Drop your picture or <span class="filepond--label-action">Browse</span>',
            imagePreviewHeight: 170,
            imageCropAspectRatio: '1:1',
            imageResizeTargetWidth: 200,
            imageResizeTargetHeight: 200
        }
    );
```

It seems like that filepond uses the default config if an the input-field contains a Id attribute.

**Comment by rikschennink** [comment]
What happens when the form is submitted with an error? Does the page reload? 

If I understand correctly when you remove the `id` attribute it does pick-up the new configuration on server error?

**Comment by floriansemm** [comment]
Yes it is a page reload. It has no effect if I remove the ID attribute. 

In our form the `images` field from above is not a file-input it is a hidden-input.

**Comment by rikschennink** [comment]
Can you try if the problem is the same with a file input, using something else is not tested and supported.
