### ISSUE TITLE
[Feature]  Frustrating that there is not finer control over chunk processing nor is any chunk information passed to the process function.

### ISSUE THREAD

**Issue by maurice-ellis** [pqina/filepond#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Frustrated that I do not have control over the chunk processing like I do regular processing. Filepond makes a lot of assumptions on my behalf and does not work for my specific case dealing with chunked uploads to AWS.

### Describe the solution you'd like

I would want a server method specifically for chunk processing that includes the chunk and specific information about the current one.

### Describe alternatives you've considered

I tried using the process serve method to do what I need, but cannot since I cannot access the current chunk information.

**Comment by rikschennink** [comment]
1. You can set up a [custom process method](https://pqina.nl/filepond/docs/api/server/#process-1).
2. You're free to fork the library and submit a PR.
3. You can use one of the other free file upload solutions on GitHub that are given to you without strings attached and have taken authors many months of work to built.

**Comment by maurice-ellis** [comment]
Hi @rikschennink thank you for your gracious response. I figured out how to do it but was unable to delete this. I was rude. I do apologize. I just found out about Filepond and was frustrated that it appeared that it didn't seem to have the ease of use customization for chunked uploads.

**Comment by rikschennink** [comment]
@maurice-ellis Glad to hear you found the solution. Appreciate the apology, development can be super frustrating, especially if things don't work and there's a time aspect involved. Good luck with the project!
