### ISSUE TITLE
Can i use this in .vue files without using the vue-filepond package?

### ISSUE THREAD

**Issue by ricky11** [pqina/filepond#88]
### Summary
The following script doesn't bind to the input element

const inputElement = document.querySelector('input');
const pond = FilePond.create(inputElement);
According to the DOCS the input element will be replaced with <div class="filepond--root">...</div>
But It doesn't get replaced.

### How to reproduce
Using a .vue create the code below:
`
<input type="file">

<script>
import * as FilePond from 'filepond';
import 'filepond/dist/filepond.min.css';
const inputElement = document.querySelector('input');
const pond = FilePond.create(inputElement);
export default {
}
</script>`

...

### Expected behaviour
The input element should be replaced with <div class="filepond--root">...</div>
...

### Additional information

...

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by ricky11** [comment]
Sorry i am not sure why my code isn't being see here, i did surround them with backticks

**Comment by rikschennink** [comment]
I would advice against this as you’d have to add most of the code that is in the Vue adapter yourself. Why not use the adapter?

Will close this issue as it’s related to Vue implementation details and not a FilePond bug/problem.
