### ISSUE TITLE
[Bug] TypeError: Cannot read properties of null (reading 'insertBefore')

### ISSUE THREAD

**Issue by MeloHenrique** [pqina/filepond#883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I am using the advanced server configuration.
Inside the Load method, I am fetching an API to receive the image to show in the preview. 

The component works as expected, and the image is loaded.

![image](https://user-images.githubusercontent.com/49417222/212779101-08a8d03f-b441-45f0-ba55-5ed79eddb52b.png)

### Reproduction

I am not sure how I can reproduce the error. I am using Blazor but I don't think it's because of that.

### Environment

```markdown
- Device: Dell Precision 5750
- OS: Windows
- Browser: Edge / Chrome
```

**Comment by MeloHenrique** [comment]
Hello, 

I found time to debug the problem, and the destroy method throws an error.
The problem is when it tries to execute "insertAfter", the value of "referenceNode" is null.

If it's ok, I could try to make a PR in the next few hours.
Let me know if there's anything that you saw that could help.

I am also implementing multiple file uploads, and when the component has files in the creation, the method "getFiles" always returns an empty list. Then deleting the files and trying to upload new ones, the list is still empty, and the upload is insucess.

**Comment by rikschennink** [comment]
Hey, super busy, I can't promise anything but always appreciate a PR.

Also working on v5 of FilePond, which will replace all code.

**Comment by MeloHenrique** [comment]
I just saw the comment.
I think that part of the problem was due to be using Blazor and the lifecycle is a little different.
I was able to fix it from our end.

Waiting for the v5 😁
