### ISSUE TITLE
[Bug] File is invalid type when it should be a valid type

### ISSUE THREAD

**Issue by trymeouteh** [pqina/filepond#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

When I set the _accept_ attribute to only accept specific file types and select those file with the FilePond file selector, it will return an error saying that the "File is invalid type".

### Reproduction

```
<link rel="stylesheet" href="node_modules/filepond/dist/filepond.min.css">



<div>
    <input type="file" id="myInput" accept=".iso, .flac">
</div>



<script src="node_modules/filepond/dist/filepond.min.js"></script>
<script src="node_modules/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.min.js"></script>

<script>
    FilePond.registerPlugin(FilePondPluginFileValidateType);

    FilePond.create(document.querySelector('#myInput'), {
        credits: false
    });
</script>
```

### Environment

```markdown
- Device: Laptop
- OS: Linux Mint 21.1
- Browser: Firefox & Ungoogled Chromium
```

**Comment by rikschennink** [comment]
Extension are not supported. Please use mime types. 

You can use custom type detection to allow more fine grained control:
https://pqina.nl/filepond/docs/api/plugins/file-validate-type/#custom-type-detection
