### ISSUE TITLE
[Bug] beforeRemoveFile

### ISSUE THREAD

**Issue by mrkazmierczak** [pqina/filepond#889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I was trying to run beforeRemoveFile hook to show modal before remove file to ask user if he really want to remove permanently this file from the server... and nothing. So so I decided to dig deeper and analyzed the plugin code. There is beforeRemoveFile hook.... and this hook is only declared in hooks section.

   // hooks
        beforeDropFile: [null, Type.FUNCTION],
        beforeAddFile: [null, Type.FUNCTION],
        beforeRemoveFile: [null, Type.FUNCTION],
        beforePrepareFile: [null, Type.FUNCTION],
        
Unfortunately, outside of this place, this hook is not used in the plugin logic at all and is not triggered before the file is removed. 

Rik I read in the bug history that you added this feature, but I guess you didn't commit correctly because this hook is not triggered in any way before remove action. I know that most users only use FilePond to upload files, but since we have such a beautiful tool, why not use it also as a handler for files on edit. Any chance we can get in touch somehow and discuss how to do these two fixes? Do you need more coffee? ;)

Cheers 
Marcin

### Reproduction

There's nothing to reproduce, the hooks logic doesn't exist in the FilePond. 

### Environment

```markdown
- Device: mac
- OS: Mojave
- Browser: Chrome
```

**Comment by rikschennink** [comment]
https://codesandbox.io/s/vanilla-filepond-forked-bmoj00?file=/src/index.js
