### ISSUE TITLE
Add close button after upload.

### ISSUE THREAD

**Issue by yukyolol** [pqina/filepond#89]
Hello, is possible to add "close" button after success upload?

https://puu.sh/B4BtG/1c711e55b9.png

Like tap to close. I disabled undo action because I don't want it. But now I can't close a file after upload.

Thanks.

**Comment by rikschennink** [comment]
This should do it:

- Set `instantUpload` to `true`
- Set the `iconUndo` property to a SVG depicting a cross
- Set `labelTapToUndo` to `'tap to remove'`
- Disable the revert fuction

```js
FilePond.create(document.querySelector('input'), {
    server: {
        url: 'url-to-server',
        revert: null
    }
});
```
