### ISSUE TITLE
[Bug] beforeAddFile this hook doesn't

### ISSUE THREAD

**Issue by mrkazmierczak** [pqina/filepond#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

This hook is initialize but there is only this line of code, there is no logic behind this line of code to control this event. 

beforeAddFile: [null, Type.FUNCTION],

### Reproduction

There's nothing to reproduce, the hooks logic doesn't exist in the FilePond.

### Environment

```markdown
- Device: mac
- OS: mojave
- Browser: Chrome
```

**Comment by rikschennink** [comment]
https://github.com/pqina/filepond/blob/master/src/js/app/actions.js#L874
