### ISSUE TITLE
[Bug] beforeAddFile hook don't work

### ISSUE THREAD

**Issue by mrkazmierczak** [pqina/filepond#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I was trying to run beforeAddFile. So so I decided to dig deeper and analyzed the plugin code. There is beforeAddFile hook.... and this hook is only declared in hooks section.

// hooks
beforeDropFile: [null, Type.FUNCTION],
beforeAddFile: [null, Type.FUNCTION],
beforeRemoveFile: [null, Type.FUNCTION],
beforePrepareFile: [null, Type.FUNCTION],

Unfortunately, outside of this place, this hook is not used in the plugin logic at all and is not triggered before the file is removed.

### Reproduction

There's nothing to reproduce, the hooks logic doesn't exist in the FilePond.

### Environment

```markdown
- Device: mac
- OS: mojave
- Browser: Chrome
```

**Comment by rikschennink** [comment]
https://codesandbox.io/s/vanilla-filepond-forked-mzx95n?file=/src/index.js

**Comment by maclonghorn** [comment]
I'd like to reopen this.  Here are my options:
```
this.filePondOptions = {
      storeAsFile: true,
      name: this.name,
      labelIdle: 'Drag files or click here to upload',
      allowDrop: true,
      allowMultiple: false,
      acceptedFileTypes: ['application/pdf'],
      beforeAddFile: (e) => {
        console.log('adding file', e.file);
        // debugger;
        // if (e.file.file.type != 'application/pdf') {
        //   this.notificationsService.notifyDanger('File is not a PDF');
        //   return false;
        // }
      }
```
The problem occurs when user selects "All Files" and chooses a file that is not a PDF (or drops a non-PDF).  This hook is not being called.

**Comment by maclonghorn** [comment]
Here's how I got around this issue, and was able to cancel a file upload when type was disallowed.  I am using `addFile` to handle `onaddfile` event (in Angular):
```
addFile(e) {
    // Verify file is PDF since user can drag any file type to FilePond
    if (e.file.file.type != 'application/pdf') {
      alert('File is not a PDF');
      e.pond.removeFile(e.file);
    } else {
      // handle successful file upload
    }
  }
```
I still think that if you return "false" from the error handler, it should not still call `onaddfile`.

BTW, I'm using version 4.30.4.

**Comment by rikschennink** [comment]
I'll leave this closed, agreed that there's room for improvement, will address it in v5
