### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by soixt** [pqina/filepond#894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

![image](https://user-images.githubusercontent.com/100382372/218909497-2963c4eb-7293-46fd-9f02-daa1be4e2386.png)
I think this image is the best description of the problem.
When I click outside on the inner label area (purple sides) it opens window twice, right after you pick a file or close first window, opens another one. When I click directly at label area (blue center) it opens only once.

Not sure what can cause this problem?

[Update]

My current fix is:
```
.filepond--drop-label > label {
    width: 100% !important;
    height: 100% !important;
    display: flex !important;
    justify-content: center !important;
    align-items: center !important;
}
```

### Reproduction

Click outside of the inner label

### Environment

```markdown
- Device: Lenovo Ideapad gaming
- OS: win 11 (don't even ask me)
- Browser: chrome
```

**Comment by rikschennink** [comment]
Can you reproduce this on the FilePond website?

**Comment by rikschennink** [comment]
Will close for now, will re-open if is not caused by external libraries or css, please note subject is missing.
