### ISSUE TITLE
[Bug] Uploading zip file on Windows vs macOS

### ISSUE THREAD

**Issue by MrMooky** [pqina/filepond#899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I have some issues with uploads on Windows - specifically .zip files. They work on macOS, but not on Windows. This is an incomplete list of allowed files types:

```
'application/zip',
'application/x-zip',
'application/zip-compressed',
'application/x-zip-compressed',
'application/x-7z-compressed',
'application/octet-stream'
```

When uploading the file on Windows (tested in Chrome and Firefox), I get an error that the file is not supported, while the exact same file(s) works perfectly fine on macOS (same browsers).

### Reproduction

https://codesandbox.io/s/nostalgic-mendel-fujz64

### Environment

```markdown
- Device: Lenovo Notebook
- OS: Windows 10
- Browser: Chrome and Firefox
```

**Comment by mharis** [comment]
@MrMooky What was the issue? I am going through the same issue.

**Comment by MrMooky** [comment]
@mharis In my case the mime type was slightly different on Windows. There are a few tools available to check the mime type of a file. Be sure to check the file on both Windows and macOS.
