### ISSUE TITLE
RFC: Angular wrapper

### ISSUE THREAD

**Issue by vitaliy-bobrov** [pqina/filepond#9]
Thanks for such excellent library!

Want to help with Angular (2, 4, 5, 6) wrapper, but faced few problems to get started:
1. Only dist folder available on repo
  Want to see project structure and source code.

2. AJAX requests implementation backed-in
  Angular uses own wrapper on top of requests `HttpClient` and also it is possible to use any external library instead it, for example, axios. In this case will be great to have ability use filepond without its implementation. Also Angular has change detection stuff listening for ajax calls.

3. DOM manipulations
  Angular has its abstraction on top of DOM manipulation to make it possible to use it in any environment (back-end, Web Worker, etc.) and change detection plugged into it. So it will be great to have the ability to use framework API for DOM manipulations instead library one.

**Comment by rikschennink** [comment]
@vitaliy-bobrov I'd love to!

1. I'm planning to add it in the near future, but want to clean up the source files first.

2. You can setup [custom file processing methods](https://pqina.nl/filepond/docs/patterns/api/server/#advanced) which allow you to completely customize uploads (and other requests).

3. I'm not sure what you mean with DOM manipulations, please elaborate.

**Comment by vitaliy-bobrov** [comment]
Under DOM manipulations I mean add/remove DOM nodes, etc. But we can wrap filepond calls inside separate zone with `NgZone` API to avoid unnecessary change detection calls.

**Comment by rikschennink** [comment]
There's no manipulation of the DOM outside of the FilePond root node. You can create a pond without having a target element to bind to (it will then create a node itself), the element will be available in from the `element` property. You can then add that element to the page manually.

I have limited experience with Angular 1, 2 and up. But if `NgZone` blocks mutation events than if the Angular component wraps the FilePond element in one of those, all should be fine.

**Comment by vitaliy-bobrov** [comment]
Thanks for the explanation, I need to investigate how it works and will experiment on Angular wrapper.

**Comment by rikschennink** [comment]
No problem, let me know if you've got any questions, happy to help 👍

**Comment by rikschennink** [comment]
@vitaliy-bobrov I've set up an [adapter for Angular here](https://github.com/pqina/angular-filepond), I'm no pro at this, but it seems to work, probably lots of room for improvement.
