### ISSUE TITLE
[Bug] Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string

### ISSUE THREAD

**Issue by thiagomajesk** [pqina/filepond#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I'm having the following error while trying to initialize filepond:

```
Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
```

I'm using a simple form to submit some files and I have the following logic that maps what's already on "the wire" from the previous request so the user doesn't have to upload everything again:

```javascript
const existingFiles = fileRefs.map(ref => ({
    source: ref.path,
    options: {
        type: 'limbo',
        file: {
            name: ref.filename,
            size: ref.size,
            type: ref.content_type
        }
    }
}))

const config = {
    allowMultiple: true,
    maxFiles: maxFiles,
    storeAsFile: true,
    files: existingFiles
}

const input = document.querySelector(target)
const pond = FilePond.create(input, config)
```

If I comment out the `files` key from the config the error does not happen. It seems that the input values are not getting correctly updated and I can see that on the subsequent request, it doesn't get sent to the server as expected.

### Reproduction

I've created a Codepen with the repro but the error is fairly simple to reproduce: https://codepen.io/thiagomajesk/pen/RwYEPOJ. 

### Environment

```markdown
- Device: Desktop
- OS: Win 11
- Browser: Chrome 111.0.5563.110
```

**Comment by rikschennink** [comment]
Thanks for reporting, will look into it when I have some time.

**Comment by Akash4686** [comment]
Any updates on this?

**Comment by rikschennink** [comment]
This has to do with `storeAsFile` if you set it to `true` you can't use properties that indicate use of the async `server` upload method. FilePond will then store the files in a file input and there won't be any server reference.

Removing the `type:'limbo'` from the file item in the files array solves the issue.

@Akash4686 In this case the issue probably is `allowFileEncode`, if you encode the file with the file encode plugin you can't also store it as a file object.
