### ISSUE TITLE
WordPress Integration

### ISSUE THREAD

**Issue by JakeHenshall** [pqina/filepond#91]
Hi,

Is there any way to override or Integrate Filepond into the WordPress Media Uploads.

A point in the right direction would be great.

Thanks, Jake.

**Comment by rikschennink** [comment]
Hi Jake, If WordPress exposes an api to upload files it shouldn’t be a problem to set up a custom processing method (see FilePond advanced server docs) to integrate with WP.

**Comment by JakeHenshall** [comment]
@rikschennink Great, thanks.

I'm currently getting a 401 unauthorized.

![401](https://user-images.githubusercontent.com/4720782/51719410-4c810e00-2041-11e9-9c37-6c35035b0503.png)

This is the jquery that works.

    jQuery.ajax( {
        url: RestVars.endpoint,
        method: 'POST',
        processData: false,
        contentType: false,
        beforeSend: function ( xhr ) {
            xhr.setRequestHeader( 'X-WP-Nonce', RestVars.nonce );
        },
        data: formData
    } ).success( function ( response ) {
        console.log( response.id )
    } ).error( function( response ) {
        console.log( 'error' );
        console.log( response );
    });

I've just taken the server -> Advanced -> Process code 

I think I need to add this into FilePond.setOptions ({

I've tried the below:

    request.ondata = function ( xhr ) {
        xhr.setRequestHeader( 'X-WP-Nonce', RestVars.nonce );
    }

Any help would be greatly appreciated.

Thanks,

Jake.

**Comment by rikschennink** [comment]
Something like this maybe
```js
FilePond.setOptions({
    server: {
        process: {
            url: RestVars.endpoint,
            method: 'POST',
            headers: {
                'X-WP-Nonce': RestVars.nonce
            }
        }
    }
});
```

Another options (as stated earlier) is to use a custom processing method.

```js
FilePond.setOptions({
    server: {
        process:(fieldName, file, metadata, load, error, progress, abort) => {

            // fieldName is the name of the input field
            // file is the actual file object to send
            const formData = new FormData();
            formData.append(fieldName, file, file.name);

            jQuery.ajax( {
                url: RestVars.endpoint,
                method: 'POST',
                processData: false,
                contentType: false,
                beforeSend: function ( xhr ) {
                    xhr.setRequestHeader( 'X-WP-Nonce', RestVars.nonce );
                },
                data: formData
            } ).success( function ( response ) {
                console.log( response.id )
                load(response.id);
            } ).error( function( response ) {
                console.log( 'error' );
                console.log( response );
                error(response); // not sure if that contains the response message
            });

            // Should expose an abort method so the request can be canceled
            return {
                abort: () => {
                    // This function is entered if the user has tapped the cancel button
                    // request.abort();

                    // Let FilePond know the request has been cancelled
                    abort();
                }
            };
        }
    }
});
```
