### ISSUE TITLE
[Feature] Add example for compress images

### ISSUE THREAD

**Issue by mejobloggs** [pqina/filepond#910]
Originally I created this feature as a request for image compression examples, as I could not find any.

Then a few minutes later I realized the Image Transform plugin does compression using imageTransformOutputQuality. (https://pqina.nl/filepond/docs/api/plugins/image-transform/)

Maybe you could mention the word "compression" on the image-transform page, because other places you talk about "compression" so I was specifically looking for the keyword "compression" when i searched

Example of other places: 

 - The "That's not all" section here https://pqina.nl/filepond/?ref=pqina#examples says "Compress JPEG images"
 - This article (how I discovered filepond) suggested we could use FilePond to handle the file upload and compression

**Comment by rikschennink** [comment]
Thanks, good suggestion I'll add it to the docs.
