### ISSUE TITLE
[Bug] css problem with div {width=100%}

### ISSUE THREAD

**Issue by a-peace** [pqina/filepond#916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I have this css in the project: 
`
body div {
	width: 100%;
}
`

Uploading some txt file. Result - label is gone.
![image](https://github.com/pqina/filepond/assets/28490108/cfb68829-7d83-43c2-8619-7ae0479fe99a)

I understand that the problem is on my side. But that's probably not supposed to happen?
Should i adjust css for .filepond--file-info-main with something like {width: initial}?

### Reproduction

https://codepen.io/a-peace/pen/LYgaxeq

### Environment

```markdown
- Browser: Chrome
```

**Comment by rikschennink** [comment]
This is not a bug. If you're going to apply styles to each element on the page you're going to run into CSS issues, that's just the nature of CSS.
