### ISSUE TITLE
Empty temporary files after upload

### ISSUE THREAD

**Issue by oalejos** [pqina/filepond#92]
Hello!

I've been trying to integrate filepond in a WEB page that I'm building up. I have used the filepond PHP boilerplate as a starting point for development. However, although files are apparently uploaded (from the point of view of the WEB browser user, since the message 'upload complete' appears), the files stored in the tmp folder of the server are completely empty.

I must admit that I'm a complete newbie, but I would be very grateful if you could provide me with any help with this issue.

Thank you in advance,

Oscar

**Comment by oalejos** [comment]
Hi, again!
Thank you for your quick response and your assistance . As you have correctly deduced, temporary files are created, but all are empty (0KB).
Although my web hosting service doesn't provide with logs, I could find a workaround to get one, so please find it attached. I'll also try to figure out what is wrong with the upload procedure. 
[error.log](https://github.com/pqina/filepond/files/2254469/error.log)
Greetings!

**Comment by rikschennink** [comment]
> PHP Warning:  Unknown: open_basedir restriction in effect. File(/storage/ssd3/146/1201146/tmp) is not within the allowed path(s): 

I guess it’s trying to save to a folder that is not allowed or does not have the correct rights assigned? I would advice to do some google searches on this and see what comes up.

**Comment by oalejos** [comment]
Yes, I've come to the same conclusion. I have contacted with my provider to get access to the open_basedir directive, or if they can suggest any workaround. 
Thank you again.

**Comment by rikschennink** [comment]
I think the default location the script tries to write to is a sub directory tmp. It’s possible that you might have to change this to the actual temp file upload directory the provider exposes.

**Comment by oalejos** [comment]
I agree with you. Apparently, the problem was related to the location of such a temporary folder. 
In any case, I've got through to the provider. They might have altered any configuration, since things seems to be properly working now.
Let me congratulate you on the good quality of the filepond libraries, and thank you again for your assistance.
Greetings!

**Comment by rikschennink** [comment]
Thanks! I very much appreciate the feedback :-) Good luck with your project!
