### ISSUE TITLE
[Bug] Accessibility issue, drop label is aria-hidden but focusable 

### ISSUE THREAD

**Issue by Tofandel** [pqina/filepond#922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

![image](https://github.com/pqina/filepond/assets/6115458/9cac3b8a-f429-47d7-acce-b682157696a9)

### Reproduction

Simply use filepond and run lighthouse on the page, you will see that the `drop-label` is `aria-hidden="true"` but the only focusable element within the filepond is the drop label which has `tabindex="0"`

I could see in the comment of the lib that it's because the reader will read the label of the input, but the input is not focusable

Aria hidden should be removed from the drop label

### Environment

```markdown
Doesn't matter
```

**Comment by kbhutiya-eab** [comment]
Any update for this issue?

**Comment by quangthien27** [comment]
This is still an issue. But the fix from @errijahi seems not merged?

**Comment by uariguzo-eab** [comment]
@errijahi Is this issue looking to be merged in at some point?

**Comment by Tofandel** [comment]
The author and maintainer of the lib is @rikschennink not the author of the closed PR

**Comment by ZaxyxaZ** [comment]
Until and if the maintainer merges, here is the work around. In your oninit callback add the following code:       

let ele = document.querySelector(".filepond--drop-label label:first-child");
ele.removeAttribute("aria-hidden");

I think that the requested fix is probably not correct place to treat the issue and why  @rikschennink has not merged. If I'm to guess he was trying to hide the drop zone not the link to add a file from the browser.

**Comment by rikschennink** [comment]
Thanks @ZaxyxaZ, fixed in 4.31.2
