### ISSUE TITLE
Small Typo in FilePond Server Docu

### ISSUE THREAD

**Issue by jdriesen** [pqina/filepond#93]
### Summary
Small typo in the documentation for [FilePond Server](https://pqina.nl/filepond/docs/patterns/api/server/)

### How to reproduce
Just take a look on the URL mentioned above (halfway the page)

### Expected behavior
mmm ... it would be nice if it could be corrected in the docu :)
Will protect other developers from confusion ...

### Additional information
In the docu, you're using a mixture of "the good old way of writing functions" , and "fat arrow notation"

__Currently in the docu__: (and not compiling)
```javascript
  onload: function(response) => {
    return response.key;
  },
  
  onerror: function(response) => {
    return response.data;
  }
```

__Suggestion__: correct this to either:

__Good old school notation__
```javascript
  onload: function(response) {
    return response.key
  },

  onerror: function(response) {
    return response.data
  },
```

or 
__Fat Arrow Syntax__
```javascript
  onload: (response) => response.key,
  
  onerror: (response) => response.data,
```

Hope it makes sense ...

Kind regards 

(and BIG CONGRATZ for the development of this component !! )
Johnny

**Comment by rikschennink** [comment]
Thanks Johnny! Just updated the docs.
