### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by C10B** [pqina/filepond#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I have users who take a series of photos and they upload via filepond. The sequence the photos are taken is important. But watching the queue of photos get uploaded, sometimes the order is not maintained! A slow uploading file might be delayed while the next in the queue completes. 

### Describe the solution you'd like

Can I force the upload to be in the strict order that the photos were added to the queue?

### Describe alternatives you've considered

An alterative might be to record the date/time that each photo is added to the queue and pass this to the upload handler. The actual order of arrival would then not be important.

**Comment by rikschennink** [comment]
Could set `maxParallelUploads` to `1` or register file index when it's added using file metadata.
