### ISSUE TITLE
[Bug] accepted filetypes audio on iPhone doesn't work

### ISSUE THREAD

**Issue by tomaswallentinus** [pqina/filepond#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

If using the plugin FilePondPluginFileValidateType on an iPhone the file browser in iPhone only displays movie files.
acceptedFileTypes: ['audio/*']

When used on Chrome macOS it displays the test m4a file correctly.

But on iOS Safari the file is grayed out and the only selectable files are movie-files. But when selecting them you get the wrong filetype error from Filepond.

### Reproduction

`import "filepond/dist/filepond.min.css";

import FilePondPluginFileValidateType from "filepond-plugin-file-validate-type";
import { create, registerPlugin } from "filepond";

registerPlugin(FilePondPluginFileValidateType);

const inputElement = document.querySelector('input[type="file"]');

create(inputElement, {
  acceptedFileTypes: ["audio/*"]
});`
[https://codesandbox.io/s/thirsty-tristan-47ctw2?file=/src/index.js](url)

### Environment

```markdown
- Device: iPhone
- OS: iOS 16.6
- Browser: Safari
```

**Comment by tomaswallentinus** [comment]
A work around was adding acceptedFileTypes: ["audio/*","audio/x-m4a"]
Now it works for both iOS and macOS. But it feels like the asterix should handle the m4a. 

https://codepen.io/rikschennink/pen/NzRvbj gave me the iOS mime type.

**Comment by rikschennink** [comment]
Glad to hear it's resolved, this is a problem with the input element itself and the OS, not with FilePond so I'll close the issue for now.
