### ISSUE TITLE
[Feature] Option to Disable the Remove File Button

### ISSUE THREAD

**Issue by dineshmsd051** [pqina/filepond#947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In my scenario, I need to manually upload a file and process the response without using the server property. I want to prevent users from removing the uploaded file and simply disable the remove button associated with the uploaded file. Is there a way or workaround to achieve this?

Here is my code:
```
const handleUploadFile = async (fileItems: FilePondFile[]) => {
  const file = fileItems.map((fileItem) => fileItem.file);
  const uploadFile = file?.[0];

  const formData = new FormData();
  formData.append("file", uploadFile);

  axios
    .post("API_URL", formData)
    .then((response) => {
      console.log("Upload successful:", response);
      // process something with the response here
    })
    .catch((error) => {
      console.error("Error uploading files:", error);
    });
};

<FilePond files={files} onupdatefiles={handleFileUpload} />
```

### Describe the solution you'd like

Currently the uploaded file details card will look like below. Now we want to remove the rounded part
<img width="605" alt="Screenshot 2023-11-22 at 11 21 03 PM" src="https://github.com/pqina/filepond/assets/62438808/b3528335-f84b-439c-8c63-cd243c6ca4e5">

And What we expect is like below:
<img width="599" alt="Screenshot 2023-11-22 at 11 42 30 PM" src="https://github.com/pqina/filepond/assets/62438808/02df0eba-c288-4d2d-9bb8-8b9f0ed96d39">

### Describe alternatives you've considered

I Just Take a look at existing issues like [allowRemove is missing](https://github.com/pqina/react-filepond/issues/238), [How to disable the ‘tab to cancel](https://github.com/pqina/filepond/issues/369), but those doesn't help in my case.

**Comment by rikschennink** [comment]
https://stackblitz.com/edit/github-mg9scw?file=index.html%3AL113

**Comment by dineshmsd051** [comment]
@rikschennink Thanks for responding to this issue. It appears that the `allowRemove` option is currently only available in JavaScript. When using the Filepond React component, I couldn't find the allowRemove prop to prevent the removal of a file. 
<img width="610" alt="Screenshot 2023-11-23 at 7 34 18 PM" src="https://github.com/pqina/filepond/assets/62438808/60adce46-081f-4920-a261-89556caf56f9">
