### ISSUE TITLE
[Bug] url.split is not a function when attempting to load "local" images (React 18)

### ISSUE THREAD

**Issue by wwkimball** [pqina/filepond#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

# Describe the bug

When attempting to load "local" (previously-uploaded) images per the documentation regarding [load](https://pqina.nl/filepond/docs/api/server/#load) and [files](https://pqina.nl/filepond/docs/api/instance/properties/#files), FilePond throws exception, "url.split is not a function".  The full stack trace is as follows (expandable):

<details>
  <summary>filepond.js:4170  Uncaught TypeError: url.split is not a function</summary>

```text
    at getFilenameFromURL (filepond.js:4170:1)
    at request.onload (filepond.js:4771:1)
    at xhr.onload (filepond.js:4649:1)
getFilenameFromURL @ filepond.js:4170
request.onload @ filepond.js:4771
xhr.onload @ filepond.js:4649
load (async)
sendRequest @ filepond.js:4646
eval @ filepond.js:4758
loadURL @ filepond.js:4481
load @ filepond.js:4460
load @ filepond.js:5862
ADD_ITEM @ filepond.js:6927
dispatch @ filepond.js:74
eval @ filepond.js:6400
DID_SET_FILES @ filepond.js:6390
dispatch @ filepond.js:74
obj.<computed> @ filepond.js:1848
dispatch @ filepond.js:74
eval @ filepond.js:7418
SET_OPTIONS @ filepond.js:7417
dispatch @ filepond.js:74
setOptions @ filepond.js:11763
componentDidUpdate @ react-filepond.js:145
commitLayoutEffectOnFiber @ react-dom.development.js:23333
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```
</details>

I don't know which URL FilePond expects (and is not receiving) but I have -- as far as I can tell -- properly set the `url` property on the FilePond entity (see below).  Should the error be related to building an image URL, I could provide that URL -- if the `files` object allowed it -- to spare FilePond the extra processing.

## Research

I see this issue has been reported several times before here and at StackExchange but those have been closed.  I have carefully reviewed all of them that I could find and none of those issues apply here other than other unresolved reports where React is in use.

## Proposal

React is weird.  It often renders and then immediately re-renders a page, with or without the original/State data.  It is entirely possible that React is attempting to render the FilePond without all of its properties merely because one or more are dependent upon a State value that hasn't yet resolved by the time React has decided to begin the render.  I'm forced to write considerable defensive code to control for these oddities.  So, I have two proposals:

1. Could you check that `url` is set (not `undefined` or `null`) and a string (call `.toString()` on it) before attempting to parse it?  That bit of defensive programming would prevent the error from popping where it is today.  React could be creating a race condition whereby the `url` set on the FilePond is missing when the `load` is running.  So, if you don't have an `url`, skip parsing it.  Your code may very well get it on the next component render.
2. If the missing URL is for the image that is being loaded, would you please provide an explicit means of setting it in the `files` object in addition to the `source`?  That way, it doesn't matter how/when React is rendering

# Reproduction

The images are handled by a substantial Node.js API server.  This occurs during image load where binary blobs are in play, so there's no reasonable way for me to write sufficient reproduction code for you at codesandbox.io.  That said, I have gathered the salient artifacts here and in the **Environment** input on this form, which should help you to create a local reproduction.

## The FilePond Instance

The affected FilePond configuration is exactly:

```javascript
<FilePond
  files={packingSlipPhotos}
  onupdatefiles={handlePackingSlipPhotosChange}
  acceptedFileTypes={['image/*']}
  allowMultiple={true}
  maxFiles={10}
  name="packingSlipPhotos"
  server={{
    url: `${protectedResources.apiPartOrderPics.endpoint}/part_order/${id}/packing_slip`
    , onerror: (response) => {
      console.error("ReceivingEntryCard:  Error uploading packing slip photo:", response);
      let errorMessage = "";
      try {
        const jsonResponse = JSON.parse(response);
        if (jsonResponse.error) {
          errorMessage = jsonResponse.error;
        } else if (jsonResponse.errors) {
          errorMessage = jsonResponse.errors.join("; ");
        } else {
          errorMessage = response;
        }
      } catch (err) {
        errorMessage = response;
      }
      setPackingSlipPhotosError(errorMessage);
    }
    , headers: {
      Authorization: `Bearer ${apiAuthToken}`
    }
    , process: {
      ondata: (formData) => {
        formData.append("user_id", apiUserID);
        return formData;
      }
      , onload: (response) => JSON.parse(response).file_id
    }
  }}
  required
/>
```

Apart from being unable to load previously-saved images, everything about the FilePond is working as expected.  Processes (uploads) and reverts (deletions) work.

Except for image `load` requests from FilePond, the API server responds to most requests with JSON.  This is why `onload` must pull the `file_id` out of the JSON response.  For load requests from FilePond however, the API server properly responds with a binary blob (with required headers) as illustrated below.

## The Files Data

On page load, the `files` object contains exactly:

```json
[
  {
    "source": 23,
    "options": {
      "type": "local"
    }
  }
]
```

That "source" is correct; it is the unique image ID as tracked in my PostgreSQL database.  The image itself is stored on the filesystem; PostgreSQL merely stores a relative path to it.  When FilePond requests the image, the API server correctly responds with the image blob per your documentation.  The (abridged for brevity) browser's Network data regarding this transaction is included below.

## General Network Fields

Field | Value
--- | ---
Request URL | http://localhost:8081/api/v1/part_order_pic/part_order/2/packing_slip?load=23
Request Method | GET
Status Code | 200
Referrer Policy | strict-origin-when-cross-origin

## Response Fields

Field | Value
--- | ---
Accept-Ranges | bytes
Content-Disposition | inline; filename="1c152a0b34a4e92919cf27dd05274b65.jpeg"
Content-Length | 393229
Content-Type | application/octet-stream

# Relevant API Server Code

The following are bits of code from the backend API server.  This is the bulk of the code which runs when FilePond makes a load request.

### Bits of router.mjs

```javascript
const getPhotoSchema = {
  id: {
    in: ['params']
    , isInt: true
    , errorMessage: 'part_order_id is required'
  }
  , load: {
    in: ['query']
    , isInt: { errorMessage: 'load must be an integer' }
    , optional: true
  }
};
const getPhotoSchemaValidator = validator.checkSchema(getPhotoSchema);

router.get(
  '/part_order/:id/packing_slip'
  , getPhotoSchemaValidator
  , getPackingSlipsAction
);
```

## Bits of controller.mjs

```javascript
// To return a binary blob, we need to set the Content-Type header
// to the appropriate MIME type and set the Content-Disposition
// header to 'inline; filename="..."'.
function sendOrderPicFile(response, partOrderID, orderPicFileName, isPackingSlip) {
  const orderPicFilePath = `${process.env.INIT_CWD}/${buildPartOrderPicsDirectory(partOrderID, isPackingSlip)}/${orderPicFileName}`;

  response.setHeader('Content-Disposition', `inline; filename="${orderPicFileName}"`);
  response.sendFile(orderPicFilePath);
}

async function getOrderPicFileBlob(response, partOrderID, picID, isPackingSlip) {
  const queryRecords = await getAll({
    where: {
      id: picID
      , part_order_id: partOrderID
      , is_packing_slip: isPackingSlip
    }
  });
  if (queryRecords.length === 0) {
    response.status(404).send('Not Found');
    return;
  }

  const record = queryRecords[0];
  sendOrderPicFile(response, partOrderID, record.file_name, isPackingSlip);
}

async function getPackingSlipsAction(request, response) {
  try {
    const partOrderID = parseInt(request.params.id, 10);

    // This becomes a file blob download when the optional load query
    // parameter is set.  When set, it is the unique record ID.  Load its
    // record from the database to identify the correct filename.  Then,
    // return the binary data in the response body.  When load is not set,
    // the response body is a JSON object containing an array of objects
    // with the reference structure.
    if (request.query.load) {
      const recordID = parseInt(request.query.load, 10);
      getOrderPicFileBlob(response, partOrderID, recordID, true);
      return;
    }

    // This is a request for record data (no binary blobs).
    const queryRecords = await getAll({
      where: {
        part_order_id: partOrderID
        , is_packing_slip: true
      }
    });
    const responseBody = {
      part_order_pics: queryRecords
      , links: [{
        rel: 'self'
        , href: `${request.baseUrl}/${partOrderID}/packing_slip`
      }]
    };
    response.json(responseBody);
  } catch (error) {
    console.error(error);
    response.status(500).send('Internal Server Error');
  }
}
```

The response is healthy.  The requested file is transferred to the client in the request body as evidenced by the browser's Network > Preview tab.

# More About the Client

Should you find it helpful, the following code is directly copied from the client which is experiencing this error.

## From ReceivingEntryCard.js

This is the `handlePackingSlipPhotosChange` function referred to by the FilePond instance:

```javascript
function handlePackingSlipPhotosChange(fileMetadata) {
  let errorMessage = "";
  if (fileMetadata.length === 0) {
    errorMessage = "required";
  }
  setPackingSlipPhotosError(errorMessage);
  setPackingSlipPhotos(fileMetadata);
};
```

It merely provides UI feedback that at least one image is required and otherwise passes all file data back to the FilePond via `setPackingSlipPhotos(...)`.

This is the `useEffect` (runs on page load to populate the FilePond) and related `useState` values:

```javascript
const [packingSlipsLoaded, setPackingSlipsLoaded] = useState(false);
const [packingSlipPhotos, setPackingSlipPhotos] = useState([]);
const [packingSlipPhotosError, setPackingSlipPhotosError] = useState("required");

// Load the part order packing slip photos
useEffect(() => {
  if (packingSlipsLoaded || !canReceivePartOrders) {
    return;
  }
  if (id === undefined || id === null || id === '' || Number.isNaN(id)) {
    return;
  }

  const apiURL = `${protectedResources.apiPartOrderPics.endpoint}/part_order/${id}/packing_slip`;
  execute("GET", apiURL)
  .then(response => {
    if (!response) {
      console.warn("ReceivingEntryCard:  No response from the API (useFetchWithMsal failed to properly await).");
      return;
    }
    setPackingSlipsLoaded(true);
    if (response.status === 200) {
      console.log("ReceivingEntryCard:  Received packing slip photos: ", response);
      const filePondFiles = [];
      response.part_order_pics.forEach((pic) => {
        filePondFiles.push({
          source: pic.id
          // Doesn't seem to help:, url: `${appBaseURL}/${pic.relative_url}`
          , options: {
            type: 'local'
          }
        });
      });
      setPackingSlipPhotos(filePondFiles);
      console.log("ReceivingEntryCard:  Set packing slip photos: ", filePondFiles);
      return;
    }
    console.error("ReceivingEntryCard:  API error fetching data:", response);
  }).catch(err => {
    console.error("ReceivingEntryCard:  General error fetching data:", err);
  });
}, [id, canReceivePartOrders, packingSlipsLoaded, execute]);
```

This code runs exactly as expected, producing the `files` array replicated near the top of this entry.  Note that `execute` isn't included here; it's just a wrapper hook for most API queries to ensure the user is logged-in and the requisite Authentication Bearer header is set.  The same header is properly added in the FilePond's properties; user authentication is not at issue.

# Environment

```markdown
- Device: MacBook Pro (2023 M2 Max)
- OS: macOS Sonoma
- Browser: Microsoft Edge 119

The Backend and Frontend servers are both running via Docker containers on the MacBook Pro.

- Backend Server:  Node.js (express); running modules:
├── cors@2.8.5
├── express-fileupload@1.4.3
├── express-jwt@8.4.1
├── express-rate-limit@7.1.4
├── express-session@1.17.3
├── express-validator@7.0.1
├── express@4.18.2
├── jsonwebtoken@9.0.2
├── morgan@1.10.0
├── passport-azure-ad@4.3.5
├── passport@0.6.0
├── pg-hstore@2.3.4
├── pg@8.11.3
├── sequelize@6.33.0
├── swagger-jsdoc@6.2.8
└── swagger-ui-express@5.0.0

- Frontend Server:  React 18 (Next.js 14) running modules:
├── @azure/msal-browser@3.5.0
├── @azure/msal-react@2.0.7
├── @headlessui/react@1.7.17
├── @heroicons/react@2.0.18
├── autoprefixer@10.4.16
├── classnames@2.3.2
├── eslint-config-next@14.0.2
├── eslint@8.53.0
├── filepond-plugin-file-validate-type@1.2.8
├── filepond-plugin-image-exif-orientation@1.0.11
├── filepond-plugin-image-preview@4.6.11
├── filepond@4.30.4
├── next-themes@0.2.1
├── next@14.0.2
├── postcss@8.4.31
├── react-dom@18.2.0
├── react-filepond@7.1.2
├── react@18.2.0
└── tailwindcss@3.3.5
```

**Comment by wwkimball** [comment]
Update:  I noticed in [your documentation about the files array](https://pqina.nl/filepond/docs/api/instance/properties/#files) that you're showing `source` as a String despite the sample value clearly being an Integer.  So, I added `.toString()` to my own Integer-based `source` and sure enough, this resolves the error.

That's obscure and fragile, especially since the documentation doesn't explicitly state something like "**Note**:  `source` *must* be a String value."  If I may request, please either:

1. Cast `source` to String when you load it so that the onus is not on your end-users to ensure that we do so.
2. Add a specific note like the above suggestion to ensure that readers of your documentation know to ensure `source` is a String.

Option 1 would be a better service to your end-users.

That said, the FilePond isn't behaving quite right despite the original error now resolved.  Despite receiving the data it seems to need, the FilePond is showing only gray boxes with the Stringified source as a title and the file size as a subtitle on each box, each with an X button that seems to do nothing except remove the gray box from the control (it does not trigger a call to the back-end API).

I'll try to research this as a new issue...

**Comment by wwkimball** [comment]
Update on the follow-up issue:  It turns out, Express' `sendFile` function can't tell that file-extension `jpeg` is the same as `jpg` and should therefore be sent with a Content-Type header value of `image/jpeg`; it was instead sending application/octet-stream.

I had to modify my Node.js server to forcibly rename `*.jpeg' uploads to '*.jpg'.  This is IMHO entirely absurd on Express' part and fortunately, that issue has nothing to do with FilePond.

However, upon fixing that issue, another did arise:  Upon (finally) successfully reloading previously uploaded images via FilePond, the FilePond component shows an X button on each image thumbnail.  Clicking that button does nothing except review the image preview from view; FilePond makes no effort to contact the back-end API server to signal deletion of the image.  I expect clicking the X to trigger a delete event.

I will attempt to research this as a new issue...

**Comment by wwkimball** [comment]
Update on the issue of the X button failing to send a DELETE to the back-end API server:  this behavior is evidently by design per [the FilePond documentation](https://pqina.nl/filepond/docs/api/server/#remove).  I have to say, I do not understand why.

While uploading files, when I click the X, it sends a DELETE signal.  I therefore, reasonably, expect that clicking any X on a FilePond entry would invoke identical behavior.  To do otherwise is a frustrating surprise.

For posterity, I resolved this discrepancy by adding the following to my FilePond instance:

```javascript
, remove: (source, load, error) => {
  const url = `${protectedResources.apiPartOrderPics.endpoint}/${source}`;
  execute("DELETE", url)
  .then(response => {
    if (!response) {
      return;
    }
    if (response.status === 204) {
      console.log("ReceivingEntryCard:  Deleted packing slip photo: ", response);
      setPackingSlipPhotos(packingSlipPhotos.filter((file) => file.source !== source));

      // If the last packing slip photo was deleted, set the error message to required
      if (packingSlipPhotos.length === 1) {
        // 1 (not 0) because React hasn't updated the file list yet
        setPackingSlipPhotosError("required");
      }

      load();
      return;
    }
    console.error("ReceivingEntryCard:  API error deleting data:", response);
    error("API error deleting data");
  }).catch(err => {
    console.error("ReceivingEntryCard:  General error deleting data:", err);
    error("General error deleting data");
  });
}
```

**Comment by rikschennink** [comment]
Thanks for the detailed implementation story.

I've just pushed a fix for the "setting source with a number" issue. Past-Rik wrote this library 6 years ago, and I myself ran into it yesterday when testing something and it was quite confusing.

> However, upon fixing that issue, another did arise: Upon (finally) successfully reloading previously uploaded images via FilePond, the FilePond component shows an X button on each image thumbnail. Clicking that button does nothing except remove the image preview from view without removing it from the API server; FilePond makes no effort to contact the back-end API server to signal deletion of the image. I expect clicking the X to trigger a delete event.

You'll have to implement the "remove" endpoint, see:
https://pqina.nl/filepond/docs/api/server/#remove

It's not implemented as allowing users to remove files from the server is a potential security risk.

**Comment by wwkimball** [comment]
> Thanks for the detailed implementation story.

Happy to help!



> I've just pushed a fix for the "setting source with a number" issue. Past-Rik wrote this library 6 years ago, and I myself ran into it yesterday when testing something and it was quite confusing.

Great!  I'll pull down the update today and test it out.


> > However, upon fixing that issue, another did arise: Upon (finally) successfully reloading previously uploaded images via FilePond, the FilePond component shows an X button on each image thumbnail. Clicking that button does nothing except remove the image preview from view without removing it from the API server; FilePond makes no effort to contact the back-end API server to signal deletion of the image. I expect clicking the X to trigger a delete event.
> 
> 
> 
> You'll have to implement the "remove" endpoint, see:
> 
> https://pqina.nl/filepond/docs/api/server/#remove
> 
> 
> 
> It's not implemented as allowing users to remove files from the server is a potential security risk.

I do not understand this reasoning based on existing contradictory behavior of FilePond:

1. Upon upload, the API must already issue a unique ID back to FilePond.  This necessitates permanent artifacts on the server (filesystem and/or database).  We API authors must necessarily already take precautions that the destructive operation is rendered secure.
2. During the process/revert cycle, FilePond already emits a DELETE command to the API server whenever the user clicks the X button.  This triggers the API to destroy the permanent artifacts (filesystem and/or database) which were created to respond to the initial upload.
3. Merely loading the same files back into FilePond does not change the security implications of what the API server already had to handle to enable revert/DELETE during the upload/process mode.
4. Every destructive operation carries with it the same security risks, no matter whether the user is (likely unknowingly) deleting a temp or permanent asset.  It always falls on the API implementer to handle destructive operations with due care.

I don't understand the argument that one press of the X button is more/less "secure" than another.  The same ID is transmitted between client and server, either way.

As illustrated above, I have added the additional code to handle pressing the X button after a `load`.  I had no choice but to expend the time to do so.  I posit that it isn't any more/less secure than just letting FilePond send the DELETE command, sparing FilePond users the surprise and frustration of finding that the X button does nothing on its own.

**Comment by rikschennink** [comment]
Thanks for your input, I'll take it in consideration for FilePond v5

> Above all else, I do want to say, "Thank you, so much for making FilePond!" Despite the loss of a few days to the original and subsequent issues, it is clear to me that your work did save me many countless days/weeks of implementing such a solution myself. For that, I am sincerely thankful to you.

I'm glad to hear that. ☺️
