### ISSUE TITLE
Converting Headers key to CamelCase?

### ISSUE THREAD

**Issue by HabiboIV** [pqina/filepond#954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I set one header 

'X-CSRF-TOKEN'

the server always returns 419, meaning issues with csrf token. 
Headers are case sensitive.

when checking what header the are contained in the request, I see that the csrf header is present however the case has been altered to 

X-Csrf-Token

### Reproduction

Laravel 10 with vue 3 using composition api and vue-filepond 

### Environment

```markdown
- Device: 
- OS: windows
- Browser: chrome
```

**Comment by rikschennink** [comment]
This is just how `XMLHttpRequest.setRequestHeader` and `fetch` works, both scripts below result in `X-Hello` header key.

```js
const xhr = new XMLHttpRequest();
xhr.open('GET', '/');
xhr.setRequestHeader('X-HELLO', 'World');
xhr.send();
```

```js
fetch('/', {
    headers: {
        'X-HELLO': 'World'
    }
})
```
