### ISSUE TITLE
Upload of a large file (100s Mb) restarted each time a response received from back-end

### ISSUE THREAD

**Issue by h4k1m0u** [pqina/filepond#970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I'm trying to upload a large file (hunderds of Megabytes), knowing that there's a server-side validation which sends an http request with status code = 403 to interrupt the upload.
However this doesn't work: filepond keep uploading. Besides, when uploading a 800MB file, each time it reaches ~43%, it starts all over again (for three or four times). When I look at logs of HTTP requests, I can see it's my 403 http requests that cause the upload to restart each time.

Isn't filepond supposed to stop the upload if it receives a status code > 400 from the back-end?

p.s.: I've tried to implement following the example in the [advanced page][1].

[1]: https://pqina.nl/filepond/docs/api/server/#advanced

### Reproduction

Just upload a large file.

### Environment

```markdown
- Device: PC
- OS: Ubuntu
- Browser: Firefox
```

**Comment by h4k1m0u** [comment]
There's a workaround but I was just wondering if it was normal that even if the http response looked to be sent from the server (it appears in the logs), filepond (or the browser) didn't react to that till later on.

**Comment by rikschennink** [comment]
I think it depends on the browser, you cant act sooner than the XMLHttpRequest updates / errors.
