### ISSUE TITLE
how  to handle custom error message on maxFilesLimit

### ISSUE THREAD

**Issue by lsdev200** [pqina/filepond#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I have disabled FilePond preview, and now I want to display my custom error message when the maxFilesLimit is exceeded

### Reproduction

I have disabled FilePond preview, and now I want to display my custom error message when the maxFilesLimit is exceeded

### Environment

```markdown
- Device:PC
- OS:windows
- Browser:chrome
```

**Comment by rikschennink** [comment]
As requested in the issue template, please ask questions on StackOverflow.

**Comment by lsdev200** [comment]
i added their also but no one reply
