### ISSUE TITLE
Consider upload result successful only when return is a valid JSON and has result=OK value in it

### ISSUE THREAD

**Issue by nightrider77** [pqina/filepond#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The problem is that if some backend unexpected error happens, filepond shows successful result.
But not all errors can be catchable in system.

### Describe the solution you'd like

Consider upload result successful only when return is a valid JSON and has result=OK value in it.
All other results consider as failed (error).

### Describe alternatives you've considered

All filepond error events only being triggered with http response code 400.
That's problem.

**Comment by rikschennink** [comment]
If your server cannot respond with error codes, then you can use a custom process function instead.
https://pqina.nl/filepond/docs/api/server/#process-1

**Comment by nightrider77** [comment]
> If your server cannot respond with error codes, then you can use a custom process function instead. https://pqina.nl/filepond/docs/api/server/#process-1

Thank you for answer! But why did you choose this way?
It means that if any problem on server arises, user will misbelief that his file was uploaded.
This is not logical or reliable and forces user to use additional code.

**Comment by rikschennink** [comment]
> Thank you for answer! But why did you choose this way?
It means that if any problem on server arises, user will misbelief that his file was uploaded.
This is not logical or reliable and forces user to use additional code.

It _is_ logical. It means that if the server responds with matching http codes it just works.

If the server for whatever reason doesn't respond with the expected http codes the developer has the flexibility to use a custom process method to still integrate FilePond.
