### ISSUE TITLE
[Feature] Send file previews generated by filepond and other plugins to server

### ISSUE THREAD

**Issue by nightrider77** [pqina/filepond#986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It doesn't

### Describe the solution you'd like

Hello.

I am sorry it can be a duplicate, but search results didn't show anything similar.

The idea is to send along with file also its preview picture.
If frontend has already generated preview, why not to use it further?
Especially preview for PDF, it will be useful as server-side PDF processing is a little bit complicated.

### Describe alternatives you've considered

Not present

**Comment by rikschennink** [comment]
Thanks, this is something that is definitely possible with FilePond v5.
