### ISSUE TITLE
[Bug] Not compatible with WCAG 4.1.3 for alert of max filesize

### ISSUE THREAD

**Issue by NamikSigmax** [pqina/filepond#988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

When you use the pluging "filepond-plugin-file-validate-size" and you try to upload a file bigger than the max value, then you see an alert that the file is too big. The role attribute of this alert is "status" (role="status"). But this attribute must be "alert" (role="alert")

**Generated code:**
`<span class="filepond--assistant" id="filepond--assistant-kb2ty7h9i" role="status" aria-live="polite" aria-relevant="additions"> red.tiff File is too large</span>`

### Reproduction

Use pluging "filepond-plugin-file-validate-size".
Upload a file bigger then the max file size.
Look at the html code of the alert that the file is too large.

### Environment

```markdown
- Device:laptop
- OS: windows10 
- Browser: google chrome Versie 126.0.6478.127
```

**Comment by rikschennink** [comment]
Fixed in v4.32.0
