### ISSUE TITLE
[Bug] ImagePreview

### ISSUE THREAD

**Issue by hn1** [pqina/filepond#999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

If using the ImagePreview Plugin one upload different heights of images at the same time, the Filepond html expands and covers other elements below it, destroying the page's layout.

### Reproduction

1-Include ImagePreviewPlugin.
2-Upload several images of different heights.
3-See atttached image
![filepond](https://github.com/user-attachments/assets/df66c6cc-91c5-406e-96d0-ad75bdd35426)

### Environment

```markdown
- Device: Laptop
- OS: Windows
- Browser: Chrome
```

We are trying to use Filepond and have just logged a bug. There seems to be 100 issues outsatnding. Is this library maintained anymore?

**Comment by rikschennink** [comment]
See: https://pqina.nl/filepond/docs/api/style/#grid-layout

> We are trying to use Filepond and have just logged a bug. There seems to be 100 issues outsatnding. Is this library maintained anymore?

If you feel it's not maintained you can simply use another library. It's free. 

Yes there are issues, some are relevant, some not, some will be addressed in v5, others are kept open as a reminder.
